-- Insert galactic systems from UR-2650 to Vispil
INSERT INTO public.galactic_systems (name, sector, region, grid_coordinates) VALUES
('UR-2650', 'Zuma (Moddell)', 'Outer Rim Territories', 'H-16'),
('UR-3741', 'Zuma (Moddell)', 'Outer Rim Territories', 'H-16'),
('UR-5292-FH', NULL, 'Wild Space', 'H-7'),
('UR-6572-AK', NULL, 'Unknown Regions', 'G-8'),
('UR-8827', 'Zuma (Moddell)', 'Outer Rim Territories', 'H-16'),
('UR-9353', 'Zuma (Moddell)', 'Outer Rim Territories', 'H-16'),
('UR41-284', NULL, 'Unknown Regions', 'G-8'),
('Urajab', 'Vulcusion', 'Expansion Region', 'L-16'),
('Urber', 'Videnda', 'Outer Rim Territories', 'L-18'),
('Urce', 'Urce Space', 'Mid Rim', 'L-6'),
('Urch Tower', 'Dimension*', 'Unknown Regions', 'F-7'),
('Urdur', 'Corporate Sector', 'Outer Rim Territories', 'S-4'),
('Uridia', 'Yucrales', 'Mid Rim', 'R-14'),
('Uriek', 'Ash Worlds', 'Outer Rim Territories', 'T-7'),
('Urkupp', 'Auril', 'Outer Rim Territories', 'R-6'),
('Uro', 'Wazta', 'Outer Rim Territories', 'I-17'),
('Ursellin', 'Noolian', 'Mid Rim', 'Q-13'),
('Urthak', 'Gendius', 'Mid Rim', 'J-17'),
('Uru', 'Atravis', 'Outer Rim Territories', 'L-19'),
('Urun', 'Belasco', 'Expansion Region', 'O-11'),
('Usean', 'Tunka', 'Outer Rim Territories', 'I-18'),
('Useria', NULL, 'Inner Rim', 'N-9'),
('Ushmin', 'Relgim', 'Outer Rim Territories', 'K-4'),
('Ushruu', 'Altier', 'Expansion Region', 'O-13'),
('Usk', NULL, 'Hutt Space', 'T-10'),
('Usnia', 'Senex', 'Mid Rim', 'L-18'),
('Usta', 'Gordian Reach', 'Outer Rim Territories', 'Q-6'),
('Ut', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Utapau', 'Tarabba', 'Outer Rim Territories', 'N-19'),
('Utaruun', 'Arkanis', 'Outer Rim Territories', 'R-16'),
('Utegetu Nebula', NULL, 'Wild Space', 'I-8'),
('Utharis', NULL, 'Core Worlds', 'K-10'),
('Uthor', 'Agarix', 'Mid Rim', 'K-18'),
('Uthtara', 'Eucer', 'Mid Rim', 'R-7'),
('Uthura', NULL, 'Inner Rim', 'M-13'),
('Utor', NULL, 'Inner Rim', 'L-15'),
('Utrica', 'Tamarin', 'Outer Rim Territories', 'N-19'),
('Utrost', 'Corusca (Coruscant)', 'Core Worlds', 'L-9'),
('Uukaablis', 'Kathol (Outback)', 'Outer Rim Territories', 'M-21'),
('Uvadala', 'Ividal', 'Mid Rim', 'P-15'),
('Uvena', 'Seswenna', 'Outer Rim Territories', 'M-18'),
('Uviuy', 'Exen Shwuy', 'Colonies', 'L-9'),
('Uvoss', 'Cassander (Tadrin)', 'Outer Rim Territories', 'K-5'),
('Uyter', 'Lantillian', 'Mid Rim', 'P-9'),
('V''shar', NULL, 'Wild Space', 'U-15'),
('Va''art', 'Roche', 'Mid Rim', 'Q-8'),
('Vaal', 'Gordian Reach', 'Outer Rim Territories', 'P-5'),
('Vaathkree', 'Tharin (Periphery)', 'Outer Rim Territories', 'S-8'),
('Vaced', 'Jalor', 'Mid Rim', 'J-7'),
('Vactooine', 'Arkanis', 'Outer Rim Territories', 'R-16'),
('Vadnay', 'Spinward', 'Outer Rim Territories', 'M-2'),
('Vadooria', 'Halla', 'Mid Rim', 'S-9'),
('Vadran', 'Rago', 'Mid Rim', 'I-7'),
('Vaenrood', 'Pakuuni', 'Outer Rim Territories', 'T-6'),
('Vagadarr', NULL, 'Inner Rim', 'K-14'),
('Vagar Praxut', NULL, 'Unknown Regions', 'H-9'),
('Vagneria', NULL, 'Core Worlds', 'K-12'),
('Vagran', 'Corellian', 'Core Worlds', 'M-11'),
('Vahaba', 'Quelii', 'Outer Rim Territories', 'N-6'),
('Vakkar', 'Fakir', 'Colonies', 'K-9'),
('Vaklin', NULL, 'Inner Rim', 'M-14'),
('Valahari', 'D''Astan (Valahari)', 'Outer Rim Territories', 'N-5'),
('Valashar', 'Churnis', 'Mid Rim', 'I-7'),
('Valc', 'Perinn', 'Outer Rim Territories', 'J-4'),
('Vale', 'Atravis', 'Outer Rim Territories', 'L-19'),
('Valera', NULL, 'Colonies', 'L-13'),
('Valeria', NULL, 'Core Worlds', 'M-12'),
('Valfin', 'Meram', 'Outer Rim Territories', 'O-4'),
('Valgauth', 'Nojic', 'Expansion Region', 'P-9'),
('Validusia', 'Bes Ber Bikade', 'Expansion Region', 'L-15'),
('Vallt', 'Juris', 'Outer Rim Territories', 'P-17'),
('Vallusk Cluster', 'Gordian Reach', 'Outer Rim Territories', 'Q-6'),
('Valnoos', 'Morshdine', 'Outer Rim Territories', 'O-5'),
('Valo', 'Rseik', 'Outer Rim Territories', 'N-19'),
('Valorsi', 'Juvex', 'Mid Rim', 'L-17'),
('Valrar', 'Glythe', 'Mid Rim', 'J-7'),
('Valron', 'Rocantor', 'Expansion Region', 'L-15'),
('Valsedian', NULL, 'Hutt Space', 'S-11'),
('Valtava', 'Valtava', 'Inner Rim', 'I-8'),
('Valtha Divide', NULL, 'Wild Space', 'S-4'),
('Valtos', NULL, 'Wild Space', 'I-8'),
('Vanahame', 'Grumani', 'Outer Rim Territories', 'N-17'),
('Vanan', 'Atravis', 'Outer Rim Territories', 'L-19'),
('Vanaria', 'Rseik', 'Outer Rim Territories', 'N-20'),
('Vandelae', NULL, 'Inner Rim', 'O-10'),
('Vandelhelm', 'Epsi Collective', 'Expansion Region', 'M-15'),
('Vandin', 'Tharin', 'Outer Rim Territories', 'S-8'),
('Vandor', 'Sloo', 'Mid Rim', 'P-14'),
('Vandos', 'Nuiri', 'Outer Rim Territories', 'Q-7'),
('Vandron', 'D''Aelgoth', 'Mid Rim', 'L-17'),
('Vandyne', 'Morshdine', 'Outer Rim Territories', 'O-5'),
('Vanguerre', 'Roche', 'Mid Rim', 'Q-8'),
('Vanik', NULL, 'Inner Rim', 'L-14'),
('Vanjervalis', NULL, 'Colonies', 'N-11'),
('Vannan', 'Nijune', 'Outer Rim Territories', 'O-4'),
('Vannix', NULL, 'Core Worlds', 'M-10'),
('Vanooria', NULL, 'Core Worlds', 'M-10'),
('Vanqor', 'Sertar', 'Outer Rim Territories', 'R-5'),
('Vanquo', 'Meerian', 'Outer Rim Territories', 'O-6'),
('Vantillia', NULL, 'Inner Rim', 'M-13'),
('Vanzeist', 'Suolriep', 'Outer Rim Territories', 'S-8'),
('Var-Shaa', 'Dustig', 'Mid Rim', 'N-17'),
('Varada', 'Varada', 'Outer Rim Territories', 'I-19'),
('Varadan', 'Senex', 'Mid Rim', 'L-18'),
('Vardos', NULL, 'Core Worlds', 'L-9'),
('Vardoss', 'Vardoss', 'Expansion Region', 'J-8'),
('Vargos', 'Mortex', 'Outer Rim Territories', 'R-5'),
('Varic', 'Chorlian', 'Outer Rim Territories', 'S-4'),
('Varkana', 'Quelii', 'Outer Rim Territories', 'O-6'),
('Varl', NULL, 'Hutt Space', 'S-11'),
('Varlinaar', 'Koradin', 'Outer Rim Territories', 'J-18'),
('Varn', 'Quelii', 'Outer Rim Territories', 'O-6'),
('Varnak', 'Kurost', 'Mid Rim', 'Q-11'),
('Varonat', 'Javin (Anoat)', 'Outer Rim Territories', 'K-18'),
('Varristad', 'Abrion', 'Outer Rim Territories', 'S-15'),
('Vartos', 'Tharin', 'Outer Rim Territories', 'S-8'),
('Varvrona', 'Obtrexta', 'Outer Rim Territories', 'K-4'),
('Varvva', 'Barsa', 'Mid Rim', 'J-6'),
('Vasar', 'Corellian', 'Core Worlds', 'M-11'),
('Vasch', 'Arkanis', 'Outer Rim Territories', 'R-17'),
('Vasha', 'Zuma (Moddell)', 'Outer Rim Territories', 'H-16'),
('Vashka', 'Kibilini', 'Outer Rim Territories', 'Q-17'),
('Vassek', 'Wazta', 'Outer Rim Territories', 'I-17'),
('Vastrip', NULL, 'Inner Rim', 'N-7'),
('Vasuuli', 'Kliap', 'Colonies', 'M-9'),
('Vatleria', 'Calaron', 'Outer Rim Territories', 'T-9'),
('Vatta', NULL, 'Wild Space', 'M-21'),
('Vavarna', 'Jjannex', 'Outer Rim Territories', 'L-18'),
('Vaykaaris', NULL, 'Colonies', 'K-13'),
('Vaynai', 'Chorlian', 'Outer Rim Territories', 'S-4'),
('Veccacopia', 'Tunka', 'Outer Rim Territories', 'I-19'),
('Vectinia', 'Hewett', 'Mid Rim', 'M-7'),
('Vedis', 'Mayagil', 'Outer Rim Territories', 'N-18'),
('Veil Nebula', 'D''Astan', 'Outer Rim Territories', 'N-5'),
('Veil, The', 'Farstey', 'Expansion Region', 'O-8'),
('Velabri', NULL, 'Outer Rim Territories', 'S-18'),
('Velanaria', 'Videnda', 'Outer Rim Territories', 'L-18'),
('Velex', 'Locris', 'Expansion Region', 'O-8'),
('Velga', 'Juvex', 'Mid Rim', 'L-18'),
('Vellas Pavo', 'Grumani', 'Outer Rim Territories', 'M-17'),
('Vellity', 'Trax', 'Mid Rim', 'Q-10'),
('Velmor', 'Halori', 'Mid Rim', 'P-7'),
('Velossia', 'Manda', 'Mid Rim', 'R-15'),
('Velusia', NULL, 'Core Worlds', 'L-9'),
('Velx-Shel', 'Corellian', 'Core Worlds', 'M-11'),
('Vena', 'Nojic', 'Expansion Region', 'P-9'),
('Venaari', 'Venaarian', 'Mid Rim', 'O-8'),
('Vendara', 'Kwymar', 'Outer Rim Territories', 'Q-4'),
('Vendaxa', 'Chaykin', 'Expansion Region', 'O-14'),
('Vendrak', 'Videnda', 'Outer Rim Territories', 'M-18'),
('Vendusii', 'Vendusii', 'Mid Rim', 'P-16'),
('Venedlia', 'Instrop', 'Outer Rim Territories', 'S-16'),
('Venerable Stirta', 'Ghost Nebula', 'Expansion Region', 'P-10'),
('Venestria', 'Clacis', 'Outer Rim Territories', 'K-4'),
('Vengler', NULL, 'Wild Space', 'H-18'),
('Venir', 'Kuat', 'Core Worlds', 'M-10'),
('Venjagga', NULL, 'Colonies', 'K-9'),
('Vensor', 'Vensori', 'Mid Rim', 'P-8'),
('Ventil', 'Trax', 'Mid Rim', 'Q-10'),
('Vento', NULL, 'Core Worlds', 'L-9'),
('Ventooine', 'Corva', 'Outer Rim Territories', 'P-3'),
('Ventran', 'Var Hagen', 'Mid Rim', 'M-16'),
('Ventruun', 'Grumani', 'Outer Rim Territories', 'M-17'),
('Ventrux', 'Thesme', 'Outer Rim Territories', 'O-6'),
('Venustria', NULL, 'Colonies', 'N-12'),
('Venzeiia', 'Venzeiia', 'Expansion Region', 'O-12'),
('Veragi', 'Veragi', 'Outer Rim Territories', 'L-3'),
('Verdanaia', NULL, 'Core Worlds', 'M-11'),
('Verdanth', 'Bon''nyuw-Luq', 'Outer Rim Territories', 'N-17'),
('Verde', 'Tharin (Periphery)', 'Outer Rim Territories', 'S-8'),
('Verdi', 'Rayter', 'Outer Rim Territories', 'J-19'),
('Verdoria', NULL, 'Core Worlds', 'M-11'),
('Vergill', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Verig', 'Raioballo', 'Outer Rim Territories', 'L-4'),
('Verisin', 'Bajic', 'Outer Rim Territories', 'P-17'),
('Verkuyl', 'Stensen', 'Outer Rim Territories', 'H-17'),
('Vernet', 'Baroli', 'Expansion Region', 'N-14'),
('Vernid', 'Kanz', 'Outer Rim Territories', 'M-4'),
('Veroleem', NULL, 'Unknown Regions', 'I-6'),
('Veron', 'Senex', 'Mid Rim', 'L-17'),
('Veron Minor', 'Mektrun', 'Mid Rim', 'L-17'),
('Veronia', 'Oricho', 'Outer Rim Territories', 'M-6'),
('Veros', 'Dimean', 'Expansion Region', 'P-13'),
('Verossia', 'Strabin', 'Mid Rim', 'M-7'),
('Verroth', 'Belsmuth', 'Outer Rim Territories', 'O-6'),
('Vertseth', NULL, 'Colonies', 'N-10'),
('Verullia', 'Kira', 'Expansion Region', 'N-15'),
('Vesari', NULL, 'Inner Rim', 'O-10'),
('Vesla', 'Corosi', 'Outer Rim Territories', 'N-6'),
('Vesla Minor', NULL, 'Wild Space', 'I-14'),
('Vespaara', 'Suolriep', 'Outer Rim Territories', 'S-8'),
('Vessitoar', 'Ottega', 'Mid Rim', 'M-6'),
('Vestar', 'Rseik', 'Outer Rim Territories', 'N-20'),
('Vestor Nebula', 'Trans-Nebular', 'Mid Rim', 'R-16'),
('Vestral', 'Mortex', 'Outer Rim Territories', 'R-5'),
('Vetine', 'Merrick', 'Inner Rim', 'L-14'),
('Vex', 'Zuma (Moddell)', 'Outer Rim Territories', 'H-16'),
('Vexar', 'Corporate Sector', 'Outer Rim Territories', 'S-4'),
('Vexos', NULL, 'Wild Space', 'G-14'),
('Vexta', 'Carrion', 'Outer Rim Territories', 'J-4'),
('Viamarr', NULL, 'Inner Rim', 'N-7'),
('Vicondor', 'Vorc', 'Mid Rim', 'J-7'),
('Videll', NULL, 'Colonies', 'M-13'),
('Vidicx', 'Eclorar', 'Mid Rim', 'Q-12'),
('Viga', 'Lostar', 'Expansion Region', 'M-7'),
('Viidaav', 'Bryx', 'Mid Rim', 'R-7'),
('Vilosoria', 'Lifh', 'Mid Rim', 'R-8'),
('Vincorba', 'Piryn Shar', 'Expansion Region', 'K-16'),
('Vindalia', NULL, 'Colonies', 'L-13'),
('Vinnax', NULL, 'Wild Space', 'S-3'),
('Vinsoth', 'Quelii', 'Outer Rim Territories', 'N-5'),
('Vint', 'Sevetta', 'Outer Rim Territories', 'T-16'),
('Vinth', 'Venzeiia', 'Expansion Region', 'O-13'),
('Vintrus', 'Manda', 'Mid Rim', 'R-15'),
('Vinzen Neela', 'Parmic', 'Outer Rim Territories', 'P-18'),
('Vir Aphshire', 'Tharin', 'Outer Rim Territories', 'S-8'),
('Viraanntesse', 'Dona Laza', 'Expansion Region', 'P-9'),
('Virgillia', 'Koradin', 'Outer Rim Territories', 'I-18'),
('Viridia', 'Halthor', 'Outer Rim Territories', 'M-6'),
('Virkoi', NULL, 'Inner Rim', 'N-9'),
('Virmeude', 'Mayagil', 'Outer Rim Territories', 'M-18'),
('Virujansi', NULL, 'Inner Rim', 'O-10'),
('Vishay', 'Vish', 'Mid Rim', 'N-16'),
('Vispil', 'Thrasybule', 'Outer Rim Territories', 'P-6');