-- Insert additional galactic systems data
INSERT INTO public.galactic_systems (name, sector, region, grid_coordinates) VALUES
('Alderath', 'Alderath', 'Mid Rim', 'L-7'),
('Alderbathe', 'Churnis', 'Mid Rim', 'J-6'),
('Aldereen', NULL, 'Inner Rim', 'M-14'),
('Aldhani', 'Cademimu', 'Outer Rim Territories', 'M-6'),
('Aldin', 'Aldino', 'Mid Rim', 'J-17'),
('Aldivy', 'Illisurevimurasi', 'Outer Rim Territories', 'Q-4'),
('Aldo Spach', 'Jospro', 'Outer Rim Territories', 'S-7'),
('Aldraig', NULL, 'Core Worlds', 'M-10'),
('Alee', NULL, 'Hutt Space', 'R-9'),
('Aleen', 'Bright Jewel', 'Mid Rim', 'L-7'),
('Aleen Minor', NULL, 'Inner Rim', 'M-13'),
('Aleron', 'Tapani', 'Colonies', 'L-13'),
('Alfestril', NULL, 'Inner Rim', 'N-12'),
('Algara', 'Lambda', 'Mid Rim', 'P-15'),
('Algarian', 'Dufilvian', 'Mid Rim', 'Q-15'),
('Algarra', 'Thrasybule', 'Outer Rim Territories', 'P-6'),
('Algnadesh', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Algor', 'Cronese Mandate', 'Outer Rim Territories', 'S-6'),
('Algunnis', 'Trax', 'Mid Rim', 'Q-10'),
('Alion', NULL, 'Inner Rim', 'L-14'),
('Alios', 'Rachuk', 'Colonies', 'N-11'),
('Alis Point', 'Tamarin', 'Outer Rim Territories', 'N-18'),
('Alisandor', 'Tapani', 'Colonies', 'L-13'),
('Alk''Lellish', 'Sumitra', 'Expansion Region', 'N-7'),
('Alkenak', NULL, 'Core Worlds', 'M-12'),
('Alland', NULL, 'Core Worlds', 'K-10'),
('Allandor', 'Tapani', 'Colonies', 'L-13'),
('Allanteen', 'Tynna', 'Expansion Region', 'O-14'),
('Alliga', 'Phelleem', 'Outer Rim Territories', 'S-7'),
('Allst Prime', 'Taldot', 'Mid Rim', 'Q-8'),
('Alluuvia', 'Elrood', 'Outer Rim Territories', 'M-19'),
('Allyuen', 'Javin (Anoat)', 'Outer Rim Territories', 'K-18'),
('Almagest, The', NULL, 'Inner Rim', 'J-13'),
('Almak', 'Almak', 'Mid Rim', 'J-17'),
('Almakar', NULL, 'Inner Rim', 'N-9'),
('Almania', 'Mortex (Almanian)', 'Outer Rim Territories', 'S-5'),
('Almar', 'Elrood', 'Outer Rim Territories', 'M-19'),
('Almera', NULL, 'Inner Rim', 'M-8'),
('Aloxl', NULL, 'Deep Core', 'L-10'),
('Aloxor', 'Kontahr', 'Mid Rim', 'R-11'),
('Alpheridies', 'Farstey', 'Expansion Region', 'O-8'),
('Alphoresis', 'Grumani', 'Outer Rim Territories', 'M-17'),
('Alpinn', 'Kanz', 'Outer Rim Territories', 'N-4'),
('Alsakan', 'Alsaka', 'Core Worlds', 'L-9'),
('Altair', 'Thrasybule', 'Outer Rim Territories', 'P-6'),
('Altano', 'Piryn Shar', 'Expansion Region', 'K-16'),
('Altarrn', 'Glythe', 'Mid Rim', 'J-7'),
('Altawar', 'Corellian', 'Core Worlds', 'M-11'),
('Althir', 'Rolion', 'Outer Rim Territories', 'P-6'),
('Altier', 'Altier', 'Expansion Region', 'O-13'),
('Altikar', 'Toblain', 'Outer Rim Territories', 'O-18'),
('Altooni', 'Corellian', 'Core Worlds', 'M-11'),
('Altor', 'Zoraster', 'Outer Rim Territories', 'U-13'),
('Altora', 'Dalonbian', 'Outer Rim Territories', 'L-3'),
('Altratonne', 'Ash Worlds', 'Outer Rim Territories', 'S-7'),
('Altunna', 'Cassander', 'Outer Rim Territories', 'K-5'),
('Altyr', 'Morshdine', 'Outer Rim Territories', 'O-5'),
('Aludia', 'Trilon', 'Outer Rim Territories', 'H-16'),
('Alui', 'Alui', 'Mid Rim', 'O-17'),
('Alun', 'Oriolan', 'Mid Rim', 'J-16'),
('Alurion', 'Raioballo', 'Outer Rim Territories', 'L-4'),
('Alvorine', 'Yminis', 'Outer Rim Territories', 'S-14'),
('Alzar', 'Thanium', 'Outer Rim Territories', 'R-6'),
('Alzoc', 'Sujimis', 'Outer Rim Territories', 'P-19'),
('Amaltanna', 'Kanz', 'Outer Rim Territories', 'N-4'),
('Amar', 'Airon', 'Inner Rim', 'O-10'),
('Amarin', 'Allied Tion', 'Outer Rim Territories', 'S-6'),
('Amaxine Station', 'Tunka', 'Outer Rim Territories', 'J-19'),
('Ambria', 'Airon', 'Inner Rim', 'O-10'),
('Amethia Prime', NULL, 'Inner Rim', 'L-14'),
('Amfar', NULL, 'Inner Rim', 'O-8'),
('Ammon', 'Ciutric', 'Outer Rim Territories', 'N-5'),
('Ammuud', 'Corporate Sector', 'Outer Rim Territories', 'S-4'),
('Amorphiia', 'Eidoloni', 'Mid Rim', 'L-16'),
('Amorris', 'Quelii', 'Outer Rim Territories', 'O-6'),
('Ampliquen', 'Meridian', 'Outer Rim Territories', 'R-7'),
('Anadeen', NULL, 'Inner Rim', 'O-9'),
('Anantapar', 'Javin (Yarith)', 'Outer Rim Territories', 'K-18'),
('Anarak', 'Wyl', 'Outer Rim Territories', 'R-4'),
('Anaxes', 'Antemeridian', 'Outer Rim Territories', 'R-7'),
('Ancathia', 'Albarrio', 'Outer Rim Territories', 'K-5'),
('Anchoron', 'Mayagil', 'Outer Rim Territories', 'M-18'),
('Andalia', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Andara', NULL, 'Core Worlds', 'L-13'),
('Andasala', 'Cor''ric', 'Outer Rim Territories', 'P-18'),
('Andelm', 'Svivreni', 'Outer Rim Territories', 'O-19'),
('Ando', 'Lambda', 'Mid Rim', 'Q-15'),
('Andooweel', 'Arkanis', 'Outer Rim Territories', 'R-16'),
('Andosha', 'Lambda', 'Mid Rim', 'P-15'),
('Andraven', 'Wazta', 'Outer Rim Territories', 'J-18'),
('Andulia', 'Doldur', 'Mid Rim', 'P-15'),
('Andurkoss', 'Nouane', 'Inner Rim', 'N-8'),
('Anduvia', 'Immalia', 'Expansion Region', 'K-8'),
('Anelsana', 'Farstey', 'Expansion Region', 'O-8'),
('Anemcoro', 'Albarrio', 'Outer Rim Territories', 'K-5'),
('Anga', 'Sarka', 'Mid Rim', 'Q-8'),
('Angeria', 'Venaarian', 'Mid Rim', 'O-8'),
('Angor', 'Myto', 'Outer Rim Territories', 'K-4'),
('Angrallia', 'Fath', 'Outer Rim Territories', 'K-6'),
('Angratha', 'Senex', 'Mid Rim', 'L-18'),
('Anic', 'Xan', 'Mid Rim', 'Q-15'),
('Ank Ki''Shor', 'Indrexu', 'Outer Rim Territories', 'S-5'),
('Ank Kit''aar', 'Druess', 'Mid Rim', 'O-15'),
('Ankhural', NULL, 'Hutt Space', 'R-9'),
('Ankori', 'Kossa', 'Expansion Region', 'P-10'),
('Ankot Station', 'Brema', 'Outer Rim Territories', 'M-17'),
('Ankus', NULL, 'Mid Rim', 'I-7'),
('Annaj', 'Zuma (Moddell)', 'Outer Rim Territories', 'H-16'),
('Annamar', 'Bes Ber Bikade', 'Expansion Region', 'L-15'),
('Annoo', 'Tharin', 'Outer Rim Territories', 'S-8'),
('Anoat', 'Javin (Anoat)', 'Outer Rim Territories', 'K-18'),
('Anobis', 'Bright Jewel', 'Mid Rim', 'L-7');