-- Insertar nuevos sistemas galácticos desde Dithanune hasta Empartheca
INSERT INTO public.galactic_systems (name, sector, region, grid_coordinates) VALUES
('Dithanune', 'Bortele', 'Mid Rim', 'R-8'),
('Divac', 'Nuiri', 'Outer Rim Territories', 'Q-6'),
('Divora', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Dix''thaar', NULL, 'Inner Rim', 'K-8'),
('Diyu', 'Hutt Space', 'Hutt Space', 'S-12'),
('Dizon Fray', NULL, 'Outer Rim Territories', 'U-7'),
('Djurmo', 'Strabin', 'Mid Rim', 'M-7'),
('Dles', 'Tharin (Periphery)', 'Outer Rim Territories', 'S-8'),
('Dlor', 'Dononter', 'Mid Rim', 'I-16'),
('DNX-N1', NULL, 'Wild Space', 'N-21'),
('Doan', 'Halthor', 'Outer Rim Territories', 'M-6'),
('Doaskin', 'Bruanii', 'Mid Rim', 'K-18'),
('Dodz', 'Zoraster', 'Outer Rim Territories', 'U-13'),
('Dohlban', 'Dohlbani', 'Mid Rim', 'R-13'),
('Dohnia', 'Semagi', 'Mid Rim', 'I-16'),
('Dohu', 'Dohu', 'Mid Rim', 'K-7'),
('Dol''har Hyde', 'Sanbra', 'Outer Rim Territories', 'O-17'),
('Doldur', 'Doldur', 'Mid Rim', 'P-15'),
('Doli', 'D''Astan', 'Outer Rim Territories', 'O-6'),
('Dolis', 'Obtrexta', 'Outer Rim Territories', 'J-3'),
('Dolla', 'Videnda', 'Outer Rim Territories', 'L-18'),
('Dolomar', 'Dolomar', 'Core Worlds', 'K-9'),
('Dolsan', NULL, 'Core Worlds', 'K-9'),
('Dolstan', 'Kathol (Outback)', 'Outer Rim Territories', 'M-21'),
('Dolva Prime', 'Semagi', 'Mid Rim', 'I-16'),
('Dom-Bradden', 'Lol', 'Outer Rim Territories', 'Q-18'),
('Domancion', 'Suolriep', 'Outer Rim Territories', 'S-8'),
('Domgrin', 'Prefsbelt', 'Outer Rim Territories', 'K-6'),
('Dominus', 'Lothal (Dominus)', 'Outer Rim Territories', 'U-7'),
('Don I', 'Tapani', 'Colonies', 'L-13'),
('Don II', 'Tapani', 'Colonies', 'L-13'),
('Dona Laza', 'Dona Laza', 'Expansion Region', 'P-9'),
('Donadus', 'Bamula', 'Inner Rim', 'J-13'),
('Doneer''so', 'Fakir', 'Colonies', 'K-9'),
('Doniphon', 'Kwymar', 'Outer Rim Territories', 'P-4'),
('Dononter Minor', 'Dononter', 'Mid Rim', 'I-16'),
('Donovia', 'Hali', 'Expansion Region', 'O-9'),
('Dontamo', 'Dantus', 'Outer Rim Territories', 'J-6'),
('Dooma', 'Dentari', 'Expansion Region', 'O-7'),
('Doornik-1142', 'Farlax', 'Core Worlds', 'K-10'),
('Doornik-207', 'Farlax', 'Core Worlds', 'K-10'),
('Dor Nameth', 'Bright Jewel', 'Mid Rim', 'L-7'),
('Dorajan', 'Lannik Space', 'Mid Rim', 'Q-12'),
('Dorande', 'Quiberon', 'Outer Rim Territories', 'T-15'),
('Dorax', NULL, 'Core Worlds', 'L-9'),
('Dorcin', 'Minos Cluster', 'Outer Rim Territories', 'M-20'),
('Dordolum', NULL, 'Colonies', 'K-13'),
('Doreen', 'Senex', 'Mid Rim', 'L-18'),
('Dorella', 'Tapani', 'Colonies', 'L-13'),
('Dorellia', 'Tapani', 'Colonies', 'L-13'),
('Dorenia', 'Mayagil', 'Outer Rim Territories', 'M-18'),
('Dorin', 'Deadalis', 'Expansion Region', 'J-8'),
('Doris', 'Tapani', 'Colonies', 'L-13'),
('Dorlo', 'Atravis', 'Outer Rim Territories', 'L-19'),
('Dorlon', NULL, 'Colonies', 'M-9'),
('Dornea', 'Lothal', 'Outer Rim Territories', 'U-7'),
('Dorriella', 'Wazta', 'Outer Rim Territories', 'I-17'),
('Dorsis', 'Corellian', 'Core Worlds', 'M-11'),
('Dorvalla', 'Videnda', 'Outer Rim Territories', 'M-18'),
('Doshan', 'Drannik', 'Expansion Region', 'K-8'),
('Dosuun', NULL, 'Wild Space', 'H-20'),
('Dotharian', 'Hutt Space', 'Hutt Space', 'S-12'),
('Dothnia', 'Hunnoverrs', 'Outer Rim Territories', 'S-17'),
('Douglas', 'Centrality', 'Outer Rim Territories', 'U-8'),
('Dowut', NULL, 'Core Worlds', 'J-12'),
('Doxxen', 'Seitia', 'Outer Rim Territories', 'K-19'),
('Dozoisia', 'Sevetta', 'Outer Rim Territories', 'S-15'),
('Dra', 'Wyl', 'Outer Rim Territories', 'R-4'),
('Draay', 'Pelgrin', 'Outer Rim Territories', 'R-18'),
('Draboon', 'Mandalore', 'Outer Rim Territories', 'O-7'),
('Drackmar', 'Quelii', 'Outer Rim Territories', 'O-6'),
('Dractu', 'Lannik Space', 'Mid Rim', 'Q-13'),
('Drada', 'Halthor', 'Outer Rim Territories', 'L-6'),
('Draflago', 'Sertar', 'Outer Rim Territories', 'R-5'),
('Dragon Void', 'Gomar', 'Inner Rim', 'K-14'),
('Dragonflower Nebula', 'Doldur', 'Mid Rim', 'P-15'),
('Dragos', 'Boeus', 'Expansion Region', 'M-15'),
('Drahgor', 'Colundra', 'Outer Rim Territories', 'S-4'),
('Draik', 'Alui', 'Mid Rim', 'O-17'),
('Dramassia', 'Juvex', 'Mid Rim', 'L-18'),
('Drannik', 'Drannik', 'Expansion Region', 'K-8'),
('Draria', 'Lostar', 'Expansion Region', 'M-7'),
('Drash-So', 'Yminis', 'Outer Rim Territories', 'S-14'),
('Drashima', 'Majoor', 'Expansion Region', 'N-15'),
('Draukyze', 'Thanium', 'Outer Rim Territories', 'R-6'),
('Dravian Starport', 'Tamarin', 'Outer Rim Territories', 'N-18'),
('Dravin', 'Subterrel', 'Outer Rim Territories', 'L-20'),
('Dravione', 'Allied Tion', 'Outer Rim Territories', 'S-6'),
('Drayberia', 'Sertar', 'Outer Rim Territories', 'R-5'),
('Drazkel', 'Oriolan', 'Mid Rim', 'J-16'),
('Drearia', NULL, 'Inner Rim', 'L-8'),
('Dreena', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Dreffon', NULL, 'Colonies', 'J-9'),
('Dreighton', 'Dantus', 'Outer Rim Territories', 'J-6'),
('Dreighton Nebula', 'Dantus', 'Outer Rim Territories', 'J-6'),
('Dreivus', 'Oeiros', 'Expansion Region', 'P-10'),
('Dreizan', NULL, 'Core Worlds', 'M-12'),
('Dremulae', NULL, 'Deep Core', 'M-10'),
('Dresscol', 'Trax', 'Mid Rim', 'Q-10'),
('Dressel', 'Noolian', 'Mid Rim', 'Q-13'),
('Dressia', NULL, 'Colonies', 'L-8'),
('Dreve', NULL, 'Inner Rim', 'N-7'),
('Drexel', 'Lol', 'Outer Rim Territories', 'Q-18'),
('Drexel Minor', 'Khuiumin', 'Outer Rim Territories', 'O-19'),
('Drezzi', 'Esstran (Sith Worlds)', 'Outer Rim Territories', 'Q-5'),
('Drgi', 'Tokamac', 'Expansion Region', 'O-13'),
('Drift, The', 'Elrood', 'Outer Rim Territories', 'M-20'),
('Drilbia', 'Brema', 'Outer Rim Territories', 'M-17'),
('Droecil', 'Boeus', 'Expansion Region', 'M-15'),
('Drog', 'Corporate Sector', 'Outer Rim Territories', 'R-4'),
('Drogheda', 'Teraab', 'Mid Rim', 'Q-11'),
('Dromondar Beta', NULL, 'Unknown Regions', 'H-7'),
('Drompani', 'Prefsbelt', 'Outer Rim Territories', 'J-6'),
('Dromund Kaas', 'Esstran (Sith Worlds)', 'Outer Rim Territories', 'R-5'),
('Drong', 'Steniplis', 'Outer Rim Territories', 'L-18'),
('Drongar', NULL, 'Outer Rim Territories', 'T-5'),
('Dronseen', 'Thrasybule', 'Outer Rim Territories', 'P-6'),
('Drophun', NULL, 'Colonies', 'L-13'),
('Droxine', 'Esstran', 'Outer Rim Territories', 'Q-5'),
('Droxu', 'Bheriz', 'Outer Rim Territories', 'T-11'),
('Drualkiin', 'Kessel', 'Outer Rim Territories', 'T-10'),
('Druckenwell', 'Doldur', 'Mid Rim', 'P-15'),
('Drunost', 'Shelsha', 'Colonies', 'M-9'),
('Drup''s Star', 'Saijo', 'Outer Rim Territories', 'J-20'),
('Drurish', 'Kuat', 'Core Worlds', 'M-10'),
('Druulgotha', 'Thesme', 'Outer Rim Territories', 'O-6'),
('Dryorkeen Cluster', 'Parmic', 'Outer Rim Territories', 'P-18'),
('Du Hutta', 'Hutt Space', 'Hutt Space', 'S-11'),
('Du Mai', 'Bryx', 'Mid Rim', 'R-8'),
('Dubloviann', NULL, 'Inner Rim', 'M-8'),
('Dubraib', 'Cegul', 'Outer Rim Territories', 'M-20'),
('Dubrava', 'Albanin', 'Outer Rim Territories', 'T-13'),
('Dubrillion', 'Myto', 'Outer Rim Territories', 'K-3'),
('Dubrovia', 'Aldino', 'Mid Rim', 'J-17'),
('Duhma', 'Kallea', 'Outer Rim Territories', 'K-20'),
('Duinarbulon', 'Cronese Mandate', 'Outer Rim Territories', 'S-6'),
('Dulathia', 'Lantillian', 'Mid Rim', 'P-8'),
('Dulin', NULL, 'Inner Rim', 'K-14'),
('Dulvoyinn', NULL, 'Deep Core', 'K-12'),
('Dunari''s Rest', 'Mayagil', 'Outer Rim Territories', 'N-18'),
('Duneeden', 'Corusca', 'Core Worlds', 'K-9'),
('Dunnak', NULL, 'Inner Rim', 'N-8'),
('Dur Sabon', 'Morshdine', 'Outer Rim Territories', 'O-5'),
('Dura-Kahn', 'Bes Ber Bikade', 'Expansion Region', 'L-15'),
('Durace', NULL, 'Unknown Regions', 'H-6'),
('Duran', NULL, 'Core Worlds', 'K-9'),
('Durgen''s Star', 'Gordian Reach', 'Outer Rim Territories', 'P-6'),
('Durgeon', 'Galov', 'Outer Rim Territories', 'T-13'),
('Durkteel', 'Kastolar', 'Mid Rim', 'Q-10'),
('Duro', 'Duro', 'Core Worlds', 'M-11'),
('Durollia', 'Kalamith', 'Outer Rim Territories', 'P-5'),
('Duron', 'Semagi', 'Mid Rim', 'I-16'),
('Duroon', 'Corporate Sector', 'Outer Rim Territories', 'S-4'),
('Durren', 'Meridian', 'Outer Rim Territories', 'R-7'),
('Dustig', 'Dustig', 'Mid Rim', 'N-16'),
('Duunir', 'Kibilini', 'Outer Rim Territories', 'Q-17'),
('Duzay', 'Alui', 'Mid Rim', 'O-17'),
('Dwartii', 'Nouane', 'Inner Rim', 'N-8'),
('Dweem', 'Calaron', 'Outer Rim Territories', 'T-9'),
('Dwor', 'Steniplis', 'Outer Rim Territories', 'L-19'),
('Dybbron', 'Nythlide', 'Inner Rim', 'L-15'),
('Dybrin', NULL, 'Deep Core', 'L-12'),
('Dyspeth', 'Varada', 'Outer Rim Territories', 'I-20'),
('Dzass', 'Seswenna', 'Outer Rim Territories', 'M-17'),
('Eadu', 'Bheriz', 'Outer Rim Territories', 'U-10'),
('Ealor', 'Parmic', 'Outer Rim Territories', 'P-18'),
('Eamus', NULL, 'Core Worlds', 'L-13'),
('Ebaq', NULL, 'Deep Core', 'M-11'),
('Ebenmal', 'Irnaj', 'Mid Rim', 'K-17'),
('Eberon', 'Mytaranor', 'Mid Rim', 'P-9'),
('Ebiwaan', 'Sarin', 'Outer Rim Territories', 'P-18'),
('Ebra', 'Kesh', 'Mid Rim', 'L-6'),
('Ec Pand', 'Ado', 'Mid Rim', 'M-17'),
('Echerta', 'Koradin', 'Outer Rim Territories', 'J-18'),
('Echnos', 'Hadar', 'Mid Rim', 'L-17'),
('Eckless', NULL, 'Wild Space', 'J-3'),
('Eczar', 'Seswenna', 'Outer Rim Territories', 'M-18'),
('Edan', 'Hythrope', 'Expansion Region', 'M-15'),
('Edatha', 'Vatha', 'Expansion Region', 'K-16'),
('Ediorung', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Edis', 'Farana', 'Wild Space', 'S-3'),
('Edonaaris', 'Thrasybule', 'Outer Rim Territories', 'P-6'),
('Edusa', 'Morshdine', 'Outer Rim Territories', 'O-5'),
('Eedoq', 'Tantra (Methall''has)', 'Outer Rim Territories', 'M-19'),
('Eeyyon', 'Halm', 'Mid Rim', 'J-16'),
('Egaria', 'Svivreni', 'Outer Rim Territories', 'O-19'),
('Egips', 'Tharin (Periphery)', 'Outer Rim Territories', 'S-8'),
('Ehjenla', 'Kathol (Outback)', 'Outer Rim Territories', 'M-21'),
('Eiattu', 'Ado', 'Mid Rim', 'L-17'),
('Eibon', 'Cronese Mandate', 'Outer Rim Territories', 'S-6'),
('Eidoloni', 'Eidoloni', 'Mid Rim', 'M-16'),
('Eilnia', NULL, 'Inner Rim', 'N-9'),
('Eiloroseint', 'Tokamac', 'Expansion Region', 'N-13'),
('Eiram', 'Tunka (Dalnan)', 'Outer Rim Territories', 'I-19'),
('Eirrauus', 'Quence', 'Outer Rim Territories', 'P-18'),
('Eislo', 'Eislomi', 'Inner Rim', 'O-8'),
('Ejolus', NULL, 'Inner Rim', 'M-8'),
('Ekibo', 'Trianii Space', 'Wild Space', 'R-3'),
('Elamposnia', 'Gordian Reach', 'Outer Rim Territories', 'Q-5'),
('Elatha', 'Stensen', 'Outer Rim Territories', 'I-17'),
('Elbara', 'Elbaran', 'Mid Rim', 'J-17'),
('Elbra', 'Airam', 'Outer Rim Territories', 'M-20'),
('Elcorth', 'Farlax', 'Core Worlds', 'K-10'),
('Elegasso', 'Irishi', 'Mid Rim', 'K-6'),
('Elerion', 'Thanium', 'Outer Rim Territories', 'R-6'),
('Elessia', 'Vendusii', 'Mid Rim', 'P-16'),
('Elgamor', 'Maldrood', 'Mid Rim', 'R-7'),
('Elgit', 'Hutt Space', 'Hutt Space', 'T-10'),
('Eliad', 'Minos Cluster', 'Outer Rim Territories', 'M-20'),
('Elin Roe', NULL, 'Colonies', 'N-12'),
('Elkeenar', NULL, 'Wild Space', 'K-21'),
('Elkkasinn', 'Phelleem', 'Outer Rim Territories', 'S-7'),
('Elliirad', 'Airam', 'Outer Rim Territories', 'L-20'),
('Elom', 'Sertar', 'Outer Rim Territories', 'R-5'),
('Elphrona', 'Bri''ahl', 'Outer Rim Territories', 'I-17'),
('Elriss', 'Onatos', 'Mid Rim', 'R-15'),
('Elrood', 'Elrood', 'Outer Rim Territories', 'M-20'),
('Elshandruu Pica', 'Quence', 'Outer Rim Territories', 'O-18'),
('Embaril', 'Allied Tion', 'Outer Rim Territories', 'S-6'),
('Emberlene', 'Authala', 'Expansion Region', 'P-12'),
('Emmer', 'Nilgaard', 'Outer Rim Territories', 'S-5'),
('Emoh', 'Ploo', 'Expansion Region', 'N-7'),
('Emorus', NULL, 'Inner Rim', 'O-10'),
('Empartheca', 'Hook Nebula', 'Outer Rim Territories', 'O-18');