-- Insert galactic systems from Quellus to Rirsack (224 systems)
INSERT INTO galactic_systems (name, sector, region, grid_coordinates) VALUES
('Quellus', NULL, 'Wild Space', 'G-14'),
('Queluhan Nebula', NULL, 'Wild Space', 'H-12'),
('Quenk', 'Corusca', 'Core Worlds', 'L-9'),
('Quermia', 'Nilgaard', 'Outer Rim Territories', 'S-5'),
('Ques', 'Hutt Space', 'Outer Rim Territories', 'S-8'),
('Quesaya', 'Andirma', 'Expansion Region', 'L-15'),
('Quesh', 'Hutt Space', 'Outer Rim Territories', 'S-10'),
('Quesna', 'Toblain', 'Outer Rim Territories', 'O-18'),
('Questal', 'Questal', 'Core Worlds', 'J-12'),
('Quethold', NULL, 'Unknown Regions', 'I-5'),
('Queyta', 'Danjar', 'Outer Rim Territories', 'M-19'),
('Quian', NULL, 'Core Worlds', 'L-9'),
('Quiberon', 'Quiberon', 'Outer Rim Territories', 'T-15'),
('Quila', 'Rolion', 'Outer Rim Territories', 'P-7'),
('Quilan', 'Roche', 'Mid Rim', 'Q-8'),
('Quilken', 'Abrion', 'Outer Rim Territories', 'R-15'),
('Quint', NULL, 'Inner Rim', 'M-8'),
('Quintar Nebula', 'Surron', 'Expansion Region', 'O-13'),
('Quintarad, The', NULL, 'Wild Space', 'H-18'),
('Quintil', 'Svivreni', 'Outer Rim Territories', 'N-19'),
('Quintus', 'Albarrio', 'Outer Rim Territories', 'K-5'),
('Quockra', 'Minos Cluster', 'Outer Rim Territories', 'M-20'),
('Quooria', 'Farstey', 'Expansion Region', 'O-8'),
('Quyste', 'Thesme', 'Outer Rim Territories', 'O-6'),
('R-Duba', 'Quiberon', 'Outer Rim Territories', 'T-15'),
('R''alla', 'Corporate Sector', 'Outer Rim Territories', 'S-3'),
('R''terleD''er', 'Kriz', 'Outer Rim Territories', 'J-18'),
('Raada', 'D''Astan', 'Outer Rim Territories', 'O-5'),
('Raamen', 'Tacuni', 'Expansion Region', 'N-15'),
('Rachuk', 'Rachuk', 'Colonies', 'N-11'),
('Radama Void', 'Esstran', 'Outer Rim Territories', 'Q-5'),
('Raddan', 'Tharin', 'Outer Rim Territories', 'S-8'),
('Radhii', NULL, 'Wild Space', 'I-18'),
('Radnor', 'Daimar', 'Mid Rim', 'Q-16'),
('Raed', NULL, 'Colonies', 'N-11'),
('Rafa', 'Centrality', 'Outer Rim Territories', 'T-8'),
('Rafft', NULL, 'Inner Rim', 'J-8'),
('Ragith', 'Majoor', 'Expansion Region', 'N-15'),
('Ragmar', 'Karthakk', 'Outer Rim Territories', 'Q-17'),
('Ragna', 'Daimar', 'Mid Rim', 'Q-16'),
('Ragnar', 'Merel', 'Outer Rim Territories', 'Q-18'),
('Ragnook', 'Bothan', 'Mid Rim', 'R-14'),
('Rago', NULL, 'Wild Space', 'I-7'),
('Ragoon', NULL, 'Core Worlds', 'K-9'),
('Raider''s Point', 'Corellian', 'Core Worlds', 'M-11'),
('Rainboh', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Rainbow Nebulae', 'Hunnoverrs', 'Outer Rim Territories', 'R-16'),
('Rainos Cluster', 'Rocantor', 'Expansion Region', 'L-15'),
('Raithal', NULL, 'Colonies', 'M-9'),
('Rajtiri', 'Dona Laza', 'Expansion Region', 'P-9'),
('Rakaa', NULL, 'Core Worlds', 'J-12'),
('Rakata Prime', NULL, 'Unknown Regions', 'G-11'),
('Rakhuuun', 'Mytaranor', 'Mid Rim', 'Q-10'),
('Rakrir', 'Kwymar', 'Outer Rim Territories', 'Q-4'),
('Ralgos', 'Esstran', 'Outer Rim Territories', 'Q-5'),
('Ralltiir', 'Darpa', 'Core Worlds', 'L-9'),
('Ralme', 'Brak', 'Expansion Region', 'O-14'),
('Raltac', NULL, 'Inner Rim', 'K-8'),
('Ramoa', 'Sprizen', 'Outer Rim Territories', 'N-5'),
('Ramodi', 'Tregillis', 'Expansion Region', 'M-15'),
('Ramook', NULL, 'Wild Space', 'O-3'),
('Ramordia', 'Majoor', 'Expansion Region', 'N-15'),
('Ramorea', NULL, 'Inner Rim', 'O-7'),
('Rampa', 'Corporate Sector', 'Outer Rim Territories', 'S-4'),
('Rampa Minor', 'Baxel', 'Outer Rim Territories', 'U-12'),
('Ramsir', 'Jospro', 'Outer Rim Territories', 'S-7'),
('Randa', 'Kessel', 'Outer Rim Territories', 'T-10'),
('Randon', 'Mytaranor', 'Mid Rim', 'Q-10'),
('Randorn', 'Belderone', 'Outer Rim Territories', 'Q-6'),
('Rango Tan', 'Relgim', 'Outer Rim Territories', 'L-5'),
('Rangorah', 'Calaron', 'Outer Rim Territories', 'T-9'),
('Ranklinge', 'Shelsha', 'Colonies', 'M-9'),
('Rannon', 'Instrop', 'Outer Rim Territories', 'T-17'),
('Ranroon', 'Mortex', 'Outer Rim Territories', 'R-5'),
('Rantine Space Station', 'Tamarin', 'Outer Rim Territories', 'N-19'),
('Rantofar', NULL, 'Core Worlds', 'M-11'),
('Rapacc', 'Paccian Governance', 'Unknown Regions', 'E-7'),
('Raquish', 'Lambda', 'Mid Rim', 'Q-15'),
('Rarlech', NULL, 'Unknown Regions', 'H-5'),
('Rashfond', NULL, 'Inner Rim', 'L-14'),
('Raskane', 'Sepan', 'Expansion Region', 'P-13'),
('Raspar', 'Tragan Cluster', 'Outer Rim Territories', 'N-5'),
('Rasterous', NULL, 'Inner Rim', 'O-10'),
('Rata Nebula', 'Chiss Space', 'Unknown Regions', 'E-9'),
('Ratamesh', 'Farstey', 'Expansion Region', 'O-8'),
('Rathalay', 'Taldot', 'Mid Rim', 'R-9'),
('Ratit', NULL, 'Inner Rim', 'M-14'),
('Rattatak', 'Trilon', 'Outer Rim Territories', 'H-16'),
('Ravaath', 'Pacanth Reach', 'Outer Rim Territories', 'H-16'),
('Ravager''s Rift', 'Iska', 'Mid Rim', 'J-17'),
('Raxus Prime', 'Tion Hegemony', 'Outer Rim Territories', 'S-5'),
('Raxxa', NULL, 'Core Worlds', 'M-10'),
('Raydonia', 'Belsmuth', 'Outer Rim Territories', 'O-6'),
('Raysol Prime', 'Duluur', 'Colonies', 'M-13'),
('Razia', NULL, 'Colonies', 'M-13'),
('Rbollea', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Reamma', 'Corbett', 'Outer Rim Territories', 'I-17'),
('Reaper''s World', 'Nilgaard', 'Outer Rim Territories', 'S-5'),
('Rearqu Cluster', 'Taldot', 'Mid Rim', 'P-8'),
('Reboam', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Recluse''s Nebula', 'Irishi', 'Mid Rim', 'K-6'),
('Recopia', NULL, 'Core Worlds', 'M-11'),
('Red Hand Cluster', 'Trax', 'Mid Rim', 'Q-10'),
('Red Nebula', NULL, 'Wild Space', 'G-21'),
('Red Twins, The', NULL, 'Wild Space', 'I-7'),
('Red Yars', 'Croynar', 'Inner Rim', 'M-14'),
('Redcap', 'Savareen', 'Outer Rim Territories', 'Q-17'),
('Redhurne', 'Metatessu', 'Mid Rim', 'R-9'),
('Redoubt, The', NULL, 'Unknown Regions', 'H-7'),
('Redrish', 'Kuat', 'Core Worlds', 'M-10'),
('Redspace Reefs', 'Oktos', 'Mid Rim', 'R-12'),
('Reecee', NULL, 'Inner Rim', 'J-8'),
('Reega', 'Demetras', 'Outer Rim Territories', 'P-7'),
('Reegian', 'Sumitra', 'Expansion Region', 'O-7'),
('Reena', 'Tapani', 'Colonies', 'L-13'),
('Reena Minor', 'Bothan', 'Mid Rim', 'R-14'),
('Reesaria', 'Bheriz', 'Outer Rim Territories', 'U-10'),
('Refgar', 'Demophon', 'Core Worlds', 'M-10'),
('Refnar', 'Pakuuni', 'Outer Rim Territories', 'T-6'),
('Refnu', 'Sprizen', 'Outer Rim Territories', 'N-5'),
('Refrax', 'Mortex', 'Outer Rim Territories', 'R-5'),
('Regalia', 'Meram', 'Outer Rim Territories', 'O-4'),
('Regalia Station', 'Cadavine', 'Outer Rim Territories', 'P-17'),
('Regel', NULL, 'Wild Space', 'I-7'),
('Regellia', 'Minos Cluster', 'Outer Rim Territories', 'M-20'),
('Reginard', 'Pakuuni', 'Outer Rim Territories', 'T-6'),
('Regolith', NULL, 'Colonies', 'N-12'),
('Regor-Mada', 'Tantra', 'Outer Rim Territories', 'M-19'),
('Regulan', 'Albanin', 'Outer Rim Territories', 'U-12'),
('Regulgo', 'Ryndellian', 'Mid Rim', 'P-17'),
('Rehemsa', NULL, 'Core Worlds', 'M-11'),
('Rehn', 'Brak', 'Expansion Region', 'O-14'),
('Reibrin', 'Suolriep (Ansuroer)', 'Outer Rim Territories', 'S-8'),
('Reigalius', 'Yucrales', 'Mid Rim', 'Q-15'),
('Rekelos', 'Arc d''Stot', 'Expansion Region', 'K-15'),
('Rekkana', NULL, 'Core Worlds', 'L-9'),
('Rekkiad', 'Chorlian', 'Outer Rim Territories', 'S-4'),
('Relarr', NULL, 'Core Worlds', 'M-10'),
('Relatta', NULL, 'Inner Rim', 'N-8'),
('Relephon', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Relkass', 'Saijo', 'Outer Rim Territories', 'K-20'),
('Rellio', 'Tapani', 'Colonies', 'L-13'),
('Rellnas', 'Har Worlds', 'Expansion Region', 'J-16'),
('Reltooine', 'Corporate Sector', 'Outer Rim Territories', 'R-3'),
('Remitik', 'Wazta', 'Outer Rim Territories', 'J-18'),
('Remmon Nebula', 'Iskin', 'Mid Rim', 'O-16'),
('Rena', NULL, 'Colonies', 'K-13'),
('Renatasia', 'Centrality', 'Outer Rim Territories', 'U-8'),
('Rend', 'Surron', 'Expansion Region', 'O-13'),
('Rendili', NULL, 'Core Worlds', 'M-11'),
('Renforra', 'Dalicron', 'Outer Rim Territories', 'K-20'),
('Renigg', 'Kuat', 'Core Worlds', 'M-10'),
('Renillis', NULL, 'Inner Rim', 'L-14'),
('Rennokk', 'Kessel', 'Outer Rim Territories', 'U-10'),
('Rentalles', 'D''Astan', 'Outer Rim Territories', 'O-4'),
('Rentaxius', NULL, 'Inner Rim', 'O-8'),
('Rentean', 'Jjannex', 'Outer Rim Territories', 'K-19'),
('Rentor', 'Chiss Space', 'Unknown Regions', 'F-8'),
('Reo', 'Maraqoo', 'Mid Rim', 'I-7'),
('Reopi', NULL, 'Core Worlds', 'M-10'),
('Repea', 'Auril', 'Outer Rim Territories', 'R-7'),
('Resh 9376', 'Nuiri', 'Outer Rim Territories', 'Q-6'),
('Resht', NULL, 'Colonies', 'N-10'),
('Resilon', 'Bortele', 'Mid Rim', 'S-8'),
('Resti Kel', 'Juvex', 'Mid Rim', 'L-18'),
('Retep', 'Daimar', 'Mid Rim', 'Q-16'),
('Rethel Point Far', 'Xandil', 'Mid Rim', 'P-16'),
('Retta', NULL, 'Wild Space', 'U-8'),
('Rettna', 'Esaga', 'Mid Rim', 'Q-11'),
('Reuss', 'Portmoak', 'Outer Rim Territories', 'P-18'),
('Revery', 'Noonian', 'Outer Rim Territories', 'N-6'),
('Revkinn', 'Parmel', 'Outer Rim Territories', 'O-18'),
('Revyia', 'Veragi', 'Outer Rim Territories', 'L-2'),
('Rex Strata', 'Wazta', 'Outer Rim Territories', 'J-18'),
('Reyna', 'Tapani', 'Colonies', 'L-13'),
('Reyniu', 'Mayagil', 'Outer Rim Territories', 'N-18'),
('Reynon', 'Albarrio', 'Outer Rim Territories', 'K-5'),
('Reytha', 'Harron', 'Expansion Region', 'O-12'),
('Rezi', 'Bajic', 'Outer Rim Territories', 'P-17'),
('Rhamalai', 'Varada', 'Outer Rim Territories', 'I-19'),
('Rhamsis Callo', 'Danjar', 'Outer Rim Territories', 'N-19'),
('Rhelg', 'Esstran (Sith Worlds)', 'Outer Rim Territories', 'R-5'),
('Rhen Var', 'Thanium', 'Outer Rim Territories', 'R-6'),
('Rhigar', 'Chiss Space', 'Unknown Regions', 'E-9'),
('Rhilithan', 'Indrexu', 'Outer Rim Territories', 'S-5'),
('Rhinnal', 'Darpa', 'Core Worlds', 'L-9'),
('Rhommamool', 'Merthian', 'Expansion Region', 'N-13'),
('Rhuvia', 'Relgim', 'Outer Rim Territories', 'L-5'),
('Rial Kroon', 'Noonian', 'Outer Rim Territories', 'M-6'),
('Rianon', 'Tapani', 'Colonies', 'L-13'),
('Ricaldi', 'Tapani', 'Colonies', 'L-13'),
('Riddellia', 'Albanin', 'Outer Rim Territories', 'T-12'),
('Ridlay', 'Lambda', 'Mid Rim', 'P-16'),
('Riesa', 'Tapani', 'Colonies', 'L-13'),
('Riflor', 'Narrant', 'Mid Rim', 'J-16'),
('Rigel', 'Bheriz', 'Outer Rim Territories', 'U-11'),
('Rigoron', 'Dimean', 'Expansion Region', 'P-13'),
('Rigovia', NULL, 'Inner Rim', 'N-8'),
('Riileb', 'Hutt Space', 'Outer Rim Territories', 'T-12'),
('Rijel', 'Dalqan', 'Expansion Region', 'M-7'),
('Rikadi', NULL, 'Inner Rim', 'J-13'),
('Rikmania', 'Steniplis', 'Outer Rim Territories', 'L-19'),
('Rim', 'Kibilini', 'Outer Rim Territories', 'Q-17'),
('Rimbaux', 'Halthor', 'Outer Rim Territories', 'M-6'),
('Rimcee Station', 'Braxant', 'Outer Rim Territories', 'J-3'),
('Rimma', NULL, 'Core Worlds', 'L-13'),
('Rina Major', 'Stensen', 'Outer Rim Territories', 'I-17'),
('Rinagom', 'Corporate Sector', 'Outer Rim Territories', 'S-3'),
('Rindao', 'Hadar', 'Mid Rim', 'L-17'),
('Rindia', 'Nembus', 'Outer Rim Territories', 'P-4'),
('Rindoon', 'Rseik', 'Outer Rim Territories', 'N-19'),
('Rine-cathe', NULL, 'Core Worlds', 'L-9'),
('Ring of Kafrene', 'Thand', 'Expansion Region', 'J-15'),
('Ring, The', 'Javin (Anoat)', 'Outer Rim Territories', 'K-18'),
('Ringali Nebula', 'Bormea', 'Core Worlds', 'L-9'),
('Ringlite', 'Tamarin', 'Outer Rim Territories', 'N-19'),
('Ringneldia', 'Centrality', 'Outer Rim Territories', 'T-8'),
('Ringo Vinda', 'Eucer', 'Mid Rim', 'R-7'),
('Rinn', 'Baxel', 'Outer Rim Territories', 'U-12'),
('Rintonne', 'Lambda', 'Mid Rim', 'P-16'),
('Rion', 'Kessel', 'Outer Rim Territories', 'T-10'),
('Rior', 'Tamarin', 'Outer Rim Territories', 'N-18'),
('Riosa', NULL, 'Inner Rim', 'J-8'),
('Rirsack', 'Belsmuth', 'Outer Rim Territories', 'O-6');