-- Insert galactic systems from Tion to UR-2212-GR
INSERT INTO public.galactic_systems (name, sector, region, grid_coordinates) VALUES
('Tion', 'Tion Hegemony', 'Outer Rim Territories', 'S-5'),
('Tirac', 'Munda Hevvrol', 'Mid Rim', 'P-15'),
('Tiragga', 'Mieru''kar', 'Outer Rim Territories', 'N-3'),
('Tirahnn', 'Zeemacht Cluster', 'Inner Rim', 'N-8'),
('Tirn', 'Esstran', 'Outer Rim Territories', 'Q-5'),
('Tirsa', 'Corporate Sector', 'Outer Rim Territories', 'S-4'),
('Tisheraan', NULL, 'Inner Rim', 'N-8'),
('Tisht', NULL, 'Hutt Space', 'T-11'),
('Tiss''sharl', 'Xappyh', 'Outer Rim Territories', 'R-4'),
('Tizon', 'Farlax', 'Core Worlds', 'K-10'),
('Tlactehon', 'Kailion', 'Expansion Region', 'O-13'),
('Tlönia', 'Demetras', 'Outer Rim Territories', 'P-7'),
('To''hok', 'Neige Kriz', 'Outer Rim Territories', 'J-18'),
('Tocan', 'Sumitra', 'Expansion Region', 'N-7'),
('Tocco', 'Tapani', 'Colonies', 'L-13'),
('Tocoya', 'Ktilac Regions', 'Inner Rim', 'N-9'),
('Todirium', 'Demetras', 'Outer Rim Territories', 'P-7'),
('Todola', 'Albarrio', 'Outer Rim Territories', 'K-5'),
('Todouhar', 'Seswenna', 'Outer Rim Territories', 'M-18'),
('Togominda', 'Javin (Yarith)', 'Outer Rim Territories', 'K-18'),
('Togoria', 'Taldot', 'Mid Rim', 'P-9'),
('Tokmia', 'Javin (Anoat)', 'Outer Rim Territories', 'K-18'),
('Tokuut', 'Demetras', 'Mid Rim', 'P-7'),
('Tol Ado', 'Seitia', 'Outer Rim Territories', 'K-19'),
('Tol Amn', NULL, 'Hutt Space', 'R-11'),
('Tolan', NULL, 'Colonies', 'L-9'),
('Toledian', 'Narrant', 'Mid Rim', 'I-16'),
('Tolfrania', NULL, 'Inner Rim', 'N-9'),
('Tolig', 'Mayagil', 'Outer Rim Territories', 'N-18'),
('Tomark', 'Ividal', 'Mid Rim', 'Q-14'),
('Tomo-Reth', NULL, 'Inner Rim', 'L-14'),
('Ton-Falk', 'Pakuuni', 'Outer Rim Territories', 'T-5'),
('Tonnis', 'Tonnis', 'Inner Rim', 'I-9'),
('Toola', 'Nilgaard', 'Outer Rim Territories', 'S-5'),
('Tooma', 'Colundra', 'Outer Rim Territories', 'S-5'),
('Toor''l', 'Jubilar', 'Outer Rim Territories', 'T-7'),
('Toorja', 'Tapani', 'Colonies', 'L-13'),
('Toprawa', 'Kalamith', 'Outer Rim Territories', 'P-5'),
('Torch Nebula', 'Torch Nebula', 'Outer Rim Territories', 'P-19'),
('Toria-vic Nebula', NULL, 'Wild Space', 'S-3'),
('Torina', 'Elrood', 'Outer Rim Territories', 'M-19'),
('Torize', 'Kathol', 'Outer Rim Territories', 'M-21'),
('Tormin', 'Prackla', 'Expansion Region', 'O-8'),
('Torn Station', 'Mytaranor', 'Mid Rim', 'P-10'),
('Torolis', 'Bothan', 'Mid Rim', 'Q-13'),
('Torost', 'Bryx', 'Mid Rim', 'R-7'),
('Torphlus', 'Roche', 'Mid Rim', 'Q-8'),
('Torpris', 'Uoti', 'Core Worlds', 'K-9'),
('Torque', 'Gordian Reach', 'Outer Rim Territories', 'P-6'),
('Torrad', 'Talcene', 'Mid Rim', 'Q-8'),
('Torrenoteer', 'Spadja', 'Outer Rim Territories', 'R-5'),
('Torria', NULL, 'Core Worlds', 'M-12'),
('Tortali', 'Airam', 'Outer Rim Territories', 'L-19'),
('Torve', 'Brak', 'Expansion Region', 'O-14'),
('Toshara', 'Cadma', 'Outer Rim Territories', 'T-8'),
('Toskhowwl', 'Ottega', 'Mid Rim', 'M-6'),
('Tosste', 'Atravis', 'Outer Rim Territories', 'L-19'),
('Tothis', 'Corporate Sector', 'Outer Rim Territories', 'S-3'),
('Touksingal', 'Corva', 'Outer Rim Territories', 'P-3'),
('Tourani', 'Yucrales', 'Mid Rim', 'R-15'),
('Tovarskl', NULL, 'Wild Space', 'J-4'),
('Tovash', 'Tchii Alui', 'Mid Rim', 'O-17'),
('Tovio', 'Aida', 'Mid Rim', 'Q-13'),
('Toydaria', NULL, 'Hutt Space', 'R-11'),
('Tozeer', 'Hunnoverrs', 'Outer Rim Territories', 'R-16'),
('Tragrud', 'Tharin (Periphery)', 'Outer Rim Territories', 'S-8'),
('Trailia', 'Lothal', 'Outer Rim Territories', 'U-7'),
('Tralfin', 'Xappyh', 'Outer Rim Territories', 'Q-3'),
('Tralgaria', 'Parmic', 'Outer Rim Territories', 'P-18'),
('Trallan', NULL, 'Colonies', 'K-9'),
('Tramanos', 'Grumani', 'Outer Rim Territories', 'N-17'),
('Trammen', 'Harron', 'Expansion Region', 'O-11'),
('Trammis', 'Centrality', 'Outer Rim Territories', 'U-8'),
('Tran Mariel', 'Farlax', 'Core Worlds', 'K-10'),
('Tranchar', 'Belderone', 'Outer Rim Territories', 'R-6'),
('Trancret', 'Perkell', 'Mid Rim', 'Q-7'),
('Transel', NULL, 'Colonies', 'L-13'),
('Tranthellix', 'Senex', 'Mid Rim', 'L-18'),
('Trantor', NULL, 'Core Worlds', 'M-10'),
('Traptoforia', 'Thrasybule', 'Outer Rim Territories', 'P-6'),
('Trascor', 'Corva', 'Outer Rim Territories', 'P-3'),
('Trasemene', 'Phelleem', 'Outer Rim Territories', 'S-7'),
('Trasse', 'Sarka', 'Mid Rim', 'Q-8'),
('Trassitan', 'Veragi', 'Outer Rim Territories', 'L-3'),
('Traval-Pacor', 'Pacor', 'Mid Rim', 'K-7'),
('Travnin', 'Minos Cluster', 'Outer Rim Territories', 'M-20'),
('Trebela', 'Altier', 'Expansion Region', 'O-13'),
('Treffani', 'Treffani', 'Expansion Region', 'O-14'),
('Tregillis', 'Tregillis', 'Expansion Region', 'M-15'),
('Trellen', NULL, 'Core Worlds', 'M-10'),
('Trenchenovu', 'Kriz', 'Outer Rim Territories', 'K-19'),
('Trendivar', 'Hunnoverrs', 'Outer Rim Territories', 'R-16'),
('Trenwyth', 'Stensen', 'Outer Rim Territories', 'I-16'),
('Tresidiss', 'Quence', 'Outer Rim Territories', 'P-18'),
('Trevi', 'Quess', 'Mid Rim', 'N-17'),
('Trevura', NULL, 'Inner Rim', 'K-14'),
('Treylon', NULL, 'Colonies', 'L-13'),
('Tri-Barr Station', NULL, 'Inner Rim', 'N-11'),
('Trian', 'Trianii Space*', 'Wild Space', 'R-3'),
('Triellus', 'Jospro', 'Outer Rim Territories', 'R-7'),
('Triewahl', 'Homon', 'Mid Rim', 'M-7'),
('Trif', 'Ciutric', 'Outer Rim Territories', 'N-4'),
('Triffis', 'Hevvrol', 'Mid Rim', 'O-15'),
('Trigalis', 'Juris', 'Outer Rim Territories', 'P-17'),
('Trigaskian Blur', NULL, 'Wild Space', 'W-10'),
('Triitus', 'Corva', 'Outer Rim Territories', 'P-4'),
('Trillia', 'Imberlin', 'Expansion Region', 'P-14'),
('Trindello', 'Zuma (Moddell)', 'Outer Rim Territories', 'H-16'),
('Trinith', 'Mondress', 'Expansion Region', 'I-7'),
('Trinovat', 'Gordian Reach', 'Outer Rim Territories', 'P-6'),
('Trinta', 'Halthor', 'Outer Rim Territories', 'L-6'),
('Trionak', 'Javin (Yarith)', 'Outer Rim Territories', 'J-18'),
('Tristall', NULL, 'Colonies', 'L-9'),
('Triton', 'Mayagil', 'Outer Rim Territories', 'M-18'),
('Trivar', 'Nuiri', 'Outer Rim Territories', 'Q-6'),
('Trogan', 'Jospro', 'Outer Rim Territories', 'R-7'),
('Troglofa', 'Belderone', 'Outer Rim Territories', 'R-6'),
('Troika', 'Colundra', 'Outer Rim Territories', 'S-5'),
('Troiken', 'Colundra', 'Outer Rim Territories', 'S-5'),
('Troos', 'Gordian Reach', 'Outer Rim Territories', 'Q-5'),
('Trosh', 'Cegul', 'Outer Rim Territories', 'L-20'),
('Troska', 'Dantus', 'Outer Rim Territories', 'J-6'),
('Troxar', 'Bes Ber Bikade', 'Expansion Region', 'L-15'),
('Trundalki', 'Xan', 'Mid Rim', 'Q-15'),
('Trunska', NULL, 'Colonies', 'J-13'),
('Trupellia', NULL, 'Colonies', 'M-13'),
('Truuine', NULL, 'Inner Rim', 'O-11'),
('Truuzdann', 'Corellian', 'Core Worlds', 'M-11'),
('Truwel', 'Videnda', 'Outer Rim Territories', 'L-18'),
('Trydara', 'Barsa', 'Mid Rim', 'J-6'),
('Trymant', 'Subterrel', 'Outer Rim Territories', 'L-20'),
('Tsevuka', 'Cademimu', 'Outer Rim Territories', 'M-6'),
('Tsoss Beacon', NULL, 'Deep Core', 'L-11'),
('Tsukimitsurin', 'Churnis', 'Mid Rim', 'J-6'),
('Tsukkia', 'Fakir', 'Colonies', 'K-9'),
('Tsyk', NULL, 'Hutt Space', 'T-13'),
('Tu''oon', 'Juris', 'Outer Rim Territories', 'P-13'),
('Tuerto', 'Brema', 'Outer Rim Territories', 'M-17'),
('Tujiamoor', NULL, 'Inner Rim', 'K-14'),
('Tulatharri Junction', 'Veragi', 'Outer Rim Territories', 'K-3'),
('Tumani', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Tumus', 'Tapani', 'Colonies', 'L-13'),
('Tun Wala', 'Ktilac Regions', 'Inner Rim', 'N-9'),
('Tund', 'Centrality', 'Outer Rim Territories', 'U-8'),
('Tungra', 'Tungra', 'Outer Rim Territories', 'K-18'),
('Turak', 'Parmel', 'Outer Rim Territories', 'O-18'),
('Turcan', 'Parmel', 'Outer Rim Territories', 'O-18'),
('Turclom', 'Dustig', 'Mid Rim', 'N-16'),
('Turco Prime', 'Sarka', 'Mid Rim', 'Q-8'),
('Tureen', 'Kriz', 'Outer Rim Territories', 'K-19'),
('Turkana', 'Pakuuni', 'Outer Rim Territories', 'T-6'),
('Turrani', 'Bheriz', 'Outer Rim Territories', 'U-11'),
('Tusken''s Eye', NULL, 'Wild Space', 'I-8'),
('Tuttin', NULL, 'Inner Rim', 'M-14'),
('Twilight Void, The', NULL, 'Unknown Regions', 'D-7'),
('Twin Nebulae', 'Javin', 'Outer Rim Territories', 'K-18'),
('Twin Sun Station', 'Garis', 'Outer Rim Territories', 'N-17'),
('Twins, The', 'Obtrexta', 'Outer Rim Territories', 'K-4'),
('Twith', NULL, 'Core Worlds', 'K-9'),
('Twon Ketee', 'Quence', 'Outer Rim Territories', 'P-18'),
('Tyan', 'Tyan', 'Mid Rim', 'K-7'),
('Tyaonon', NULL, 'Wild Space', 'R-18'),
('Tyberious', NULL, 'Inner Rim', 'L-8'),
('Tydane', 'Bryx', 'Mid Rim', 'R-7'),
('Tyed Kant', NULL, 'Core Worlds', 'M-10'),
('Tyegin', NULL, 'Inner Rim', 'O-10'),
('Tyluun', 'Juvex', 'Mid Rim', 'L-18'),
('Tyne Albamon', 'Rseik', 'Outer Rim Territories', 'N-20'),
('Tyne''s Horky', 'Teraab', 'Mid Rim', 'Q-11'),
('Tynna', 'Tynna', 'Expansion Region', 'N-14'),
('Typhonic Nebula', 'Trax', 'Mid Rim', 'Q-11'),
('Tyrellia', 'Minos Cluster', 'Outer Rim Territories', 'M-20'),
('Tyria', 'Hevvrol', 'Mid Rim', 'P-15'),
('Tyrusia', NULL, 'Inner Rim', 'N-8'),
('Tyshapahl', 'Kalamith', 'Outer Rim Territories', 'P-5'),
('Tythe', 'Savareen', 'Outer Rim Territories', 'Q-16'),
('Tython', NULL, 'Deep Core', 'L-10'),
('Tyus Cluster', 'Tyus', 'Mid Rim', 'N-16'),
('Tyybann', NULL, 'Inner Rim', 'J-13'),
('Tzarib', 'Mestani', 'Inner Rim', 'J-9'),
('U-Tendik', 'Trans-Nebular', 'Mid Rim', 'Q-16'),
('U''Dray', 'Hook Nebula', 'Outer Rim Territories', 'O-18'),
('Uaua', 'Centrality', 'Outer Rim Territories', 'U-8'),
('Uba', 'Barsa', 'Mid Rim', 'J-6'),
('Ubardia', NULL, 'Colonies', 'N-12'),
('Ubduria', NULL, 'Inner Rim', 'N-8'),
('Ubertica', 'Barsa', 'Mid Rim', 'J-6'),
('Ubrikkia', 'Kastolar', 'Mid Rim', 'Q-10'),
('Ubuuga', 'Halori', 'Mid Rim', 'Q-7'),
('Ucret', NULL, 'Core Worlds', 'K-10'),
('Udine', NULL, 'Inner Rim', 'M-15'),
('Udnil', 'Airam', 'Outer Rim Territories', 'M-20'),
('Udrin', 'Cara Lannik Wilds', 'Mid Rim', 'R-13'),
('Uhltenden', 'Thrasybule', 'Outer Rim Territories', 'P-6'),
('Ukatis', NULL, 'Inner Rim', 'L-15'),
('Ukio', 'Abrion', 'Outer Rim Territories', 'S-15'),
('Ulda Frav', 'Hangshan', 'Expansion Region', 'P-11'),
('Ulicia', 'Corporate Sector', 'Outer Rim Territories', 'S-3'),
('Ulion', 'Kuat', 'Core Worlds', 'M-10'),
('Ulkantha', 'Tharin', 'Outer Rim Territories', 'S-8'),
('Ulmatra', NULL, 'Hutt Space', 'S-10'),
('Ulness Prime', 'Merthian', 'Expansion Region', 'N-13'),
('Ultaar', 'Bortele', 'Mid Rim', 'R-8'),
('Umaren''k', NULL, 'Unknown Regions', 'G-9'),
('Umbara', 'Ghost Nebula', 'Expansion Region', 'P-10'),
('Umgul', 'Mulgard', 'Mid Rim', 'N-16'),
('Umme', 'Trilon', 'Outer Rim Territories', 'G-15'),
('Umthyg', 'Juvex', 'Mid Rim', 'K-18'),
('Unagin', 'Al''Nasrl', 'Outer Rim Territories', 'T-13'),
('Unavartan', 'Gaulus', 'Outer Rim Territories', 'S-17'),
('Unguule Nebula', NULL, 'Wild Space', 'I-20'),
('Unnipar', NULL, 'Wild Space', 'H-19'),
('Unox', 'Astal', 'Outer Rim Territories', 'P-18'),
('Unroola Dawn', 'Doldur', 'Mid Rim', 'P-15'),
('Unzel', 'Lantillian', 'Mid Rim', 'P-9'),
('Uogo''cor', 'Trax', 'Mid Rim', 'Q-10'),
('Upekzar', 'Esstran (Sith Worlds)', 'Outer Rim Territories', 'R-5'),
('Upell', 'Agarix', 'Mid Rim', 'K-18'),
('Uphrades', NULL, 'Inner Rim', 'M-8'),
('Upper Brightday', 'Trestis', 'Expansion Region', 'K-8'),
('Upper Etrega', NULL, 'Colonies', 'M-10'),
('Uquine', NULL, 'Colonies', 'N-10'),
('UR-1060', 'Zuma (Moddell)', 'Outer Rim Territories', 'H-16'),
('UR-2212-GR', NULL, 'Unknown Regions', 'H-6');