-- Insert galactic systems from Visseon to Yavin
INSERT INTO public.galactic_systems (name, sector, region, grid_coordinates) VALUES
('Visseon', NULL, 'Inner Rim', 'N-10'),
('Vivonah', 'Atravis', 'Outer Rim Territories', 'L-19'),
('Vixnix', 'Rago', 'Mid Rim', 'I-7'),
('Vizcarra', 'Cegul', 'Outer Rim Territories', 'L-20'),
('Vjun', 'Nuiri', 'Outer Rim Territories', 'Q-6'),
('Vlemoth Port', 'Instrop', 'Outer Rim Territories', 'S-16'),
('Vnex', 'Gordian Reach', 'Outer Rim Territories', 'Q-6'),
('Vo Tunbren', 'Cegul (Tadra)', 'Outer Rim Territories', 'M-20'),
('Vob', 'Ktilac Regions', 'Inner Rim', 'N-9'),
('Vobes', NULL, 'Core Worlds', 'J-10'),
('Vodran', NULL, 'Hutt Space', 'S-9'),
('Vogel', 'Var Hagen', 'Mid Rim', 'M-16'),
('Vohai', 'Parmel', 'Outer Rim Territories', 'O-18'),
('Void of Aogros', NULL, 'Wild Space', 'H-18'),
('Void of Chopani', 'Chopani', 'Outer Rim Territories', 'L-4'),
('Void Station', 'Bothan', 'Mid Rim', 'R-14'),
('Voidfire Nebula', 'Palamut', 'Expansion Region', 'N-13'),
('Voktunma', NULL, 'Core Worlds', 'M-11'),
('Volgax', NULL, 'Core Worlds', 'K-10'),
('Volik', NULL, 'Unknown Regions', 'H-7'),
('Volta', 'Chaykin', 'Expansion Region', 'O-14'),
('Voltare', NULL, 'Inner Rim', 'K-8'),
('Von-Alai', 'Locris', 'Expansion Region', 'O-8'),
('Vonak', 'Dalonbian', 'Outer Rim Territories', 'L-3'),
('Vondarc', 'Var Hagen', 'Mid Rim', 'M-16'),
('Vondoru', NULL, 'Unknown Regions', 'G-6'),
('Voniss', NULL, 'Mid Rim', 'I-7'),
('Vontor', NULL, 'Hutt Space', 'S-9'),
('Voolukaria', NULL, 'Core Worlds', 'K-13'),
('Voon', 'Krenher', 'Core Worlds', 'K-9'),
('Voorlach', 'Duluur', 'Colonies', 'M-13'),
('Voorsbain', 'Senex', 'Mid Rim', 'L-18'),
('Vor Deo', 'Arkanis', 'Outer Rim Territories', 'R-17'),
('Vorian', 'Immalia', 'Expansion Region', 'K-8'),
('Vorkaa', 'Graador', 'Mid Rim', 'I-17'),
('Vorlag', 'Thuris', 'Outer Rim Territories', 'P-18'),
('Vornax', 'Thanium', 'Outer Rim Territories', 'S-5'),
('Vorpa''ya', 'Mandalore', 'Outer Rim Territories', 'O-7'),
('Vorpal Nebula', 'Halthor', 'Outer Rim Territories', 'M-6'),
('Vorrnti', NULL, 'Inner Rim', 'L-8'),
('Vorsia', NULL, 'Inner Rim', 'N-9'),
('Vortex', 'Glythe', 'Mid Rim', 'K-7'),
('Vorusku', 'Juris', 'Outer Rim Territories', 'P-17'),
('Vorzyd', 'Vorzyd', 'Outer Rim Territories', 'R-6'),
('Vosch Cluster', 'Ado', 'Mid Rim', 'M-17'),
('Voss', 'Allied Tion', 'Outer Rim Territories', 'S-6'),
('Vosteltig', 'Oplovis', 'Outer Rim Territories', 'M-5'),
('Voxx Cluster', 'Ash Worlds', 'Outer Rim Territories', 'S-7'),
('Vr''gedia', 'Mytaranor', 'Mid Rim', 'P-9'),
('Vrakolia', NULL, 'Core Worlds', 'K-13'),
('Vretha', 'Hollan', 'Mid Rim', 'M-7'),
('Vrogas Vas', 'Sujimis', 'Outer Rim Territories', 'O-19'),
('Vrosynri', 'Nijune', 'Outer Rim Territories', 'N-5'),
('Vryssa', 'Dalicron', 'Outer Rim Territories', 'K-19'),
('Vuchelle', 'Atrivis', 'Outer Rim Territories', 'L-5'),
('Vulcar', 'Juvex', 'Mid Rim', 'L-18'),
('Vulcusion', 'Vulcusion', 'Expansion Region', 'L-16'),
('Vulderania', NULL, 'Core Worlds', 'L-10'),
('Vulpinus Nebula', 'Vatha', 'Expansion Region', 'K-16'),
('Vulpter', NULL, 'Deep Core', 'L-10'),
('Vulta', 'Trans-Vulta', 'Mid Rim', 'N-7'),
('Vultar', NULL, 'Core Worlds', 'L-10'),
('Vulvarch', NULL, 'Colonies', 'L-13'),
('Vuma', NULL, 'Core Worlds', 'M-10'),
('Vun''Hanna', NULL, 'Unknown Regions', 'D-7'),
('Vunakia', 'Phelleem', 'Outer Rim Territories', 'S-7'),
('Vundaria', NULL, 'Inner Rim', 'N-9'),
('Vur', 'Ojoster', 'Outer Rim Territories', 'N-7'),
('Vurdon Ka', 'Darlonn', 'Inner Rim', 'M-9'),
('Vuundalla', 'Tungra', 'Outer Rim Territories', 'K-18'),
('Vuzsa', 'Arkanis', 'Outer Rim Territories', 'R-16'),
('VV-99-7JE-2N71', 'Shiwal', 'Mid Rim', 'L-7'),
('Vvaw', 'Calaron', 'Outer Rim Territories', 'U-9'),
('Vycinyth', 'Tapani', 'Colonies', 'L-13'),
('Vykos', 'Relgim', 'Outer Rim Territories', 'L-5'),
('Vyndal', 'Chorlian', 'Outer Rim Territories', 'S-4'),
('Vyron', 'Kurost', 'Mid Rim', 'Q-11'),
('Wadi Raffa', 'Airam', 'Outer Rim Territories', 'M-20'),
('Wakeelmui', NULL, 'Colonies', 'L-9'),
('Wakiza', 'Farlax', 'Core Worlds', 'K-10'),
('Walalla', NULL, 'Inner Rim', 'J-13'),
('Walin''or', 'Shiwal', 'Mid Rim', 'M-7'),
('Wann Tsir', 'Sepan', 'Expansion Region', 'P-13'),
('Warchigade', 'Toblain', 'Outer Rim Territories', 'O-18'),
('Warlentta', 'Strabin', 'Mid Rim', 'M-7'),
('Warrin Station', 'Couronne', 'Expansion Region', 'P-10'),
('Wasco', 'Bri''ahl', 'Outer Rim Territories', 'I-17'),
('Waskiro', 'Jospro', 'Outer Rim Territories', 'R-7'),
('Wayland', 'Ojoster', 'Outer Rim Territories', 'N-7'),
('Waymancy', NULL, 'Inner Rim', 'K-8'),
('Wazta', 'Wazta', 'Outer Rim Territories', 'J-18'),
('Wecacoe', NULL, 'Colonies', 'K-13'),
('Weerden', 'Corusca', 'Core Worlds', 'K-9'),
('Wehttam', 'Farlax', 'Core Worlds', 'K-10'),
('Weik', NULL, 'Wild Space', 'H-20'),
('Weldii', NULL, 'Core Worlds', 'L-13'),
('Wells', 'Perkell', 'Mid Rim', 'Q-7'),
('Wellsia', 'Illodia', 'Core Worlds', 'K-13'),
('Wellte-ir', 'Trax', 'Mid Rim', 'Q-10'),
('Welsl', 'Brak', 'Expansion Region', 'O-14'),
('Wen''he''dinae', 'Eidoloni', 'Mid Rim', 'L-16'),
('Wenderal', 'Aparo', 'Outer Rim Territories', 'R-3'),
('Werania', 'Biivren', 'Expansion Region', 'P-9'),
('Werma', 'Xappyh', 'Outer Rim Territories', 'Q-3'),
('Werncin', 'Kwymar', 'Outer Rim Territories', 'Q-4'),
('Werta', 'Oriolan', 'Mid Rim', 'J-16'),
('Wetyin''s Colony', 'Gordian Reach', 'Outer Rim Territories', 'Q-5'),
('Weytta', 'Auril', 'Outer Rim Territories', 'S-6'),
('Wheel, The', 'Maldrood', 'Mid Rim', 'R-7'),
('Whelori', NULL, 'Colonies', 'K-13'),
('Whendyll', 'Cademimu', 'Outer Rim Territories', 'L-6'),
('Whiforla', NULL, 'Inner Rim', 'M-13'),
('Whinndor', 'Grumani', 'Outer Rim Territories', 'N-17'),
('Whirl, The', NULL, 'Inner Rim', 'K-8'),
('Wick', 'Instrop', 'Outer Rim Territories', 'S-16'),
('Widek', 'Farlax', 'Core Worlds', 'K-10'),
('Wielu', NULL, 'Inner Rim', 'N-13'),
('Wilpiet', 'Cademimu', 'Outer Rim Territories', 'M-6'),
('Winagrew', 'Graador', 'Mid Rim', 'J-17'),
('Winnikk', 'Sumitra', 'Expansion Region', 'O-7'),
('Winsit', 'Cegul', 'Outer Rim Territories', 'L-20'),
('Winter''s Edge', 'Koradin', 'Outer Rim Territories', 'J-18'),
('Wistril', 'Fath', 'Outer Rim Territories', 'K-6'),
('Witch Nebula', NULL, 'Colonies', 'L-9'),
('Wizar', NULL, 'Wild Space', 'I-8'),
('Wobani', 'Bryx', 'Mid Rim', 'R-8'),
('Wodan', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Wodenstam', 'Skine', 'Outer Rim Territories', 'Q-19'),
('Wol Cabassh', 'Quelii', 'Outer Rim Territories', 'O-6'),
('Woldona', 'Sevetta', 'Outer Rim Territories', 'T-16'),
('Womrik', 'Dufilvian', 'Mid Rim', 'Q-15'),
('Woostri', 'Woostri', 'Expansion Region', 'M-16'),
('Woqua', NULL, 'Core Worlds', 'K-10'),
('Wor Tandell', 'Dolomar', 'Core Worlds', 'K-9'),
('Worru''du', 'Torranix', 'Core Worlds', 'K-10'),
('Worxer', 'Elrood', 'Outer Rim Territories', 'M-20'),
('Woteba', NULL, 'Wild Space', 'I-8'),
('Wranag', 'Bajic', 'Outer Rim Territories', 'P-17'),
('Wrea', 'Gaulus', 'Outer Rim Territories', 'S-17'),
('Wretch of Tayron', 'Videnda', 'Outer Rim Territories', 'L-18'),
('Wrodi', 'Meerian', 'Outer Rim Territories', 'O-6'),
('Wroona', NULL, 'Inner Rim', 'L-15'),
('Wukkar', NULL, 'Core Worlds', 'L-10'),
('Wxtm', 'Gaulus', 'Outer Rim Territories', 'R-17'),
('Wyloff', 'Wyloff', 'Colonies', 'L-8'),
('Wyndigal', 'Ash Worlds', 'Outer Rim Territories', 'S-7'),
('Wynkahthu', 'Alderath', 'Mid Rim', 'L-7'),
('Wynth', 'Wyloff', 'Colonies', 'L-8'),
('Wyveral', 'Homon', 'Mid Rim', 'M-7'),
('X3-299-11', NULL, 'Wild Space', 'S-4'),
('Xa Fel', 'Kanchen', 'Core Worlds', 'K-9'),
('Xagobah', 'Mayagil', 'Outer Rim Territories', 'M-18'),
('Xais', 'Yminis', 'Outer Rim Territories', 'S-14'),
('Xal', 'Zuma (Ablajeck)', 'Outer Rim Territories', 'H-16'),
('Xala', NULL, 'Wild Space', 'H-14'),
('Xanas', 'Xan', 'Mid Rim', 'Q-15'),
('Xandil', 'Lambda', 'Mid Rim', 'P-16'),
('Xandonia', 'Askarian', 'Expansion Region', 'P-11'),
('Xandros', 'Locris', 'Expansion Region', 'O-8'),
('Xanlanner', 'Wyl', 'Outer Rim Territories', 'S-4'),
('Xantar', 'Corva', 'Outer Rim Territories', 'P-4'),
('Xartun', 'Ojoster', 'Outer Rim Territories', 'O-7'),
('Xaza', 'Xan', 'Mid Rim', 'Q-15'),
('Xend', NULL, 'Inner Rim', 'M-8'),
('Xendek', 'Calaron', 'Outer Rim Territories', 'T-9'),
('Xenxiar', 'Trax', 'Mid Rim', 'P-10'),
('Xeron', NULL, 'Inner Rim', 'M-14'),
('Xerthia', NULL, 'Inner Rim', 'K-14'),
('Xerton', NULL, 'Wild Space', 'J-3'),
('Xerxes', NULL, 'Core Worlds', 'M-11'),
('Xibariz', NULL, 'Inner Rim', 'O-9'),
('Xifal', 'Allied Tion', 'Outer Rim Territories', 'S-6'),
('Xilxash', 'Yminis', 'Outer Rim Territories', 'S-15'),
('Xirl', NULL, 'Wild Space', 'O-20'),
('Xiunsrus', 'Quence', 'Outer Rim Territories', 'P-18'),
('Xo', 'Spinward', 'Outer Rim Territories', 'N-2'),
('Xobome', NULL, 'Colonies', 'N-10'),
('Xochtl', 'Gordian Reach', 'Outer Rim Territories', 'P-6'),
('Xoemefel', 'Marzoon', 'Mid Rim', 'I-16'),
('Xolu', NULL, 'Hutt Space', 'S-13'),
('Xoman', 'Halla', 'Mid Rim', 'S-9'),
('Xorao', 'Mezeg', 'Mid Rim', 'M-7'),
('Xorrn', 'Ferra', 'Outer Rim Territories', 'S-16'),
('Xorth', NULL, 'Core Worlds', 'L-10'),
('XT987', NULL, 'Inner Rim', 'J-8'),
('Xu''hu', 'Quiberon', 'Outer Rim Territories', 'S-15'),
('Xuaquarres', 'Ash Worlds', 'Outer Rim Territories', 'S-7'),
('XV-344H', 'Esstran', 'Outer Rim Territories', 'Q-5'),
('Xxan', 'Antemeridian', 'Outer Rim Territories', 'R-7'),
('Xyquine', 'Corellian', 'Core Worlds', 'M-11'),
('Y''Dar', 'Astal', 'Outer Rim Territories', 'P-17'),
('Y''nybeth', 'Tokamac', 'Expansion Region', 'O-13'),
('Y''Trella', 'Sarin', 'Outer Rim Territories', 'P-18'),
('Yablari', 'Vorzyd', 'Outer Rim Territories', 'R-6'),
('Yabol Opa', NULL, 'Colonies', 'M-9'),
('Yabosta', 'Rocantor', 'Expansion Region', 'L-15'),
('Yag''Dhul', NULL, 'Inner Rim', 'L-14'),
('Yaga Minor', 'Prefsbelt', 'Outer Rim Territories', 'K-5'),
('Yagara', 'Hadar', 'Mid Rim', 'L-17'),
('Yaka', NULL, 'Colonies', 'M-8'),
('Yakorki', 'Pacanth Reach', 'Outer Rim Territories', 'G-16'),
('Yalara', NULL, 'Wild Space', 'I-21'),
('Yalbec Prime', 'Rolion', 'Outer Rim Territories', 'P-7'),
('Yaled', 'Jubilar', 'Outer Rim Territories', 'T-7'),
('Yalln', 'Mortex', 'Outer Rim Territories', 'R-5'),
('Yama''chen', 'Nicandra', 'Mid Rim', 'L-7'),
('Yamradi', 'Varada', 'Outer Rim Territories', 'I-19'),
('Yan Korelda', 'Prefsbelt', 'Outer Rim Territories', 'J-5'),
('Yanibar', NULL, 'Wild Space', 'R-19'),
('Yanis', NULL, 'Core Worlds', 'L-12'),
('Yankirk', 'Ado', 'Mid Rim', 'L-17'),
('Yantha', NULL, 'Inner Rim', 'N-8'),
('Yar Togna', 'Sarin', 'Outer Rim Territories', 'P-18'),
('Yarille', 'Fath', 'Outer Rim Territories', 'K-6'),
('Yarith', 'Javin (Yarith)', 'Outer Rim Territories', 'J-18'),
('Yarma', 'Tharin', 'Outer Rim Territories', 'T-8'),
('Yarnil', 'Toblain', 'Outer Rim Territories', 'N-18'),
('Yaronn', NULL, 'Wild Space', 'T-5'),
('Yarrv', NULL, 'Core Worlds', 'K-13'),
('Yartiga', 'Spirva', 'Mid Rim', 'K-17'),
('Yashuvhu', NULL, 'Unknown Regions', 'F-9'),
('Yasilor', 'Bajic', 'Outer Rim Territories', 'P-17'),
('Yathik', 'Boeus', 'Expansion Region', 'M-15'),
('Yavin', 'Gordian Reach', 'Outer Rim Territories', 'P-6');