-- Insert galactic systems from Perithal to Quellor (223 systems)
INSERT INTO galactic_systems (name, sector, region, grid_coordinates) VALUES
('Perithal', NULL, 'Inner Rim', 'N-14'),
('Perlemia', NULL, 'Core Worlds', 'L-9'),
('Perma', NULL, 'Core Worlds', 'M-11'),
('Permondiri', NULL, 'Core Worlds', 'J-13'),
('Pernam Minor', 'Minos Cluster', 'Outer Rim Territories', 'M-20'),
('Pernella', 'Tapani', 'Colonies', 'L-13'),
('Persavi', 'Taldot', 'Mid Rim', 'Q-9'),
('Persaya', NULL, 'Inner Rim', 'K-8'),
('Persis', 'Bes Ber Bikade', 'Expansion Region', 'L-15'),
('Perthrillia', NULL, 'Colonies', 'J-13'),
('Pervi', NULL, 'Colonies', 'L-13'),
('Pervick', 'Corva', 'Outer Rim Territories', 'P-3'),
('Pesfavri', NULL, 'Unknown Regions', 'G-8'),
('Peshara', NULL, 'Core Worlds', 'L-10'),
('Pesitiin', NULL, 'Expansion Region', 'I-8'),
('Pesmenben', 'Teraab', 'Mid Rim', 'Q-11'),
('Pestoriv', NULL, 'Colonies', 'N-12'),
('Petabys Station', 'Halm', 'Mid Rim', 'J-16'),
('Petrakis', NULL, 'Inner Rim', 'O-11'),
('Petrusia', 'Nuon e Safyd', 'Expansion Region', 'P-12'),
('Phaeda', 'Cademimu', 'Outer Rim Territories', 'L-6'),
('Phaegon', 'Grumani', 'Outer Rim Territories', 'N-17'),
('Phandas', NULL, 'Deep Core', 'M-11'),
('Phaseera', 'Lantillian', 'Mid Rim', 'P-8'),
('Phateem', NULL, 'Inner Rim', 'N-8'),
('Phatrong', 'Thrasybule', 'Outer Rim Territories', 'P-6'),
('Phattro', 'Abrion', 'Outer Rim Territories', 'S-15'),
('Phelarion', 'Seswenna', 'Outer Rim Territories', 'M-18'),
('Phelbos', 'Bright Jewel', 'Mid Rim', 'L-7'),
('Phelope', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Phelzepham', 'Esuain', 'Mid Rim', 'P-7'),
('Phemis', 'Corellian', 'Core Worlds', 'M-11'),
('Pheryon', NULL, 'Inner Rim', 'J-8'),
('Phibia', 'Haserian', 'Mid Rim', 'Q-15'),
('Philaxia', 'Har Worlds', 'Expansion Region', 'J-16'),
('Phindar', 'Demetras', 'Outer Rim Territories', 'P-6'),
('Phinel''s Folly', 'Auril', 'Outer Rim Territories', 'R-7'),
('Pho Ph''eah', 'Kalamith', 'Outer Rim Territories', 'P-5'),
('Phoebus', 'Thanium', 'Outer Rim Territories', 'R-6'),
('Phorliss', 'Dolomar', 'Core Worlds', 'K-9'),
('Phorose', NULL, 'Colonies', 'M-13'),
('Phorsa Gedd', 'Dohlbani', 'Mid Rim', 'R-13'),
('Phosphura Belt Nebula', 'Atravis', 'Outer Rim Territories', 'L-20'),
('Phr''sha', 'Fei Hu', 'Mid Rim', 'P-13'),
('Phracas', NULL, 'Core Worlds', 'J-10'),
('Phraetiss', 'Farrfin', 'Core Worlds', 'K-9'),
('Phu', NULL, 'Colonies', 'J-13'),
('Pickerin', 'Bright Jewel', 'Mid Rim', 'L-7'),
('Picutorion', 'Kwymar', 'Outer Rim Territories', 'Q-4'),
('Pieldi', 'Juvex', 'Mid Rim', 'L-18'),
('Pii', 'Arkanis', 'Outer Rim Territories', 'R-16'),
('Pijal', NULL, 'Inner Rim', 'L-8'),
('Pil Diller', 'Quelii', 'Outer Rim Territories', 'O-6'),
('Piluvia', 'Torch Nebula', 'Outer Rim Territories', 'P-19'),
('Pindra', NULL, 'Inner Rim', 'N-9'),
('Pinett', 'Elrood', 'Outer Rim Territories', 'M-20'),
('Pinoora', 'Gordian Reach', 'Outer Rim Territories', 'P-6'),
('Pinperu', 'Calamari', 'Outer Rim Territories', 'U-6'),
('Pinurquia', 'Rolion', 'Outer Rim Territories', 'Q-7'),
('Pioku', 'Trans-Jardeen', 'Expansion Region', 'K-15'),
('Pion', NULL, 'Wild Space', 'H-14'),
('Pipada', 'Videnda', 'Outer Rim Territories', 'M-18'),
('Pippip', 'Illisurevimurasi', 'Outer Rim Territories', 'Q-4'),
('Pirik', 'Tharin (Divis Arm)', 'Outer Rim Territories', 'S-8'),
('Pirin', 'Locris', 'Expansion Region', 'O-8'),
('Piroket', 'Arkanis', 'Outer Rim Territories', 'R-16'),
('Pirol', 'Farlax', 'Core Worlds', 'K-10'),
('Pirralor', 'Juvex', 'Mid Rim', 'L-18'),
('Pirsen', 'Eidoloni', 'Mid Rim', 'L-16'),
('Pitann', 'Kathol (Outback)', 'Outer Rim Territories', 'M-21'),
('Piton', NULL, 'Core Worlds', 'K-12'),
('Pitrillistia', 'Mieru''kar', 'Outer Rim Territories', 'O-3'),
('Pits of Plooma', 'Veragi', 'Outer Rim Territories', 'L-3'),
('Piu', 'Kallea', 'Outer Rim Territories', 'K-21'),
('Pizilis', 'Terr''skiar', 'Mid Rim', 'P-10'),
('Pizkoss', NULL, 'Core Worlds', 'K-10'),
('Pkihantri', NULL, 'Core Worlds', 'L-12'),
('Pkori', NULL, 'Wild Space', 'J-5'),
('Plavin', NULL, 'Colonies', 'L-9'),
('Plavonia', 'Kriz', 'Outer Rim Territories', 'J-18'),
('Plazir', NULL, 'Outer Rim Territories', 'N-2'),
('Pleem''s Nexus', 'Mezeg', 'Mid Rim', 'N-7'),
('Pleida', 'Oricho', 'Outer Rim Territories', 'M-6'),
('Pleknok', NULL, 'Unknown Regions', 'G-9'),
('Plesstil', 'Veragi', 'Outer Rim Territories', 'L-3'),
('Plexis', NULL, 'Core Worlds', 'L-13'),
('Plin Minor', NULL, 'Inner Rim', 'K-14'),
('Ploo', 'Ploo', 'Expansion Region', 'N-7'),
('Plood', 'Pacanth Reach', 'Outer Rim Territories', 'G-16'),
('Plooriod', 'Ploo', 'Expansion Region', 'N-7'),
('Pluthan', NULL, 'Wild Space', 'U-8'),
('Plympto', 'Corellian', 'Core Worlds', 'M-11'),
('Poderis', 'Orus', 'Inner Rim', 'M-8'),
('Polaar', 'Eidoloni', 'Mid Rim', 'L-16'),
('Polanis', 'Corellian', 'Core Worlds', 'M-11'),
('Polis Massa', 'Subterrel', 'Outer Rim Territories', 'K-20'),
('Pollillus', 'Vannell', 'Core Worlds', 'J-10'),
('Polmanar', 'Javin (Anoat)', 'Outer Rim Territories', 'K-18'),
('Poln', 'Candoras', 'Outer Rim Territories', 'J-5'),
('Polneye', 'Farlax', 'Core Worlds', 'K-10'),
('Polomie', 'Oriolan', 'Mid Rim', 'J-16'),
('Polordio', 'Danjar', 'Outer Rim Territories', 'M-19'),
('Polus', 'Oricho', 'Outer Rim Territories', 'M-6'),
('Polyneus', NULL, 'Inner Rim', 'J-14'),
('Pondakree', NULL, 'Colonies', 'N-12'),
('Pondut Station', 'Corporate Sector', 'Outer Rim Territories', 'S-4'),
('Ponemah', 'Zuma (Spar)', 'Outer Rim Territories', 'H-16'),
('Ponolapo', 'Atravis', 'Outer Rim Territories', 'L-19'),
('Ponton', 'Tharin', 'Outer Rim Territories', 'S-8'),
('Porchello', 'Elbaran', 'Mid Rim', 'J-17'),
('Poressi', 'Dantus', 'Outer Rim Territories', 'K-6'),
('Pormthulis', 'Kira', 'Expansion Region', 'N-16'),
('Porpor', 'Grohl', 'Outer Rim Territories', 'S-16'),
('Port Bianco', NULL, 'Colonies', 'L-13'),
('Port Evokk', 'Senex', 'Mid Rim', 'L-18'),
('Port Ferrule', 'Suolriep (Iotran Expanse)', 'Outer Rim Territories', 'S-8'),
('Port Jerrell', 'Koradin', 'Outer Rim Territories', 'J-18'),
('Port Lasgo', 'Bheriz', 'Outer Rim Territories', 'U-10'),
('Port Lennax', 'Ojoster', 'Outer Rim Territories', 'N-7'),
('Port Nowhere', NULL, 'Wild Space', 'H-19'),
('Port Yonder', 'Pelgrin', 'Outer Rim Territories', 'R-18'),
('Portminia', 'Sprizen', 'Outer Rim Territories', 'N-5'),
('Portocari', 'Belmsuth', 'Outer Rim Territories', 'O-6'),
('Porus Vida', NULL, 'Inner Rim', 'O-9'),
('Poseidenna', 'Calamari', 'Outer Rim Territories', 'U-7'),
('Pothor', 'Roche', 'Mid Rim', 'Q-8'),
('Pouffra', 'Rolion', 'Outer Rim Territories', 'Q-7'),
('Povanaria', 'Gordian Reach', 'Outer Rim Territories', 'P-6'),
('Poviduze', NULL, 'Expansion Region', 'J-14'),
('Poytta', 'Hutt Space', 'Outer Rim Territories', 'T-12'),
('Pozzi', 'Tapani', 'Colonies', 'L-13'),
('Praadost', 'Nembus', 'Outer Rim Territories', 'P-4'),
('Praesitlyn', 'Sluis', 'Outer Rim Territories', 'M-19'),
('Prahvin', NULL, 'Inner Rim', 'M-14'),
('Praidaw', NULL, 'Inner Rim', 'K-14'),
('Prakith', NULL, 'Deep Core', 'K-10'),
('Prakith Minor', NULL, 'Colonies', 'L-9'),
('Praktin', 'Thusa', 'Mid Rim', 'O-7'),
('Pral', NULL, 'Wild Space', 'L-21'),
('Praven Prime', 'Quelii', 'Outer Rim Territories', 'O-6'),
('Praxat Sil', 'Jidlor Marches', 'Mid Rim', 'J-16'),
('Praxlis', 'Praxlis', 'Core Worlds', 'J-10'),
('Praya', 'Clacis', 'Outer Rim Territories', 'K-4'),
('Prazhi', 'Cyrillian Protectorate', 'Expansion Region', 'O-12'),
('Prefsbelt', 'Prefsbelt', 'Outer Rim Territories', 'K-5'),
('Prekaz', NULL, 'Core Worlds', 'K-9'),
('Presbalin', 'Gordian Reach', 'Outer Rim Territories', 'P-6'),
('Pressylla', 'Oricho', 'Outer Rim Territories', 'M-6'),
('Presteen', 'Senex', 'Mid Rim', 'L-17'),
('Prexiar', 'Steniplis', 'Outer Rim Territories', 'L-19'),
('Pria', NULL, 'Core Worlds', 'M-10'),
('Prildaz', 'Farlax', 'Core Worlds', 'K-10'),
('Primarin', NULL, 'Inner Rim', 'M-13'),
('Primea', 'Vak Combine', 'Unknown Regions', 'F-7'),
('Primtara', 'Primtara', 'Mid Rim', 'P-15'),
('Primus Cabru', 'Allied Tion', 'Outer Rim Territories', 'S-6'),
('Prine', 'Vilonis', 'Mid Rim', 'O-16'),
('Priole Danna', 'Sprizen', 'Outer Rim Territories', 'O-5'),
('Prishardia', 'Antemeridian', 'Outer Rim Territories', 'R-7'),
('Prishella', 'Kessel', 'Outer Rim Territories', 'T-10'),
('Procopia', 'Tapani', 'Colonies', 'L-13'),
('Prolifera', 'Corosi', 'Outer Rim Territories', 'N-6'),
('Promencius', 'Thanium', 'Outer Rim Territories', 'S-5'),
('Prospera Jang', 'Kurost', 'Mid Rim', 'Q-11'),
('Protazk', 'Kwymar', 'Outer Rim Territories', 'Q-4'),
('Protobranch', NULL, 'Core Worlds', 'J-13'),
('Protogeyser', NULL, 'Inner Rim', 'K-8'),
('Proxima Dibal', NULL, 'Wild Space', 'Q-3'),
('Pugal', 'Glythe', 'Mid Rim', 'J-7'),
('Pulassas Minor', 'Koradin', 'Outer Rim Territories', 'J-18'),
('Puloorn', 'Spinward', 'Outer Rim Territories', 'M-3'),
('Purala', 'Kibilini', 'Outer Rim Territories', 'Q-17'),
('Purcassia', NULL, 'Colonies', 'L-13'),
('Purnham', 'Shelsha', 'Colonies', 'M-9'),
('Pursin', 'Atravis', 'Outer Rim Territories', 'L-19'),
('Pusat Station', 'Halla', 'Mid Rim', 'R-8'),
('Pybus', 'Hutt Space', 'Outer Rim Territories', 'S-11'),
('Pygorix', 'Gordian Reach', 'Outer Rim Territories', 'Q-6'),
('Pyjridj', 'Agarix', 'Mid Rim', 'K-17'),
('Pyolli', 'Seswenna', 'Outer Rim Territories', 'M-18'),
('Pypin', 'Trianii Space', 'Wild Space', 'R-3'),
('Pyra', 'Fei Hu', 'Mid Rim', 'P-13'),
('Pyros', NULL, 'Colonies', 'K-13'),
('Pyrr', NULL, 'Wild Space', 'U-6'),
('Pzandias', 'Bryx', 'Mid Rim', 'S-7'),
('Pzob', 'Herios', 'Outer Rim Territories', 'T-15'),
('Q''Maere', 'Kathol (Rift)', 'Outer Rim Territories', 'M-21'),
('Q''mara', 'Juvex', 'Mid Rim', 'L-18'),
('Q''nithian', 'Nembus', 'Outer Rim Territories', 'P-4'),
('Qalita Prime', NULL, 'Inner Rim', 'J-13'),
('Qalydon', 'Sertar', 'Outer Rim Territories', 'R-5'),
('Qaras', 'Minyavi', 'Mid Rim', 'I-16'),
('Qat Chrystac', 'Parnabe', 'Expansion Region', 'L-16'),
('Qeimet', 'Juris', 'Outer Rim Territories', 'P-17'),
('Qemia', 'Strabin', 'Mid Rim', 'M-7'),
('Qexis', 'Danjar', 'Outer Rim Territories', 'N-19'),
('Qhulosk', 'Tharin', 'Outer Rim Territories', 'T-8'),
('Qi Lozar', 'Grumani', 'Outer Rim Territories', 'M-17'),
('Qiaxx', 'Cor''ric', 'Outer Rim Territories', 'P-18'),
('Qiilura', 'Qiilura', 'Mid Rim', 'L-7'),
('Qina', 'Zuma (Moddell)', 'Outer Rim Territories', 'H-16'),
('Qixoni Nebula', NULL, 'Colonies', 'K-13'),
('Qlothos', NULL, 'Inner Rim', 'M-14'),
('Qonto', NULL, 'Wild Space', 'J-3'),
('Qoribu', NULL, 'Unknown Regions', 'H-7'),
('Qotile', 'Colundra', 'Outer Rim Territories', 'S-5'),
('Qretu', NULL, 'Inner Rim', 'L-15'),
('Qu''mock', 'Kathol (Outback)', 'Outer Rim Territories', 'M-21'),
('Quadrant Seven', 'Barsa', 'Mid Rim', 'J-6'),
('Quaensan Prime', 'Gendius', 'Mid Rim', 'J-17'),
('Quaggia', 'Hutt Space', 'Outer Rim Territories', 'S-9'),
('Qualai', 'Kallea', 'Outer Rim Territories', 'K-20'),
('Qualthrough', 'Belsmuth', 'Outer Rim Territories', 'O-6'),
('Quamar', 'Bruanii', 'Mid Rim', 'K-17'),
('Quan-Shui', 'Montitian Grant', 'Expansion Region', 'J-15'),
('Quanducial', 'Gordian Reach', 'Outer Rim Territories', 'Q-6'),
('Quanton', 'Obtrexta', 'Outer Rim Territories', 'K-4'),
('Quarmendy', 'Yucrales', 'Mid Rim', 'R-15'),
('Quarzite', NULL, 'Inner Rim', 'M-13'),
('Quas Killam', 'Terr''skiar', 'Mid Rim', 'P-10'),
('Queel', 'Doldur', 'Mid Rim', 'P-15'),
('Quelii', 'Quelii', 'Outer Rim Territories', 'O-6'),
('Quell', 'Nuiri', 'Outer Rim Territories', 'Q-6'),
('Quellor', 'Quellor', 'Colonies', 'N-12');