-- Insert galactic systems from Serat to Sorfina (250 systems)
INSERT INTO galactic_systems (name, sector, region, grid_coordinates) VALUES
('Serat', 'Senex', 'Mid Rim', 'L-18'),
('Sereeda', 'Ash Worlds', 'Outer Rim Territories', 'T-7'),
('Seregar', 'Calaron', 'Outer Rim Territories', 'U-9'),
('Serelia', 'Oriolan', 'Mid Rim', 'J-16'),
('Serenity', 'Tashtor', 'Mid Rim', 'J-16'),
('Serenno', 'D''Astan', 'Outer Rim Territories', 'P-5'),
('Sergia', 'Kalakan', 'Inner Rim', 'J-15'),
('Serianan', NULL, 'Wild Space', 'P-2'),
('Sermeria', 'Locris', 'Expansion Region', 'O-8'),
('Sern Prime', 'Sern', 'Colonies', 'L-13'),
('Sernpidal', 'Dalonbian', 'Outer Rim Territories', 'L-3'),
('Serolonis', 'Kriz', 'Outer Rim Territories', 'J-18'),
('Serpine', 'Illisurevimurasi', 'Outer Rim Territories', 'Q-4'),
('Serria', 'Rocantor', 'Expansion Region', 'L-15'),
('Serroco', 'Ploo', 'Expansion Region', 'N-7'),
('Serule', NULL, 'Core Worlds', 'K-9'),
('Sesid', 'Corva', 'Outer Rim Territories', 'P-4'),
('Sespe', 'Tharin (Periphery)', 'Outer Rim Territories', 'S-9'),
('Sestina', NULL, 'Core Worlds', 'M-11'),
('Sestooine', 'Relgim', 'Outer Rim Territories', 'L-5'),
('Sestria', 'Testarr', 'Core Worlds', 'M-13'),
('Seswenna', 'Seswenna', 'Outer Rim Territories', 'M-18'),
('Setolio', 'Tapani', 'Colonies', 'L-13'),
('Setor', NULL, 'Colonies', 'L-8'),
('Sev Tok', 'Kurost', 'Mid Rim', 'Q-11'),
('Sevarcos', 'Tamarin', 'Outer Rim Territories', 'N-19'),
('Sevari', 'Chorlian', 'Outer Rim Territories', 'S-4'),
('Sevetta', 'Sevetta', 'Outer Rim Territories', 'T-16'),
('Sewalia', NULL, 'Inner Rim', 'L-14'),
('Seylott', 'Sarin', 'Outer Rim Territories', 'P-18'),
('Seymarti', NULL, 'Colonies', 'M-13'),
('Seyugi', NULL, 'Core Worlds', 'M-11'),
('Sh''ung-tesk', 'Ciutric', 'Outer Rim Territories', 'N-4'),
('Sha''rellia', 'Hutt Space', 'Outer Rim Territories', 'S-12'),
('Shackel', 'Chaykin', 'Expansion Region', 'O-14'),
('Shadda Nebula', 'Toblain', 'Outer Rim Territories', 'O-18'),
('Shador', 'Maerdocian', 'Mid Rim', 'Q-13'),
('Shadren', 'Belsmuth', 'Outer Rim Territories', 'O-6'),
('Shafr', 'Toblain', 'Outer Rim Territories', 'O-17'),
('Shahkir', NULL, 'Inner Rim', 'M-14'),
('Shalam', NULL, 'Inner Rim', 'M-7'),
('Shalankie', NULL, 'Inner Rim', 'O-9'),
('Shallow March', 'Mortex', 'Outer Rim Territories', 'S-5'),
('Shalm', 'Zuma (Ikenomin)', 'Outer Rim Territories', 'H-16'),
('Shaltin', 'Thanium', 'Outer Rim Territories', 'S-6'),
('Shalyvane', 'Indrexu', 'Outer Rim Territories', 'S-5'),
('Shantipole', 'Roche', 'Mid Rim', 'Q-8'),
('Shar''Ack', 'Atrivis', 'Outer Rim Territories', 'L-5'),
('Sharb', 'Chiss Space', 'Unknown Regions', 'F-8'),
('Shard', 'Wazta', 'Outer Rim Territories', 'J-18'),
('Sharlissia', 'Bon''nyuw-Luq', 'Outer Rim Territories', 'N-18'),
('Shasa', NULL, 'Inner Rim', 'N-12'),
('Shasfath', NULL, 'Inner Rim', 'J-14'),
('Shatuun', 'Kathol (Outback)', 'Outer Rim Territories', 'M-21'),
('Shaum Hii', 'Tragan Cluster', 'Outer Rim Territories', 'N-5'),
('Shawken', NULL, 'Core Worlds', 'L-9'),
('Shawti', 'Hutt Space', 'Outer Rim Territories', 'S-9'),
('Shaylin', 'Pakuuni', 'Outer Rim Territories', 'T-6'),
('Shaymore', 'Immerian Outback', 'Expansion Region', 'N-14'),
('Shedu Maad', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Sheela', 'Abrion', 'Outer Rim Territories', 'S-15'),
('Sheh Soahi', 'Cassander', 'Outer Rim Territories', 'K-5'),
('Shelkonwa', 'Shelsha', 'Colonies', 'M-9'),
('Shella', 'Tapani', 'Colonies', 'L-13'),
('Shenio', 'Kalamith', 'Outer Rim Territories', 'P-5'),
('Sheris', 'Belsmuth', 'Outer Rim Territories', 'O-6'),
('Shesharile', 'Minos Cluster', 'Outer Rim Territories', 'M-20'),
('Sheva', 'Tapani', 'Colonies', 'L-13'),
('Shi''kar Straits', 'Nembus', 'Outer Rim Territories', 'P-4'),
('Shibric', NULL, 'Inner Rim', 'N-14'),
('Shifa', 'Tapani', 'Colonies', 'L-13'),
('Shiffrin', 'Tammuz', 'Outer Rim Territories', 'T-15'),
('Shihon', 'Chiss Space', 'Unknown Regions', 'E-8'),
('Shikitari', NULL, 'Unknown Regions', 'G-14'),
('Shili', 'Ehosiq', 'Expansion Region', 'L-8'),
('Shimia', 'Dalchon', 'Outer Rim Territories', 'R-17'),
('Shimmer', 'Rayter', 'Outer Rim Territories', 'J-19'),
('Shinbone', NULL, 'Wild Space', 'T-17'),
('Shindra', 'Tapani', 'Colonies', 'L-13'),
('Shintel', 'Kathol', 'Outer Rim Territories', 'M-21'),
('Shiva', NULL, 'Wild Space', 'L-21'),
('Shogun', 'Quence', 'Outer Rim Territories', 'O-18'),
('Shola', 'Tammuz', 'Outer Rim Territories', 'U-14'),
('Shoon', 'Senex', 'Mid Rim', 'L-18'),
('Shopani', 'Tapani', 'Colonies', 'L-13'),
('Shoroni', NULL, 'Colonies', 'M-9'),
('Shosho', 'Graador', 'Mid Rim', 'I-17'),
('Shotem', NULL, 'Colonies', 'J-13'),
('Shownar', 'Parmic', 'Outer Rim Territories', 'P-19'),
('Shramar', 'Clacis', 'Outer Rim Territories', 'K-4'),
('Shrokaan', 'Baroli', 'Expansion Region', 'N-14'),
('Shu-Torun', 'Chaama', 'Mid Rim', 'J-7'),
('Shuldene', 'Javin (Yarith)', 'Outer Rim Territories', 'J-18'),
('Shulstine', NULL, 'Colonies', 'M-9'),
('Shulxi', NULL, 'Core Worlds', 'L-12'),
('Shumari', 'Parmel', 'Outer Rim Territories', 'O-18'),
('Shumavar', 'Atravis', 'Outer Rim Territories', 'L-19'),
('Shumogi', NULL, 'Core Worlds', 'M-12'),
('Shuraden', 'Koradin', 'Outer Rim Territories', 'I-18'),
('Shurrupak', 'Vulcusion', 'Expansion Region', 'L-16'),
('Shusugaunt', 'Raioballo', 'Outer Rim Territories', 'L-4'),
('Shuxl', 'Javin (Yarith)', 'Outer Rim Territories', 'K-18'),
('Sibensko', 'Bes Ber Bikade', 'Expansion Region', 'L-15'),
('Sibilaar', 'Bozhnee', 'Outer Rim Territories', 'L-18'),
('Sibisime', 'Sombure', 'Mid Rim', 'K-17'),
('Sidi', 'Illisurevimurasi', 'Outer Rim Territories', 'Q-4'),
('Sif-Alula', 'Trestis', 'Expansion Region', 'K-8'),
('Sif-Uwana', NULL, 'Colonies', 'K-8'),
('Sif''kric', 'Mezeg', 'Mid Rim', 'M-7'),
('Sifuchi', 'Lostar', 'Expansion Region', 'M-7'),
('Sigil', 'Chorlian', 'Outer Rim Territories', 'S-4'),
('Sigma Station', 'Demetras', 'Mid Rim', 'P-7'),
('Sika', 'Brevost', 'Expansion Region', 'O-15'),
('Sikkem', 'Thanium', 'Outer Rim Territories', 'R-6'),
('Sikurd', 'Tynquay', 'Outer Rim Territories', 'Q-4'),
('Sil Gohtta', 'Lol', 'Outer Rim Territories', 'Q-18'),
('Sil''Lume', 'Seitia', 'Outer Rim Territories', 'K-19'),
('Sileria', 'Corellian', 'Core Worlds', 'M-11'),
('Silken', NULL, 'Wild Space', 'O-20'),
('Silla', 'Strabin', 'Mid Rim', 'M-7'),
('Silorna', 'Imberlin', 'Expansion Region', 'P-13'),
('Silunes', 'Arc d''Stot', 'Expansion Region', 'K-15'),
('Siluria', 'Atravis', 'Outer Rim Territories', 'L-19'),
('Silver Station', 'Doldur', 'Mid Rim', 'P-15'),
('Silversisi', NULL, 'Inner Rim', 'M-8'),
('Silvestri', 'Ado', 'Mid Rim', 'L-17'),
('Sim''char''ser', 'Albanin', 'Outer Rim Territories', 'U-12'),
('Simbarc', 'Cadma', 'Outer Rim Territories', 'T-8'),
('Simento-Threk', 'Meram', 'Outer Rim Territories', 'O-4'),
('Simik', NULL, 'Inner Rim', 'L-14'),
('Simocadia', NULL, 'Inner Rim', 'J-13'),
('Simoom', 'Senex', 'Mid Rim', 'L-18'),
('Simoth', 'Mortex', 'Outer Rim Territories', 'R-5'),
('Simpla', 'Kalamith', 'Outer Rim Territories', 'O-5'),
('Simra', NULL, 'Colonies', 'L-13'),
('Sinded', 'D''Aelgoth', 'Mid Rim', 'L-17'),
('Sinjan', 'Albarrio', 'Outer Rim Territories', 'K-5'),
('Sinkar', 'Fakir', 'Colonies', 'K-9'),
('Sinsang', 'Raioballo', 'Outer Rim Territories', 'L-4'),
('Sinta', 'Hune', 'Mid Rim', 'Q-12'),
('Sintheti', 'Noonian', 'Outer Rim Territories', 'N-6'),
('Sinton', 'Rago', 'Mid Rim', 'I-7'),
('Siola', NULL, 'Core Worlds', 'K-12'),
('Sionia', 'Hutt Space', 'Outer Rim Territories', 'S-10'),
('Sipo', 'Kwymar', 'Outer Rim Territories', 'Q-4'),
('Sipsk', 'Kanz', 'Outer Rim Territories', 'N-4'),
('Sirdar', 'Oricho', 'Outer Rim Territories', 'M-6'),
('Siriamp', 'Halm', 'Mid Rim', 'J-16'),
('Sirpar', 'Arkanis', 'Outer Rim Territories', 'R-17'),
('Sisk', 'Calaron', 'Outer Rim Territories', 'U-9'),
('Siskeen', 'Hunnoverrs', 'Outer Rim Territories', 'R-17'),
('Sittana', NULL, 'Core Worlds', 'L-9'),
('Sivad', 'Iskin', 'Mid Rim', 'O-16'),
('Siveria', 'Kibilini', 'Outer Rim Territories', 'Q-17'),
('Sivoria', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Sixela', 'Thuris', 'Outer Rim Territories', 'P-18'),
('Skako', NULL, 'Core Worlds', 'L-9'),
('Skangravi', 'Msst', 'Mid Rim', 'P-7'),
('Skann', 'Astal', 'Outer Rim Territories', 'Q-18'),
('Skaradosh', NULL, 'Inner Rim', 'N-13'),
('Skaross', 'Morshdine', 'Outer Rim Territories', 'O-4'),
('Skarpos', 'Grumani', 'Outer Rim Territories', 'N-17'),
('Skartis', 'Senex', 'Mid Rim', 'L-17'),
('Skeebo', 'Shadola', 'Outer Rim Territories', 'U-8'),
('Skeressa', 'Cadma', 'Outer Rim Territories', 'T-8'),
('Skine', 'Skine', 'Outer Rim Territories', 'Q-19'),
('Skone', 'Brak', 'Expansion Region', 'O-14'),
('Skorrupon', 'Trans-Vulta', 'Mid Rim', 'N-7'),
('Skree', 'Chitargahr', 'Expansion Region', 'K-15'),
('Skuhl', 'Spadja', 'Outer Rim Territories', 'R-5'),
('Skustell Cluster', 'Tarabba', 'Outer Rim Territories', 'N-19'),
('Skuumaa', 'Mytaranor', 'Mid Rim', 'Q-9'),
('Skye', 'Varada', 'Outer Rim Territories', 'H-19'),
('Skynara', 'Skine', 'Outer Rim Territories', 'P-19'),
('Sleedara', NULL, 'Core Worlds', 'L-12'),
('Sleheyron', 'Hutt Space', 'Outer Rim Territories', 'S-10'),
('Slession', NULL, 'Inner Rim', 'K-14'),
('Slivia', 'Astal', 'Outer Rim Territories', 'Q-17'),
('Sljee', 'Ehosiq', 'Expansion Region', 'M-8'),
('Sloogaria', 'Rseik', 'Outer Rim Territories', 'N-19'),
('Slotern', 'Wazta', 'Outer Rim Territories', 'J-18'),
('Sluis Van', 'Sluis', 'Outer Rim Territories', 'M-19'),
('Sluudren', 'Chorlian', 'Outer Rim Territories', 'S-4'),
('Smarab', 'Dohlbani', 'Mid Rim', 'R-14'),
('Smarck', 'Cademimu', 'Outer Rim Territories', 'K-6'),
('Smarteel', NULL, 'Wild Space', 'U-14'),
('Smuggler''s Run', 'Gaulus', 'Outer Rim Territories', 'S-18'),
('Sneeve', 'Kastolar', 'Mid Rim', 'Q-10'),
('Snevu', NULL, 'Unknown Regions', 'H-7'),
('Snowdn', 'Centrality', 'Outer Rim Territories', 'U-8'),
('Snugano', 'Spirva', 'Mid Rim', 'L-17'),
('Sochi', NULL, 'Inner Rim', 'M-9'),
('Soco-Jarel', 'Xappyh', 'Outer Rim Territories', 'Q-4'),
('Socorro', 'Kibilini', 'Outer Rim Territories', 'Q-17'),
('Soika', NULL, 'Inner Rim', 'M-8'),
('Sojourn', 'Carrion', 'Outer Rim Territories', 'J-4'),
('Solacton', 'Tharin (Periphery)', 'Outer Rim Territories', 'S-8'),
('Solaest', 'Belsmuth', 'Outer Rim Territories', 'O-6'),
('Solanus', 'Lothal', 'Outer Rim Territories', 'U-7'),
('Solarine', 'Suolriep', 'Outer Rim Territories', 'S-8'),
('Solassus', NULL, 'Core Worlds', 'M-11'),
('Solay', 'Lothal', 'Outer Rim Territories', 'U-7'),
('Solem', 'Rayter', 'Outer Rim Territories', 'J-19'),
('Solibus', 'Chitarghar', 'Expansion Region', 'K-15'),
('Solitair', 'Garwian Unity', 'Unknown Regions', 'D-8'),
('Solloops', 'Kuat', 'Core Worlds', 'M-10'),
('Solu', 'Meridian', 'Outer Rim Territories', 'R-6'),
('Solubria', 'Shadola', 'Outer Rim Territories', 'T-8'),
('Somavva', 'Tharin (Divis Arm)', 'Outer Rim Territories', 'S-8'),
('Someilk', 'Seswenna', 'Outer Rim Territories', 'M-17'),
('Somov Rit', 'Onatos', 'Mid Rim', 'R-15'),
('Son-tuul', 'Perinn', 'Outer Rim Territories', 'J-4'),
('Sondarr', 'Sertar', 'Outer Rim Territories', 'R-5'),
('Sonn', 'Vilmari Colundra', 'Outer Rim Territories', 'S-5'),
('Sontara', NULL, 'Core Worlds', 'M-12'),
('Sontor', 'Tungra', 'Outer Rim Territories', 'K-19'),
('Soola', 'Khuiumin', 'Outer Rim Territories', 'O-18'),
('Sooma', 'Thanium', 'Outer Rim Territories', 'R-6'),
('Sooncanoo', NULL, 'Inner Rim', 'K-8'),
('Sorca Retreat', NULL, 'Inner Rim', 'O-8'),
('Sorderia', 'Suolriep', 'Outer Rim Territories', 'S-9'),
('Sorella', 'Tapani', 'Colonies', 'L-13'),
('Skor', 'Airam', 'Outer Rim Territories', 'M-20'),
('Sorfina', NULL, 'Inner Rim', 'O-8');