-- Insert final galactic systems from Ychthyton to Zznza
INSERT INTO public.galactic_systems (name, sector, region, grid_coordinates) VALUES
('Ychthyton', 'Belderone', 'Outer Rim Territories', 'R-6'),
('Yde', 'Nicandra', 'Mid Rim', 'M-7'),
('Yeksom', 'Antemeridian', 'Outer Rim Territories', 'R-7'),
('Yelsain', 'Minos Cluster', 'Outer Rim Territories', 'M-20'),
('Yerbana', 'Savareen', 'Outer Rim Territories', 'Q-17'),
('Yerej', 'Tungra', 'Outer Rim Territories', 'K-18'),
('Yerphonia', NULL, 'Core Worlds', 'L-9'),
('Yeshocq', 'Mulgard', 'Mid Rim', 'N-16'),
('Yethra', 'Bon''nyuw-Luq', 'Outer Rim Territories', 'N-17'),
('Yetnis', NULL, 'Inner Rim', 'K-8'),
('Yetoom', 'Senex', 'Mid Rim', 'L-18'),
('Yev', 'Yushan', 'Mid Rim', 'K-17'),
('Yhifar', 'Juvex', 'Mid Rim', 'L-17'),
('Yhuli', 'Jospro', 'Outer Rim Territories', 'R-7'),
('Yinchorr', 'Fellwe', 'Expansion Region', 'L-8'),
('Yir Tangee', NULL, 'Colonies', 'L-8'),
('Yirt-4138-Grek-12', 'Fakir', 'Colonies', 'K-9'),
('Yisgga', NULL, 'Inner Rim', 'M-13'),
('Yitabo', 'Kastolar', 'Mid Rim', 'Q-10'),
('Yityl', 'Quence', 'Outer Rim Territories', 'O-18'),
('Ylesia', NULL, 'Hutt Space', 'T-12'),
('Ylix', 'M''shinni', 'Mid Rim', 'M-7'),
('Yllotat', 'Bothan', 'Mid Rim', 'R-14'),
('Yn', NULL, 'Inner Rim', 'K-14'),
('Yntrann', NULL, 'Wild Space', 'O-3'),
('Yoberra', 'Airam', 'Outer Rim Territories', 'M-20'),
('Yoggoy', NULL, 'Unknown Regions', 'H-7'),
('Yolthani', 'Nijune', 'Outer Rim Territories', 'N-5'),
('Yoon Cloud', NULL, 'Wild Space', 'V-9'),
('Yordain Core', NULL, 'Inner Rim', 'L-15'),
('Yorgraxx', 'Prefsbelt', 'Outer Rim Territories', 'K-5'),
('Yoribuunt', 'Tharin', 'Outer Rim Territories', 'S-8'),
('Yorn Skot', NULL, 'Inner Rim', 'N-14'),
('Yoturba', NULL, 'Mid Rim', 'I-7'),
('Yout', 'Qiilura', 'Mid Rim', 'L-7'),
('Yrrna', 'Tamarin', 'Outer Rim Territories', 'N-19'),
('Ytha''ac Cluster', 'Airam', 'Outer Rim Territories', 'M-20'),
('Yuga', 'Sanbra', 'Outer Rim Territories', 'O-17'),
('Yugami', 'Atravis', 'Outer Rim Territories', 'L-19'),
('Yulant', NULL, 'Core Worlds', 'L-10'),
('Yungbrii', 'Far Xandil', 'Mid Rim', 'O-16'),
('Yunkor', 'Jjannex', 'Outer Rim Territories', 'K-19'),
('Yurb', 'Suolriep', 'Outer Rim Territories', 'S-10'),
('Yutan', 'Ombakond', 'Expansion Region', 'P-12'),
('Yutusk', 'Mortex', 'Outer Rim Territories', 'R-5'),
('Yuvern', 'Oplovis', 'Outer Rim Territories', 'M-5'),
('Yuw', 'Herdessa', 'Mid Rim', 'Q-16'),
('Yvara', 'Kathol (Rift)', 'Outer Rim Territories', 'M-21'),
('Ywllandr', 'Prefsbelt', 'Outer Rim Territories', 'K-5'),
('Z-LOQ', 'D''Aelgoth', 'Mid Rim', 'L-17'),
('Z''fell', 'Farlax', 'Core Worlds', 'K-10'),
('Z''trop', 'Tamarin', 'Outer Rim Territories', 'N-18'),
('Zaadja', 'Savareen', 'Outer Rim Territories', 'R-16'),
('Zabba', 'Bheriz', 'Outer Rim Territories', 'T-11'),
('Zabian', 'Phelleem', 'Outer Rim Territories', 'S-7'),
('Zadaria', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Zaddja', 'Trilon', 'Outer Rim Territories', 'H-15'),
('Zairona', 'Bon''nyuw-Luq', 'Outer Rim Territories', 'N-18'),
('Zakuul', NULL, 'Unknown Regions', 'F-4'),
('Zallo', 'Tamarin', 'Outer Rim Territories', 'N-18'),
('Zalori', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Zaloriis', 'Askarian', 'Expansion Region', 'P-12'),
('Zalso', NULL, 'Core Worlds', 'M-11'),
('Zamael', NULL, 'Deep Core', 'K-12'),
('Zanbar', 'Mandalore', 'Outer Rim Territories', 'O-7'),
('Zandrax', 'Nilgaard', 'Outer Rim Territories', 'T-5'),
('Zarak', 'Greater Plooriod', 'Expansion Region', 'M-7'),
('Zaraksander', 'Imberlin', 'Expansion Region', 'P-14'),
('Zardossa Stix', NULL, 'Colonies', 'J-13'),
('Zaria', 'Juvex', 'Mid Rim', 'L-17'),
('Zarkis', 'Suolriep', 'Outer Rim Territories', 'S-9'),
('Zarracina', 'Zarracina', 'Expansion Region', 'O-14'),
('Zarsteck', NULL, 'Core Worlds', 'M-12'),
('Zastiga', 'Kallea', 'Outer Rim Territories', 'K-20'),
('Zav Alox', 'Trilon', 'Outer Rim Territories', 'H-15'),
('Zavian Abyss', 'Ghost Nebula', 'Expansion Region', 'P-10'),
('Zaxxovia', 'Gomar', 'Inner Rim', 'K-14'),
('Zchtek', 'Bortele', 'Mid Rim', 'R-8'),
('Zebitrope', 'Centrality', 'Outer Rim Territories', 'T-8'),
('Zeenada', 'Immerian Outback', 'Expansion Region', 'O-14'),
('Zeffo', 'Kanz', 'Outer Rim Territories', 'M-3'),
('ZeHeth', 'Dustig', 'Mid Rim', 'N-16'),
('Zeitooine', NULL, 'Inner Rim', 'N-13'),
('Zekulae', 'Zeemacht Cluster', 'Inner Rim', 'N-8'),
('Zelaba', 'Outer Jalor', 'Mid Rim', 'I-7'),
('Zelos', 'Tyus', 'Mid Rim', 'N-16'),
('Zeltros', NULL, 'Inner Rim', 'O-10'),
('Zemiah''s Den', NULL, 'Core Worlds', 'J-12'),
('Zenezia', 'Thand', 'Expansion Region', 'J-15'),
('Zenn-La', 'Venzeiia', 'Expansion Region', 'O-12'),
('Zenox Cluster', NULL, 'Colonies', 'K-13'),
('Zeolosia', 'Mulgard (Hallu)', 'Mid Rim', 'N-16'),
('Zephry', 'Javin (Anoat)', 'Outer Rim Territories', 'K-18'),
('Zequardia', 'Dalchon', 'Outer Rim Territories', 'R-17'),
('Zerm', 'Kessel', 'Outer Rim Territories', 'T-10'),
('Zero Drift', 'Lantillian', 'Mid Rim', 'P-8'),
('Zeta 0-9', NULL, 'Wild Space', 'K-2'),
('Zhadalene', 'Kanz', 'Outer Rim Territories', 'N-4'),
('Zhann', NULL, 'Colonies', 'M-13'),
('Zhanox', 'Javin (Anoat)', 'Outer Rim Territories', 'K-18'),
('Zhina', 'Farlax', 'Core Worlds', 'K-10'),
('Zhotta', 'Mayagil', 'Outer Rim Territories', 'M-18'),
('Zi''Dek', 'Kallea', 'Outer Rim Territories', 'K-20'),
('Zigoola', NULL, 'Wild Space', 'U-6'),
('Zimara', 'Calaron', 'Outer Rim Territories', 'U-9'),
('Zin Taal', 'Carrion', 'Outer Rim Territories', 'J-4'),
('Ziost', 'Esstran (Sith Worlds)', 'Outer Rim Territories', 'R-4'),
('Zipthar', 'Dalonbian', 'Outer Rim Territories', 'L-2'),
('Zircon', 'Calaron', 'Outer Rim Territories', 'T-9'),
('Zirulast', 'Belasco', 'Expansion Region', 'P-11'),
('Zisia', NULL, 'Hutt Space', 'S-10'),
('Zissh', 'Brevost', 'Expansion Region', 'O-15'),
('Ziugen', NULL, 'Hutt Space', 'T-12'),
('Zlarbv', NULL, 'Inner Rim', 'O-10'),
('Zobbera', 'Karthakk', 'Outer Rim Territories', 'Q-17'),
('Zoh', 'Sarka', 'Mid Rim', 'Q-8'),
('Zohakka', 'Corthenia', 'Mid Rim', 'K-7'),
('Zolan', 'Lambda', 'Mid Rim', 'P-16'),
('Zoma', 'Hunnoverrs', 'Outer Rim Territories', 'S-17'),
('Zona Miki', 'Thrasybule', 'Outer Rim Territories', 'P-6'),
('Zongorlu', 'Noonian', 'Outer Rim Territories', 'M-6'),
('Zonju', NULL, 'Wild Space', 'J-21'),
('Zoph', 'Wazta', 'Outer Rim Territories', 'J-18'),
('Zoraster', 'Zoraster', 'Outer Rim Territories', 'U-13'),
('Zorb', 'Meram', 'Outer Rim Territories', 'O-4'),
('Zorbia', 'Zuma (Moddell)', 'Outer Rim Territories', 'H-16'),
('Zosha', NULL, 'Unknown Regions', 'F-6'),
('Zrak', 'Nijune', 'Outer Rim Territories', 'N-5'),
('Zuggit', NULL, 'Inner Rim', 'M-13'),
('Zuliria', 'Eucer', 'Mid Rim', 'R-7'),
('Zusi', 'Var Hagen', 'Mid Rim', 'M-16'),
('ZXK-100346', 'Atravis', 'Outer Rim Territories', 'L-19'),
('Zybahhod', 'Herios', 'Outer Rim Territories', 'T-15'),
('Zygerria', 'Chorlian', 'Outer Rim Territories', 'S-4'),
('Zygia', 'Manda', 'Mid Rim', 'R-14'),
('Zyluria', 'Juvex', 'Mid Rim', 'L-17'),
('Zyzar', 'Astal', 'Outer Rim Territories', 'Q-17'),
('Zyzek', NULL, 'Unknown Regions', 'F-9'),
('Zznza', 'Yminis', 'Outer Rim Territories', 'S-14');