-- Insert galactic systems from Sorgal to Tarchalia (250 systems)
INSERT INTO galactic_systems (name, sector, region, grid_coordinates) VALUES
('Sorgal', 'Mieru''kar', 'Outer Rim Territories', 'N-4'),
('Sorgan', 'Karthakk', 'Outer Rim Territories', 'Q-17'),
('Sorimow', 'Pacanth Reach', 'Outer Rim Territories', 'H-16'),
('Sorjus', 'Meridian', 'Outer Rim Territories', 'R-7'),
('Sorl', 'Dantus', 'Outer Rim Territories', 'J-6'),
('Sormahil', 'Corva', 'Outer Rim Territories', 'P-3'),
('Sorotarr', 'Yushan', 'Mid Rim', 'K-17'),
('Sorrus', 'Kalamith', 'Outer Rim Territories', 'O-5'),
('Sortuvia', 'Xappyh', 'Outer Rim Territories', 'Q-3'),
('Soruus', 'Cronese Mandate', 'Outer Rim Territories', 'S-6'),
('Soterios', 'Tapani', 'Colonies', 'L-13'),
('Soul''s Lament', 'Greater Plooriod', 'Expansion Region', 'M-7'),
('Soule', NULL, 'Core Worlds', 'L-12'),
('Soullex', NULL, 'Wild Space', 'P-3'),
('Soun', NULL, 'Expansion Region', 'J-8'),
('Space Station Scardia', 'Null Zone', 'Expansion Region', 'P-12'),
('Space Station Trenchant', 'Trax', 'Mid Rim', 'Q-10'),
('Spaceport THX1138', 'Fath', 'Outer Rim Territories', 'K-6'),
('Spalex', 'Dantus', 'Outer Rim Territories', 'J-6'),
('Spangled Veil Nebula', 'Meridian', 'Outer Rim Territories', 'R-7'),
('Spanthaer', NULL, 'Inner Rim', 'N-9'),
('Sparingia', NULL, 'Core Worlds', 'L-13'),
('Sparth', 'Prefsbelt', 'Outer Rim Territories', 'K-6'),
('Spawn Nebula', 'Corva', 'Outer Rim Territories', 'P-4'),
('Speco', 'Bon''nyuw-Luq', 'Outer Rim Territories', 'N-18'),
('Spee', 'Saijo', 'Outer Rim Territories', 'K-20'),
('Spefik', 'Atrivis', 'Outer Rim Territories', 'L-5'),
('Spellhaus', 'Meerian', 'Outer Rim Territories', 'O-6'),
('Sperin', 'Bajic', 'Outer Rim Territories', 'P-17'),
('Spice Terminus', 'Parmic', 'Outer Rim Territories', 'P-18'),
('Spillwater', 'Candoras', 'Outer Rim Territories', 'J-5'),
('Spinax', 'Allied Tion', 'Outer Rim Territories', 'S-6'),
('Spindrift', 'Rseik', 'Outer Rim Territories', 'N-20'),
('Spintir', 'Spadja', 'Outer Rim Territories', 'Q-6'),
('Spira', 'Lytton', 'Core Worlds', 'L-10'),
('Spirador', 'Tandon', 'Mid Rim', 'Q-14'),
('Spirana', NULL, 'Inner Rim', 'N-13'),
('Sposia', 'Chiss Space', 'Unknown Regions', 'F-8'),
('Sprizen', 'Sprizen', 'Outer Rim Territories', 'N-5'),
('Spuma', 'Seswenna', 'Outer Rim Territories', 'M-18'),
('Spunchina', NULL, 'Wild Space', 'H-17'),
('Spur, The', 'Quence', 'Outer Rim Territories', 'O-18'),
('Squamat', 'Mayagil', 'Outer Rim Territories', 'M-18'),
('Squan Station', 'Arboo', 'Outer Rim Territories', 'S-16'),
('Squarr', 'Atrivis', 'Outer Rim Territories', 'L-5'),
('Sran', 'Ash Worlds', 'Outer Rim Territories', 'T-6'),
('Sriluur', 'Tharin (Periphery)', 'Outer Rim Territories', 'S-8'),
('Sronk', 'Oplovis', 'Outer Rim Territories', 'M-5'),
('Ssi-ruuvi Cluster', NULL, 'Unknown Regions', 'C-16'),
('Ssori', 'Klina', 'Outer Rim Territories', 'S-13'),
('Staggec', 'Bajic', 'Outer Rim Territories', 'P-17'),
('Stalimur', 'Tion Hegemony', 'Outer Rim Territories', 'S-6'),
('Stalsinek', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('StarForge Nebula', 'Ado', 'Mid Rim', 'M-17'),
('Starlag', 'Hevvrol', 'Mid Rim', 'O-15'),
('Starlyte Station', 'Ado', 'Mid Rim', 'M-17'),
('Starport Borgo', 'Oricho', 'Outer Rim Territories', 'M-6'),
('StarStation 12', NULL, 'Wild Space', 'O-20'),
('Starswarm Cluster', 'Koros', 'Deep Core', 'L-10'),
('Stassia', NULL, 'Deep Core', 'L-10'),
('Station 88', 'Vorc', 'Mid Rim', 'J-7'),
('Station Zeta', NULL, 'Inner Rim', 'K-14'),
('Steelious', NULL, 'Core Worlds', 'K-13'),
('Steergard', 'Thesme', 'Outer Rim Territories', 'O-6'),
('Stellan', 'Hunnoverrs', 'Outer Rim Territories', 'R-16'),
('Stend', 'Juris', 'Outer Rim Territories', 'P-17'),
('Stennaros', 'Har Worlds (Stennes)', 'Expansion Region', 'K-16'),
('Stenness', 'Airon', 'Inner Rim', 'O-10'),
('Stenos', 'Spadja', 'Outer Rim Territories', 'R-5'),
('Stensen''s Colony', 'Stensen', 'Outer Rim Territories', 'I-16'),
('Sterdic', 'Ryndellian', 'Mid Rim', 'P-17'),
('Stewjon', NULL, 'Deep Core', 'M-10'),
('Stic', 'Xappyh', 'Outer Rim Territories', 'Q-3'),
('Stieg', 'Calaron', 'Outer Rim Territories', 'T-9'),
('Stivic', 'Garwian Unity', 'Unknown Regions', 'D-8'),
('Stobar', 'Boeus', 'Expansion Region', 'M-15'),
('Stoga', 'Bitrose', 'Outer Rim Territories', 'T-17'),
('Storinal', 'Noonian', 'Outer Rim Territories', 'N-6'),
('Storthus', 'Churba', 'Mid Rim', 'P-15'),
('Stovax', NULL, 'Core Worlds', 'J-10'),
('Strata', NULL, 'Inner Rim', 'L-8'),
('Stribos', NULL, 'Core Worlds', 'M-10'),
('Strokill Prime', 'Calamari', 'Outer Rim Territories', 'U-6'),
('Stygeon', 'Nuiri', 'Outer Rim Territories', 'Q-6'),
('Stygian Caldera', 'Esstran (Sith Worlds)', 'Outer Rim Territories', 'R-5'),
('Stygmarn', 'Bri''ahl', 'Outer Rim Territories', 'I-17'),
('Stylar Nebula', 'Corva', 'Outer Rim Territories', 'P-4'),
('Styx', 'Baxel', 'Outer Rim Territories', 'U-11'),
('Suarbi', 'Quence', 'Outer Rim Territories', 'O-19'),
('Suba', 'Atravis', 'Outer Rim Territories', 'L-19'),
('Subterrel', 'Subterrel', 'Outer Rim Territories', 'L-20'),
('Sucharme', 'Grohl', 'Outer Rim Territories', 'R-15'),
('Sufezz', 'Jubilar', 'Outer Rim Territories', 'T-8'),
('Suhuurmin', 'Quence', 'Outer Rim Territories', 'P-18'),
('Sukkult', NULL, 'Inner Rim', 'L-14'),
('Suliana', 'Senex', 'Mid Rim', 'L-18'),
('Sulloria', 'Svivreni', 'Outer Rim Territories', 'O-19'),
('Sullust', 'Brema', 'Outer Rim Territories', 'M-17'),
('Sulorine', 'Suolriep', 'Outer Rim Territories', 'S-7'),
('Sumarin', 'Abrion', 'Outer Rim Territories', 'S-15'),
('Sumitra', 'Sumitra', 'Expansion Region', 'N-7'),
('Sump', 'Koradin', 'Outer Rim Territories', 'I-18'),
('Sunaj', 'Videnda', 'Outer Rim Territories', 'L-18'),
('Sundered Veil, The', 'Phelleem', 'Outer Rim Territories', 'S-7'),
('Sunin', 'Tharin', 'Outer Rim Territories', 'S-8'),
('Sunrise', NULL, 'Unknown Regions', 'F-7'),
('Sunshi', 'Rseik', 'Outer Rim Territories', 'N-20'),
('Suntilla', NULL, 'Colonies', 'N-12'),
('Suolriep', 'Suolriep', 'Outer Rim Territories', 'S-8'),
('Suraz', 'Kalamith (Mirrin)', 'Outer Rim Territories', 'P-5'),
('Surcaris', 'Trans-Vulta', 'Mid Rim', 'O-7'),
('Surd Nebula', 'Atravis', 'Outer Rim Territories', 'L-19'),
('Surdapan Station', 'Ojoster', 'Mid Rim', 'N-7'),
('Suria', 'Kira', 'Expansion Region', 'N-16'),
('Surrakea', 'Terr''skiar', 'Mid Rim', 'P-10'),
('Surron', 'Surron', 'Expansion Region', 'O-13'),
('Suurja', 'Ojoster', 'Outer Rim Territories', 'N-7'),
('Sva''leer', 'Corva', 'Outer Rim Territories', 'P-3'),
('Svaaha', NULL, 'Core Worlds', 'K-9'),
('Svivren', 'Svivreni', 'Outer Rim Territories', 'O-19'),
('Svolten', 'Esstran (Sith Worlds)', 'Outer Rim Territories', 'R-4'),
('Swarquen', 'Videnda', 'Outer Rim Territories', 'M-18'),
('Swedlan', 'Kathol (Outback)', 'Outer Rim Territories', 'M-21'),
('Swellen', 'Airam', 'Outer Rim Territories', 'L-20'),
('Switchmount', 'Gendius', 'Mid Rim', 'J-17'),
('Sy Myrth', 'Jospro', 'Outer Rim Territories', 'S-7'),
('Syboona', 'Danjar', 'Outer Rim Territories', 'N-18'),
('Symbia', 'Koros', 'Deep Core', 'K-10'),
('Syndaar', 'Thrasybule', 'Outer Rim Territories', 'P-6'),
('Syned', 'Grumani', 'Outer Rim Territories', 'N-17'),
('Syngia', 'Sertar', 'Outer Rim Territories', 'R-5'),
('Syni', NULL, 'Wild Space', 'P-19'),
('Synistahg', 'Lothal', 'Outer Rim Territories', 'U-7'),
('Synjax', 'Maldrood', 'Mid Rim', 'R-7'),
('Syruss', 'Pakuuni', 'Outer Rim Territories', 'T-5'),
('Syvris', 'Al''Nasrl', 'Outer Rim Territories', 'T-13'),
('T''olan', 'Tiala', 'Mid Rim', 'K-7'),
('T''surr', 'Nuon e Safyd', 'Expansion Region', 'P-12'),
('Taanab', NULL, 'Inner Rim', 'O-8'),
('Tabiid', 'Perkell', 'Mid Rim', 'Q-7'),
('Taboon', 'Airon', 'Inner Rim', 'O-10'),
('Taborin', 'Mayagil', 'Outer Rim Territories', 'M-18'),
('Tah''Nuhna', 'Haserian', 'Mid Rim', 'Q-14'),
('Tahina', 'Chorlian', 'Outer Rim Territories', 'R-4'),
('Tahlboor', 'Thanium', 'Outer Rim Territories', 'R-5'),
('Tais Brabbo', 'Shadola', 'Outer Rim Territories', 'U-8'),
('Taka Shier', 'Tharin', 'Outer Rim Territories', 'S-8'),
('Takobo', 'Noonian', 'Outer Rim Territories', 'N-6'),
('Takodana', 'Tashtor', 'Mid Rim', 'J-16'),
('Tal Nami', 'Hutt Space', 'Outer Rim Territories', 'R-9'),
('Tal Pi', 'D''Astan', 'Outer Rim Territories', 'P-5'),
('Tala', NULL, 'Inner Rim', 'N-9'),
('Talasea', 'Morobe', 'Colonies', 'N-11'),
('Talay', 'Dufilvian', 'Mid Rim', 'Q-16'),
('Talcene', 'Talcene', 'Mid Rim', 'Q-8'),
('Talcharaim', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Talcim Cluster', 'Cegul', 'Outer Rim Territories', 'M-20'),
('Taldorrah', 'Baroli', 'Expansion Region', 'N-14'),
('Taldot', 'Taldot', 'Mid Rim', 'Q-9'),
('Talesia', 'Sarka', 'Mid Rim', 'Q-8'),
('Talfaglio', 'Corellian', 'Core Worlds', 'M-11'),
('Talhovi', 'Juvex', 'Mid Rim', 'L-18'),
('Talir', 'Tharin (Karstaxon)', 'Outer Rim Territories', 'S-8'),
('Talivar', 'Chorlian', 'Outer Rim Territories', 'S-4'),
('Tallaan', 'Tapani', 'Colonies', 'L-13'),
('Tallaso', 'D''Aelgoth', 'Mid Rim', 'K-17'),
('Tallek', 'Dalicron', 'Outer Rim Territories', 'K-19'),
('Tallia', NULL, 'Core Worlds', 'K-10'),
('Talofan', 'Bajic', 'Outer Rim Territories', 'P-18'),
('Talor', 'Varada', 'Outer Rim Territories', 'H-19'),
('Taloron', NULL, 'Wild Space', 'I-6'),
('Talpiddi', 'Koradin', 'Outer Rim Territories', 'I-18'),
('Talravin', NULL, 'Core Worlds', 'M-10'),
('Talrezan', 'Tandon', 'Mid Rim', 'Q-14'),
('Talu', 'Ojoster', 'Outer Rim Territories', 'N-7'),
('Talvaria', 'Phelleem', 'Outer Rim Territories', 'S-7'),
('Tamazall', 'Boeus', 'Expansion Region', 'M-15'),
('Tamban', NULL, 'Core Worlds', 'K-10'),
('Tamber', 'Tapani', 'Colonies', 'L-13'),
('Tamboon', 'Tungra', 'Outer Rim Territories', 'K-19'),
('Tambor Station', 'Belasco', 'Expansion Region', 'P-11'),
('Tammar', 'Tharin', 'Outer Rim Territories', 'T-8'),
('Tammuz-an', 'Tammuz', 'Outer Rim Territories', 'T-14'),
('Tamra', 'Tolonda', 'Outer Rim Territories', 'Q-17'),
('Tamsye Prime', 'Thanium', 'Outer Rim Territories', 'R-5'),
('Tanalorr', 'Varada', 'Outer Rim Territories', 'H-19'),
('Tanaria', 'Esuain', 'Mid Rim', 'P-7'),
('Tancon', 'Koradin', 'Outer Rim Territories', 'J-18'),
('Tanda', 'Tapani', 'Colonies', 'L-13'),
('Tandankin', 'Spadja', 'Outer Rim Territories', 'R-6'),
('Tandgor', 'Sertar', 'Outer Rim Territories', 'R-5'),
('Tandhor', 'Kwymar', 'Outer Rim Territories', 'P-4'),
('Tandis', NULL, 'Inner Rim', 'N-8'),
('Tandun', 'Kalamith', 'Outer Rim Territories', 'P-5'),
('Tangar', 'Fath', 'Outer Rim Territories', 'K-6'),
('Tangerine', 'Tangerine', 'Core Worlds', 'M-12'),
('Tanger', 'Tapani', 'Colonies', 'L-13'),
('Tangrada-Nii', NULL, 'Core Worlds', 'K-13'),
('Tangrene', 'Morshdine', 'Outer Rim Territories', 'O-4'),
('Tanis', 'Atravis', 'Outer Rim Territories', 'L-19'),
('Tanjay', NULL, 'Core Worlds', 'K-9'),
('Tanquilla Beach', 'Kathol', 'Outer Rim Territories', 'M-21'),
('Tansyl', 'Iskin', 'Mid Rim', 'O-16'),
('Tanta Aurek', 'Grumani', 'Outer Rim Territories', 'M-17'),
('Tanta Besh', 'Grumani', 'Outer Rim Territories', 'M-17'),
('Tantajo', 'Halori', 'Mid Rim', 'P-7'),
('Tantara', NULL, 'Inner Rim', 'K-8'),
('Tanthior', 'Corellian', 'Core Worlds', 'M-11'),
('Tantiss Station', 'Dalonbian', 'Outer Rim Territories', 'M-3'),
('Tantive', 'Kwymar', 'Outer Rim Territories', 'Q-4'),
('Tanto Winn', 'Alui', 'Mid Rim', 'O-17'),
('Tantra', 'Tantra', 'Outer Rim Territories', 'M-19'),
('Tantsor', NULL, 'Unknown Regions', 'I-5'),
('Tanya', 'Tapani', 'Colonies', 'L-13'),
('Tanzis', 'Tapani', 'Colonies', 'L-13'),
('Tao-Grant', 'Manda', 'Mid Rim', 'R-15'),
('Tar Morden', 'Vensensor', 'Expansion Region', 'K-16'),
('Tarabba Prime', 'Tarabba', 'Outer Rim Territories', 'M-19'),
('Taral', 'Calamari', 'Outer Rim Territories', 'U-7'),
('Taraloon', 'Surron', 'Expansion Region', 'O-13'),
('Taratos', NULL, 'Inner Rim', 'J-14'),
('Tarawa', 'Steniplis', 'Outer Rim Territories', 'L-19'),
('Tarchalia', 'Luuq', 'Mid Rim', 'L-7'),
('Taloraan', NULL, 'Expansion Region', 'I-15');