-- Insert additional galactic systems data
INSERT INTO public.galactic_systems (name, sector, region, grid_coordinates) VALUES
('Arron Prime', 'Cassander', 'Outer Rim Territories', 'L-5'),
('Arsteni', NULL, 'Colonies', 'L-8'),
('Artemesium', 'Lifh', 'Mid Rim', 'R-8'),
('Artesia', 'Hangshan', 'Expansion Region', 'P-11'),
('Arthon', 'Ottega', 'Mid Rim', 'L-6'),
('Arthuria', 'Merthian', 'Expansion Region', 'N-14'),
('Artiod Minor', 'Morellian CW*', 'Wild Space', 'S-3'),
('Artom', 'Nuon e Safyd', 'Expansion Region', 'P-12'),
('Artorias', 'Myto', 'Outer Rim Territories', 'K-3'),
('Artus Prime', 'Kwymar', 'Outer Rim Territories', 'Q-4'),
('Aruza', NULL, 'Expansion Region', 'I-14'),
('Arvaka Prime', NULL, 'Inner Rim', 'N-9'),
('Arvala', 'Sevetta', 'Outer Rim Territories', 'S-15'),
('Arveesh Station', 'Eclorar', 'Mid Rim', 'Q-12'),
('Arvina', 'Quiberon', 'Outer Rim Territories', 'S-15'),
('Arzid', 'Calaron', 'Outer Rim Territories', 'T-9'),
('Asamin', 'Strabin', 'Mid Rim', 'M-7'),
('Asation', 'Veragi (Gree Enclave)', 'Outer Rim Territories', 'K-3'),
('Ash Moon 1', 'Jubilar (Kartovian)', 'Outer Rim Territories', 'T-7'),
('Ashas Ree', 'Esstran (Sith Worlds)', 'Outer Rim Territories', 'R-5'),
('Ashas Rine', 'Mortex', 'Outer Rim Territories', 'R-5'),
('Ashash', 'Zarracina', 'Expansion Region', 'N-14'),
('Asher', 'Sprizen', 'Outer Rim Territories', 'N-5'),
('Ashkas-kov', 'Shelsha', 'Colonies', 'M-9'),
('Ashteri''s Cloud', 'Kessel', 'Outer Rim Territories', 'T-10'),
('Askaj', 'Cegul', 'Outer Rim Territories', 'M-20'),
('Askaria', 'Askarian', 'Expansion Region', 'P-12'),
('Askkto-Fen', NULL, 'Wild Space', 'P-19'),
('Asmall', 'Ara Dyelle', 'Inner Rim', 'O-9'),
('Asmeru', 'Senex', 'Mid Rim', 'L-17'),
('Asog', 'Esstran', 'Outer Rim Territories', 'Q-4'),
('Asran', 'Brak', 'Expansion Region', 'O-14'),
('Asrat', NULL, 'Inner Rim', 'N-8'),
('Ast Kikorie', 'Zuma (Moddell)', 'Outer Rim Territories', 'H-16'),
('Asteph''skaff', NULL, 'Wild Space', 'I-6'),
('Asterios', 'Narrant', 'Mid Rim', 'I-16'),
('Asturias', 'Epsi Collective', 'Expansion Region', 'M-16'),
('Asuin', NULL, 'Hutt Space', 'S-11'),
('Asusto', 'Gordian Reach', 'Outer Rim Territories', 'P-5'),
('Asyrphus', 'Perkell', 'Mid Rim', 'Q-7'),
('At Attin', 'Quelii', 'Outer Rim Territories', 'N-6'),
('Atanu', 'Alderath', 'Mid Rim', 'L-7'),
('Atapap', NULL, 'Inner Rim', 'N-12'),
('Atchorb', 'Corporate Sector', 'Outer Rim Territories', 'S-3'),
('Athallia', 'Athallia', 'Expansion Region', 'M-15'),
('Athamar', 'Hewett', 'Mid Rim', 'M-7'),
('Ather', 'Atravis', 'Outer Rim Territories', 'L-20'),
('Athio', 'Mayagil', 'Outer Rim Territories', 'N-18'),
('Athiss', 'Esstran (Sith Worlds)', 'Outer Rim Territories', 'R-4'),
('Athus Klee', 'Kalamith', 'Outer Rim Territories', 'P-5'),
('Atoa', 'Ghost Nebula', 'Expansion Region', 'P-10'),
('Atollon', 'Lothal', 'Outer Rim Territories', 'T-7'),
('Ator', NULL, 'Core Worlds', 'M-10'),
('Atorra', 'Gordian Reach', 'Outer Rim Territories', 'Q-5'),
('Atraken', 'Rolion', 'Outer Rim Territories', 'Q-7'),
('Atrakus', 'Mikaster', 'Expansion Region', 'M-15'),
('Atravis', 'Atravis', 'Outer Rim Territories', 'L-19'),
('Atron', 'Senex', 'Mid Rim', 'L-18'),
('Attahox', 'Hocatar', 'Expansion Region', 'P-12'),
('Atterol', 'Atravis', 'Outer Rim Territories', 'L-19'),
('Atterra', 'Kanz', 'Outer Rim Territories', 'N-4'),
('Aturi Cluster', 'Hook Nebula', 'Outer Rim Territories', 'O-18'),
('Atzerri', NULL, 'Inner Rim', 'M-13'),
('Aur', NULL, 'Colonies', 'J-13'),
('Auratera', 'Vorzyd', 'Outer Rim Territories', 'R-6'),
('Aurea', 'Corellian', 'Core Worlds', 'M-11'),
('Auril', 'Auril', 'Outer Rim Territories', 'R-6'),
('Aurimaus', NULL, 'Wild Space', 'I-16'),
('Austan', 'Arkanis', 'Outer Rim Territories', 'R-16'),
('Avedot', NULL, 'Colonies', 'L-8'),
('Avenel', NULL, 'Inner Rim', 'O-8'),
('Avenelle', 'Lantillian', 'Mid Rim', 'P-9'),
('Averam', 'Seswenna', 'Outer Rim Territories', 'M-18'),
('Averill', 'Teraab', 'Mid Rim', 'P-11'),
('Avernio', NULL, 'Unknown Regions', 'G-5'),
('Avery', 'Belderone', 'Outer Rim Territories', 'R-6'),
('Avidich', 'Chiss Space*', 'Unknown Regions', 'E-8'),
('Aviles Prime', 'Hythrope', 'Expansion Region', 'M-15'),
('Awalia', 'Raioballo', 'Outer Rim Territories', 'L-4'),
('AX-456', 'Barma', 'Colonies', 'M-9'),
('Axion', 'Axion', 'Expansion Region', 'P-10'),
('Axtria', NULL, 'Core Worlds', 'L-9'),
('Axxila', 'D''Astan', 'Outer Rim Territories', 'O-5'),
('Aybaria', 'Steniplis', 'Outer Rim Territories', 'L-19'),
('Ayceezee', 'Kanz', 'Outer Rim Territories', 'N-4'),
('Aylayl', NULL, 'Hutt Space', 'S-12'),
('Aynaboni', NULL, 'Outer Rim Territories', 'J-5'),
('Azbrian', NULL, 'Core Worlds', 'L-12'),
('Azna', 'Demetras', 'Outer Rim Territories', 'P-6'),
('Aztubek', 'Javin', 'Outer Rim Territories', 'K-18'),
('Azum', 'Itopol', 'Expansion Region', 'K-15'),
('Azura', 'Oricho', 'Outer Rim Territories', 'M-6'),
('Azure', 'Truum', 'Mid Rim', 'P-8'),
('Azzameen Station', 'Garis', 'Outer Rim Territories', 'N-17'),
('B-Foroon', 'Arkanis', 'Outer Rim Territories', 'R-16'),
('B''Knos', NULL, 'Wild Space', 'G-16'),
('B''nish', 'Tharin', 'Outer Rim Territories', 'S-8'),
('B''trilla', 'Gordian Reach', 'Outer Rim Territories', 'Q-5'),
('Baarstal', 'Sanbra', 'Outer Rim Territories', 'N-17'),
('Babali', 'Corva', 'Outer Rim Territories', 'P-3'),
('Babbadod', NULL, 'Inner Rim', 'N-14'),
('Bacia', NULL, 'Inner Rim', 'M-14'),
('Bacrana', 'Brak', 'Expansion Region', 'O-14'),
('Bactriasa', NULL, 'Inner Rim', 'O-10'),
('Badfellow Station', NULL, 'Core Worlds', 'M-10'),
('Badtibira', NULL, 'Core Worlds', 'K-12'),
('Baes Logia', 'Quence', 'Outer Rim Territories', 'O-18'),
('Baffia', NULL, 'Deep Core', 'L-12'),
('Baffop', 'Tamarin', 'Outer Rim Territories', 'O-19'),
('Bahalian', 'Astal', 'Outer Rim Territories', 'P-18'),
('Bahlah', 'Thesme', 'Outer Rim Territories', 'O-6'),
('Bajic', 'Bajic', 'Outer Rim Territories', 'P-18'),
('Bakisian Drift', 'Tragan Cluster', 'Outer Rim Territories', 'N-5'),
('Bakkah', 'Thrasybule', 'Outer Rim Territories', 'P-6'),
('Baklek', NULL, 'Inner Rim', 'N-12'),
('Bakura', NULL, 'Wild Space', 'G-16'),
('Bal''demnic', 'Auril', 'Outer Rim Territories', 'R-7'),
('Balaidas', NULL, 'Colonies', 'L-8'),
('Balamak', 'Taldot', 'Mid Rim', 'Q-9'),
('Balanor', 'Noonian', 'Outer Rim Territories', 'M-6'),
('Baldavia', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Baldur', 'Nojic', 'Expansion Region', 'P-9'),
('Balfron', 'Dolomar', 'Core Worlds', 'K-9'),
('Balis-Baurgh', 'Sombure', 'Mid Rim', 'K-16'),
('Balith', NULL, 'Inner Rim', 'N-7'),
('Balmorra', NULL, 'Colonies', 'M-10'),
('Balnab', 'Bright Jewel', 'Mid Rim', 'L-7'),
('Balosar', NULL, 'Core Worlds', 'L-12'),
('Balowa', 'Daalang', 'Mid Rim', 'Q-12'),
('Baltimn', 'Chorlian', 'Outer Rim Territories', 'S-4'),
('Baltizaar', 'Corthenia', 'Mid Rim', 'K-7'),
('Baltro', 'Onatos', 'Mid Rim', 'R-15'),
('Bamasia', NULL, 'Inner Rim', 'N-9'),
('Bamayar', 'Maldrood', 'Mid Rim', 'R-7'),
('Bampa''k', 'Prefsbelt', 'Outer Rim Territories', 'K-5'),
('Ban-Satir', 'Corporate Sector', 'Outer Rim Territories', 'S-4'),
('Banas', 'Sanbra', 'Outer Rim Territories', 'O-17'),
('Banasthau', NULL, 'Inner Rim', 'O-11'),
('Bancar', 'Rayter', 'Outer Rim Territories', 'J-19'),
('Banchii', 'Jjannex', 'Outer Rim Territories', 'K-19'),
('Bandomeer', 'Meerian', 'Outer Rim Territories', 'O-6'),
('Bandonia', NULL, 'Core Worlds', 'L-10'),
('Bannistar Station', 'Hevvrol', 'Mid Rim', 'O-15'),
('Bantu', 'Emmo', 'Core Worlds', 'M-12'),
('Banvhar Station', 'Kriz', 'Outer Rim Territories', 'J-18'),
('Bar Neth', 'Albarrio', 'Outer Rim Territories', 'K-5'),
('Bar''leth', NULL, 'Core Worlds', 'M-10'),
('Baraan-Fa', 'Grumani', 'Outer Rim Territories', 'N-17'),
('Barab', 'Albanin', 'Outer Rim Territories', 'U-12'),
('Barabaras', NULL, 'Mid Rim', 'J-15'),
('Barabesh', NULL, 'Mid Rim', 'I-16'),
('Baraboo', NULL, 'Core Worlds', 'M-11'),
('Baradas', NULL, 'Colonies', 'L-8'),
('Baralou', 'Varada', 'Outer Rim Territories', 'H-20'),
('Baramorra', 'Carrion', 'Outer Rim Territories', 'J-4'),
('Barancar', 'Cronese Mandate', 'Outer Rim Territories', 'S-6'),
('Barbadel', NULL, 'Core Worlds', 'K-13'),
('Barbeen', NULL, 'Deep Core', 'L-10'),
('Barcaria', 'Sombure', 'Mid Rim', 'K-16'),
('Barcola', NULL, 'Colonies', 'N-10'),
('Bardelberan', 'Churnis', 'Mid Rim', 'J-6'),
('Bardotta', 'Shasos', 'Colonies', 'K-13'),
('Bardram', 'Scoft', 'Unknown Regions', 'D-7'),
('Barenth', 'Drannik', 'Expansion Region', 'K-8'),
('Barison', 'Gordian Reach', 'Outer Rim Territories', 'Q-6'),
('Barkhesh', 'Seitia', 'Outer Rim Territories', 'K-19'),
('Barlok', 'Marcol', 'Inner Rim', 'L-8'),
('Barnaba', 'Tapani', 'Colonies', 'L-13'),
('Barnahof', 'Yminis', 'Outer Rim Territories', 'S-14'),
('Baroli', 'Baroli', 'Expansion Region', 'N-14'),
('Baroonda', 'Calaron', 'Outer Rim Territories', 'T-9'),
('Baros', 'Lothal', 'Outer Rim Territories', 'U-7'),
('Barpine', 'Weneen', 'Outer Rim Territories', 'N-6'),
('Barraken', 'Varada', 'Outer Rim Territories', 'H-19'),
('Bars Barka', 'Barsa', 'Mid Rim', 'J-6'),
('Barseg', 'Allied Tion', 'Outer Rim Territories', 'S-6'),
('Bartokan', 'Tamarin', 'Outer Rim Territories', 'N-19'),
('Barton', 'Colundra', 'Outer Rim Territories', 'S-5'),
('Barundi', 'Thanium', 'Outer Rim Territories', 'S-5'),
('Basan', 'Churba', 'Mid Rim', 'P-15'),
('Basarais', 'Kossa', 'Expansion Region', 'O-11'),
('Basath', NULL, 'Colonies', 'J-13'),
('Basilisk', NULL, 'Core Worlds', 'L-9'),
('Baskarn', 'Noonian', 'Outer Rim Territories', 'M-6'),
('Baskron', 'Trax', 'Mid Rim', 'Q-10'),
('Bassadro', NULL, 'Colonies', 'L-13'),
('Bassel', NULL, 'Inner Rim', 'N-13'),
('Basta', 'Core Wyl', 'Outer Rim Territories', 'R-4'),
('Bastatha', NULL, 'Inner Rim', 'N-10'),
('Basteel', 'Corva', 'Outer Rim Territories', 'P-3'),
('Bastion', 'Braxant', 'Outer Rim Territories', 'K-3'),
('Bastooine', 'Graador', 'Mid Rim', 'I-17'),
('Bathoris', NULL, 'Inner Rim', 'N-8'),
('Batonn', 'Ash Worlds (Batonn)', 'Outer Rim Territories', 'T-7'),
('Bator', 'Bai Senex', 'Mid Rim', 'L-18'),
('Batorine', NULL, 'Colonies', 'J-9'),
('Batravia', 'Serathrace', 'Expansion Region', 'P-11'),
('Batuu', 'Trilon', 'Outer Rim Territories', 'G-15'),
('Batuv', 'Askarian', 'Expansion Region', 'P-12'),
('Baummu', 'Shadola', 'Outer Rim Territories', 'U-8'),
('Bavva', 'Javin (Anoat)', 'Outer Rim Territories', 'K-18'),
('Baylagon', NULL, 'Core Worlds', 'M-10'),
('Baylin Cluster', 'Trans-Nebular', 'Mid Rim', 'R-16'),
('Bayora', 'Extorin', 'Expansion Region', 'J-15'),
('Bazaar', 'Halthor', 'Outer Rim Territories', 'M-6'),
('Bazarre', 'Cademimu', 'Outer Rim Territories', 'M-6'),
('Beauchen', 'Vensori', 'Mid Rim', 'P-8'),
('Beckoning Call', 'Starr', 'Inner Rim', 'O-10'),
('Bedlam', 'Thusa', 'Mid Rim', 'O-7'),
('Bedlam Pulsar', 'Thusa', 'Mid Rim', 'O-7'),
('Beetle Nebula', 'Bon''nyuw-Luq', 'Outer Rim Territories', 'N-18'),
('Begali', NULL, 'Inner Rim', 'M-8'),
('Begamor', 'Lahara', 'Outer Rim Territories', 'M-5'),
('Begeren', 'Esstran (Sith Worlds)', 'Outer Rim Territories', 'R-4'),
('Beheboth', 'Sanbra', 'Outer Rim Territories', 'O-17'),
('Beixander', NULL, 'Mid Rim', 'H-15'),
('Belasco', 'Belasco', 'Expansion Region', 'O-11'),
('Belassar', 'Sarla', 'Expansion Region', 'J-8'),
('Belat', 'Vilonis', 'Mid Rim', 'O-16'),
('Belazura', NULL, 'Colonies', 'M-13'),
('Belderone', 'Belderone', 'Outer Rim Territories', 'R-6'),
('Beledeen', NULL, 'Colonies', 'K-13'),
('Belgaroth', NULL, 'Core Worlds', 'K-13'),
('Belial', 'Sanbra', 'Outer Rim Territories', 'N-17');