-- Insert galactic systems from Morgania to Nimban (195 systems)
INSERT INTO galactic_systems (name, sector, region, grid_coordinates) VALUES
('Morgania', 'Yminis', 'Outer Rim Territories', 'S-14'),
('Morishim', 'Albarrio', 'Outer Rim Territories', 'K-5'),
('Morning''s Bell', 'Farlax', 'Core Worlds', 'K-10'),
('Moro', 'Rago', 'Mid Rim', 'I-7'),
('Morogia', NULL, 'Core Worlds', 'M-10'),
('Morseer', 'Quelii', 'Outer Rim Territories', 'O-6'),
('Morton', 'Majoor', 'Expansion Region', 'N-15'),
('Morturia', 'Relgim', 'Outer Rim Territories', 'L-4'),
('Morvogodine', 'Calaron', 'Outer Rim Territories', 'T-9'),
('Moseum', 'Thesme', 'Outer Rim Territories', 'O-6'),
('Moshaw', 'Seswenna', 'Outer Rim Territories', 'M-18'),
('Moskk', 'Albarrio', 'Outer Rim Territories', 'K-5'),
('Mossak', 'Thanium', 'Outer Rim Territories', 'R-6'),
('Motexx', NULL, 'Colonies', 'M-13'),
('Movris', 'Noonian', 'Outer Rim Territories', 'M-6'),
('Mowgle', 'Demophon', 'Core Worlds', 'M-10'),
('Mrinzebon', 'Sombure', 'Mid Rim', 'K-16'),
('Mrisst', 'Fakir', 'Colonies', 'K-9'),
('Mrlsst', 'Tapani', 'Colonies', 'L-13'),
('Msst', 'Msst', 'Mid Rim', 'P-7'),
('Mugaar', 'Bruanii', 'Mid Rim', 'K-18'),
('Mulatan', 'Hutt Space', 'Outer Rim Territories', 'S-10'),
('Muldore', NULL, 'Core Worlds', 'J-9'),
('Mulita', NULL, 'Wild Space', 'H-19'),
('Mullan', 'Keldrath', 'Outer Rim Territories', 'T-6'),
('Mulvar', 'Obtrexta', 'Outer Rim Territories', 'K-3'),
('Munlali', 'Mafir', 'Unknown Regions', 'G-5'),
('Munt Ontdal', 'Fei Hu', 'Mid Rim', 'Q-13'),
('Munto Codru', 'Pakuuni', 'Outer Rim Territories', 'T-6'),
('Muntro', 'Mayagil', 'Outer Rim Territories', 'N-18'),
('Muntuur', 'Sloo', 'Mid Rim', 'P-14'),
('Mupin', 'Rocantor', 'Expansion Region', 'L-15'),
('Muqular', 'Montitian Grant', 'Expansion Region', 'J-15'),
('Murakam', NULL, 'Deep Core', 'M-11'),
('Murgo', NULL, 'Wild Space', 'I-7'),
('Murk', 'Zuma (Moddell)', 'Outer Rim Territories', 'H-16'),
('Murkhana', 'Auril', 'Outer Rim Territories', 'S-6'),
('Murninkam', 'Corva', 'Outer Rim Territories', 'O-3'),
('Musca', 'Merthian', 'Expansion Region', 'N-14'),
('Muskree', 'Colundra', 'Outer Rim Territories', 'S-5'),
('Musson', 'Karthakk', 'Outer Rim Territories', 'Q-16'),
('Mussubir', 'Senex', 'Mid Rim', 'L-17'),
('Mustafar', 'Atravis', 'Outer Rim Territories', 'L-19'),
('Muunilinst', 'Obtrexta', 'Outer Rim Territories', 'K-4'),
('Muuria', NULL, 'Inner Rim', 'M-13'),
('Muzara', 'Trestis', 'Expansion Region', 'K-8'),
('Muzzli', 'Citlik', 'Expansion Region', 'O-15'),
('Mycroft', 'Fakir', 'Colonies', 'K-9'),
('Mydasos', 'Dalicron', 'Outer Rim Territories', 'K-19'),
('Mygeeto', 'Albarrio', 'Outer Rim Territories', 'K-5'),
('Mykapo', 'Ash Worlds', 'Outer Rim Territories', 'T-7'),
('Mylok', 'Airam', 'Outer Rim Territories', 'L-20'),
('Mynock 7 Station', 'Mayagil', 'Outer Rim Territories', 'M-18'),
('Myomar', 'Deadalis', 'Expansion Region', 'J-7'),
('Myrenia', NULL, 'Core Worlds', 'L-9'),
('Myrkr', NULL, 'Inner Rim', 'N-7'),
('Mytar', 'Dufilvian', 'Mid Rim', 'Q-15'),
('Mytaranor', 'Mytaranor', 'Mid Rim', 'P-10'),
('Mytus', NULL, 'Wild Space', 'S-3'),
('MZX32905', 'Kanz', 'Outer Rim Territories', 'N-4'),
('N''dian', 'Spadja', 'Outer Rim Territories', 'R-6'),
('N''ildwab', 'Tynquay', 'Outer Rim Territories', 'Q-4'),
('N''zoth', 'Farlax', 'Core Worlds', 'K-10'),
('Naalol', 'Spirva', 'Mid Rim', 'L-17'),
('Naator', NULL, 'Colonies', 'L-13'),
('Naboo', 'Chommell', 'Mid Rim', 'O-17'),
('Nacon', NULL, 'Deep Core', 'L-10'),
('Nacronis', 'Hollan', 'Mid Rim', 'M-7'),
('Nadaav', NULL, 'Inner Rim', 'M-8'),
('Nadhe', 'Rolion', 'Outer Rim Territories', 'Q-6'),
('Nadiem', 'Baxel', 'Outer Rim Territories', 'U-11'),
('Nadiri', 'Bormea', 'Core Worlds', 'L-9'),
('Nag Ubdur', 'Demetras', 'Outer Rim Territories', 'P-7'),
('Nagoa', NULL, 'Wild Space', 'O-3'),
('Nahsu Minor', 'Ktilac Regions', 'Inner Rim', 'N-9'),
('Najan-Rovi', 'Brema', 'Outer Rim Territories', 'M-17'),
('Najarka', 'Rayter', 'Outer Rim Territories', 'J-19'),
('Najiba', 'Arkanis', 'Outer Rim Territories', 'R-17'),
('Nak Shimor', NULL, 'Colonies', 'M-9'),
('Nakadia', 'Tregillis', 'Expansion Region', 'M-15'),
('Nakrikal Singularity', 'Grumani', 'Outer Rim Territories', 'N-17'),
('Nal Hutta', 'Hutt Space', 'Outer Rim Territories', 'S-12'),
('Nal Kapok', 'Taldot', 'Mid Rim', 'Q-9'),
('Naldar', 'Phelleem', 'Outer Rim Territories', 'S-7'),
('Nalrith', 'Rseik', 'Outer Rim Territories', 'N-20'),
('Nalyd', 'Tharin', 'Outer Rim Territories', 'S-7'),
('Nam Chorios', 'Meridian', 'Outer Rim Territories', 'R-6'),
('Nam Priax', 'Nilgaard', 'Outer Rim Territories', 'S-5'),
('Nam''ta', 'Atrivis', 'Outer Rim Territories', 'L-5'),
('Namadii', 'Churnis', 'Mid Rim', 'I-6'),
('Nameel', 'Mytaranor', 'Mid Rim', 'Q-10'),
('Namore', NULL, 'Colonies', 'L-13'),
('Namzor', 'Esuain', 'Mid Rim', 'P-7'),
('Nanta-Ri', 'Farlax', 'Core Worlds', 'K-10'),
('Nantama', 'Senex', 'Mid Rim', 'L-17'),
('Nanth''ri', 'Kurost', 'Mid Rim', 'Q-12'),
('Nantoon', NULL, 'Colonies', 'M-13'),
('Nantuker', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Naos', NULL, 'Wild Space', 'S-18'),
('Naplousea', 'Tynquay', 'Outer Rim Territories', 'R-4'),
('Naporar', 'Chiss Space', 'Unknown Regions', 'F-8'),
('Naps Fral Cluster', 'Ferra', 'Outer Rim Territories', 'S-16'),
('Nar Bo Sholla', 'Hutt Space', 'Outer Rim Territories', 'R-10'),
('Nar Chunna', 'Hutt Space', 'Outer Rim Territories', 'S-10'),
('Nar Haaska', 'Hutt Space', 'Outer Rim Territories', 'T-11'),
('Nar Kaaga', 'Hutt Space', 'Outer Rim Territories', 'S-13'),
('Nar Kanji', 'Suolriep', 'Outer Rim Territories', 'S-9'),
('Nar Kreeta', 'Hutt Space', 'Outer Rim Territories', 'S-10'),
('Nara', NULL, 'Colonies', 'L-9'),
('Naraka', 'Phelleem', 'Outer Rim Territories', 'S-7'),
('Naran-Shiv', 'Tacuni', 'Expansion Region', 'O-15'),
('Naratar', 'Wornal', 'Mid Rim', 'K-16'),
('Narg', 'Rayter', 'Outer Rim Territories', 'J-19'),
('Narigus', 'Belsmuth', 'Outer Rim Territories', 'O-6'),
('Narkina', 'Abrion', 'Outer Rim Territories', 'S-15'),
('Narq', NULL, 'Colonies', 'N-11'),
('Narragader', 'Kibilini', 'Outer Rim Territories', 'Q-17'),
('Narrant', 'Narrant', 'Mid Rim', 'J-17'),
('Nars', 'Senex', 'Mid Rim', 'L-17'),
('Narth', 'Mayagil', 'Outer Rim Territories', 'N-18'),
('Narvath', 'Narvath', 'Expansion Region', 'O-14'),
('Natalon', 'Piryn Shar', 'Expansion Region', 'K-16'),
('Nath Goordi', 'Tennuutta', 'Mid Rim', 'Q-7'),
('Nathas', 'Questal', 'Core Worlds', 'J-12'),
('Nathema', 'Chorlian', 'Outer Rim Territories', 'S-4'),
('Natinati', NULL, 'Wild Space', 'S-4'),
('Nativum', 'Halla', 'Mid Rim', 'R-9'),
('Nauton', 'Taldot', 'Mid Rim', 'Q-9'),
('Nazzri', 'Lantillian', 'Mid Rim', 'P-9'),
('NCW-781', NULL, 'Wild Space', 'H-18'),
('Nea Dajanam', 'Sern', 'Colonies', 'L-13'),
('Near Indosa', 'Gordian Reach', 'Outer Rim Territories', 'P-6'),
('Near Pando', 'Hutt Space', 'Outer Rim Territories', 'S-14'),
('Neary', 'Calaron', 'Outer Rim Territories', 'T-9'),
('Nebula Forso', 'Meram', 'Outer Rim Territories', 'P-4'),
('Necr''ygor', 'Chommell', 'Mid Rim', 'O-16'),
('Necropolis', 'Zuma (Sugai)', 'Outer Rim Territories', 'H-16'),
('Nedij', 'Samix', 'Outer Rim Territories', 'Q-19'),
('Needan', NULL, 'Wild Space', 'I-20'),
('Neelabi', 'Kibilini', 'Outer Rim Territories', 'Q-17'),
('Neelanon', 'Senex', 'Mid Rim', 'L-17'),
('Neelgaimon', 'Xappyh', 'Outer Rim Territories', 'Q-3'),
('Nefitifi', 'Wazta', 'Outer Rim Territories', 'J-18'),
('Nefri', 'Ciutric', 'Outer Rim Territories', 'N-5'),
('Neijaia', 'Majoor', 'Expansion Region', 'N-15'),
('Neimoidia', 'Quellor', 'Colonies', 'M-10'),
('Neka', 'Raioballo', 'Outer Rim Territories', 'L-4'),
('Nela-Ray', 'Kalamith', 'Outer Rim Territories', 'P-5'),
('Nelfrus', 'Elrood', 'Outer Rim Territories', 'M-20'),
('Nelgenam', 'Tashtor', 'Mid Rim', 'I-16'),
('Nella', 'Tapani', 'Colonies', 'L-13'),
('Nellac Kram', 'Bon''nyuw-Luq', 'Outer Rim Territories', 'N-18'),
('Nelvaan', 'Savareen', 'Outer Rim Territories', 'Q-16'),
('Nelvana Gas Cluster', 'Iskin', 'Mid Rim', 'O-16'),
('Nentan', 'Glythe', 'Mid Rim', 'K-7'),
('Neoli', NULL, 'Wild Space', 'O-20'),
('Neona', 'Tapani', 'Colonies', 'L-13'),
('Nepotis', 'Calaron', 'Outer Rim Territories', 'T-9'),
('Nepoy', 'Senex', 'Mid Rim', 'L-17'),
('Neral', 'Corellian', 'Core Worlds', 'M-11'),
('Neree', 'Suolriep', 'Outer Rim Territories', 'S-9'),
('Nerria', 'Suolriep', 'Outer Rim Territories', 'S-9'),
('Nerrif', 'Vilonis', 'Mid Rim', 'O-16'),
('Neshei', 'Neshei', 'Expansion Region', 'J-8'),
('Neshtab', 'Quohag', 'Inner Rim', 'K-8'),
('Neskar', 'Tashtor', 'Mid Rim', 'I-16'),
('Nessem', 'Lostar', 'Expansion Region', 'M-8'),
('Netalych', NULL, 'Inner Rim', 'N-14'),
('Netolio', 'Tapani', 'Colonies', 'L-13'),
('Nettehi', 'Paataatus Hiveborn', 'Unknown Regions', 'F-9'),
('Neutra', 'Oeiros', 'Expansion Region', 'P-10'),
('Neuvia', NULL, 'Colonies', 'L-9'),
('Nevarro', 'Dalicron', 'Outer Rim Territories', 'K-20'),
('New Agamar', 'Sprizen', 'Outer Rim Territories', 'N-5'),
('New Alderaan', 'Ash Worlds', 'Outer Rim Territories', 'T-6'),
('New Apsolon', 'Terr''skiar', 'Mid Rim', 'P-10'),
('New Ator', 'Arkanis', 'Outer Rim Territories', 'R-16'),
('New Bakstre', 'Cassander (Tendrannan)', 'Outer Rim Territories', 'K-5'),
('New Balosar', 'Arc d''Stot', 'Expansion Region', 'K-15'),
('New Bornalex', 'Belsmuth', 'Outer Rim Territories', 'O-6'),
('New Brampis', NULL, 'Inner Rim', 'M-13'),
('New Brigia', 'Farlax', 'Core Worlds', 'K-10'),
('New Canistel', 'Demetras', 'Outer Rim Territories', 'P-7'),
('New Cov', 'Churba', 'Mid Rim', 'P-14'),
('New Cylimba', 'D''Aelgoth', 'Mid Rim', 'L-17'),
('New Drev''starn', 'Thesme', 'Outer Rim Territories', 'O-6'),
('New Heurkea', 'Calamari', 'Outer Rim Territories', 'U-6'),
('New Holgha', 'Ciutric', 'Outer Rim Territories', 'N-5'),
('New Holstice', 'Maldrood', 'Mid Rim', 'R-7'),
('New Javis', 'Tapani', 'Colonies', 'L-13'),
('New Parsh', 'Perinn', 'Outer Rim Territories', 'J-4'),
('New Plympto', 'Corellian', 'Core Worlds', 'M-11'),
('New Polokia', NULL, 'Inner Rim', 'M-13'),
('New Raithal', 'Annecy', 'Expansion Region', 'P-9'),
('New Ralltiir', 'Lantillian', 'Mid Rim', 'P-8'),
('New Shella', 'Tapani', 'Colonies', 'L-13'),
('New Valis', 'Bri''ahl', 'Outer Rim Territories', 'I-17'),
('Nexator', NULL, 'Inner Rim', 'O-10'),
('Nexer', 'Prackla', 'Expansion Region', 'O-8'),
('Nexus Ortai', 'Hertae', 'Mid Rim', 'Q-14'),
('Nez Peron', 'D''Astan', 'Outer Rim Territories', 'O-5'),
('Nezni', 'Mayagil', 'Outer Rim Territories', 'N-18'),
('Nfolgai', 'Esstran (Sith Worlds)', 'Outer Rim Territories', 'R-4'),
('Nharqis''l', 'Veragi', 'Outer Rim Territories', 'K-2'),
('Niamos', 'Vorzyd', 'Outer Rim Territories', 'R-6'),
('Nibiru', 'Zuma (Kakani)', 'Outer Rim Territories', 'H-16'),
('Nicandra', 'Nicandra', 'Mid Rim', 'M-7'),
('Nichen', 'Morshdine', 'Outer Rim Territories', 'N-4'),
('Nicht Ka', 'Esstran (Sith Worlds)', 'Outer Rim Territories', 'R-5'),
('Niele', NULL, 'Colonies', 'K-13'),
('Nierport', NULL, 'Colonies', 'L-8'),
('Nieuth', 'Wyloff', 'Colonies', 'L-8'),
('Nigel', 'Kira', 'Expansion Region', 'N-16'),
('Nightsend', 'Phelleem', 'Outer Rim Territories', 'S-7'),
('Nightside', 'Sertar', 'Outer Rim Territories', 'R-5'),
('Niian', 'Thaere', 'Expansion Region', 'O-14'),
('Nijune', 'Nijune', 'Outer Rim Territories', 'N-5'),
('Nilash', 'Grumani', 'Outer Rim Territories', 'M-17'),
('Nilg', 'Alderath', 'Mid Rim', 'L-7'),
('Nilgaria', 'Masla', 'Mid Rim', 'J-16'),
('Nim Drovis', 'Meridian', 'Outer Rim Territories', 'R-7'),
('Nimat', 'Tharin', 'Outer Rim Territories', 'T-8'),
('Nimba', NULL, 'Wild Space', 'T-17'),
('Nimban', 'Hutt Space', 'Outer Rim Territories', 'S-10');