-- Insert galactic systems from Risban to Seraphan (250 systems)
INSERT INTO galactic_systems (name, sector, region, grid_coordinates) VALUES
('Risban', 'Tion Hegemony', 'Outer Rim Territories', 'S-5'),
('Rishi', 'Abrion', 'Outer Rim Territories', 'S-15'),
('Risso', NULL, 'Inner Rim', 'N-14'),
('Rivoria', 'Tunka', 'Outer Rim Territories', 'J-19'),
('Rivvidu', 'D''Astan', 'Outer Rim Territories', 'O-5'),
('Ro-Loo Triangle', 'Lambda', 'Mid Rim', 'P-16'),
('Rocantor', 'Rocantor', 'Expansion Region', 'L-15'),
('Rocrin', 'Airam', 'Outer Rim Territories', 'M-20'),
('Rocun Cluster', 'Yminis', 'Outer Rim Territories', 'S-14'),
('Rodaj', NULL, 'Inner Rim', 'L-15'),
('Rodia', 'Savareen', 'Outer Rim Territories', 'R-16'),
('Rodis', 'Zuma (Sugai)', 'Outer Rim Territories', 'H-16'),
('Rogue Antar', 'Steniplis', 'Outer Rim Territories', 'M-18'),
('Roil, The', 'Gordian Reach', 'Outer Rim Territories', 'Q-5'),
('Rokaria', 'Tynquay', 'Outer Rim Territories', 'Q-4'),
('Rokirex', 'Herios', 'Outer Rim Territories', 'T-16'),
('Rol', 'Noonian', 'Outer Rim Territories', 'M-6'),
('Roldalna', 'Kira', 'Expansion Region', 'N-16'),
('Romar', 'Galov', 'Outer Rim Territories', 'T-13'),
('Romik', 'Quelii', 'Outer Rim Territories', 'O-6'),
('Romin', 'Romintine', 'Mid Rim', 'Q-8'),
('Romossobar', 'Eucer', 'Mid Rim', 'R-7'),
('Rondai', NULL, 'Inner Rim', 'J-8'),
('Ronyards', NULL, 'Inner Rim', 'N-13'),
('Roon', 'Abrion', 'Outer Rim Territories', 'S-15'),
('Roona', 'Bes Ber Bikade', 'Expansion Region', 'L-15'),
('Roost', 'Bitrose', 'Outer Rim Territories', 'T-17'),
('Ropagi', 'Kira', 'Expansion Region', 'N-16'),
('Roqoo Depot', NULL, 'Inner Rim', 'O-9'),
('Rorak', 'Hutt Space', 'Outer Rim Territories', 'S-12'),
('Rordak', 'Pelgrin', 'Outer Rim Territories', 'R-17'),
('Rorgam', 'Terr''skiar', 'Mid Rim', 'Q-10'),
('Rotas', 'Yminis', 'Outer Rim Territories', 'S-14'),
('Rothana', 'Quiberon', 'Outer Rim Territories', 'T-15'),
('Rotoga', 'Alchenaut', 'Expansion Region', 'L-16'),
('Roundtree', NULL, 'Inner Rim', 'M-14'),
('Routh', 'Velcar', 'Outer Rim Territories', 'J-5'),
('Rowacki', NULL, 'Inner Rim', 'O-10'),
('Roxuli', NULL, 'Expansion Region', 'I-8'),
('Rrulinn', 'Yushan', 'Mid Rim', 'K-17'),
('Rseik', 'Rseik', 'Outer Rim Territories', 'N-20'),
('RTK111', 'Yminis', 'Outer Rim Territories', 'S-14'),
('Ruac', 'Lothal', 'Outer Rim Territories', 'U-7'),
('Ruan', NULL, 'Core Worlds', 'K-10'),
('Rubinero', NULL, 'Core Worlds', 'L-12'),
('Rubogea', NULL, 'Core Worlds', 'L-9'),
('Rudrig', 'Tion Hegemony', 'Outer Rim Territories', 'S-6'),
('Rudun', 'Kontahr', 'Mid Rim', 'R-11'),
('Rugosa', 'Sanbra', 'Outer Rim Territories', 'O-17'),
('Ruhe', 'Savareen', 'Outer Rim Territories', 'Q-17'),
('Ruhnuk', NULL, 'Wild Space', 'H-11'),
('Ruisto', 'Calamari', 'Outer Rim Territories', 'U-6'),
('Rulaar', 'Senex', 'Mid Rim', 'L-17'),
('Rullag', 'Cadma', 'Outer Rim Territories', 'T-8'),
('Ruloosia', 'Oktos', 'Mid Rim', 'R-12'),
('Rumil', 'Mezeg', 'Mid Rim', 'N-7'),
('Runaway Prince', 'Hutt Space', 'Outer Rim Territories', 'R-11'),
('Ruoss Minor', NULL, 'Colonies', 'M-9'),
('Rurgavea', NULL, 'Core Worlds', 'L-13'),
('Rushan', 'Andirma', 'Expansion Region', 'L-15'),
('Rustibar', 'Churnis', 'Mid Rim', 'J-7'),
('Rutal', NULL, 'Wild Space', 'J-13'),
('Rutan', 'Atravis', 'Outer Rim Territories', 'L-20'),
('Ruugia', 'Altier', 'Expansion Region', 'O-13'),
('Ruul', NULL, 'Core Worlds', 'M-10'),
('Ruuria', 'Xappyh', 'Outer Rim Territories', 'Q-3'),
('Ruusan', 'Teraab', 'Mid Rim', 'P-11'),
('Ruweln', 'Bothan', 'Mid Rim', 'R-14'),
('Rya', 'Kwymar', 'Outer Rim Territories', 'P-4'),
('Ryarten', 'Corthenia', 'Mid Rim', 'K-7'),
('Ryborea', 'Ryborean', 'Expansion Region', 'J-8'),
('Rycep', 'Jjannex', 'Outer Rim Territories', 'L-19'),
('Rychel', 'Dalonbian', 'Outer Rim Territories', 'L-2'),
('Rydar', 'Antemeridian', 'Outer Rim Territories', 'R-7'),
('Rydonni Prime', NULL, 'Core Worlds', 'M-11'),
('Ryloon', 'Velcar', 'Outer Rim Territories', 'J-5'),
('Rylorii Minor', 'Rocantor', 'Expansion Region', 'L-15'),
('Ryloth', 'Gaulus (Ryloth)', 'Outer Rim Territories', 'R-17'),
('Ryndellia', 'Ryndellian', 'Mid Rim', 'O-17'),
('Rynmar', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Ryoone', 'Wazta', 'Outer Rim Territories', 'I-17'),
('Rystan', NULL, 'Wild Space', 'M-20'),
('Ryvellia', 'Treffani', 'Expansion Region', 'O-14'),
('Ryvester', 'Meridian', 'Outer Rim Territories', 'R-7'),
('Ryyk Nebula', 'Trans-Vulta', 'Mid Rim', 'N-7'),
('RZ7-6113-23', 'Chopani', 'Outer Rim Territories', 'L-4'),
('Saarn', 'Esstran', 'Outer Rim Territories', 'P-5'),
('Sab Rufo', NULL, 'Inner Rim', 'N-8'),
('Sabanash', 'Tyus', 'Mid Rim', 'N-16'),
('Sabata', 'Halla', 'Mid Rim', 'R-9'),
('Saberhing', 'Corellian', 'Core Worlds', 'M-11'),
('Sabrash', 'Metatessu', 'Mid Rim', 'R-9'),
('Sabrixin', 'Samix', 'Outer Rim Territories', 'Q-19'),
('Saclas', 'Corporate Sector', 'Outer Rim Territories', 'S-4'),
('Sacorria', 'Corellian', 'Core Worlds', 'M-11'),
('Saffa', 'Halla', 'Mid Rim', 'R-8'),
('Saffalore', 'Corporate Sector', 'Outer Rim Territories', 'S-4'),
('Safrifa', 'Videnda', 'Outer Rim Territories', 'M-18'),
('Sag Kemper', 'Tamarin', 'Outer Rim Territories', 'N-18'),
('Sagar', 'Wentrion', 'Inner Rim', 'N-13'),
('Sagma', 'Illisurevimurasi', 'Outer Rim Territories', 'Q-4'),
('Sahbrontee', NULL, 'Mid Rim', 'I-15'),
('Saheelindeel', 'Tion Hegemony', 'Outer Rim Territories', 'S-6'),
('Saijo', 'Saijo', 'Outer Rim Territories', 'K-20'),
('Saila Na', 'Javin (Anoat)', 'Outer Rim Territories', 'K-18'),
('Sakavi', 'Tar', 'Outer Rim Territories', 'I-19'),
('Saki', 'Hutt Space', 'Outer Rim Territories', 'S-11'),
('Sakidopa', 'Hutt Space', 'Outer Rim Territories', 'S-11'),
('Sakiduba', 'Hutt Space', 'Outer Rim Territories', 'S-11'),
('Sakifwanna', 'Hutt Space', 'Outer Rim Territories', 'T-11'),
('Sakreen', 'Ash Worlds', 'Outer Rim Territories', 'S-7'),
('Sakuub', 'Pelgrin', 'Outer Rim Territories', 'R-18'),
('Salagor', NULL, 'Inner Rim', 'N-13'),
('Salaktori Anchorage', NULL, 'Inner Rim', 'O-10'),
('Salaniss', NULL, 'Wild Space', 'H-17'),
('Saleucami', 'Suolriep', 'Outer Rim Territories', 'S-8'),
('Salgarus', NULL, 'Colonies', 'L-9'),
('Salient', 'Aparo', 'Outer Rim Territories', 'R-3'),
('Salin', 'Sprizen', 'Outer Rim Territories', 'N-5'),
('Salissia', NULL, 'Outer Rim Territories', 'T-5'),
('Salliche', NULL, 'Core Worlds', 'K-10'),
('Salmagodro', NULL, 'Inner Rim', 'M-8'),
('Salobea', 'Noonian', 'Outer Rim Territories', 'M-6'),
('Salstan', 'Marzoon', 'Mid Rim', 'I-16'),
('Salteract', 'Rayter', 'Outer Rim Territories', 'J-19'),
('Salvara', 'Tennuutta', 'Mid Rim', 'Q-7'),
('Samaria', NULL, 'Core Worlds', 'M-11'),
('Samarine', 'D''Astan (Samarine)', 'Outer Rim Territories', 'O-5'),
('Samhar', 'Grumani', 'Outer Rim Territories', 'N-17'),
('Sammun', 'Ash Worlds (Batonn)', 'Outer Rim Territories', 'T-7'),
('Samovar', 'Koradin', 'Outer Rim Territories', 'I-18'),
('Sanbra', 'Sanbra', 'Outer Rim Territories', 'O-17'),
('Sandonia', NULL, 'Inner Rim', 'N-14'),
('Sanej', NULL, 'Inner Rim', 'N-13'),
('Sanjin', NULL, 'Colonies', 'M-13'),
('Sanrafsix', 'Grumani', 'Outer Rim Territories', 'N-17'),
('Santarine Hook Nebula', NULL, 'Outer Rim Territories', 'O-18'),
('Santheria', 'Esuain', 'Mid Rim', 'Q-7'),
('Sanyassa', 'Zuma (Moddell)', 'Outer Rim Territories', 'H-16'),
('Sanza', 'Sloo', 'Mid Rim', 'P-14'),
('Sapella', 'Kathol (Outback)', 'Outer Rim Territories', 'M-21'),
('Sappire', 'Dalicron', 'Outer Rim Territories', 'K-20'),
('Saqqar', 'Hutt Space', 'Outer Rim Territories', 'T-11'),
('Saracor', 'Oriolan', 'Mid Rim', 'J-16'),
('Saraf Cobar', 'Montitian Grant', 'Expansion Region', 'J-15'),
('Sarapin', NULL, 'Core Worlds', 'M-10'),
('Sarconia', NULL, 'Colonies', 'M-10'),
('Sardoran', NULL, 'Core Worlds', 'M-11'),
('Sareet', 'Stensen', 'Outer Rim Territories', 'I-17'),
('Sargesso', 'Tharin', 'Outer Rim Territories', 'S-8'),
('Sargon', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Sarina', 'Mektrun', 'Mid Rim', 'L-17'),
('Sarjenn', 'Tragan Cluster', 'Outer Rim Territories', 'N-5'),
('Sarka', 'Sarka', 'Mid Rim', 'Q-8'),
('Sarkania', NULL, 'Inner Rim', 'M-14'),
('Sarkhai', 'M''shinni', 'Mid Rim', 'M-7'),
('Sarko', 'Venzeiia', 'Expansion Region', 'O-12'),
('Sarlucif', NULL, 'Wild Space', 'S-4'),
('Sarm', NULL, 'Wild Space', 'I-8'),
('Sarnikken', 'Fakir', 'Colonies', 'K-9'),
('Sarnus', NULL, 'Wild Space', 'O-3'),
('Sarpazia', 'Illodia', 'Core Worlds', 'K-13'),
('Sarq', NULL, 'Mid Rim', 'I-15'),
('Sarrahban', 'Cyrillian Protectorate', 'Expansion Region', 'O-12'),
('Sarranket', 'Brevost', 'Expansion Region', 'O-15'),
('Sarrassia', 'Grumani', 'Outer Rim Territories', 'N-17'),
('Sarrelon', 'Brevost', 'Expansion Region', 'O-15'),
('Sarrish', 'Vensensor', 'Expansion Region', 'K-16'),
('Sartoy', 'Mieru''kar', 'Outer Rim Territories', 'N-3'),
('Saruwen Station', 'Tamarin', 'Outer Rim Territories', 'N-18'),
('Sarvchi', 'Chiss Space', 'Unknown Regions', 'F-9'),
('Sathiemon', 'Illisurevimurasi', 'Outer Rim Territories', 'Q-4'),
('Sauwecera', NULL, 'Inner Rim', 'N-8'),
('Savareen', 'Savareen', 'Outer Rim Territories', 'Q-16'),
('Savek', 'Esstran (Sith Worlds)', 'Outer Rim Territories', 'R-4'),
('Sawaya', 'Thesme', 'Outer Rim Territories', 'O-6'),
('Sayblohn', 'Quess', 'Mid Rim', 'N-16'),
('Scarif', 'Abrion', 'Outer Rim Territories', 'S-15'),
('Scarl', 'Tapani', 'Colonies', 'L-13'),
('Schesa', 'Chiss Space', 'Unknown Regions', 'F-8'),
('Scillal', 'Centrality', 'Outer Rim Territories', 'T-8'),
('Scipio', 'Albarrio', 'Outer Rim Territories', 'K-5'),
('Seatos', 'Sluis', 'Outer Rim Territories', 'M-19'),
('Sebaddon', NULL, 'Mid Rim', 'Q-11'),
('Sebiris', 'Kathol', 'Outer Rim Territories', 'M-21'),
('Sechar', 'Tharin (Divis Arm)', 'Outer Rim Territories', 'S-8'),
('Secundus Ando', 'Lambda', 'Mid Rim', 'Q-15'),
('Sedapard Cluster', NULL, 'Mid Rim', 'O-16'),
('Sedesia', 'Druess', 'Mid Rim', 'O-16'),
('Sedratis', NULL, 'Core Worlds', 'M-11'),
('Sedri', 'Tharin (Periphery)', 'Outer Rim Territories', 'S-8'),
('Seelos', 'Kwymar', 'Outer Rim Territories', 'Q-4'),
('Seeratter', NULL, 'Wild Space', 'G-14'),
('Seezar''s Planet', 'Jjannex', 'Outer Rim Territories', 'L-19'),
('Sefon', 'Tapani', 'Colonies', 'L-13'),
('Seftek', 'Vorzyd', 'Outer Rim Territories', 'R-6'),
('Segra Milo', 'Jospro', 'Outer Rim Territories', 'R-7'),
('Seidhkona', NULL, 'Wild Space', 'T-5'),
('Seikosha', 'Nembus', 'Outer Rim Territories', 'P-4'),
('Seitia Prime', 'Seitia', 'Outer Rim Territories', 'K-19'),
('Selab', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Selaggis', 'Quelii', 'Outer Rim Territories', 'N-6'),
('Selavia', 'Suolriep', 'Outer Rim Territories', 'S-10'),
('Selenius', 'D''Aelgoth', 'Mid Rim', 'L-17'),
('Seline', 'Dalonbian', 'Outer Rim Territories', 'M-3'),
('Selitan', 'Gordian Reach', 'Outer Rim Territories', 'P-6'),
('Sellasas', 'Jjannex', 'Outer Rim Territories', 'L-18'),
('Selnesh', 'Irishi', 'Mid Rim', 'K-6'),
('Selsor', 'Zarracina', 'Expansion Region', 'O-14'),
('Seltaya Major', 'Mieru''kar', 'Outer Rim Territories', 'O-3'),
('Seltos', 'Mulgard', 'Mid Rim', 'N-16'),
('Seluket', NULL, 'Inner Rim', 'I-9'),
('Selvaris', NULL, 'Wild Space', 'I-9'),
('Semag', 'Semagi', 'Mid Rim', 'I-16'),
('Sembla', 'Sertar (Mahrusha)', 'Outer Rim Territories', 'S-5'),
('Senex', 'Senex', 'Mid Rim', 'L-17'),
('Sennatt', 'Bothan', 'Mid Rim', 'R-14'),
('Sennex', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Sennoa', 'Ojoster', 'Outer Rim Territories', 'N-7'),
('Senthrodys', NULL, 'Inner Rim', 'O-10'),
('Seoul', NULL, 'Wild Space', 'H-20'),
('Sepan', 'Sepan', 'Expansion Region', 'P-13'),
('Septevorres', 'Antemeridian', 'Outer Rim Territories', 'R-7'),
('Seraphan', NULL, 'Colonies', 'N-10');