-- Insert galactic systems from Nimgorrhea to Ord Namurt (193 systems)
INSERT INTO galactic_systems (name, sector, region, grid_coordinates) VALUES
('Nimgorrhea', 'Yminis', 'Outer Rim Territories', 'S-14'),
('Nimia', 'Hutt Space', 'Outer Rim Territories', 'S-9'),
('Ningoth', 'Karthakk', 'Outer Rim Territories', 'Q-16'),
('Ninn', 'Corporate Sector', 'Outer Rim Territories', 'R-3'),
('Ninzam', 'Ryndellian', 'Mid Rim', 'P-17'),
('Niorven', 'Lambda', 'Mid Rim', 'P-16'),
('Niran', 'Tunka', 'Outer Rim Territories', 'I-18'),
('Nirauan', NULL, 'Wild Space', 'I-5'),
('Nirellia', 'Oktos', 'Mid Rim', 'Q-11'),
('Niro', 'Circarpous', 'Expansion Region', 'O-12'),
('Nishmar', NULL, 'Wild Space', 'G-15'),
('Nishr', 'Hunnoverrs', 'Outer Rim Territories', 'R-17'),
('Nista', 'Tapani', 'Colonies', 'L-13'),
('Nithorni', NULL, 'Colonies', 'K-8'),
('Nivek', 'Citlik', 'Expansion Region', 'O-14'),
('Nixor', 'Eclorar', 'Mid Rim', 'Q-12'),
('Nixus', 'Parmic', 'Outer Rim Territories', 'P-18'),
('Nkllon', 'Alchenaut', 'Expansion Region', 'L-16'),
('No-ad', 'Bryx', 'Mid Rim', 'R-7'),
('Noaxson', 'Oricho', 'Outer Rim Territories', 'M-6'),
('Nocto', 'Airam', 'Outer Rim Territories', 'L-20'),
('Noctralis', 'Ehosiq', 'Expansion Region', 'L-8'),
('Noctu', NULL, 'Colonies', 'J-13'),
('Nodgra', 'Airam', 'Outer Rim Territories', 'L-20'),
('Noe''ha''on', 'Piryn Shar', 'Expansion Region', 'K-16'),
('Nojic', 'Nojic', 'Expansion Region', 'O-9'),
('Nolar', NULL, 'Inner Rim', 'N-8'),
('Nomaria', 'Suolriep', 'Outer Rim Territories', 'S-8'),
('Nomlis', 'Vilonis', 'Mid Rim', 'O-16'),
('Noola', 'Relgim', 'Outer Rim Territories', 'L-5'),
('Nooli', 'Noolian', 'Mid Rim', 'Q-13'),
('Noomis Riga', 'Yminis', 'Outer Rim Territories', 'S-14'),
('Noonar', 'Noonian', 'Outer Rim Territories', 'M-6'),
('Noopiths, The', 'Bozhnee', 'Outer Rim Territories', 'L-18'),
('Noori', 'Noori', 'Expansion Region', 'O-10'),
('Nooroyo', 'Cadavine', 'Outer Rim Territories', 'P-17'),
('Nopachi', NULL, 'Core Worlds', 'M-10'),
('Nopces', 'Bormea', 'Core Worlds', 'L-9'),
('Nopsin', NULL, 'Mid Rim', 'I-15'),
('Noquivzor', NULL, 'Colonies', 'K-9'),
('Nora', 'Belshar', 'Mid Rim', 'J-7'),
('Norah', NULL, 'Inner Rim', 'L-14'),
('Norat', 'Farlax', 'Core Worlds', 'K-10'),
('Norclune', NULL, 'Colonies', 'L-8'),
('Nord', 'Kanz', 'Outer Rim Territories', 'N-4'),
('Nordis Prime', 'Vatha', 'Mid Rim', 'K-16'),
('Nordra', NULL, 'Inner Rim', 'N-14'),
('Noremac', 'Kanz', 'Outer Rim Territories', 'N-4'),
('Noris', 'Chiss Space', 'Unknown Regions', 'F-8'),
('Norkronia', NULL, 'Core Worlds', 'K-10'),
('Norne', NULL, 'Core Worlds', 'K-10'),
('Norsid', 'Rseik', 'Outer Rim Territories', 'N-19'),
('Norulac', NULL, 'Inner Rim', 'O-9'),
('Norval', 'Calaron', 'Outer Rim Territories', 'T-9'),
('Noryath', 'Nuiri', 'Outer Rim Territories', 'Q-6'),
('Noryokon', NULL, 'Inner Rim', 'K-8'),
('Nosken', 'Prefsbelt', 'Outer Rim Territories', 'J-6'),
('Notak', 'Doldur', 'Mid Rim', 'P-15'),
('Nothoiin', 'Javin (Anoat)', 'Outer Rim Territories', 'K-18'),
('Notonia', 'Illisurevimurasi', 'Outer Rim Territories', 'Q-4'),
('Nouane', 'Nouane', 'Inner Rim', 'N-8'),
('Noult', NULL, 'Core Worlds', 'L-12'),
('Nova Garon', 'Rayter', 'Outer Rim Territories', 'J-19'),
('Novar', 'Lostar', 'Expansion Region', 'M-8'),
('Novi', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Novka', 'Manda', 'Mid Rim', 'R-14'),
('Novoil Cluster', NULL, 'Colonies', 'N-12'),
('Novolek Beacon', 'Tharin (Periphery)', 'Outer Rim Territories', 'S-8'),
('Novor', 'Tharin', 'Outer Rim Territories', 'S-8'),
('Nuala', 'Trans-Gascon', 'Mid Rim', 'P-7'),
('Nubia', 'Corellian', 'Core Worlds', 'M-11'),
('Nuja', 'Axion', 'Mid Rim', 'P-10'),
('Nulan', 'Hook Nebula', 'Outer Rim Territories', 'O-18'),
('Null', 'Trans-Vulta', 'Mid Rim', 'N-7'),
('Numatra', NULL, 'Core Worlds', 'L-12'),
('Numidian Prime', 'Bright Jewel', 'Mid Rim', 'L-7'),
('Nummunr', 'Ash Worlds', 'Outer Rim Territories', 'S-7'),
('Nunce', NULL, 'Core Worlds', 'L-13'),
('Nuralee', 'Tyus', 'Mid Rim', 'N-16'),
('Nurasenti', 'Abrion', 'Outer Rim Territories', 'S-15'),
('Nuswatta', 'Cronese Mandate', 'Outer Rim Territories', 'S-6'),
('Nuvar', 'Dustig', 'Mid Rim', 'N-17'),
('Nux', 'Endocray', 'Mid Rim', 'R-14'),
('Nwarcol', 'Tharin (Periphery)', 'Outer Rim Territories', 'S-8'),
('Nyara', NULL, 'Inner Rim', 'L-8'),
('Nyarikan Nebula', 'Msst', 'Mid Rim', 'P-7'),
('Nyasko', 'Phelleem (Colunda)', 'Outer Rim Territories', 'S-7'),
('Nyemari', 'Meridian', 'Outer Rim Territories', 'R-6'),
('Nymalia', 'Eidoloni', 'Mid Rim', 'M-17'),
('Nyny', 'Ash Worlds', 'Outer Rim Territories', 'T-7'),
('Nyonpur', 'Daimar', 'Mid Rim', 'Q-16'),
('Nyriaan', 'Trans-Vulta', 'Mid Rim', 'N-7'),
('Nyssa', 'Tapani', 'Colonies', 'L-13'),
('Nysza', 'Dalchon', 'Outer Rim Territories', 'R-17'),
('O''reen', NULL, 'Unknown Regions', 'H-13'),
('Oaka Prime', NULL, 'Inner Rim', 'J-8'),
('Oba Diah', 'Kessel', 'Outer Rim Territories', 'T-10'),
('Obana', 'Arkanis', 'Outer Rim Territories', 'R-16'),
('Obas', 'Andirma', 'Expansion Region', 'L-15'),
('Obelia', 'Tapani', 'Colonies', 'L-13'),
('Oben', NULL, 'Wild Space', 'J-4'),
('Obica', 'Grumani', 'Outer Rim Territories', 'M-17'),
('Obinipor', 'Demetras', 'Outer Rim Territories', 'P-7'),
('Obran Cluster', 'Videnda', 'Outer Rim Territories', 'L-18'),
('Obredaan', 'Irishi', 'Mid Rim', 'K-6'),
('Obroa-skai', NULL, 'Inner Rim', 'N-8'),
('Obsidia', NULL, 'Unknown Regions', 'G-7'),
('Obulette', 'Tapani', 'Colonies', 'L-13'),
('Obumubo', NULL, 'Core Worlds', 'L-13'),
('Obus', NULL, 'Wild Space', 'I-4'),
('Ocahont', 'Alui', 'Mid Rim', 'N-17'),
('Ochotl', 'Airam', 'Outer Rim Territories', 'L-20'),
('Ocktai', 'Kriz', 'Outer Rim Territories', 'K-19'),
('Ocsin', 'Corporate Sector', 'Outer Rim Territories', 'S-3'),
('Octavia', 'Nicandra', 'Mid Rim', 'M-7'),
('Octero', 'Portmoak', 'Outer Rim Territories', 'P-18'),
('Odacer-Faustin', 'Esstran (Sith Worlds)', 'Outer Rim Territories', 'Q-5'),
('Odessen', NULL, 'Wild Space', 'G-11'),
('Odik', NULL, 'Deep Core', 'K-11'),
('Odona', 'Tolonda', 'Outer Rim Territories', 'Q-17'),
('Odos', 'Meridian', 'Outer Rim Territories', 'R-7'),
('Odryn', 'Noonian', 'Outer Rim Territories', 'N-7'),
('Odynnia', 'Gavo Bryx', 'Mid Rim', 'R-7'),
('Oetchi', 'Bon''nyuw-Luq', 'Outer Rim Territories', 'N-17'),
('Oetrago', 'Mayagil', 'Outer Rim Territories', 'M-18'),
('Off-Canau', NULL, 'Colonies', 'N-12'),
('Ogden Minor', 'Maerdocian', 'Mid Rim', 'Q-12'),
('Ogem', 'D''Aelgoth', 'Mid Rim', 'L-17'),
('Oggustus Nebula', 'Kira', 'Expansion Region', 'N-15'),
('Ogoth Tiir', 'Atravis', 'Outer Rim Territories', 'L-19'),
('Ohratuu', 'Piryn Shar', 'Expansion Region', 'K-16'),
('OHS1782-03', 'Ash Worlds', 'Outer Rim Territories', 'T-7'),
('OHS2132-04', 'Ash Worlds', 'Outer Rim Territories', 'T-7'),
('OHS3842-03', 'Ash Worlds', 'Outer Rim Territories', 'T-7'),
('OHS4140-02', 'Ash Worlds', 'Outer Rim Territories', 'T-7'),
('Ojom', NULL, 'Deep Core', 'M-11'),
('Okator', 'Eucer', 'Mid Rim', 'Q-7'),
('Oko E', 'Wazta', 'Outer Rim Territories', 'J-18'),
('Oktaro', 'Lannik Space', 'Mid Rim', 'R-13'),
('Oktos Nebula', 'Hutt Space', 'Outer Rim Territories', 'R-12'),
('Okyaab', 'Ojoster', 'Outer Rim Territories', 'N-7'),
('Olabria', 'Seitia', 'Outer Rim Territories', 'J-20'),
('Olanji', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Old Barag', 'Epsi Collective', 'Expansion Region', 'M-15'),
('Old Mankoo', 'Quess', 'Mid Rim', 'N-17'),
('Oligtaz', NULL, 'Core Worlds', 'L-12'),
('Oliu', 'Jubilar', 'Outer Rim Territories', 'T-7'),
('Omaka', 'Dalchon', 'Outer Rim Territories', 'R-17'),
('Omar', NULL, 'Colonies', 'K-13'),
('Omereth', 'Albanin', 'Outer Rim Territories', 'U-13'),
('Omiddelon', 'Halla', 'Mid Rim', 'S-9'),
('Omman', 'Tion Hegemony', 'Outer Rim Territories', 'S-6'),
('Omman Minor', 'Kibilini', 'Outer Rim Territories', 'Q-17'),
('Omonoth', NULL, 'Inner Rim', 'M-8'),
('Ompersan', 'Prefsbelt', 'Outer Rim Territories', 'K-5'),
('Omphalos', 'Venaarian', 'Mid Rim', 'O-7'),
('Omwat', 'Garis', 'Outer Rim Territories', 'N-18'),
('Onadax', 'Minos Cluster', 'Outer Rim Territories', 'M-20'),
('Onatos', 'Onatos', 'Mid Rim', 'R-15'),
('Ondara', 'Lantillian', 'Mid Rim', 'P-8'),
('Onderia', NULL, 'Inner Rim', 'M-13'),
('Onderon', 'Japrael', 'Inner Rim', 'O-9'),
('Ondo', NULL, 'Colonies', 'N-12'),
('Ondos', NULL, 'Core Worlds', 'K-10'),
('Ongary', 'Ividal', 'Mid Rim', 'P-14'),
('Ongella', NULL, 'Inner Rim', 'N-10'),
('Onod', 'Irnaj', 'Mid Rim', 'K-17'),
('Ontotho', 'Nembus', 'Outer Rim Territories', 'P-4'),
('Ookbat', 'Kastolar', 'Mid Rim', 'Q-10'),
('Ool', 'Chiss Space', 'Unknown Regions', 'E-8'),
('Oolex Pulsar', 'Sumitra', 'Expansion Region', 'N-7'),
('Oolidi', 'Hythrope', 'Expansion Region', 'M-16'),
('Ooloponi', 'Bes Ber Bikade', 'Expansion Region', 'L-15'),
('Oon', 'Lothal', 'Outer Rim Territories', 'U-7'),
('Oon Tien', 'Kathol', 'Outer Rim Territories', 'M-21'),
('Ooo-sek', 'Daimar', 'Mid Rim', 'Q-16'),
('Ooo-temiuk', 'Arkanis', 'Outer Rim Territories', 'R-16'),
('Oor', 'Cronese Mandate', 'Outer Rim Territories', 'S-6'),
('Oordo', 'Strabin', 'Mid Rim', 'M-7'),
('Oorn Tchis', 'Lahara', 'Outer Rim Territories', 'M-5'),
('Oosalon', 'Baxel', 'Outer Rim Territories', 'U-12'),
('Ootoo Prime', 'Tungra', 'Outer Rim Territories', 'K-18'),
('Ootoola', 'Morshdine', 'Outer Rim Territories', 'O-5'),
('Oovo', 'Tharin', 'Outer Rim Territories', 'S-8'),
('Oovri', 'Tungra', 'Outer Rim Territories', 'K-18'),
('Opari', 'Dustig', 'Mid Rim', 'N-16'),
('Opatajji', 'Alsaka', 'Core Worlds', 'L-9'),
('Open Sea', 'Centrality', 'Outer Rim Territories', 'U-8'),
('Ophideraan', NULL, 'Colonies', 'K-13'),
('Opiteihr', 'Var Hagen', 'Mid Rim', 'M-16'),
('Opitha', 'Tren', 'Mid Rim', 'J-15'),
('Oplovis', 'Oplovis', 'Outer Rim Territories', 'M-5'),
('Opop Hibbedit', 'Sevastol', 'Mid Rim', 'Q-14'),
('OR-Kappa-2722', 'Lahara', 'Outer Rim Territories', 'M-5'),
('Oracaia', 'Dantus', 'Outer Rim Territories', 'J-6'),
('Oranessan', 'Grumani', 'Outer Rim Territories', 'M-17'),
('Orax', 'Subterrel', 'Outer Rim Territories', 'L-20'),
('Orchis', NULL, 'Inner Rim', 'N-8'),
('Ord Adinorr', 'Meridian', 'Outer Rim Territories', 'R-7'),
('Ord Antalaha', NULL, 'Colonies', 'L-8'),
('Ord Biniir', 'Relgim', 'Outer Rim Territories', 'L-5'),
('Ord Bueri', 'Nilgaard', 'Outer Rim Territories', 'S-5'),
('Ord Canfre', 'Cassander', 'Outer Rim Territories', 'K-5'),
('Ord Cantrell', 'Fath', 'Outer Rim Territories', 'K-6'),
('Ord Celbus', 'Karthakk', 'Outer Rim Territories', 'Q-16'),
('Ord Cestus', 'D''Astan', 'Outer Rim Territories', 'O-6'),
('Ord Dalet', 'Sertar', 'Outer Rim Territories', 'R-5'),
('Ord Dorlass', 'Iskin', 'Mid Rim', 'O-16'),
('Ord Dycoll', 'Lannik Wilds', 'Mid Rim', 'R-13'),
('Ord Fanthal', 'Ojoster', 'Outer Rim Territories', 'O-7'),
('Ord Gimmel', 'Ado', 'Mid Rim', 'M-17'),
('Ord Grovner', 'Khuiumin', 'Outer Rim Territories', 'O-18'),
('Ord Gustald', 'Mytaranor', 'Mid Rim', 'Q-9'),
('Ord Hout', 'Brema', 'Outer Rim Territories', 'M-17'),
('Ord Ibanna', 'Brema', 'Outer Rim Territories', 'M-17'),
('Ord Ivarn', 'Hakartha', 'Expansion Region', 'L-16'),
('Ord Janon', 'Spinward', 'Outer Rim Territories', 'N-2'),
('Ord Klina', 'Klina', 'Outer Rim Territories', 'S-13'),
('Ord Lithone', NULL, 'Inner Rim', 'L-8'),
('Ord Lonesome', 'Albanin', 'Outer Rim Territories', 'T-12'),
('Ord Mantell', 'Bright Jewel', 'Mid Rim', 'L-7'),
('Ord Marsax', 'Belderone', 'Outer Rim Territories', 'R-6'),
('Ord Mynock', 'Prefsbelt', 'Outer Rim Territories', 'K-6'),
('Ord Namurt', 'Tharin', 'Outer Rim Territories', 'S-8');