-- Insertar nuevos sistemas galácticos desde Bryndar hasta Chenowei
INSERT INTO public.galactic_systems (name, sector, region, grid_coordinates) VALUES
('Bryndar', 'Dalicron', 'Outer Rim Territories', 'K-19'),
('Bryx', 'Bryx', 'Mid Rim', 'R-8'),
('Bseto', 'Msst', 'Mid Rim', 'P-7'),
('Buamlon', 'Central Esstran', 'Outer Rim Territories', 'Q-4'),
('Bubble of the Lost', NULL, 'Wild Space', 'O-3'),
('Buchich', 'Calamari', 'Outer Rim Territories', 'U-6'),
('Budpock', 'Meridian', 'Outer Rim Territories', 'R-7'),
('Bulano', NULL, 'Core Worlds', 'M-10'),
('Bundil', 'Ferra', 'Outer Rim Territories', 'S-16'),
('Bundim', 'Trax', 'Mid Rim', 'Q-10'),
('Bunduki', 'Pacanth Reach', 'Outer Rim Territories', 'H-16'),
('Bunka', 'Illisurevimurasi', 'Outer Rim Territories', 'Q-4'),
('Buoyant', NULL, 'Inner Rim', 'J-14'),
('Burna', 'Cademimu', 'Outer Rim Territories', 'L-6'),
('Burnin Konn', 'Javin (Anoat)', 'Outer Rim Territories', 'K-18'),
('Burnsi', 'Dustig', 'Mid Rim', 'N-16'),
('Burska', NULL, 'Mid Rim', 'I-7'),
('Bursoll', NULL, 'Wild Space', 'H-17'),
('Burundang', 'Harron', 'Expansion Region', 'O-11'),
('Buruunin', 'Atravis', 'Outer Rim Territories', 'L-19'),
('Byllura', 'Grumani', 'Outer Rim Territories', 'N-17'),
('Bynarria', 'Lantillian', 'Mid Rim', 'P-8'),
('Byrnum', 'Maw', 'Inner Rim', 'L-8'),
('Byrsym', 'Paqwepori', 'Mid Rim', 'P-15'),
('Byss', NULL, 'Deep Core', 'K-11'),
('C-Foroon', 'Arkanis', 'Outer Rim Territories', 'R-16'),
('Caamas', NULL, 'Core Worlds', 'M-9'),
('Caaraz', 'Stensen', 'Outer Rim Territories', 'H-17'),
('Caarimon', 'Meridian', 'Outer Rim Territories', 'R-7'),
('Caarsin Station', 'Lannik Wilds', 'Mid Rim', 'R-13'),
('Cabarria', NULL, 'Colonies', 'M-13'),
('Cadannia', 'Msst', 'Mid Rim', 'P-7'),
('Cademimu', 'Cademimu', 'Outer Rim Territories', 'M-6'),
('Cadinth', 'Allied Tion', 'Outer Rim Territories', 'S-6'),
('Cadma', 'Centrality', 'Outer Rim Territories', 'T-8'),
('Cadomai', 'Aparo (Catarlo)', 'Outer Rim Territories', 'R-3'),
('Cal-Seti', 'Torranix', 'Core Worlds', 'K-10'),
('Calabar', NULL, 'Core Worlds', 'L-9'),
('Calabosh', 'Arc d''Stot', 'Expansion Region', 'K-15'),
('Calast', 'Grohl', 'Outer Rim Territories', 'R-16'),
('Calcoraan', NULL, 'Inner Rim', 'O-10'),
('Calderos Station', 'Bryx', 'Mid Rim', 'R-8'),
('Caldoni', NULL, 'Core Worlds', 'M-12'),
('Caldra Prime', 'Ado', 'Mid Rim', 'M-17'),
('Caldra Tertius', 'Ado', 'Mid Rim', 'M-17'),
('Calfa', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Calgon', 'Meridian', 'Outer Rim Territories', 'R-7'),
('Caliban', 'Savareen', 'Outer Rim Territories', 'Q-17'),
('Calior', 'Seitia', 'Outer Rim Territories', 'K-20'),
('Calipsa', 'Tapani', 'Colonies', 'L-13'),
('Calladus', 'Ojoster', 'Outer Rim Territories', 'N-7'),
('Calline', 'Dail', 'Outer Rim Territories', 'Q-18'),
('Callonia', 'Fakir', 'Colonies', 'K-9'),
('Callos', 'Brema', 'Outer Rim Territories', 'M-17'),
('Calonica', 'Vensensor', 'Expansion Region', 'K-16'),
('Caloria', 'Tapani', 'Colonies', 'L-13'),
('Caltinia', 'Senex', 'Mid Rim', 'L-17'),
('Caltrop Belt', 'Elrood', 'Outer Rim Territories', 'M-20'),
('Calumdarian', 'Immalia', 'Expansion Region', 'K-8'),
('Calus', NULL, 'Inner Rim', 'L-15'),
('Caluula', 'Tion Hegemony', 'Outer Rim Territories', 'T-6'),
('Camaria', 'Tarabba', 'Outer Rim Territories', 'M-19'),
('Camblia', NULL, 'Colonies', 'L-13'),
('Cambria', NULL, 'Deep Core', 'L-10'),
('Camden', 'Morshdine', 'Outer Rim Territories', 'O-5'),
('Camen', 'Tamarin', 'Outer Rim Territories', 'N-18'),
('Camson', 'Abrion', 'Outer Rim Territories', 'S-15'),
('Camus', 'Illisurevimurasi', 'Outer Rim Territories', 'Q-4'),
('Canastra', NULL, 'Core Worlds', 'K-10'),
('Candoria', NULL, 'Colonies', 'J-13'),
('Candovant', NULL, 'Colonies', 'N-12'),
('Canoliss', 'Sluis', 'Outer Rim Territories', 'M-19'),
('Canti', 'Tapani', 'Colonies', 'L-13'),
('Cantonica', 'Corporate Sector', 'Outer Rim Territories', 'S-4'),
('Cantras Gola', 'Perinn', 'Outer Rim Territories', 'J-4'),
('Cantros', 'Saijo', 'Outer Rim Territories', 'J-20'),
('Canyon', 'Montitian Grant', 'Expansion Region', 'J-15'),
('Capella', 'Gordian Reach', 'Outer Rim Territories', 'Q-6'),
('Caphexdis', 'Homon', 'Mid Rim', 'M-7'),
('Caprioril', 'Dolomar', 'Core Worlds', 'K-9'),
('Capza', 'Velcar', 'Outer Rim Territories', 'K-4'),
('Caragon-Viner', NULL, 'Colonies', 'N-12'),
('Carajam', 'Dalonbian', 'Outer Rim Territories', 'M-3'),
('Caramm', 'Talcene', 'Mid Rim', 'R-8'),
('Caraxl', 'Cassander', 'Outer Rim Territories', 'K-5'),
('Carbos', 'Roche', 'Mid Rim', 'Q-8'),
('Carcel', 'Locris', 'Expansion Region', 'O-8'),
('Carconth', NULL, 'Core Worlds', 'M-11'),
('Cardekkia', 'Corellian', 'Core Worlds', 'M-11'),
('Cardellia', 'Ojoster', 'Outer Rim Territories', 'N-7'),
('Cardo Minor', 'Meerian', 'Outer Rim Territories', 'O-6'),
('Cardooine', 'Jospro', 'Outer Rim Territories', 'R-7'),
('Cardovyte', 'Oricho', 'Outer Rim Territories', 'M-6'),
('Cardua', NULL, 'Core Worlds', 'L-10'),
('Carest', NULL, 'Inner Rim', 'N-8'),
('Cargamalis', 'Bruanii', 'Mid Rim', 'K-18'),
('Carida', NULL, 'Colonies', 'M-9'),
('Carlac', 'Prefsbelt', 'Outer Rim Territories', 'K-5'),
('Carlania', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Carlem', NULL, 'Core Worlds', 'L-10'),
('Carlix''s Folly', 'Tharin', 'Outer Rim Territories', 'S-8'),
('Carnelion', NULL, 'Wild Space', 'J-5'),
('Carnovia', 'Hutt Space', 'Hutt Space', 'S-12'),
('Carnth', 'M''shinni', 'Mid Rim', 'M-7'),
('Carosi', 'Nembus', 'Outer Rim Territories', 'P-4'),
('Carpagia', NULL, 'Colonies', 'L-9'),
('Carpastor', 'Rolion', 'Outer Rim Territories', 'Q-7'),
('Carrandar Secundus', 'Portmoak', 'Outer Rim Territories', 'P-18'),
('Carratos', NULL, 'Inner Rim', 'K-8'),
('Carreras', 'Atravis', 'Outer Rim Territories', 'L-19'),
('Carrivar', NULL, 'Unknown Regions', 'G-9'),
('Carruthia', 'D''Astan', 'Outer Rim Territories', 'O-6'),
('Carsanza', 'Juvex', 'Mid Rim', 'L-17'),
('Cartao', 'Prackla', 'Expansion Region', 'O-8'),
('Carto', 'Surron', 'Expansion Region', 'O-13'),
('Cartusio', NULL, 'Core Worlds', 'J-12'),
('Carvandir', 'Carvandir', 'Expansion Region', 'J-7'),
('Carz', 'Svivreni', 'Outer Rim Territories', 'O-20'),
('Casfield', 'Tennuutta', 'Mid Rim', 'Q-7'),
('Caska', NULL, 'Inner Rim', 'N-14'),
('Cassander', 'Cassander', 'Outer Rim Territories', 'K-5'),
('Cassidode', 'Aparo', 'Outer Rim Territories', 'R-3'),
('Castell', NULL, 'Colonies', 'M-9'),
('Castilon', 'Tashtor', 'Mid Rim', 'I-16'),
('Cataalda', 'Onatos', 'Mid Rim', 'R-15'),
('Cataract of Moons', 'Tungra (Fand)', 'Outer Rim Territories', 'K-18'),
('Cathar', 'Quelii', 'Outer Rim Territories', 'N-6'),
('Cathis', 'Jjannex', 'Outer Rim Territories', 'K-19'),
('Catlia', 'Chiss Space', 'Unknown Regions', 'G-8'),
('Cato Neimoidia', 'Quellor', 'Colonies', 'N-11'),
('Cattamascar', 'Bakura', 'Outer Rim Territories', 'G-16'),
('Caulbon', NULL, 'Inner Rim', 'L-14'),
('Cauldron Nebula', 'Corva', 'Outer Rim Territories', 'P-3'),
('Caulus Tertius', NULL, 'Inner Rim', 'M-8'),
('Cauper', 'Tapani', 'Colonies', 'L-13'),
('Caursito', NULL, 'Colonies', 'K-8'),
('Cavaell', 'Emmo', 'Core Worlds', 'M-12'),
('Cavamina', 'Doldur', 'Mid Rim', 'P-15'),
('Caviness', 'Charra', 'Expansion Region', 'P-14'),
('Cedonne', 'Dononter', 'Mid Rim', 'I-16'),
('Cedre', 'Quelii', 'Outer Rim Territories', 'O-6'),
('Cedrell', 'Emmo', 'Core Worlds', 'M-12'),
('Cegul', 'Cegul', 'Outer Rim Territories', 'M-20'),
('Ceiran', NULL, 'Inner Rim', 'N-14'),
('Ceitia', 'Bryx', 'Mid Rim', 'R-8'),
('Cejansij', 'Halla', 'Mid Rim', 'R-9'),
('Cel', 'Amiin Cantons of Lahag', 'Expansion Region', 'J-15'),
('Celanon', 'D''Astan', 'Outer Rim Territories', 'O-6'),
('Celdaru', NULL, 'Wild Space', 'I-8'),
('Celegia', 'Noori', 'Expansion Region', 'O-10'),
('Celen', 'Elochar', 'Mid Rim', 'R-9'),
('Celes', 'Herdessa', 'Mid Rim', 'Q-16'),
('Celestial Wake, The', 'Kriz', 'Outer Rim Territories', 'K-19'),
('Celsor', 'Hook Nebula', 'Outer Rim Territories', 'O-17'),
('Celwis', NULL, 'Unknown Regions', 'F-8'),
('Centares', 'Maldrood', 'Mid Rim', 'R-7'),
('Centori', 'Iskin', 'Mid Rim', 'O-16'),
('Cerberon', NULL, 'Deep Core', 'L-10'),
('Cerea', 'Semagi', 'Mid Rim', 'I-16'),
('Cerenia', 'Mbandamonte', 'Expansion Region', 'N-15'),
('Cerilia', 'Xappyh', 'Outer Rim Territories', 'Q-3'),
('Ceriun', 'Nuiri', 'Outer Rim Territories', 'Q-6'),
('Cermau', 'Bakura', 'Outer Rim Territories', 'H-16'),
('Cerosha', 'Jospro', 'Outer Rim Territories', 'R-7'),
('Cerroban', 'Bon''nyuw-Luq', 'Mid Rim', 'N-18'),
('CeSai', 'Illisurevimurasi', 'Outer Rim Territories', 'Q-4'),
('Cesya', 'Tapani', 'Colonies', 'L-13'),
('Ceti 597', 'Hollan', 'Mid Rim', 'M-7'),
('Cezith', 'Clacis', 'Outer Rim Territories', 'K-4'),
('Ch''hodos', 'Esstran (Sith Worlds)', 'Outer Rim Territories', 'R-4'),
('Ch''manss', 'Var Hagen', 'Mid Rim', 'M-17'),
('Ch''zimi''kho', 'Zeemacht Cluster', 'Inner Rim', 'N-8'),
('Chaaktil', NULL, 'Inner Rim', 'N-14'),
('Chaastern', 'Shelsha', 'Colonies', 'M-9'),
('Chabosh', 'Lahara', 'Outer Rim Territories', 'M-5'),
('Chad', 'Jospro', 'Outer Rim Territories', 'R-7'),
('Chadawa', 'Croynar', 'Inner Rim', 'N-14'),
('Chagar', 'Khuiumin', 'Outer Rim Territories', 'O-19'),
('Chagaria', 'Danjar', 'Outer Rim Territories', 'N-18'),
('Chal', 'Hudda Garis', 'Outer Rim Territories', 'N-17'),
('Chalacta', 'Metatessu', 'Mid Rim', 'R-10'),
('Chalcedon', 'Tashtor', 'Mid Rim', 'I-16'),
('Challon', NULL, 'Core Worlds', 'L-9'),
('Chamble', 'Mytaranor', 'Mid Rim', 'Q-10'),
('Chamm', NULL, 'Core Worlds', 'M-12'),
('Champala', NULL, 'Inner Rim', 'L-8'),
('Champat', NULL, 'Core Worlds', 'M-12'),
('Chanceuxi', 'Kanz', 'Outer Rim Territories', 'N-4'),
('Chandaar', 'Cronese Mandate', 'Outer Rim Territories', 'S-6'),
('Chandar''s Folly', 'Saijo', 'Outer Rim Territories', 'J-20'),
('Chandel', 'Ojoster', 'Outer Rim Territories', 'N-6'),
('Chandrila', 'Bormea', 'Core Worlds', 'L-9'),
('Changa', 'Tolonda', 'Outer Rim Territories', 'Q-18'),
('Chankin', 'Jidlor Marches', 'Mid Rim', 'I-16'),
('Chanosant', 'Harron', 'Expansion Region', 'O-11'),
('Charbodia', NULL, 'Inner Rim', 'N-9'),
('Chardaan', NULL, 'Inner Rim', 'N-13'),
('Chardis', 'Trilon', 'Outer Rim Territories', 'H-16'),
('Charenthoth', NULL, 'Colonies', 'N-9'),
('Chargona', 'Citlik', 'Expansion Region', 'O-15'),
('Charis', 'Kathol', 'Outer Rim Territories', 'M-21'),
('Charissia', 'Bartahn', 'Inner Rim', 'L-15'),
('Charmath', 'Farrfin', 'Core Worlds', 'K-9'),
('Charra', 'Charra', 'Expansion Region', 'P-14'),
('Charros', 'Numesira', 'Mid Rim', 'R-9'),
('Charubah', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Chashima', 'Auril', 'Outer Rim Territories', 'S-6'),
('Chasidron Shoals', 'Bortele', 'Mid Rim', 'R-8'),
('Chasin', NULL, 'Core Worlds', 'M-12'),
('Chasmeene', NULL, 'Inner Rim', 'O-10'),
('Chateuse', 'Tungra', 'Outer Rim Territories', 'K-19'),
('Chaykin', 'Chaykin', 'Expansion Region', 'O-14'),
('Chazwa', 'Orus', 'Inner Rim', 'N-8'),
('Cheedoa', NULL, 'Colonies', 'M-12'),
('Cheelit', 'Semagi', 'Mid Rim', 'I-16'),
('Cheeyoom', 'Matee', 'Core Worlds', 'K-9'),
('Chekria', 'Shelsha', 'Colonies', 'M-9'),
('Cheku', 'Brevost', 'Expansion Region', 'O-15'),
('Chelleya', 'Seswenna', 'Outer Rim Territories', 'M-18'),
('Chelloa', 'Grumani', 'Outer Rim Territories', 'M-17'),
('Chemvau', NULL, 'Colonies', 'M-13'),
('Chennis', 'Greater Plooriod', 'Expansion Region', 'M-7'),
('Chenowei', 'Gordian Reach', 'Outer Rim Territories', 'Q-5');