-- Insert additional galactic systems data
INSERT INTO public.galactic_systems (name, sector, region, grid_coordinates) VALUES
('Belkadan', 'Dalonbian', 'Outer Rim Territories', 'L-1'),
('Belladoon', 'Myto', 'Outer Rim Territories', 'K-3'),
('Bellassa', NULL, 'Core Worlds', 'M-11'),
('Bellis', 'Demetras', 'Outer Rim Territories', 'P-7'),
('Belloria', 'Seswenna', 'Outer Rim Territories', 'M-18'),
('Belnar', 'Belnar', 'Colonies', 'M-9'),
('Belovia', 'Ombakond', 'Expansion Region', 'P-12'),
('Belsavis', 'Bozhnee', 'Outer Rim Territories', 'L-18'),
('Belshar', 'Othacuu Belshar', 'Mid Rim', 'J-7'),
('Belsmuth', 'Belsmuth', 'Outer Rim Territories', 'O-6'),
('Belthu', 'Demetras', 'Outer Rim Territories', 'O-7'),
('Beltire', 'Narrant', 'Mid Rim', 'J-17'),
('Beltrix', NULL, 'Inner Rim', 'M-14'),
('Belukat', 'Corpheli', 'Expansion Region', 'M-7'),
('Belvaria', 'Corweillian', 'Mid Rim', 'P-15'),
('Benath', NULL, 'Wild Space', 'I-7'),
('Bendeluum', 'Javin (Anoat)', 'Outer Rim Territories', 'K-18'),
('Bendii', 'Seitia', 'Outer Rim Territories', 'K-19'),
('Bendone', 'Bosph', 'Outer Rim Territories', 'R-3'),
('Benetage', 'Thanium', 'Outer Rim Territories', 'R-6'),
('Bengat', NULL, 'Inner Rim', 'J-8'),
('Bengely', 'Tamarin', 'Outer Rim Territories', 'N-19'),
('Benglor', 'Onatos', 'Mid Rim', 'R-15'),
('Benja-Rihn', 'Sevastol', 'Mid Rim', 'Q-14'),
('Benkal', NULL, 'Wild Space', 'H-17'),
('Bentora', 'Samix', 'Outer Rim Territories', 'Q-19'),
('Benwabula', 'Shadola', 'Outer Rim Territories', 'U-7'),
('Ber de Val', NULL, 'Colonies', 'M-9'),
('Berason', 'Eclorar', 'Mid Rim', 'Q-12'),
('Berchest', 'Anthos', 'Inner Rim', 'N-8'),
('Berea', 'Elrood', 'Outer Rim Territories', 'M-19'),
('Beris', 'Fei Hu', 'Mid Rim', 'Q-13'),
('Bernilla', NULL, 'Inner Rim', 'L-14'),
('Beroq', 'Baroli', 'Expansion Region', 'N-14'),
('Berri', NULL, 'Inner Rim', 'N-9'),
('Berrol''s Donn', 'Kriz', 'Outer Rim Territories', 'K-19'),
('Berrun', NULL, 'Colonies', 'M-10'),
('Berullia', 'Quence', 'Outer Rim Territories', 'O-18'),
('Berzite', NULL, 'Wild Space', 'U-8'),
('Bes', 'Airam', 'Outer Rim Territories', 'M-20'),
('Besberra', 'Cegul', 'Outer Rim Territories', 'L-20'),
('Bescane', 'Obtrexta', 'Outer Rim Territories', 'K-3'),
('Besero', NULL, 'Deep Core', 'L-10'),
('Beshka', 'Aparo', 'Outer Rim Territories', 'R-3'),
('Besn', 'Mayagil', 'Outer Rim Territories', 'N-18'),
('Besnia', NULL, 'Colonies', 'N-12'),
('Bespin', 'Javin (Anoat)', 'Outer Rim Territories', 'K-18'),
('Bessimir', NULL, 'Core Worlds', 'L-9'),
('Bestal', 'Varada', 'Outer Rim Territories', 'I-19'),
('Bestine', NULL, 'Inner Rim', 'M-14'),
('Bestoon', NULL, 'Colonies', 'J-9'),
('Beta Olikark', 'Wyl', 'Outer Rim Territories', 'S-4'),
('Beta Rhama', 'Dalchon', 'Outer Rim Territories', 'R-17'),
('Betal', NULL, 'Wild Space', 'J-5'),
('Betha', 'Corva', 'Outer Rim Territories', 'P-4'),
('Bethal', 'Tapani', 'Colonies', 'L-13'),
('Bethars', 'Emmo', 'Core Worlds', 'M-12'),
('Betolio', 'Tapani', 'Colonies', 'L-13'),
('Betshish', 'Gordian Reach', 'Outer Rim Territories', 'P-5'),
('Bettel', 'Javin (Yarith)', 'Outer Rim Territories', 'K-18'),
('Betthanie', 'Wornal', 'Mid Rim', 'K-16'),
('Bettok', 'Velcar', 'Outer Rim Territories', 'J-4'),
('Bevell', NULL, 'Inner Rim', 'L-8'),
('Bextar', 'Velcar', 'Outer Rim Territories', 'J-4'),
('Bezha', NULL, 'Colonies', 'N-10'),
('Bezim', 'Vorc', 'Mid Rim', 'J-7'),
('Beznaz', 'Quiberon', 'Outer Rim Territories', 'T-15'),
('Bhargebba', 'Esstran (Sith Worlds)', 'Outer Rim Territories', 'R-4'),
('Bheriz', 'Bheriz', 'Outer Rim Territories', 'U-10'),
('Bhuna Sound', 'Yushan', 'Mid Rim', 'K-17'),
('Bianas', 'Tapani', 'Colonies', 'L-13'),
('Bid''jerma', 'Prefsbelt', 'Outer Rim Territories', 'J-5'),
('Biewa', 'Corporate Sector', 'Outer Rim Territories', 'S-4'),
('Biitu', 'Cassander (Tadrin)', 'Outer Rim Territories', 'K-5'),
('Biivren', 'Biivren', 'Expansion Region', 'P-9'),
('Bilbringi', NULL, 'Inner Rim', 'J-8'),
('Bilios', 'Tapani', 'Colonies', 'L-13'),
('Billaron', 'Chitargarh', 'Expansion Region', 'K-15'),
('Bilzen', NULL, 'Wild Space', 'U-12'),
('Bimin Three', 'Majoor', 'Expansion Region', 'N-15'),
('Bimmiel', 'Kanz', 'Outer Rim Territories', 'N-4'),
('Bimmisaari', 'Halla', 'Mid Rim', 'R-9'),
('Binaros', 'Kathol (Outback)', 'Outer Rim Territories', 'M-21'),
('Binquaros', 'Ciutric', 'Outer Rim Territories', 'N-5'),
('Biravia', 'Venaarian', 'Mid Rim', 'O-7'),
('Birba', NULL, 'Deep Core', 'M-10'),
('Birgis', 'Dalonbian', 'Outer Rim Territories', 'M-3'),
('Birix', 'Bryx', 'Mid Rim', 'R-8'),
('Birjis', 'Dalchon', 'Outer Rim Territories', 'R-17'),
('Birren', NULL, 'Inner Rim', 'O-10'),
('Birsingrial', NULL, 'Core Worlds', 'L-10'),
('Birukay', NULL, 'Outer Rim Territories', 'M-1'),
('Bisellia', 'Clacis', 'Outer Rim Territories', 'K-4'),
('Biskar', NULL, 'Inner Rim', 'K-14'),
('Bissillirus', 'Trax', 'Mid Rim', 'Q-10'),
('Bith', NULL, 'Core Worlds', 'L-13'),
('Bitmus Cloud', 'Wazta', 'Outer Rim Territories', 'J-18'),
('Bittelari Cluster', 'Fath', 'Outer Rim Territories', 'K-6'),
('Bivoli', NULL, 'Inner Rim', 'L-15'),
('Bizikia', 'Kwymar', 'Outer Rim Territories', 'P-4'),
('Black Bantha', NULL, 'Inner Rim', 'K-8'),
('Black Delve, The', 'Har Worlds', 'Expansion Region', 'J-16'),
('Black Hole of Nakat', NULL, 'Inner Rim', 'N-7'),
('Black Hole of Quintas', 'Kriz', 'Outer Rim Territories', 'J-19'),
('Black Nebula', NULL, 'Colonies', 'M-12'),
('Black Widow Nebula', 'Calaron', 'Outer Rim Territories', 'T-9'),
('Blackfel', 'Greater Plooriod', 'Expansion Region', 'M-7'),
('Blacktar Cyst', 'Oktos', 'Mid Rim', 'R-12'),
('Blair Cluster', 'Airam', 'Outer Rim Territories', 'L-20'),
('Blarrum', 'Mayagil', 'Outer Rim Territories', 'N-18'),
('Blathar', 'Yucrales', 'Mid Rim', 'R-15'),
('Blenjeel', 'Dufilvian', 'Mid Rim', 'Q-15'),
('Bleuf', NULL, 'Core Worlds', 'L-13'),
('Blimph', 'Kastolar', 'Mid Rim', 'Q-10'),
('Blood Nest', 'Halori', 'Mid Rim', 'P-7'),
('Bloxia', NULL, 'Wild Space', 'I-7'),
('Blutopia', 'Vensensor', 'Expansion Region', 'K-16'),
('Blyte', 'Tapani', 'Colonies', 'L-13'),
('Bnach', 'Calaron', 'Outer Rim Territories', 'T-9'),
('Bnar', 'Braxant', 'Outer Rim Territories', 'K-3'),
('Boden', 'Videnda', 'Outer Rim Territories', 'M-18'),
('Bodoria', 'Andirma', 'Expansion Region', 'L-15'),
('Bodrin', 'Elrood', 'Outer Rim Territories', 'M-20'),
('Bofa', 'Steniplis', 'Outer Rim Territories', 'M-18'),
('Bogano', 'Mieru''kar', 'Outer Rim Territories', 'N-3'),
('Bogden', NULL, 'Inner Rim', 'M-8'),
('Bogo Rai', NULL, 'Unknown Regions', 'E-8'),
('Bogoa', 'Immerian Outback', 'Expansion Region', 'N-14'),
('Boiyuh', NULL, 'Colonies', 'J-9'),
('Bolad', 'Tharin', 'Outer Rim Territories', 'S-8'),
('Bolbotarp', 'Corellian', 'Core Worlds', 'M-11'),
('Boledge', NULL, 'Inner Rim', 'N-12'),
('Bolenia', NULL, 'Core Worlds', 'K-9'),
('Boltrunia', 'Baxel', 'Outer Rim Territories', 'U-11'),
('Bomis Koori', 'Wornal', 'Mid Rim', 'K-16'),
('Bomodon', 'Churba', 'Mid Rim', 'O-15'),
('Bompreil', 'Demetras', 'Outer Rim Territories', 'P-7'),
('Bonadan', 'Corporate Sector', 'Outer Rim Territories', 'S-3'),
('Bontormia', 'Bortele', 'Mid Rim', 'R-8'),
('Boonta', 'Suolriep', 'Outer Rim Territories', 'S-8'),
('Boordii', 'Sumitra', 'Expansion Region', 'N-7'),
('Boosodia', NULL, 'Inner Rim', 'N-8'),
('Bootana Shagplan', NULL, 'Hutt Space', 'S-10'),
('Boothi', 'Abrion', 'Outer Rim Territories', 'S-15'),
('Boranall', 'Doldur', 'Mid Rim', 'P-15'),
('Boranda', 'Manda', 'Mid Rim', 'R-14'),
('Borao', NULL, 'Inner Rim', 'M-14'),
('Borcorash', 'Weneen', 'Outer Rim Territories', 'N-6'),
('Borga', 'Yminis', 'Outer Rim Territories', 'S-14'),
('Boriin', NULL, 'Inner Rim', 'N-14'),
('Borkeen', 'Belsmuth', 'Outer Rim Territories', 'O-6'),
('Borkyne', 'Bes Ber Bikade', 'Expansion Region', 'L-15'),
('Borleias', NULL, 'Colonies', 'K-9'),
('Borloria', 'Dentari', 'Expansion Region', 'O-8'),
('Borlov', 'Tunka', 'Outer Rim Territories', 'J-19'),
('Bormea', 'Bormea', 'Core Worlds', 'L-9'),
('Bormter', NULL, 'Wild Space', 'H-14'),
('Bormus', 'Dustig', 'Mid Rim', 'N-16'),
('Boro-borosa', 'Senex', 'Mid Rim', 'L-18'),
('Borosk', 'Prefsbelt', 'Outer Rim Territories', 'K-5'),
('Bortele Cluster', 'Bortele', 'Mid Rim', 'R-8'),
('Bortras', 'Brema (Reithcas)', 'Outer Rim Territories', 'M-18'),
('Boruga', NULL, 'Core Worlds', 'L-10'),
('Bos-Una', NULL, 'Inner Rim', 'J-14'),
('Bosch', NULL, 'Core Worlds', 'K-10'),
('Bosph', 'Bosph', 'Outer Rim Territories', 'Q-3'),
('Bosthirda', 'Esstran (Sith Worlds)', 'Outer Rim Territories', 'R-5'),
('Botajef', 'Belsmuth', 'Outer Rim Territories', 'O-6'),
('Bothawui', 'Bothan', 'Mid Rim', 'R-14'),
('Bothsoliman', 'Hollan', 'Mid Rim', 'M-7'),
('Botor', 'Botor Enclave', 'Core Worlds', 'K-12'),
('Boudolayz', NULL, 'Colonies', 'N-12'),
('Bovo Yagen', 'Kailion', 'Expansion Region', 'O-13'),
('Bowane Nebula', 'Tungra (Fand)', 'Outer Rim Territories', 'K-18'),
('Boxer Point Station', 'Prackla', 'Expansion Region', 'O-8'),
('Boz Pity', 'Halla', 'Mid Rim', 'S-9'),
('Boztrok', 'Aparo', 'Outer Rim Territories', 'R-3'),
('Bpfassh', 'Sluis', 'Outer Rim Territories', 'M-19'),
('Bracca', 'Lantillian', 'Mid Rim', 'P-9'),
('Braccio', NULL, 'Wild Space', 'I-5'),
('Brachi', 'Sertar', 'Outer Rim Territories', 'R-5'),
('Brachnis Chorios', 'Meridian', 'Outer Rim Territories', 'R-7'),
('Bragkis', 'Belderone', 'Outer Rim Territories', 'R-6'),
('Bramior', NULL, 'Inner Rim', 'M-9'),
('Branteez', 'Tolonda', 'Outer Rim Territories', 'Q-17'),
('Brask Oto', NULL, 'Unknown Regions', 'H-7'),
('Bravais', NULL, 'Inner Rim', 'O-9'),
('Bravis', 'Spadja', 'Outer Rim Territories', 'R-5'),
('Bray', 'Piryn Shar', 'Expansion Region', 'K-16'),
('Breeka', 'Cadavine', 'Outer Rim Territories', 'P-17'),
('Brella', 'Temior Barma', 'Colonies', 'M-9'),
('Brentaal', 'Bormea', 'Core Worlds', 'L-9'),
('Bresallis', 'Cadma', 'Outer Rim Territories', 'T-8'),
('Bresan', 'Kathol (Outback)', 'Outer Rim Territories', 'M-21'),
('Breshig', 'Mandalore', 'Outer Rim Territories', 'O-7'),
('Breshkall', 'Khuiumin', 'Outer Rim Territories', 'O-19'),
('Bresnia', 'Tandon', 'Mid Rim', 'Q-14'),
('Breta Yaga', 'Mieru''kar', 'Outer Rim Territories', 'O-3'),
('Bretta', 'Ojoster', 'Outer Rim Territories', 'N-7'),
('Brevost', 'Brevost', 'Expansion Region', 'O-15'),
('Bri''ahl', 'Bri''ahl', 'Outer Rim Territories', 'I-17'),
('Bri''n', 'Lothal', 'Outer Rim Territories', 'U-7'),
('Bridin Anchorage', 'Portmoak', 'Outer Rim Territories', 'P-18'),
('Brield', NULL, 'Colonies', 'M-12'),
('Brightday', NULL, 'Inner Rim', 'K-8'),
('Brigia', 'Tion Hegemony', 'Outer Rim Territories', 'T-6'),
('Brink Station', NULL, 'Wild Space', 'O-3'),
('Brint-wo', 'Koradin', 'Outer Rim Territories', 'I-18'),
('Brintooin', 'Seswenna', 'Outer Rim Territories', 'M-18'),
('Briston', 'Shelsha', 'Colonies', 'M-9'),
('Britaxis Minor', NULL, 'Inner Rim', 'O-11'),
('Brix', NULL, 'Colonies', 'N-10'),
('Brochiib', 'Trianii Space*', 'Wild Space', 'S-3'),
('Brodo Asogi', 'Perinn', 'Outer Rim Territories', 'J-4'),
('Brodogon', 'Bozhnee', 'Outer Rim Territories', 'L-18'),
('Broest', NULL, 'Core Worlds', 'L-10'),
('Brolsam', 'Kathol', 'Outer Rim Territories', 'M-21'),
('Bromlarch', 'Vish', 'Mid Rim', 'O-16'),
('Bronsoon', 'Gordian Reach', 'Outer Rim Territories', 'P-6'),
('Bront', 'Svivreni', 'Outer Rim Territories', 'O-19'),
('Brosi', 'Corporate Sector', 'Outer Rim Territories', 'S-3'),
('Brunet', 'Prefsbelt', 'Outer Rim Territories', 'J-5'),
('Bruvia', 'Harron Marches', 'Expansion Region', 'P-11'),
('Bryexx', 'Varvenna', 'Colonies', 'M-13');