-- Add galactic systems from Kolos to Likasha (batch 4)
INSERT INTO galactic_systems (name, sector, region, grid_coordinates) VALUES
('Kolos', 'Paqwepori', 'Mid Rim', 'P-15'),
('Koltine', NULL, 'Wild Space', 'L-21'),
('Komnor', 'Suolriep', 'Outer Rim Territories', 'S-8'),
('Kondoraan', 'Saijo', 'Outer Rim Territories', 'K-20'),
('Konkiv', 'Cadma', 'Outer Rim Territories', 'T-8'),
('Konos', NULL, 'Colonies', 'N-10'),
('Kooda', 'Herglic Space', 'Colonies', 'K-13'),
('Koolach', NULL, 'Inner Rim', 'O-10'),
('Kooriva', NULL, 'Inner Rim', 'M-14'),
('Koovis', NULL, 'Inner Rim', 'L-8'),
('Koozebane', 'Calaron', 'Outer Rim Territories', 'T-9'),
('Kor Anjiliac', NULL, 'Hutt Space', 'S-11'),
('Kor Bareesh', NULL, 'Hutt Space', 'S-11'),
('Kor Besadii', NULL, 'Hutt Space', 'S-10'),
('Kor Desilijic', NULL, 'Hutt Space', 'S-11'),
('Kor Gejalli', NULL, 'Hutt Space', 'S-11'),
('Kor Gorensla', NULL, 'Hutt Space', 'S-10'),
('Kor Hestilic', NULL, 'Hutt Space', 'S-10'),
('Kor Hunamma', NULL, 'Hutt Space', 'S-11'),
('Kor Jiramma', NULL, 'Hutt Space', 'S-11'),
('Kor Nasirii', NULL, 'Hutt Space', 'S-10'),
('Kor Nijiladii', NULL, 'Hutt Space', 'S-10'),
('Kor Oktanivii', NULL, 'Hutt Space', 'S-11'),
('Kor Qunaalac', NULL, 'Hutt Space', 'S-11'),
('Kor Trinivii', NULL, 'Hutt Space', 'S-11'),
('Kor Usilic', NULL, 'Hutt Space', 'S-11'),
('Kor Utoradii', NULL, 'Hutt Space', 'S-11'),
('Kor Vanderijar', NULL, 'Hutt Space', 'S-11'),
('Kor Vosadii', NULL, 'Hutt Space', 'S-10'),
('Kor-Lahvan', 'Corosi', 'Outer Rim Territories', 'N-6'),
('Korad', 'Elrood', 'Outer Rim Territories', 'M-19'),
('Korbin', NULL, 'Inner Rim', 'J-14'),
('Korbori', NULL, 'Colonies', 'N-12'),
('Korda', NULL, 'Inner Rim', 'O-8'),
('Kordoku', 'Terr''skiar', 'Mid Rim', 'P-10'),
('Kordu', 'Kordu', 'Mid Rim', 'L-7'),
('Korev', 'Zaric', 'Inner Rim', 'N-9'),
('Korfanus', NULL, 'Core Worlds', 'L-10'),
('Korfo', NULL, 'Core Worlds', 'M-9'),
('Korlings', 'Kwymar', 'Outer Rim Territories', 'P-4'),
('Kormoran', 'Wyl', 'Outer Rim Territories', 'R-4'),
('Korphir', 'Gordian Reach', 'Outer Rim Territories', 'Q-6'),
('Korrilan', 'Daalang', 'Mid Rim', 'Q-12'),
('Korriz', 'Esstran (Sith Worlds)', 'Outer Rim Territories', 'R-4'),
('Korrus', 'Clacis', 'Outer Rim Territories', 'K-4'),
('Korseg', 'Grohl', 'Outer Rim Territories', 'R-16'),
('Kortatka', 'Croynar', 'Inner Rim', 'M-14'),
('Korteen', 'Kibilini', 'Outer Rim Territories', 'Q-17'),
('Koru Neimoidia', 'Quellor', 'Colonies', 'N-11'),
('Korvaii', 'Kordu', 'Mid Rim', 'L-7'),
('Koshaga', NULL, 'Wild Space', 'I-7'),
('Koshi', 'Sevastol', 'Mid Rim', 'Q-14'),
('Kossa Prime', 'Kossa (Kossa Prime)', 'Expansion Region', 'O-11'),
('Kostra', 'Romintine', 'Mid Rim', 'Q-8'),
('Kothlis', 'Bothan', 'Mid Rim', 'R-14'),
('Kovor', 'Koradin', 'Outer Rim Territories', 'I-18'),
('Kowak', 'Sevetta', 'Outer Rim Territories', 'S-16'),
('Kragis', 'Citlik', 'Expansion Region', 'O-15'),
('Krake''s Planet', 'Demetras', 'Outer Rim Territories', 'P-7'),
('Kral''to', 'Demetras', 'Outer Rim Territories', 'O-7'),
('Krann', 'Brevost', 'Expansion Region', 'O-15'),
('Krant', 'Bothan', 'Mid Rim', 'R-14'),
('Kravos', 'Gordian Reach', 'Outer Rim Territories', 'P-6'),
('Krayiss', 'Esstran (Sith Worlds)', 'Outer Rim Territories', 'R-5'),
('Kreeling', 'Chommell', 'Mid Rim', 'O-16'),
('Krenhner', 'Krenhner', 'Inner Rim', 'L-14'),
('Krevas', 'Antemeridian', 'Outer Rim Territories', 'R-7'),
('Kriekaal', NULL, 'Wild Space', 'J-14'),
('Kril''Dor', 'Outer Jalor', 'Mid Rim', 'I-7'),
('Krinemonen', 'Calamari', 'Outer Rim Territories', 'U-6'),
('Krintrino', NULL, 'Colonies', 'M-10'),
('Kriselist', 'Wornal', 'Mid Rim', 'K-16'),
('Krmar', 'Tolonda', 'Outer Rim Territories', 'R-17'),
('Krnay', 'Vilonis', 'Mid Rim', 'O-16'),
('Kro Var', NULL, 'Unknown Regions', 'H-8'),
('Kroctar', 'Shataum', 'Inner Rim', 'N-7'),
('Kromus', 'Esuain', 'Mid Rim', 'P-7'),
('Kronk', 'Auril', 'Outer Rim Territories', 'R-6'),
('Krownest', 'Mandalore', 'Outer Rim Territories', 'O-7'),
('Krozurbia', 'Shadola', 'Outer Rim Territories', 'U-8'),
('Kruskan', 'Colundra', 'Outer Rim Territories', 'S-5'),
('Krykas', 'Spirva', 'Mid Rim', 'L-16'),
('Krykis', 'Duluur', 'Colonies', 'M-13'),
('Krylon', 'Gordian Reach', 'Outer Rim Territories', 'P-5'),
('Krystar', 'Manda', 'Mid Rim', 'R-14'),
('Ksiczzic', 'Yucrales', 'Mid Rim', 'Q-15'),
('Ktath''atn', 'Chopani', 'Outer Rim Territories', 'M-4'),
('Ktil', 'Ktilac Regions', 'Inner Rim', 'N-9'),
('Kuar', 'Koros', 'Deep Core', 'K-10'),
('Kuat', 'Kuat', 'Core Worlds', 'M-10'),
('Kubindi', 'Calaron', 'Outer Rim Territories', 'T-9'),
('Kudo', 'Corvair', 'Inner Rim', 'K-14'),
('Kuliquo', NULL, 'Inner Rim', 'L-14'),
('Kullgroon', 'Authala', 'Expansion Region', 'P-12'),
('Kumru', 'Javin', 'Outer Rim Territories', 'K-18'),
('Kuna''s Eye', 'Zuma (Moddell)', 'Outer Rim Territories', 'H-16'),
('Kuna''s Fist', 'Zuma (Moddell)', 'Outer Rim Territories', 'H-16'),
('Kuna''s Horn', 'Zuma (Moddell)', 'Outer Rim Territories', 'H-16'),
('Kuna''s Tail', 'Zuma (Moddell)', 'Outer Rim Territories', 'H-16'),
('Kuna''s Tooth', 'Zuma (Moddell)', 'Outer Rim Territories', 'H-16'),
('Kundu Minor', 'Steniplis', 'Outer Rim Territories', 'M-19'),
('Kupoh', 'Dohlbani', 'Mid Rim', 'R-13'),
('Kur Minor', NULL, 'Wild Space', 'I-8'),
('Kur Nebula', 'Elrood', 'Outer Rim Territories', 'M-20'),
('Kuras', 'Elrood', 'Outer Rim Territories', 'M-19'),
('Kuratooine', NULL, 'Wild Space', 'J-5'),
('Kuratow', 'Brevost', 'Expansion Region', 'O-15'),
('Kurdavvia', NULL, 'Core Worlds', 'M-11'),
('Kurluvion', 'Weneen', 'Outer Rim Territories', 'N-6'),
('Kurost', 'Kurost', 'Mid Rim', 'Q-11'),
('Kursid', 'Esstran (Sith Worlds)', 'Outer Rim Territories', 'Q-5'),
('Kushibah', 'Gordian Reach', 'Outer Rim Territories', 'P-5'),
('Kutag', 'Farlax', 'Core Worlds', 'K-10'),
('Kuthic', 'Tharin', 'Outer Rim Territories', 'S-8'),
('Kvabja', 'Uoti', 'Core Worlds', 'K-9'),
('Kwannot', 'Alderath', 'Mid Rim', 'L-6'),
('Kwapi', NULL, 'Wild Space', 'R-3'),
('Kwenn', 'Kastolar', 'Mid Rim', 'R-10'),
('Kwevron', 'Clacis', 'Outer Rim Territories', 'K-4'),
('Kwookrrr', 'Mytaranor', 'Mid Rim', 'P-9'),
('KyLessia', 'Bes Ber Bikade', 'Expansion Region', 'L-15'),
('Kynachi', NULL, 'Wild Space', 'J-5'),
('Kyoloria', 'Xappyh', 'Outer Rim Territories', 'Q-3'),
('Kyrouac', NULL, 'Inner Rim', 'K-14'),
('Kyrska', 'Hevvrol', 'Mid Rim', 'P-15'),
('Kyryll''s World', 'Phelleem', 'Outer Rim Territories', 'S-7'),
('Laakonis', 'Glythe', 'Mid Rim', 'J-7'),
('Laakteen Depot', NULL, 'Colonies', 'L-13'),
('Laboi', 'Suolriep', 'Outer Rim Territories', 'S-8'),
('Ladarra', 'Gordian Reach', 'Outer Rim Territories', 'P-5'),
('Ladro', NULL, 'Colonies', 'J-13'),
('Laecor', 'Kallea', 'Outer Rim Territories', 'K-21'),
('Laerdocia', 'Dalonbian', 'Outer Rim Territories', 'L-3'),
('Laertos', NULL, 'Inner Rim', 'L-14'),
('Lafete', 'Tunka', 'Outer Rim Territories', 'I-18'),
('Lafra', 'Wyl', 'Outer Rim Territories', 'R-4'),
('Lah''mu', 'Raioballo', 'Outer Rim Territories', 'L-3'),
('Lahag', 'Erli Cantons of Lahag', 'Expansion Region', 'J-15'),
('Lahn', 'Noonian', 'Outer Rim Territories', 'M-6'),
('Lahsbane', 'Onatos', 'Mid Rim', 'R-15'),
('Laim', 'Rayter', 'Outer Rim Territories', 'J-19'),
('Lakra', NULL, 'Wild Space', 'I-6'),
('Lali', NULL, 'Core Worlds', 'L-13'),
('Lalmy''ash', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Laman', NULL, 'Colonies', 'L-13'),
('Lamaredd', NULL, 'Wild Space', 'S-18'),
('Lambaria', NULL, 'Colonies', 'M-13'),
('Lamman', NULL, 'Core Worlds', 'M-11'),
('Lamuir', 'Tapani', 'Colonies', 'L-13'),
('Lamus', 'Sertar', 'Outer Rim Territories', 'R-5'),
('Lan Barell', 'Hook Nebula', 'Outer Rim Territories', 'O-18'),
('Landor', 'Thesme', 'Outer Rim Territories', 'O-6'),
('Langhesa', 'Meram', 'Outer Rim Territories', 'P-4'),
('Langoona', NULL, 'Hutt Space', 'S-10'),
('Langsha-Raang', 'Tamarin', 'Outer Rim Territories', 'N-18'),
('Langston', 'Kira', 'Expansion Region', 'N-15'),
('Lanjer', 'Rseik', 'Outer Rim Territories', 'N-19'),
('Lankashiir', NULL, 'Colonies', 'N-11'),
('Lannik', 'Lannik Space', 'Mid Rim', 'R-13'),
('Lanos', 'Tandon', 'Mid Rim', 'Q-14'),
('Lansend', NULL, 'Inner Rim', 'N-12'),
('Lansono', NULL, 'Core Worlds', 'L-12'),
('Lant', 'Tharin (Periphery)', 'Outer Rim Territories', 'S-8'),
('Lanteeb', 'Bri''ahl', 'Outer Rim Territories', 'I-17'),
('Lanthe', 'Var Hagen', 'Mid Rim', 'M-16'),
('Lanthrym', 'Elrood', 'Outer Rim Territories', 'M-20'),
('Lantillies', 'Lantillian', 'Mid Rim', 'P-8'),
('Lanz Carpo', NULL, 'Core Worlds', 'M-11'),
('Lapez', 'Esstran', 'Outer Rim Territories', 'Q-5'),
('Laramus', 'Parmic', 'Outer Rim Territories', 'P-18'),
('Laria', 'Rseik', 'Outer Rim Territories', 'N-19'),
('Las Lagon', NULL, 'Inner Rim', 'M-13'),
('Lasan', NULL, 'Wild Space', 'P-20'),
('Lastelle', 'Tapani', 'Colonies', 'L-13'),
('Lasten', NULL, 'Core Worlds', 'L-13'),
('Lateron', 'Talcene', 'Mid Rim', 'Q-8'),
('Latoma', 'Brak', 'Expansion Region', 'O-14'),
('Latza', 'Spirva', 'Mid Rim', 'K-17'),
('Laud', 'Brak', 'Expansion Region', 'O-14'),
('Lavisar', 'Strabin', 'Mid Rim', 'M-7'),
('Lazerian', 'Kira', 'Expansion Region', 'N-15'),
('Leafar', 'Greater Plooriod', 'Expansion Region', 'M-7'),
('Lechra', 'Lixal', 'Inner Rim', 'M-14'),
('Ledalau', NULL, 'Core Worlds', 'L-12'),
('Ledeve', NULL, 'Expansion Region', 'I-7'),
('Lekua', 'Centrality', 'Outer Rim Territories', 'T-8'),
('Lelmra', 'Churba', 'Mid Rim', 'P-14'),
('Lemmi', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Lenahra', 'Velcar', 'Outer Rim Territories', 'J-5'),
('Lengil', 'Bes Ber Bikade', 'Expansion Region', 'L-15'),
('Lenico', 'Cademimu', 'Outer Rim Territories', 'L-6'),
('Lenniera', NULL, 'Core Worlds', 'M-10'),
('Lenthalis', 'Spirva', 'Mid Rim', 'L-17'),
('Leoxo', 'Rayter', 'Outer Rim Territories', 'J-19'),
('Lequabis', NULL, 'Expansion Region', 'I-14'),
('Lerct', 'Prackla', 'Expansion Region', 'O-8'),
('Leresen', 'Lannik Wilds', 'Mid Rim', 'R-13'),
('Leria Kerlsil', NULL, 'Core Worlds', 'M-10'),
('Leritor', 'Yucrales', 'Mid Rim', 'Q-15'),
('Lespectus', NULL, 'Core Worlds', 'M-10'),
('Lessa', 'Mytaranor', 'Mid Rim', 'P-9'),
('Lesser Sloo Gas Cloud', 'Sloo', 'Mid Rim', 'P-14'),
('Lessuris', 'Pelgrin', 'Outer Rim Territories', 'R-17'),
('Lesu', 'Dail', 'Outer Rim Territories', 'Q-18'),
('Letaki', 'Steniplis', 'Outer Rim Territories', 'L-19'),
('Letev', 'Tapani', 'Colonies', 'L-13'),
('Lettow', NULL, 'Core Worlds', 'M-11'),
('Levian', NULL, 'Inner Rim', 'N-8'),
('Lew''el', NULL, 'Wild Space', 'J-3'),
('Lexas Prime', 'Kessel', 'Outer Rim Territories', 'U-10'),
('Lexrul', 'Trax', 'Mid Rim', 'Q-10'),
('Lexus', 'Thrasybule', 'Outer Rim Territories', 'P-6'),
('Leyaki', 'Tregillis', 'Expansion Region', 'M-15'),
('LFA-509', 'Thaere', 'Expansion Region', 'P-14'),
('Lhosa', NULL, 'Inner Rim', 'N-8'),
('Li-Toran', NULL, 'Inner Rim', 'M-13'),
('Lialic', NULL, 'Deep Core', 'K-12'),
('Lianna', 'Allied Tion', 'Outer Rim Territories', 'S-6'),
('Liaq', NULL, 'Core Worlds', 'M-11'),
('Licha In', 'Veragi (Gree Enclave)', 'Outer Rim Territories', 'L-2'),
('Ligna', 'Corva', 'Outer Rim Territories', 'P-4'),
('Liinade', 'Ciutric', 'Outer Rim Territories', 'N-5'),
('Liintaar', 'Gaulus', 'Outer Rim Territories', 'R-17'),
('Likasha', 'Likasha', 'Mid Rim', 'Q-14')
ON CONFLICT (name) DO NOTHING;