-- Add galactic systems from Kankalo to Kolkur (batch 3)
INSERT INTO galactic_systems (name, sector, region, grid_coordinates) VALUES
('Kankalo', 'Esuain', 'Mid Rim', 'P-7'),
('Kant', 'Bothan', 'Mid Rim', 'R-14'),
('Kanzi', NULL, 'Colonies', 'N-12'),
('Kaon', 'Tion Hegemony', 'Outer Rim Territories', 'S-6'),
('Kar''a''katok', NULL, 'Core Worlds', 'K-9'),
('Kara-bin', 'Tharin', 'Outer Rim Territories', 'T-8'),
('Karalle', 'Albanin', 'Outer Rim Territories', 'T-13'),
('Karambola', 'Al''Nasrl', 'Outer Rim Territories', 'T-13'),
('Karatha', 'Tregillis', 'Expansion Region', 'L-15'),
('Karavis', 'Obtrexta', 'Outer Rim Territories', 'K-4'),
('Karazak', 'Sujimis', 'Outer Rim Territories', 'P-19'),
('Kardava', 'Sevastol', 'Mid Rim', 'P-14'),
('Kardoa', 'Atrivis', 'Outer Rim Territories', 'L-5'),
('Kardura', 'Juvex', 'Mid Rim', 'L-17'),
('Kareas', 'Prefsbelt', 'Outer Rim Territories', 'K-6'),
('Karee', 'Nuon e Safyd', 'Expansion Region', 'P-12'),
('Karfeddion', 'Senex', 'Mid Rim', 'L-18'),
('Karga', 'Dustig', 'Mid Rim', 'N-16'),
('Karideph', 'Minos Cluster', 'Outer Rim Territories', 'M-20'),
('Kariek', NULL, 'Wild Space', 'I-6'),
('Karinda', 'Wazta', 'Outer Rim Territories', 'J-18'),
('Karka', 'Clacis', 'Outer Rim Territories', 'K-4'),
('Karkaris', 'Nilgaard', 'Outer Rim Territories', 'S-5'),
('Karken', NULL, 'Inner Rim', 'L-8'),
('Karlinus', 'Chommell', 'Mid Rim', 'O-16'),
('Karltonia', NULL, 'Core Worlds', 'K-13'),
('Karnac', 'Cadma', 'Outer Rim Territories', 'T-8'),
('Karnak Alpha', NULL, 'Core Worlds', 'M-10'),
('Karnst', 'Tharin (Karstaxon)', 'Outer Rim Territories', 'S-8'),
('Karra', 'Rayter', 'Outer Rim Territories', 'J-19'),
('Karsten''s World', 'Gordian Reach', 'Outer Rim Territories', 'Q-6'),
('Karthon', 'Zuma (Sugai)', 'Outer Rim Territories', 'H-16'),
('Karthrexia', 'Kriz', 'Outer Rim Territories', 'K-19'),
('Kartoosh', 'Narrant', 'Mid Rim', 'I-16'),
('Karvathia', 'Tokamac', 'Expansion Region', 'N-13'),
('Karvoss', 'Parmorak', 'Core Worlds', 'M-12'),
('Kashir', 'Vardoss', 'Expansion Region', 'J-8'),
('Kashoon', 'Colundra', 'Outer Rim Territories', 'S-5'),
('Kashyyyk', 'Mytaranor', 'Mid Rim', 'P-9'),
('Kasiol', 'Pelgrin', 'Outer Rim Territories', 'R-18'),
('Kaski', 'Calaron', 'Outer Rim Territories', 'U-8'),
('Kaspas', 'Hevvrol', 'Mid Rim', 'O-15'),
('Kassido', 'Juvex', 'Mid Rim', 'L-17'),
('Katalia', 'Thesme', 'Outer Rim Territories', 'O-5'),
('Katalla', 'Kastolar', 'Mid Rim', 'R-10'),
('Katanos', 'Xan', 'Mid Rim', 'Q-15'),
('Katarr', 'Vensori', 'Mid Rim', 'O-8'),
('Katchan', 'Kallea', 'Outer Rim Territories', 'K-20'),
('Kath', 'Dustig', 'Mid Rim', 'M-17'),
('Kathol', 'Kathol (Rift)', 'Outer Rim Territories', 'M-21'),
('Kathol Rift', 'Kathol (Rift)', 'Outer Rim Territories', 'M-21'),
('Katraasii', 'Belsmuth', 'Outer Rim Territories', 'O-6'),
('Kattada', NULL, 'Colonies', 'M-10'),
('Kaump', 'Bruanii', 'Mid Rim', 'K-17'),
('Kauron', 'Meram', 'Outer Rim Territories', 'O-4'),
('Kavith', 'Corva', 'Outer Rim Territories', 'P-4'),
('Kayri', NULL, 'Expansion Region', 'I-15'),
('Kayuk', 'Sepan', 'Expansion Region', 'P-13'),
('Kayven', NULL, 'Inner Rim', 'M-14'),
('Kazarak', 'Sertar (Mahrusha)', 'Outer Rim Territories', 'S-5'),
('Kazlin', 'Suolriep', 'Outer Rim Territories', 'S-8'),
('Kebolar', 'Lahara', 'Outer Rim Territories', 'M-5'),
('Kebro', 'Bormea', 'Core Worlds', 'L-9'),
('Kedorzha', 'Senex', 'Mid Rim', 'L-18'),
('Kedra', NULL, 'Inner Rim', 'L-14'),
('Keeara Major', 'Koros', 'Deep Core', 'K-10'),
('Keedad', 'Auril', 'Outer Rim Territories', 'R-7'),
('Kegan', 'Calaron', 'Outer Rim Territories', 'T-9'),
('Keitum', 'Ariarch', 'Mid Rim', 'J-6'),
('Kejim', 'Sertar', 'Outer Rim Territories', 'R-5'),
('Kelada', 'Duluur', 'Colonies', 'M-13'),
('Kelarea', 'Tynna', 'Expansion Region', 'N-14'),
('Keldimar', 'Tharin', 'Outer Rim Territories', 'S-7'),
('Keldooine', NULL, 'Hutt Space', 'R-10'),
('Keller''s Void', NULL, 'Inner Rim', 'L-15'),
('Kellgar', 'Mieru''kar', 'Outer Rim Territories', 'O-3'),
('Kellis', 'Terr''skiar', 'Mid Rim', 'P-10'),
('Kellux', 'Seitia', 'Outer Rim Territories', 'J-20'),
('Kelrodo-Ai', 'Steniplis', 'Outer Rim Territories', 'L-18'),
('Keltos', 'Irnaj', 'Mid Rim', 'K-17'),
('Keltria', NULL, 'Core Worlds', 'L-9'),
('Kem Stor Ai', 'Tennuutta', 'Mid Rim', 'Q-7'),
('Kemal Station', 'Arkanis', 'Outer Rim Territories', 'R-16'),
('Kemix', 'Yminis', 'Outer Rim Territories', 'S-14'),
('Kemla', 'Dantus', 'Outer Rim Territories', 'K-6'),
('Kenari', 'Perkell', 'Mid Rim', 'Q-7'),
('Kendamar', 'Lol', 'Outer Rim Territories', 'Q-18'),
('Kenosha', 'Tynna', 'Expansion Region', 'N-14'),
('Keral', 'Corellian', 'Core Worlds', 'M-11'),
('Kerensik', 'Botor Enclave', 'Core Worlds', 'K-12'),
('Keresia', 'Demetras', 'Outer Rim Territories', 'P-7'),
('Kerest', 'Sluis', 'Outer Rim Territories', 'M-19'),
('Kerev Doi', 'Circarpous', 'Expansion Region', 'O-12'),
('Kergans', NULL, 'Inner Rim', 'M-14'),
('Kerig''En', 'Brema', 'Outer Rim Territories', 'M-17'),
('Kerkoidia', 'Kira', 'Expansion Region', 'N-15'),
('Keros', 'Thrasybule', 'Outer Rim Territories', 'P-6'),
('Kerroc', 'Sarin', 'Outer Rim Territories', 'O-18'),
('Kes', NULL, 'Core Worlds', 'L-9'),
('Kesh', NULL, 'Wild Space', 'U-10'),
('Keshi', 'Bheriz', 'Outer Rim Territories', 'U-10'),
('Keskin', 'Koradin', 'Outer Rim Territories', 'J-18'),
('Kesmere', 'Raioballo', 'Outer Rim Territories', 'L-4'),
('Kesmere Minor', 'Raioballo', 'Outer Rim Territories', 'L-4'),
('Kessel', 'Kessel', 'Outer Rim Territories', 'T-10'),
('Kessur', 'Dimean', 'Expansion Region', 'P-13'),
('Kestavel', NULL, 'Colonies', 'K-9'),
('Kestel', 'Mortex', 'Outer Rim Territories', 'R-5'),
('Kestos Minor', 'Kwymar', 'Outer Rim Territories', 'Q-4'),
('Ket', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Ketal', NULL, 'Inner Rim', 'L-14'),
('Ketaris', 'Oplovis', 'Outer Rim Territories', 'L-5'),
('Keteeria', 'Venaarian', 'Mid Rim', 'O-7'),
('Kethmandi', 'Hangshan', 'Expansion Region', 'P-11'),
('Ketz', NULL, 'Colonies', 'K-13'),
('Ketzali', 'Lannik Wilds', 'Mid Rim', 'R-13'),
('Kexeeria', NULL, 'Colonies', 'M-12'),
('Keyorin', 'Belderone', 'Outer Rim Territories', 'R-6'),
('Khadaji', 'Singularity Corridan', 'Core Worlds', 'J-10'),
('Khar Delba', 'Esstran (Sith Worlds)', 'Outer Rim Territories', 'R-5'),
('Kharmort''s Miasma', NULL, 'Unknown Regions', 'H-9'),
('Kharzet', 'Mortex', 'Outer Rim Territories', 'R-4'),
('Kheedar', 'Khuiumin', 'Outer Rim Territories', 'O-18'),
('Khemerion', 'Belasco', 'Expansion Region', 'P-11'),
('Kho Nai', 'Kalamith', 'Outer Rim Territories', 'P-5'),
('Khoan', 'Phelleem', 'Outer Rim Territories', 'S-7'),
('Kholes', 'Elbaran', 'Mid Rim', 'J-17'),
('Khomm', NULL, 'Deep Core', 'L-12'),
('Khomr', 'Corellian', 'Core Worlds', 'M-11'),
('Khonji', 'Prefsbelt', 'Outer Rim Territories', 'J-5'),
('Khorm', 'Halori', 'Mid Rim', 'P-8'),
('Khorya', NULL, 'Hutt Space', 'S-9'),
('Khramboa', NULL, 'Core Worlds', 'M-9'),
('Khubeaie', 'Arkanis', 'Outer Rim Territories', 'R-17'),
('Khuiumin', 'Khuiumin', 'Outer Rim Territories', 'O-18'),
('Khuteb', 'Thanium', 'Outer Rim Territories', 'S-5'),
('Kiamurr', 'Likasha', 'Mid Rim', 'Q-15'),
('Kidiet Olgo', NULL, 'Core Worlds', 'L-9'),
('Kidir', 'Kuat', 'Core Worlds', 'M-10'),
('Kidriff', 'Lostar', 'Expansion Region', 'M-8'),
('Kidron', 'Elrood', 'Outer Rim Territories', 'M-20'),
('Kiffex', 'Kiffu', 'Inner Rim', 'L-14'),
('Kiilimaar', 'Svivreni', 'Outer Rim Territories', 'O-19'),
('Kijimi', 'Bryx', 'Mid Rim', 'R-8'),
('Kile', 'Jospro', 'Outer Rim Territories', 'S-7'),
('Kilia', NULL, 'Wild Space', 'I-8'),
('Kiliea', 'Atrisian CW', 'Core Worlds', 'J-12'),
('Killaniri', 'Wornal', 'Mid Rim', 'K-17'),
('Killisu', 'Ado', 'Mid Rim', 'M-17'),
('Killun Station', 'Pakuuni', 'Outer Rim Territories', 'T-6'),
('Kilmauls', 'Vorzyd', 'Outer Rim Territories', 'R-6'),
('Kimanan', 'Orus', 'Inner Rim', 'M-8'),
('Kimm Aurek', 'Juvex', 'Mid Rim', 'L-18'),
('Kimm Besh', 'Juvex', 'Mid Rim', 'L-18'),
('Kimm Cresh', 'Juvex', 'Mid Rim', 'L-18'),
('Kindlabethia', 'Braxant', 'Outer Rim Territories', 'J-3'),
('King''s Galquek', 'Meridian', 'Outer Rim Territories', 'R-7'),
('Kinooine', NULL, 'Wild Space', 'J-21'),
('Kinoss', 'Chiss Space', 'Unknown Regions', 'E-8'),
('Kinrah', 'Onatos', 'Mid Rim', 'R-15'),
('Kintan', NULL, 'Hutt Space', 'S-9'),
('Kintarr', NULL, 'Colonies', 'L-13'),
('Kintoni', 'Ash Worlds', 'Outer Rim Territories', 'S-6'),
('Kinun Depot', 'Pelgrin', 'Outer Rim Territories', 'R-18'),
('Kinyen', 'Bes Ber Bikade', 'Expansion Region', 'L-15'),
('Kip', 'Chorlian', 'Outer Rim Territories', 'S-4'),
('Kir', 'Corporate Sector', 'Outer Rim Territories', 'S-3'),
('Kira', 'Kira', 'Expansion Region', 'N-16'),
('Kirdo', 'Tamarin', 'Outer Rim Territories', 'N-19'),
('Kiribi', NULL, 'Colonies', 'L-9'),
('Kirima', 'Elbaran', 'Mid Rim', 'J-17'),
('Kiros', 'Ehosiq', 'Expansion Region', 'L-8'),
('Kirtania', 'Nembus', 'Outer Rim Territories', 'P-4'),
('Kirtarkin', 'Javin (Anoat)', 'Outer Rim Territories', 'K-18'),
('Kishpaugh', 'Iskin', 'Mid Rim', 'O-16'),
('Kismaano', 'Cronese Mandate', 'Outer Rim Territories', 'S-6'),
('Kitaros Nebula', 'Prefsbelt', 'Outer Rim Territories', 'K-5'),
('Kitel Phard', 'Atrisian CW', 'Core Worlds', 'J-12'),
('Kiva', 'Venaarian', 'Mid Rim', 'O-7'),
('Kizan', NULL, 'Inner Rim', 'N-8'),
('Kktkt', 'Farlax', 'Core Worlds', 'K-10'),
('Klaatu', 'Airam', 'Outer Rim Territories', 'L-20'),
('Klasse Ephemora', NULL, 'Unknown Regions', 'F-9'),
('Klatooine', NULL, 'Hutt Space', 'S-9'),
('Klaymor', 'Druess', 'Mid Rim', 'O-15'),
('Kleeva', NULL, 'Hutt Space', 'R-11'),
('Klepthia', 'Tynna', 'Expansion Region', 'N-14'),
('Kler''terria', NULL, 'Core Worlds', 'K-12'),
('Kli''aar', 'Gordian Reach', 'Outer Rim Territories', 'P-5'),
('Klonoid', 'Phelleem', 'Outer Rim Territories', 'S-7'),
('Kloodavia', NULL, 'Core Worlds', 'K-13'),
('Kloper', NULL, 'Inner Rim', 'N-9'),
('Kluistar', NULL, 'Colonies', 'M-8'),
('Klytonia', 'Bheriz', 'Outer Rim Territories', 'U-11'),
('Klytus', NULL, 'Wild Space', 'H-15'),
('Knolstee', 'Corporate Sector', 'Outer Rim Territories', 'R-3'),
('Knooda', 'Askarian', 'Expansion Region', 'O-12'),
('Knores', 'Senex', 'Mid Rim', 'L-17'),
('Knot Holes', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Ko-Longava', 'Hocatar', 'Mid Rim', 'P-12'),
('Koaan', NULL, 'Inner Rim', 'N-8'),
('Koba', 'Narrant', 'Mid Rim', 'J-16'),
('Kobal''s World', 'Koradin', 'Outer Rim Territories', 'I-18'),
('Kobaria', 'Emmo', 'Core Worlds', 'M-12'),
('Kobbahn', 'Dantus', 'Outer Rim Territories', 'J-6'),
('Koboh', 'Varada', 'Outer Rim Territories', 'H-19'),
('Koboh Abyss', 'Varada', 'Outer Rim Territories', 'H-19'),
('Koboth', NULL, 'Outer Rim Territories', 'R-3'),
('Koda Space Station', 'Wazta', 'Outer Rim Territories', 'I-18'),
('Kodai', 'Belderone', 'Outer Rim Territories', 'R-6'),
('Koensayr', NULL, 'Colonies', 'N-12'),
('Kogan', 'Veragi', 'Outer Rim Territories', 'L-3'),
('Koiogra', 'Grohl', 'Outer Rim Territories', 'R-16'),
('Kojash', 'Farlax', 'Core Worlds', 'K-10'),
('Kokash', 'Kokash', 'Core Worlds', 'J-10'),
('Koke', 'Frost', 'Wild Space', 'I-7'),
('Kol Atorn', 'Kanz', 'Outer Rim Territories', 'N-4'),
('Kol Huro', 'Kanz', 'Outer Rim Territories', 'N-4'),
('Kol Iben', 'Arkanis', 'Outer Rim Territories', 'R-16'),
('Kolaador', 'Dalchon', 'Outer Rim Territories', 'R-17'),
('Kolanda Station', 'Yminis', 'Outer Rim Territories', 'S-14'),
('Kolatill', 'Kathol', 'Outer Rim Territories', 'M-21'),
('Koler', NULL, 'Deep Core', 'L-12'),
('Kolkur', 'Indrexu', 'Outer Rim Territories', 'S-5')
ON CONFLICT (name) DO NOTHING;