-- Insert next batch of galactic systems (Empress Teta to Flax)
INSERT INTO galactic_systems (name, sector, region, grid_coordinates) VALUES
('Empress Teta', 'Koros', 'Deep Core', 'L-10'),
('Emurria', NULL, 'Colonies', 'L-9'),
('Enaleh', NULL, 'Colonies', 'L-13'),
('Enarc', 'Alui', 'Mid Rim', 'O-17'),
('Encrust', 'Jubilar', 'Outer Rim Territories', 'T-7'),
('Endex', 'Velcar', 'Outer Rim Territories', 'J-5'),
('Endor', 'Zuma (Moddell)', 'Outer Rim Territories', 'H-16'),
('Endor Gate', 'Zuma (Moddell)', 'Outer Rim Territories', 'H-16'),
('Endoraan', 'Clacis', 'Outer Rim Territories', 'K-4'),
('Endovan', 'Sarka', 'Mid Rim', 'Q-8'),
('Endovar', 'Terrabe', 'Mid Rim', 'H-10'),
('Endregaad', 'Indrexu', 'Outer Rim Territories', 'S-5'),
('Endrias Minor', 'Tammuz', 'Outer Rim Territories', 'T-14'),
('Endrolia', NULL, 'Core Worlds', 'K-10'),
('Endymion', 'Kalamith', 'Outer Rim Territories', 'P-5'),
('Enet', 'Brak', 'Expansion Region', 'O-14'),
('Enferm', 'Mezeg', 'Mid Rim', 'M-7'),
('Engebo', 'Danjar', 'Outer Rim Territories', 'N-18'),
('Engira', 'Jospro', 'Outer Rim Territories', 'R-7'),
('Enisca', NULL, 'Colonies', 'M-13'),
('Ennth', 'Astal', 'Outer Rim Territories', 'Q-18'),
('Enoth', 'Calamari', 'Outer Rim Territories', 'U-6'),
('Enrivi', 'Metatessu', 'Mid Rim', 'R-9'),
('Enselon', NULL, 'Core Worlds', 'L-12'),
('Ensolica', NULL, 'Core Worlds', 'K-10'),
('Entana', 'Cademimu', 'Outer Rim Territories', 'L-6'),
('Entiia', 'Maldrood', 'Mid Rim', 'R-7'),
('Entooine', 'Danjar', 'Outer Rim Territories', 'N-18'),
('Entralla', 'Velcar', 'Outer Rim Territories', 'K-4'),
('Entropian Hive', 'Elbaran', 'Mid Rim', 'J-17'),
('Entrus', 'Trax', 'Mid Rim', 'Q-10'),
('Entruvia', 'Halla', 'Mid Rim', 'R-8'),
('Entuur', 'Urce Space', 'Mid Rim', 'L-6'),
('Eol Sha', 'Corva', 'Outer Rim Territories', 'P-3'),
('Eos', 'Cadavine', 'Outer Rim Territories', 'P-17'),
('Ephemera', NULL, 'Inner Rim', 'J-14'),
('Epica', 'Bes Ber Bikade', 'Expansion Region', 'L-15'),
('Epidimi', 'Rolion', 'Outer Rim Territories', 'Q-7'),
('Epsi Nadir', 'Epsi Collective', 'Expansion Region', 'M-15'),
('Epsi Zenith', 'Epsi Collective', 'Expansion Region', 'M-15'),
('Epsom', 'Quiberon', 'Outer Rim Territories', 'S-15'),
('Equanus', 'Veragi', 'Outer Rim Territories', 'K-3'),
('Er''Kit', 'Noonian', 'Outer Rim Territories', 'M-6'),
('Er''stacia', NULL, 'Wild Space', 'V-9'),
('Erai', 'Hangshan', 'Expansion Region', 'P-11'),
('Eredenn', 'Tion Hegemony', 'Outer Rim Territories', 'S-6'),
('Eredin', 'Astal', 'Outer Rim Territories', 'P-18'),
('Ereesus', 'Kanz', 'Outer Rim Territories', 'N-4'),
('Eremond', NULL, 'Deep Core', 'L-10'),
('Eres', 'Esuain', 'Mid Rim', 'Q-7'),
('Erhynradd', NULL, 'Inner Rim', 'N-13'),
('Eriadu', 'Seswenna', 'Outer Rim Territories', 'M-18'),
('Erian', 'Churba', 'Mid Rim', 'P-15'),
('Eridicon', 'Calamari', 'Outer Rim Territories', 'T-6'),
('Erigorm', NULL, 'Core Worlds', 'L-9'),
('Erilnar', 'Centrality', 'Outer Rim Territories', 'T-8'),
('Eriscot', 'Haserian', 'Mid Rim', 'Q-14'),
('Ermi', 'Sertar', 'Outer Rim Territories', 'R-5'),
('Eroudac', 'Doldur', 'Mid Rim', 'P-15'),
('Errimin', 'Koradin', 'Outer Rim Territories', 'J-18'),
('Ertegas', 'Javin (Anoat)', 'Outer Rim Territories', 'K-18'),
('Ertrax', NULL, 'Wild Space', 'N-21'),
('Erub', NULL, 'Inner Rim', 'N-14'),
('Erysthes', 'Corporate Sector', 'Outer Rim Territories', 'S-4'),
('Esaga', 'Esaga', 'Mid Rim', 'R-11'),
('Escabar', NULL, 'Expansion Region', 'I-8'),
('Escalan', 'Cademimu', 'Outer Rim Territories', 'L-6'),
('Escander', 'Taldot', 'Mid Rim', 'Q-9'),
('Escarte', 'Keldrath', 'Outer Rim Territories', 'T-6'),
('Eschaton', 'Far Xandil', 'Mid Rim', 'O-16'),
('Esfandia', NULL, 'Wild Space', 'I-6'),
('Eshan', NULL, 'Inner Rim', 'N-8'),
('Esooma', 'Sprizen', 'Outer Rim Territories', 'N-5'),
('Espinar', NULL, 'Core Worlds', 'K-9'),
('Espirion', NULL, 'Inner Rim', 'N-12'),
('Essebra', 'Airam', 'Outer Rim Territories', 'M-20'),
('Esseles', 'Darpa', 'Core Worlds', 'L-9'),
('Esseveya', 'Maldrood', 'Mid Rim', 'R-7'),
('Essien', 'Halthor', 'Outer Rim Territories', 'M-6'),
('Ession', 'Corporate Sector', 'Outer Rim Territories', 'S-4'),
('Essowyn', 'Trax', 'Mid Rim', 'Q-10'),
('Estaph', 'Tapani', 'Colonies', 'L-13'),
('Estaria', 'Indrexu', 'Outer Rim Territories', 'S-5'),
('Esyram', 'Atravis', 'Outer Rim Territories', 'L-20'),
('Etai', 'Druess', 'Mid Rim', 'O-15'),
('Ethav Major', 'Ethav Regions', 'Wild Space', 'P-3'),
('Ethrani', 'D''Astan (Valahari)', 'Outer Rim Territories', 'N-5'),
('Etorasp', 'Hakartha', 'Expansion Region', 'K-16'),
('Etti', 'Corporate Sector', 'Outer Rim Territories', 'S-4'),
('Euceron', 'Eucer', 'Mid Rim', 'Q-7'),
('Eufornis Major', NULL, 'Core Worlds', 'M-11'),
('Eufornis Minor', 'Shadola', 'Outer Rim Territories', 'U-8'),
('Eva-T', 'Quence', 'Outer Rim Territories', 'O-18'),
('Evas', 'Belshar', 'Mid Rim', 'I-7'),
('Excarga', 'Herios', 'Outer Rim Territories', 'T-16'),
('Exegol', NULL, 'Unknown Regions', 'F-7'),
('Exigar', 'Weneen', 'Outer Rim Territories', 'N-6'),
('Exocron', 'Kathol (Outback)', 'Outer Rim Territories', 'M-21'),
('Exodeen', NULL, 'Colonies', 'M-12'),
('Exodo', 'Meridian', 'Outer Rim Territories', 'R-7'),
('Extorin Major', 'Extorin', 'Expansion Region', 'J-15'),
('Extorin Minor', 'Extorin', 'Expansion Region', 'J-15'),
('Extrictarium Nebula', 'Ash Worlds', 'Outer Rim Territories', 'T-7'),
('Eyar', NULL, 'Inner Rim', 'O-10'),
('Ezaraa', 'Spinward', 'Outer Rim Territories', 'M-2'),
('Ezran', 'Onatos', 'Mid Rim', 'Q-15'),
('F''Dann', 'Dufilvian', 'Mid Rim', 'R-15'),
('F''tral', 'Calaron', 'Outer Rim Territories', 'T-9'),
('F''tzner', 'Bartahn', 'Inner Rim', 'L-15'),
('Faarlsun', NULL, 'Wild Space', 'T-4'),
('Fabrin', 'Circarpous', 'Expansion Region', 'O-12'),
('Fadden', NULL, 'Inner Rim', 'N-11'),
('Fair Hollis', 'Karthakk', 'Outer Rim Territories', 'Q-17'),
('Fait d''Fait', 'Venaarian', 'Mid Rim', 'O-7'),
('Faket', NULL, 'Wild Space', 'G-15'),
('Fakir', 'Fakir', 'Colonies', 'K-9'),
('Falang Minor', 'Thanium', 'Outer Rim Territories', 'R-6'),
('Falasia', NULL, 'Inner Rim', 'N-10'),
('Falaston', 'Kallea', 'Outer Rim Territories', 'K-21'),
('Faldos', 'Saijo', 'Outer Rim Territories', 'K-20'),
('Falko', 'Centrality', 'Outer Rim Territories', 'U-8'),
('Falleen', 'Doldur', 'Mid Rim', 'P-15'),
('Fallex', 'Belderone', 'Outer Rim Territories', 'R-6'),
('Fallowan', 'Sujimis', 'Outer Rim Territories', 'P-19'),
('Fangol', 'Mortex', 'Outer Rim Territories', 'S-5'),
('Fanha', 'Seitia', 'Outer Rim Territories', 'K-19'),
('Faos Station', 'Belsmuth', 'Outer Rim Territories', 'P-6'),
('Far Dostany', 'M''shinni', 'Mid Rim', 'M-7'),
('Far Indosa', 'Gordian Reach', 'Outer Rim Territories', 'P-6'),
('Far Pando', 'Hutt Space', 'Outer Rim Territories', 'S-13'),
('Fara''s Belt', 'Rolion', 'Outer Rim Territories', 'Q-6'),
('Farana', 'Farana', 'Wild Space', 'S-3'),
('Farbinda', NULL, 'Inner Rim', 'N-14'),
('Farbog', 'Vorzyd', 'Outer Rim Territories', 'R-6'),
('Farboon', 'Tantra', 'Outer Rim Territories', 'M-19'),
('Farfalla', 'Indra-su-Mar', 'Expansion Region', 'P-12'),
('Farfax', 'Marzoon', 'Mid Rim', 'I-16'),
('Farfeld', 'Jjannex', 'Outer Rim Territories', 'L-18'),
('Farhava Beta', 'Tantra', 'Outer Rim Territories', 'M-19'),
('Farnica', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Faro', NULL, 'Colonies', 'N-10'),
('Farquar', 'Kurost', 'Mid Rim', 'Q-11'),
('Farrfin', 'Farrfin', 'Core Worlds', 'K-9'),
('Farseen', 'Msst', 'Mid Rim', 'P-7'),
('Farsellah', 'Farstey', 'Expansion Region', 'O-8'),
('Farstey', 'Farstey', 'Expansion Region', 'O-8'),
('Farstine', 'Ryndellian', 'Mid Rim', 'P-17'),
('Farstone', 'Juvex', 'Mid Rim', 'K-18'),
('Farwell Station', 'Eucer', 'Mid Rim', 'R-7'),
('Fashinder Prime', 'Primtara', 'Mid Rim', 'P-15'),
('Faz', 'Farlax', 'Core Worlds', 'K-10'),
('Feather Nebula', 'Irnaj', 'Mid Rim', 'K-17'),
('Febrini', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Fedalle', NULL, 'Core Worlds', 'M-10'),
('Feddasyr', 'Elus', 'Inner Rim', 'N-12'),
('Federian', 'Stensen', 'Outer Rim Territories', 'I-17'),
('Fedevoi End', 'Croynar', 'Inner Rim', 'M-14'),
('Fedje', 'Atrivis', 'Outer Rim Territories', 'L-5'),
('Feena', 'Gordian Reach', 'Outer Rim Territories', 'Q-5'),
('Feenicks', 'Jjannex', 'Outer Rim Territories', 'K-19'),
('Feenix', 'D''Aelgoth', 'Mid Rim', 'K-17'),
('Fef', 'Glythe', 'Mid Rim', 'J-7'),
('Fegorosk', 'Obtrexta', 'Outer Rim Territories', 'K-4'),
('Fehern', 'Trax', 'Mid Rim', 'Q-10'),
('Fekunda', 'Shadola', 'Outer Rim Territories', 'U-8'),
('Felacat', 'Grohl', 'Outer Rim Territories', 'R-15'),
('Feldrona', 'Glythe', 'Mid Rim', 'J-7'),
('Feldwes', 'Gordian Reach', 'Outer Rim Territories', 'Q-6'),
('Felin', 'Spinward', 'Outer Rim Territories', 'M-2'),
('Fellio', 'Cadavine', 'Outer Rim Territories', 'P-17'),
('Felucia', 'Thanium', 'Outer Rim Territories', 'R-6'),
('Fendry', 'Druess', 'Mid Rim', 'O-15'),
('Fenel', 'Demetras', 'Outer Rim Territories', 'O-7'),
('Fengrine', 'Senex', 'Mid Rim', 'L-18'),
('Fenion', 'Rolion', 'Outer Rim Territories', 'P-7'),
('Fenn', 'Dufilvian', 'Mid Rim', 'R-15'),
('Fennesa', NULL, 'Inner Rim', 'K-14'),
('Fentersohn', NULL, 'Expansion Region', 'I-9'),
('Fenves', 'Boeus', 'Expansion Region', 'L-15'),
('Feraleech', 'Noolian', 'Mid Rim', 'Q-13'),
('Fere', 'Quelii', 'Outer Rim Territories', 'O-6'),
('Ferijia', NULL, 'Core Worlds', 'M-10'),
('Feris', 'Agarix', 'Mid Rim', 'K-17'),
('Fermic', 'Wazta', 'Outer Rim Territories', 'J-18'),
('Ferona', 'Vivaros', 'Colonies', 'N-10'),
('Ferrelia', 'Hunnoverrs', 'Outer Rim Territories', 'R-16'),
('Ferrhast', NULL, 'Core Worlds', 'L-13'),
('Ferrix', 'Xappyh (Morlana)', 'Outer Rim Territories', 'Q-3'),
('Ferro', 'Illisurevimurasi', 'Outer Rim Territories', 'Q-4'),
('Ferrok', 'Pax Ombakond', 'Expansion Region', 'P-12'),
('Ferros', 'Ojoster', 'Outer Rim Territories', 'N-7'),
('Ferrous Aurora Nebula', 'Thesme', 'Outer Rim Territories', 'O-6'),
('Ferton', 'Al''Nasrl', 'Outer Rim Territories', 'T-13'),
('Fest', 'Atrivis', 'Outer Rim Territories', 'L-5'),
('Feswe Minor', 'Gordian Reach', 'Outer Rim Territories', 'P-5'),
('Feswe Prime', 'Gordian Reach', 'Outer Rim Territories', 'P-5'),
('Fether', 'Corporate Sector', 'Outer Rim Territories', 'S-3'),
('Fex', NULL, 'Deep Core', 'L-12'),
('Fhost', NULL, 'Wild Space', 'H-7'),
('Fial', 'Auril', 'Outer Rim Territories', 'S-6'),
('Fibuli', 'Trianii Space', 'Wild Space', 'S-3'),
('Fikari', 'Thanium', 'Outer Rim Territories', 'R-6'),
('Fikzwaa', NULL, 'Inner Rim', 'N-14'),
('Filata', NULL, 'Mid Rim', 'H-10'),
('Filby', NULL, 'Core Worlds', 'L-9'),
('Fillithar', NULL, 'Inner Rim', 'N-10'),
('Filordis', 'Larrin', 'Inner Rim', 'N-8'),
('Filve', 'Dufilvian', 'Mid Rim', 'R-15'),
('Fimster', NULL, 'Inner Rim', 'L-14'),
('Findris', 'Haldeen', 'Colonies', 'M-9'),
('Firrerre', 'Zuma (Sugai)', 'Outer Rim Territories', 'H-16'),
('Firrhana', 'Ojoster', 'Outer Rim Territories', 'N-7'),
('Firro', 'Farrfin', 'Core Worlds', 'K-9'),
('Fislan', 'Mortex', 'Outer Rim Territories', 'R-4'),
('Fitca Prime', 'Urce Space', 'Mid Rim', 'L-6'),
('Fiumar', 'Quanta', 'Core Worlds', 'M-12'),
('Five Points', 'Thanium', 'Outer Rim Territories', 'S-6'),
('Fiviune', 'Grumani', 'Outer Rim Territories', 'N-17'),
('Fjor', 'Grohl', 'Outer Rim Territories', 'R-15'),
('Flacharia', NULL, 'Wild Space', 'H-6'),
('Flandor', NULL, 'Inner Rim', 'N-13'),
('Flankers', 'Fakir', 'Colonies', 'K-9'),
('Flashpoint', 'Meerian', 'Outer Rim Territories', 'O-7'),
('Flax', 'Sumitra', 'Expansion Region', 'O-7');