-- Insert next batch of galactic systems (Haven to Ishram Nebula)
INSERT INTO galactic_systems (name, sector, region, grid_coordinates) VALUES
('Haven', 'Minos Cluster', 'Outer Rim Territories', 'M-20'),
('Haverling', 'Albarrio', 'Outer Rim Territories', 'K-5'),
('Havricus', NULL, 'Colonies', 'N-12'),
('Hazun', 'Astal', 'Outer Rim Territories', 'P-17'),
('Hazzard', 'Lahara', 'Outer Rim Territories', 'M-5'),
('Heap Nine', 'Boeus', 'Expansion Region', 'M-15'),
('Hebekrr', 'Ojoster', 'Outer Rim Territories', 'N-7'),
('Heffrin', 'Arkanis', 'Outer Rim Territories', 'R-17'),
('Hefi', 'Abrion', 'Outer Rim Territories', 'S-15'),
('Hei', 'Thrasybule', 'Outer Rim Territories', 'P-6'),
('Heliconia', NULL, 'Core Worlds', 'L-10'),
('Helix', 'Meridian', 'Outer Rim Territories', 'R-6'),
('Helleguth', NULL, 'Inner Rim', 'N-13'),
('Hellenah', 'Xan', 'Mid Rim', 'Q-15'),
('Hellhoop, The', 'Hocatar', 'Expansion Region', 'P-12'),
('Hellios', 'Tapani', 'Colonies', 'L-13'),
('Helmaxa', NULL, 'Inner Rim', 'M-14'),
('Helska', 'Dalonbian', 'Outer Rim Territories', 'L-2'),
('Hemei', NULL, 'Core Worlds', 'M-12'),
('Hendanyn', NULL, 'Colonies', 'M-13'),
('Hendrix', 'Iska', 'Mid Rim', 'J-16'),
('Hensara', 'Rachuk', 'Colonies', 'N-11'),
('Heptalia', NULL, 'Inner Rim', 'M-14'),
('Heptooine', 'Grumani', 'Outer Rim Territories', 'N-17'),
('Herakal', 'Ghost Nebula', 'Expansion Region', 'P-10'),
('Herdessa', 'Herdessa', 'Mid Rim', 'Q-16'),
('Herego', NULL, 'Colonies', 'M-9'),
('Herios', 'Herios', 'Outer Rim Territories', 'T-16'),
('Heriston', 'Atravis', 'Outer Rim Territories', 'L-19'),
('Hermos', 'Spadja', 'Outer Rim Territories', 'R-5'),
('Hero Twins', 'Relgim', 'Outer Rim Territories', 'L-4'),
('Herrik', 'Dantus', 'Outer Rim Territories', 'J-6'),
('Herstell', NULL, 'Colonies', 'N-12'),
('Herzob', NULL, 'Colonies', 'N-12'),
('Hestria', 'Senex', 'Mid Rim', 'L-18'),
('Heterkus', 'Tharin', 'Outer Rim Territories', 'S-8'),
('Hethar', 'Atrivis', 'Outer Rim Territories', 'L-5'),
('Hetnagaro', 'Andirma', 'Expansion Region', 'L-15'),
('Hettitite', 'Dalonbian', 'Outer Rim Territories', 'M-2'),
('Hettsk', 'Belsmuth', 'Outer Rim Territories', 'P-6'),
('Hetzal', 'Savareen', 'Outer Rim Territories', 'Q-16'),
('Heva', 'Sevetta', 'Outer Rim Territories', 'S-16'),
('Hevurion', NULL, 'Inner Rim', 'L-8'),
('Hewett', 'Hewett', 'Mid Rim', 'M-6'),
('Hewl', 'Eidoloni', 'Mid Rim', 'M-16'),
('Hexus', 'D''Astan', 'Outer Rim Territories', 'O-5'),
('Hibrath', NULL, 'Unknown Regions', 'G-7'),
('Hidden Tegoor', 'Albanin', 'Outer Rim Territories', 'T-12'),
('Hiffis', 'Jjannex', 'Outer Rim Territories', 'L-18'),
('High Chunah', 'Javin', 'Outer Rim Territories', 'K-18'),
('Hiit', 'Corporate Sector', 'Outer Rim Territories', 'S-3'),
('Hijado', 'Thesme', 'Outer Rim Territories', 'O-6'),
('Hijarna', 'Orus', 'Inner Rim', 'M-8'),
('Hijo', 'Hijoian Space', 'Expansion Region', 'J-8'),
('Hikil', 'Grohl', 'Outer Rim Territories', 'R-16'),
('Hillindor Echo', NULL, 'Inner Rim', 'M-13'),
('Hilo', 'Hilo', 'Expansion Region', 'O-13'),
('Hinakuu', 'Calamari', 'Outer Rim Territories', 'U-6'),
('Hinari', 'Thesme', 'Outer Rim Territories', 'O-6'),
('Hinda', 'Airam', 'Outer Rim Territories', 'L-20'),
('Hindasar', 'Corpheli', 'Expansion Region', 'M-8'),
('Hindle', NULL, 'Core Worlds', 'M-12'),
('Hino', NULL, 'Colonies', 'N-10'),
('Hintivan', 'Corva', 'Outer Rim Territories', 'Q-3'),
('Hiorin', 'Ash Worlds', 'Outer Rim Territories', 'T-6'),
('Hirsi', 'Elbaran', 'Mid Rim', 'J-17'),
('Hishyim', 'Abrion', 'Outer Rim Territories', 'S-15'),
('Hismaul', 'Karthakk', 'Outer Rim Territories', 'Q-16'),
('Hisseen', 'Yucrales', 'Mid Rim', 'R-15'),
('Hissrich', 'Spadja', 'Outer Rim Territories', 'R-6'),
('Hitaka', 'Cademimu', 'Outer Rim Territories', 'M-6'),
('Hivebase-1', 'Minos Cluster', 'Outer Rim Territories', 'M-20'),
('Hjaff', NULL, 'Colonies', 'J-13'),
('Hleua', 'Eucer', 'Mid Rim', 'Q-7'),
('Hofsgut', 'Hewett', 'Mid Rim', 'M-7'),
('Hok', NULL, 'Colonies', 'M-9'),
('Holador', 'Herios', 'Outer Rim Territories', 'T-16'),
('Holageus', 'Charra', 'Expansion Region', 'P-14'),
('Holess', 'Manda', 'Mid Rim', 'R-14'),
('Hollastin', 'Hutt Space', 'Outer Rim Territories', 'S-12'),
('Hologram Fun World', 'Phelleem', 'Outer Rim Territories', 'S-7'),
('Homana', 'Strabin', 'Mid Rim', 'M-6'),
('Homon', 'Homon', 'Mid Rim', 'M-7'),
('Honoghr', 'Kessel', 'Outer Rim Territories', 'T-10'),
('Hoogon', 'Dantus', 'Outer Rim Territories', 'J-6'),
('Hope Station', 'Haserian', 'Mid Rim', 'Q-14'),
('Horain', NULL, 'Inner Rim', 'L-14'),
('Horizon Base', 'Veragi', 'Outer Rim Territories', 'K-3'),
('Horn Station', 'Lahara', 'Outer Rim Territories', 'M-5'),
('Horob', 'Vardoss', 'Expansion Region', 'I-8'),
('Horos Lambda', NULL, 'Mid Rim', 'Q-15'),
('Horox', 'Lahara', 'Outer Rim Territories', 'M-5'),
('Horska', NULL, 'Colonies', 'J-9'),
('Horthav', 'Kuat', 'Core Worlds', 'M-10'),
('Hortolo', 'Trans-Vulta', 'Mid Rim', 'O-7'),
('Horuz', 'Atrivis', 'Outer Rim Territories', 'L-5'),
('Hosko', 'Hutt Space', 'Outer Rim Territories', 'S-11'),
('Hosnian Prime', 'Hosnian', 'Core Worlds', 'M-12'),
('Hosrel', 'Centrality', 'Outer Rim Territories', 'U-8'),
('Hoszh Iszhir', 'Uoti', 'Core Worlds', 'K-9'),
('Hoth', 'Javin (Anoat)', 'Outer Rim Territories', 'K-18'),
('Houche', 'Zuma (Sugai)', 'Outer Rim Territories', 'H-16'),
('Hovan', 'Senex', 'Mid Rim', 'L-18'),
('Hoven', NULL, 'Inner Rim', 'O-8'),
('Hovun', 'Sepan', 'Expansion Region', 'P-13'),
('Hoxim', NULL, 'Unknown Regions', 'G-9'),
('Hoylin', 'Fei Hu', 'Mid Rim', 'P-13'),
('Hradreek', 'Graador', 'Mid Rim', 'I-17'),
('Hraki', 'Vorzyd', 'Outer Rim Territories', 'R-6'),
('Hrasskis', 'Kossa', 'Expansion Region', 'O-11'),
('Hreeshi', 'Kalamith', 'Outer Rim Territories', 'P-5'),
('Hrel', 'Relgim', 'Outer Rim Territories', 'L-5'),
('Hrill', 'Yminis', 'Outer Rim Territories', 'S-15'),
('Hrthging', 'Mandalore', 'Outer Rim Territories', 'O-7'),
('Hudalla', 'Stensen', 'Outer Rim Territories', 'I-17'),
('Huk', NULL, 'Wild Space', 'J-4'),
('Huldamun', 'Arkanis', 'Outer Rim Territories', 'R-17'),
('Hull''s Star', 'Farana', 'Wild Space', 'S-3'),
('Huloon', 'Hutt Space', 'Outer Rim Territories', 'S-11'),
('Humbarine', 'Humbarine', 'Core Worlds', 'M-10'),
('Hurd''s Moon', 'Bortele', 'Mid Rim', 'R-8'),
('Hurikane', NULL, 'Wild Space', 'V-9'),
('Huro', 'Ciutric', 'Outer Rim Territories', 'N-5'),
('Hurrim', 'Danjar', 'Outer Rim Territories', 'N-18'),
('Huru', 'Mieru''kar', 'Outer Rim Territories', 'N-4'),
('Hutlar', 'Senex', 'Mid Rim', 'L-17'),
('Huulia', NULL, 'Colonies', 'N-12'),
('Huvveck', 'Juris', 'Outer Rim Territories', 'O-17'),
('Hyabb', 'Krenher', 'Core Worlds', 'K-9'),
('Hyborea', 'Semagi', 'Mid Rim', 'I-16'),
('Hyder', 'Tarabba', 'Outer Rim Territories', 'M-19'),
('Hydra', 'Aparo (Catarlo)', 'Outer Rim Territories', 'R-3'),
('Hydraxia', NULL, 'Inner Rim', 'M-13'),
('Hyell', 'Vilonis', 'Mid Rim', 'O-16'),
('Hylaia', NULL, 'Inner Rim', 'O-9'),
('Hylobi', 'Taldot', 'Mid Rim', 'Q-8'),
('Hynah', 'Kalamith', 'Outer Rim Territories', 'P-5'),
('Hynestia', 'Hynestian', 'Colonies', 'J-13'),
('Hyperkarn', 'Grohl', 'Outer Rim Territories', 'R-16'),
('Hypori', 'Ferra', 'Outer Rim Territories', 'S-16'),
('Hypotria', 'Bortele', 'Mid Rim', 'S-8'),
('Hyrol Preen Beta', 'Portmoak', 'Outer Rim Territories', 'P-18'),
('Hysalria', 'Sluis', 'Outer Rim Territories', 'M-19'),
('Hythrope', 'Hythrope', 'Expansion Region', 'M-15'),
('I''vorcia Prime', 'Mieru''kar', 'Outer Rim Territories', 'O-4'),
('Iakar', 'Rseik', 'Outer Rim Territories', 'N-20'),
('Ianane', NULL, 'Wild Space', 'I-10'),
('Iast', 'Aldino', 'Mid Rim', 'J-17'),
('Ibaar', 'Jubilar', 'Outer Rim Territories', 'T-8'),
('Ibanjji', 'Mieru''kar', 'Outer Rim Territories', 'N-4'),
('Iceni', 'Corporate Sector', 'Outer Rim Territories', 'R-4'),
('Ichalin Station', 'Hijoian Space', 'Expansion Region', 'J-8'),
('Ichtor', 'Sombure', 'Mid Rim', 'K-16'),
('Icindra', 'Calamari', 'Outer Rim Territories', 'U-6'),
('Idaflor', 'Sarin', 'Outer Rim Territories', 'O-18'),
('Idolia', 'Halthor', 'Outer Rim Territories', 'M-6'),
('Iego', 'Ash Worlds', 'Outer Rim Territories', 'T-7'),
('Ifmix', NULL, 'Colonies', 'M-9'),
('Ifron', 'Thuris', 'Outer Rim Territories', 'P-18'),
('Ihopek', 'Mayagil', 'Outer Rim Territories', 'N-18'),
('Ikari', NULL, 'Wild Space', 'H-14'),
('Ikkrukk', 'Ryndellian', 'Mid Rim', 'P-17'),
('Ikon', 'Majoor', 'Expansion Region', 'N-15'),
('Iktotch', 'Narvath', 'Expansion Region', 'O-14'),
('Ilamna', 'Eucer', 'Mid Rim', 'Q-7'),
('Iliabath', 'Mortex', 'Outer Rim Territories', 'R-4'),
('Ilimardon', 'Nicandra', 'Mid Rim', 'L-7'),
('Illarreen', 'Herios', 'Outer Rim Territories', 'T-16'),
('Illmuth', 'Corellian', 'Core Worlds', 'M-11'),
('Illodia', 'Illodia', 'Core Worlds', 'K-13'),
('Illoud', 'Hali', 'Expansion Region', 'O-9'),
('Iloh', NULL, 'Inner Rim', 'N-9'),
('Ilos', 'Hutt Space', 'Outer Rim Territories', 'R-10'),
('Ilos Minor', 'Hutt Space', 'Outer Rim Territories', 'R-10'),
('Ilthan', NULL, 'Core Worlds', 'M-11'),
('Ilum', NULL, 'Unknown Regions', 'G-7'),
('Imberlin', 'Imberlin', 'Expansion Region', 'P-14'),
('Imdaar', 'Dantus', 'Outer Rim Territories', 'J-6'),
('Imerria', 'Immeria', 'Expansion Region', 'O-14'),
('Immalia', 'Immalia', 'Expansion Region', 'K-8'),
('Imram', 'Lannik Space', 'Mid Rim', 'R-13'),
('Imroosia', NULL, 'Inner Rim', 'N-9'),
('Imvur', 'Hertae', 'Mid Rim', 'Q-14'),
('Imynusoph', 'Kallea', 'Outer Rim Territories', 'J-21'),
('Inamorata, The', 'Bheriz', 'Outer Rim Territories', 'U-10'),
('Inat Prime', 'Quiberon', 'Outer Rim Territories', 'S-15'),
('Indellian', 'Javin (Yarith)', 'Outer Rim Territories', 'K-18'),
('Indoumodo', NULL, 'Wild Space', 'S-18'),
('Indu San', 'Rolion', 'Outer Rim Territories', 'Q-7'),
('Indupar', 'Ado', 'Mid Rim', 'M-17'),
('Ingo', 'Bortele', 'Mid Rim', 'R-8'),
('Injopan', 'Kessel', 'Outer Rim Territories', 'T-10'),
('Innton', 'Sluis', 'Outer Rim Territories', 'M-18'),
('Insk', NULL, 'Wild Space', 'P-3'),
('Insta', 'Majoor', 'Expansion Region', 'N-15'),
('Intran', 'Brak', 'Expansion Region', 'O-14'),
('Intuci', 'Abrion', 'Outer Rim Territories', 'S-15'),
('Inusagi', 'Vilonis', 'Mid Rim', 'O-16'),
('Inysh', NULL, 'Core Worlds', 'J-12'),
('Iokath', NULL, 'Unknown Regions', 'G-5'),
('Iol', NULL, 'Unknown Regions', 'I-10'),
('Ione', 'Javin (Anoat)', 'Outer Rim Territories', 'K-18'),
('Iope', NULL, 'Deep Core', 'L-10'),
('Iotra', 'Suolriep (Iotran Expanse)', 'Outer Rim Territories', 'S-8'),
('Ipellrilla', 'Glythe', 'Mid Rim', 'K-7'),
('Iphar', NULL, 'Inner Rim', 'L-14'),
('Iphigin', NULL, 'Core Worlds', 'L-13'),
('Ipsidon', 'Corthenia', 'Mid Rim', 'K-7'),
('Irff', 'Couronne', 'Expansion Region', 'P-10'),
('Iridia', 'Glythe', 'Mid Rim', 'J-7'),
('Iridium', 'Atrivis', 'Outer Rim Territories', 'L-5'),
('Iridonia', 'Glythe', 'Mid Rim', 'J-7'),
('Irith', 'Hutt Space', 'Outer Rim Territories', 'S-11'),
('Irkalla', NULL, 'Unknown Regions', 'G-13'),
('Irmenu', 'Belsmuth', 'Outer Rim Territories', 'O-6'),
('Irudiru', 'Wyl', 'Outer Rim Territories', 'S-4'),
('Iscera', 'Dalchon', 'Outer Rim Territories', 'R-17'),
('Iscno', NULL, 'Core Worlds', 'K-12'),
('Isde Naha', 'Javin (Yarith)', 'Outer Rim Territories', 'K-18'),
('Isen', 'D''Astan', 'Outer Rim Territories', 'N-5'),
('Iseno', 'Iseno', 'Inner Rim', 'N-13'),
('Ishanna', 'Circarpous', 'Expansion Region', 'O-12'),
('Ishbix', 'Agarix', 'Mid Rim', 'K-17'),
('Ishram Nebula', 'Seitia', 'Outer Rim Territories', 'J-20');