-- Add galactic systems from Linasals to Mapuzo (batch 5)
INSERT INTO galactic_systems (name, sector, region, grid_coordinates) VALUES
('Linasals', 'Mikaster', 'Expansion Region', 'N-15'),
('Linuri', 'Doldur', 'Mid Rim', 'P-15'),
('Lioaoi', 'Lioaoin Space', 'Unknown Regions', 'E-7'),
('Liok', 'Ciutric', 'Outer Rim Territories', 'N-5'),
('Lipsec', 'Koradin', 'Outer Rim Territories', 'I-18'),
('Lira San', NULL, 'Wild Space', 'O-20'),
('Lirra', 'Baxel', 'Outer Rim Territories', 'U-12'),
('Lisal', 'Sarka', 'Mid Rim', 'Q-8'),
('Liskan', 'Ojoster', 'Outer Rim Territories', 'N-7'),
('Lissam', 'Rayter', 'Outer Rim Territories', 'J-18'),
('Listehol', 'Kwymar', 'Outer Rim Territories', 'Q-4'),
('Listoria', 'Tapani', 'Colonies', 'L-13'),
('Little Atullus', 'Anthos', 'Inner Rim', 'N-8'),
('Little Capella', 'Gordian Reach', 'Outer Rim Territories', 'Q-6'),
('Little Kessel', 'Kessel', 'Outer Rim Territories', 'T-10'),
('Little Petrovi', 'Yushan', 'Mid Rim', 'K-17'),
('Little Talhovi', 'Juvex', 'Mid Rim', 'K-18'),
('Liul', 'Demetras', 'Outer Rim Territories', 'P-7'),
('Livien', 'Tion Hegemony', 'Outer Rim Territories', 'S-5'),
('Livno', NULL, 'Wild Space', 'J-21'),
('Livorno', 'Belderone', 'Outer Rim Territories', 'R-6'),
('Llanic', 'Karthakk', 'Outer Rim Territories', 'Q-16'),
('Llewebum', 'Rolion', 'Outer Rim Territories', 'Q-7'),
('Llon Nebulae', 'Itopol', 'Expansion Region', 'K-15'),
('Llorkan', NULL, 'Inner Rim', 'N-10'),
('Lo''Uran', 'Aparo', 'Outer Rim Territories', 'R-3'),
('Loac', 'Hocatar', 'Expansion Region', 'P-12'),
('Lobaoc', 'Mieru''kar', 'Outer Rim Territories', 'N-3'),
('Lobaq Station', 'Rolion', 'Outer Rim Territories', 'Q-7'),
('Loce', NULL, 'Wild Space', 'S-4'),
('Lockest', 'Palamut', 'Expansion Region', 'N-13'),
('Loedorvia', 'Weemell', 'Core Worlds', 'K-12'),
('Lofquar', 'Chommell', 'Mid Rim', 'O-17'),
('Logal Ri', 'Chaama', 'Mid Rim', 'J-7'),
('Lohopa', 'Boeus', 'Expansion Region', 'M-15'),
('Loj', NULL, 'Colonies', 'M-9'),
('Loken', 'Bryx', 'Mid Rim', 'R-7'),
('Lokondo', 'Braxant', 'Outer Rim Territories', 'J-3'),
('Lokori', 'Karthakk', 'Outer Rim Territories', 'Q-16'),
('Lokud', 'Chopani', 'Outer Rim Territories', 'L-3'),
('Lol', 'Lol', 'Outer Rim Territories', 'Q-18'),
('Lola Sayu', 'Belderone', 'Outer Rim Territories', 'R-6'),
('Lolet', 'Haserian', 'Mid Rim', 'Q-14'),
('Loletia', 'Ojoster', 'Outer Rim Territories', 'N-7'),
('Lolnar', NULL, 'Core Worlds', 'M-11'),
('Lomabu', 'Aida', 'Mid Rim', 'Q-13'),
('Lonania', 'Kossa', 'Expansion Region', 'O-11'),
('Lonatro', 'Veragi (Gree Enclave)', 'Outer Rim Territories', 'L-3'),
('Londor', 'Londori', 'Mid Rim', 'J-7'),
('Lonera', NULL, 'Inner Rim', 'O-12'),
('Long Shadow', 'Kallea', 'Outer Rim Territories', 'K-21'),
('Longwind', 'Trax', 'Mid Rim', 'Q-10'),
('Lonjair Prime', 'Danjar', 'Outer Rim Territories', 'M-19'),
('Lonnaw', 'Droma', 'Mid Rim', 'K-6'),
('Lontar', NULL, 'Colonies', 'J-9'),
('Loovria', 'Juvex', 'Mid Rim', 'L-18'),
('Loped', NULL, 'Inner Rim', 'O-9'),
('Lopor Station', 'Spirva', 'Mid Rim', 'K-17'),
('Loposi', 'Dustig', 'Mid Rim', 'M-17'),
('Lorahns', 'Sloo', 'Mid Rim', 'P-14'),
('Lorahns Cavity', 'Sloo', 'Mid Rim', 'P-14'),
('Lorardia', 'D''Astan', 'Outer Rim Territories', 'O-6'),
('Lorattick Nebula', 'Esstran', 'Outer Rim Territories', 'Q-5'),
('Loratus', 'Sanbra', 'Outer Rim Territories', 'O-17'),
('Lorell', NULL, 'Inner Rim', 'O-9'),
('Lorenz', 'Tapani', 'Colonies', 'L-13'),
('Loreth', 'Saijo', 'Outer Rim Territories', 'K-20'),
('Loretto', NULL, 'Core Worlds', 'M-11'),
('Lorimax', 'Fakir', 'Colonies', 'K-9'),
('Lorista', 'Glythe', 'Mid Rim', 'J-7'),
('Lorn', 'Dalchon', 'Outer Rim Territories', 'R-17'),
('Loronar', NULL, 'Colonies', 'M-12'),
('Lorpfan', 'Tynquay', 'Outer Rim Territories', 'R-4'),
('Lorrd', 'Kanz', 'Outer Rim Territories', 'N-4'),
('Lorta', 'Gendius', 'Mid Rim', 'J-17'),
('Lost Clusters', NULL, 'Wild Space', 'I-20'),
('Lost Murvey', NULL, 'Wild Space', 'H-6'),
('Lost Souls', 'Cademimu', 'Outer Rim Territories', 'L-6'),
('Lota', 'Brak', 'Expansion Region', 'O-14'),
('Loth', NULL, 'Inner Rim', 'J-8'),
('Lothal', 'Lothal', 'Outer Rim Territories', 'U-7'),
('Lotho Minor', 'Wazta', 'Outer Rim Territories', 'I-17'),
('Lotide', 'Mortex', 'Outer Rim Territories', 'S-5'),
('Lovetus', NULL, 'Core Worlds', 'L-9'),
('Lovola', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Low''n', 'Romintine', 'Mid Rim', 'Q-8'),
('Lower Flora Cloud', NULL, 'Inner Rim', 'I-15'),
('Lowick', 'Calaron', 'Outer Rim Territories', 'U-9'),
('Lowik', 'Cadavine', 'Outer Rim Territories', 'P-17'),
('Lozash', 'Bes Ber Bikade', 'Expansion Region', 'L-15'),
('Lubang Minor', 'Illisurevimurasi', 'Outer Rim Territories', 'Q-4'),
('Lucazec', 'Nuiri', 'Outer Rim Territories', 'Q-6'),
('Lucrenn', 'Skine', 'Outer Rim Territories', 'Q-19'),
('Lucrusia', 'Seswenna', 'Outer Rim Territories', 'M-18'),
('Luduria', NULL, 'Colonies', 'M-12'),
('Luj', 'Tamarin', 'Outer Rim Territories', 'N-19'),
('Lujo', NULL, 'Core Worlds', 'L-12'),
('Luminous Magnificence', NULL, 'Wild Space', 'H-14'),
('Lupal', NULL, 'Wild Space', 'G-20'),
('Lupani', 'Tapani', 'Colonies', 'L-13'),
('Luprora', NULL, 'Unknown Regions', 'G-7'),
('Luptoom', 'Seswenna', 'Outer Rim Territories', 'M-18'),
('Lur', 'Aparo', 'Outer Rim Territories', 'R-4'),
('Lurania', NULL, 'Colonies', 'N-10'),
('Luristan', NULL, 'Inner Rim', 'M-14'),
('Lurr', 'Rayter', 'Outer Rim Territories', 'J-19'),
('Lusaanda', 'Meram', 'Outer Rim Territories', 'O-4'),
('Lusdu', 'Alderaan', 'Core Worlds', 'M-10'),
('Lusk', 'Tapani', 'Colonies', 'L-13'),
('Lust', NULL, 'Wild Space', 'J-20'),
('Lutrillia', 'Javin (Yarith)', 'Outer Rim Territories', 'J-18'),
('Luudria', 'Dalchon', 'Outer Rim Territories', 'R-17'),
('Luuhar', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Luuq', 'Luuq', 'Mid Rim', 'L-7'),
('Luxiar', 'Bon''nyuw-Luq', 'Outer Rim Territories', 'N-18'),
('Lwhekk', 'Ssi-ruuvi Space', 'Unknown Regions', 'C-16'),
('Lybeya', 'Bajic', 'Outer Rim Territories', 'P-18'),
('Lyjdaa', 'Kwymar', 'Outer Rim Territories', 'Q-4'),
('Lynos', 'Mortex', 'Outer Rim Territories', 'R-4'),
('Lynx', 'Tapani', 'Colonies', 'L-13'),
('Lyran', 'Quiberon', 'Outer Rim Territories', 'S-15'),
('Lysatra', NULL, 'Wild Space', 'I-8'),
('Lythia', 'Suolriep', 'Outer Rim Territories', 'S-8'),
('Lythos', 'Corporate Sector', 'Outer Rim Territories', 'S-3'),
('M''Bardi', 'Kalamith', 'Outer Rim Territories', 'P-5'),
('M''dweshuu Nova', NULL, 'Hutt Space', 'S-9'),
('M''haeli', 'Majoor', 'Expansion Region', 'N-15'),
('M''Hanna', NULL, 'Hutt Space', 'T-11'),
('M132L4', NULL, 'Inner Rim', 'K-8'),
('M2934738', 'Tragan Cluster', 'Outer Rim Territories', 'N-5'),
('M4-78', NULL, 'Inner Rim', 'O-9'),
('Ma''alkerr', 'Rago', 'Mid Rim', 'I-7'),
('Ma''ar Shaddam', 'Rseik', 'Outer Rim Territories', 'N-20'),
('Maarka', 'Perkell', 'Mid Rim', 'Q-7'),
('Maateen', NULL, 'Inner Rim', 'O-10'),
('Maccent', 'Phelleem', 'Outer Rim Territories', 'S-7'),
('Mackar', 'Hewett', 'Mid Rim', 'M-6'),
('Madurs', 'Maldrood', 'Mid Rim', 'R-7'),
('Maelstrom Nebula', 'Relgim', 'Outer Rim Territories', 'K-5'),
('Maerdocia', 'Maerdocian', 'Mid Rim', 'Q-13'),
('Magagran', 'Halthor', 'Outer Rim Territories', 'L-6'),
('Magar''s World', 'Stensen', 'Outer Rim Territories', 'H-17'),
('Magataran', 'Maelstrom', 'Inner Rim', 'N-7'),
('Magaveene', 'Prefsbelt', 'Outer Rim Territories', 'K-6'),
('Magmar', NULL, 'Core Worlds', 'M-10'),
('Magna', NULL, 'Wild Space', 'G-14'),
('Magnus Horn', 'Talcene', 'Mid Rim', 'Q-8'),
('Magravia', 'Karthakk', 'Outer Rim Territories', 'Q-17'),
('Maher', NULL, 'Unknown Regions', 'G-7'),
('Mahranee', 'Taldot', 'Mid Rim', 'P-8'),
('Maicombe', 'Corthenia', 'Mid Rim', 'K-7'),
('Maill', 'Cadavine', 'Outer Rim Territories', 'P-17'),
('Mairenhelm', 'Dona Laza', 'Expansion Region', 'P-9'),
('Maires', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Mairne', 'Kathol', 'Outer Rim Territories', 'M-21'),
('Majilop', 'Lol', 'Outer Rim Territories', 'Q-18'),
('Majoor', 'Majoor', 'Expansion Region', 'N-15'),
('Majoros', NULL, 'Inner Rim', 'O-8'),
('Makeb', 'Aida', 'Mid Rim', 'Q-13'),
('Makem Te', 'Nilgaard', 'Outer Rim Territories', 'S-5'),
('Makksre', 'Uoti', 'Core Worlds', 'K-9'),
('Mako-Ta', 'Noonian', 'Outer Rim Territories', 'M-6'),
('Makthierse', 'Cegul', 'Outer Rim Territories', 'L-20'),
('Malachor', 'Chorlian', 'Outer Rim Territories', 'S-4'),
('Maladi', 'Maladi', 'Expansion Region', 'O-12'),
('Malador', 'Juvex', 'Mid Rim', 'L-17'),
('Malaga Cluster', 'Steniplis', 'Outer Rim Territories', 'L-19'),
('Malagarr', NULL, 'Wild Space', 'V-8'),
('Malano', NULL, 'Colonies', 'N-10'),
('Malanose', 'Veragi (Gree Enclave)', 'Outer Rim Territories', 'K-2'),
('Malari', 'Churnis', 'Mid Rim', 'I-6'),
('Malastare', 'Dustig', 'Mid Rim', 'N-16'),
('Malathon', 'Ghost Nebula', 'Expansion Region', 'P-10'),
('Maldo Kreis', 'Arkanis', 'Outer Rim Territories', 'R-16'),
('Maldovea', 'Brema', 'Outer Rim Territories', 'M-17'),
('Maldra', 'Shadola', 'Outer Rim Territories', 'U-8'),
('Maldroth', 'Grumani', 'Outer Rim Territories', 'N-17'),
('Maleinator', 'Great Agash', 'Expansion Region', 'K-15'),
('Malenko', 'Eidoloni', 'Mid Rim', 'L-16'),
('Malian', NULL, 'Expansion Region', 'I-14'),
('Malicar', 'Mieru''kar', 'Outer Rim Territories', 'N-4'),
('Malkii', 'Mortex', 'Outer Rim Territories', 'S-5'),
('Mall''ordian', 'Corporate Sector', 'Outer Rim Territories', 'R-3'),
('Malloran', 'Garis', 'Outer Rim Territories', 'N-18'),
('Malo', 'Sluis', 'Outer Rim Territories', 'M-19'),
('Malpassia', NULL, 'Core Worlds', 'L-10'),
('Malpaz', 'Wazta', 'Outer Rim Territories', 'I-17'),
('Malrev', 'Thrasybule', 'Outer Rim Territories', 'P-6'),
('Malsuum', NULL, 'Inner Rim', 'L-14'),
('Maltha Obex', 'Mieru''kar', 'Outer Rim Territories', 'O-3'),
('Malthor', 'Tandon', 'Mid Rim', 'Q-14'),
('Maltorian', 'Lifh', 'Mid Rim', 'R-8'),
('Maltorra', NULL, 'Core Worlds', 'M-12'),
('Malus', 'Gaulus', 'Outer Rim Territories', 'S-17'),
('Mamendin', 'Farrfin', 'Core Worlds', 'K-9'),
('Mamkoda', 'Cassander', 'Outer Rim Territories', 'L-5'),
('Manaan', NULL, 'Inner Rim', 'O-11'),
('Manakron', 'Tashtor', 'Mid Rim', 'I-16'),
('Manali', 'Imberlin', 'Expansion Region', 'P-14'),
('Manari', 'Brevost', 'Expansion Region', 'O-15'),
('Manaxia', NULL, 'Core Worlds', 'M-10'),
('Manda', 'Manda', 'Mid Rim', 'R-15'),
('Mandalore', 'Mandalore', 'Outer Rim Territories', 'O-7'),
('Mandell', 'Bothan', 'Mid Rim', 'R-14'),
('Mandellia', 'Nuiri', 'Outer Rim Territories', 'Q-7'),
('Mandrine', 'Kessel', 'Outer Rim Territories', 'T-10'),
('Manella', NULL, 'Core Worlds', 'M-9'),
('Manforgon', 'Senex', 'Mid Rim', 'L-17'),
('Mangan', NULL, 'Colonies', 'J-9'),
('Mangez', 'Brak', 'Expansion Region', 'O-14'),
('Mannius', NULL, 'Wild Space', 'I-14'),
('Mannova', 'Gordian Reach', 'Outer Rim Territories', 'Q-5'),
('Manoe', 'Manoe', 'Mid Rim', 'K-7'),
('Manpha', 'Seitia', 'Outer Rim Territories', 'K-20'),
('Manress', NULL, 'Inner Rim', 'N-9'),
('Mantan', 'Calamari', 'Outer Rim Territories', 'U-6'),
('Mantarran', NULL, 'Inner Rim', 'L-14'),
('Mantessa', 'Orus', 'Inner Rim', 'M-8'),
('Mantilorr', 'Suolriep', 'Outer Rim Territories', 'S-10'),
('Mantooine', 'Atrivis', 'Outer Rim Territories', 'L-5'),
('Manwess', 'Kilbanis', 'Colonies', 'N-9'),
('Maphus Tria', 'Cadma', 'Outer Rim Territories', 'T-8'),
('Mapuzo', 'Hollan', 'Mid Rim', 'M-7')
ON CONFLICT (name) DO NOTHING;