-- Insert next batch of galactic systems (Isht to Kanaver)
INSERT INTO galactic_systems (name, sector, region, grid_coordinates) VALUES
('Isht', NULL, 'Core Worlds', 'L-13'),
('Isiring', 'Cassander (Tendrannan)', 'Outer Rim Territories', 'L-5'),
('Iska', 'Iska', 'Mid Rim', 'K-17'),
('Iskallon', NULL, 'Wild Space', 'H-14'),
('Iskalon', 'Trans-Nebular', 'Mid Rim', 'R-16'),
('Iskin', 'Iskin', 'Mid Rim', 'O-16'),
('Ison', 'Javin (Anoat)', 'Outer Rim Territories', 'K-18'),
('Issagra', 'Corporate Sector', 'Outer Rim Territories', 'S-4'),
('Issor', 'Arkanis', 'Outer Rim Territories', 'R-17'),
('Istic', 'Teraab', 'Mid Rim', 'Q-11'),
('Italbos', 'Halori', 'Mid Rim', 'Q-7'),
('Itani', NULL, 'Inner Rim', 'N-14'),
('Itani Nebula', NULL, 'Inner Rim', 'N-14'),
('Itapi Prime', NULL, 'Core Worlds', 'L-9'),
('Ithica', NULL, 'Inner Rim', 'K-14'),
('Ithor', 'Ottega', 'Mid Rim', 'M-6'),
('Ithori', 'Ado', 'Mid Rim', 'M-17'),
('Ithull', 'Airon', 'Inner Rim', 'O-10'),
('Iti', 'Tammuz', 'Outer Rim Territories', 'T-14'),
('Ivarujar', 'Vensensor', 'Expansion Region', 'K-16'),
('Ivatch', 'Kathol', 'Outer Rim Territories', 'M-21'),
('Ivera', NULL, 'Core Worlds', 'L-12'),
('Ivexia', 'Tennuutta', 'Mid Rim', 'Q-7'),
('Ividal', 'Ividal', 'Mid Rim', 'P-14'),
('Ivis', NULL, 'Inner Rim', 'N-10'),
('Ixilix', 'Japrael', 'Inner Rim', 'O-9'),
('Ixtlar', 'Ixtlar', 'Core Worlds', 'L-10'),
('Ixzinia', 'Agarix', 'Mid Rim', 'K-17'),
('Iyred', 'Kibilini', 'Outer Rim Territories', 'Q-17'),
('Iyuta', 'Fakir', 'Colonies', 'K-9'),
('J''doytzin', 'Maldrood', 'Mid Rim', 'R-7'),
('J''t''p''tan', 'Farlax', 'Core Worlds', 'K-10'),
('Ja-bess', 'Tragan Cluster', 'Outer Rim Territories', 'N-5'),
('Jaatovi', NULL, 'Inner Rim', 'N-14'),
('Jabiim', 'Phelleem', 'Outer Rim Territories', 'S-7'),
('Jabone', 'Tennuutta', 'Mid Rim', 'Q-7'),
('Jabor', 'Ado', 'Mid Rim', 'M-17'),
('Jaciprus', NULL, 'Core Worlds', 'M-11'),
('Jaelen', 'Irishi', 'Mid Rim', 'K-6'),
('Jaemus', 'Obtrexta', 'Outer Rim Territories', 'K-4'),
('Jafan', 'Chommell', 'Mid Rim', 'O-16'),
('Jaga''s Cluster', 'Esstran', 'Outer Rim Territories', 'Q-5'),
('Jagomir', 'Esstran', 'Outer Rim Territories', 'Q-5'),
('Jaguada', 'Esstran (Sith Worlds)', 'Outer Rim Territories', 'R-5'),
('Jahilid', NULL, 'Wild Space', 'L-21'),
('Jakelia', 'Mandalore', 'Outer Rim Territories', 'O-7'),
('Jakku', NULL, 'Inner Rim', 'I-13'),
('Jalarren', 'Senex', 'Mid Rim', 'L-18'),
('Jalin', NULL, 'Core Worlds', 'M-11'),
('Jalindi', 'Gordian Reach', 'Outer Rim Territories', 'P-6'),
('Jaloria', 'Jalor', 'Mid Rim', 'J-7'),
('Jalucaz', 'Subterrel', 'Outer Rim Territories', 'L-20'),
('Jaminere', 'Allied Tion', 'Outer Rim Territories', 'S-6'),
('Jamiri', 'Myto', 'Outer Rim Territories', 'K-4'),
('Jamiron', 'Chiss Space', 'Unknown Regions', 'F-8'),
('Janako', NULL, 'Inner Rim', 'N-11'),
('Janara', NULL, 'Inner Rim', 'L-14'),
('Jandolhoon', 'Bosph', 'Outer Rim Territories', 'Q-3'),
('Jandoon', 'Corva', 'Outer Rim Territories', 'P-4'),
('Jandur', NULL, 'Inner Rim', 'J-14'),
('JanFathal', 'Fath', 'Outer Rim Territories', 'K-6'),
('Jangelle', 'Kathol (Outback)', 'Outer Rim Territories', 'M-21'),
('Janguine', 'Halthor', 'Outer Rim Territories', 'L-6'),
('Janilis', 'Cronese Mandate', 'Outer Rim Territories', 'S-6'),
('Jankok', 'Bozhnee', 'Outer Rim Territories', 'L-18'),
('Janodral Mizar', 'Indrexu', 'Outer Rim Territories', 'S-5'),
('Jante', 'Esaga', 'Mid Rim', 'Q-11'),
('Japai', 'Yushan', 'Mid Rim', 'K-17'),
('Japeal', 'Kanz', 'Outer Rim Territories', 'N-4'),
('Jappe', 'Tapani', 'Colonies', 'L-13'),
('Jarbanov', 'Serathrace', 'Expansion Region', 'P-11'),
('Jardeen', 'Trans-Jardeen', 'Expansion Region', 'K-16'),
('Jaresh', 'Corva', 'Outer Rim Territories', 'P-4'),
('Jargridia', 'Sprizen', 'Outer Rim Territories', 'N-5'),
('Jarnollen', 'Bright Jewel', 'Mid Rim', 'L-7'),
('Jarsatt', 'Hakartha', 'Expansion Region', 'L-16'),
('Jarvanam', 'Astal', 'Outer Rim Territories', 'P-17'),
('Jastro', NULL, 'Core Worlds', 'M-10'),
('Jatir', NULL, 'Colonies', 'L-9'),
('Javarica', 'Tynquay', 'Outer Rim Territories', 'Q-4'),
('Javin', 'Javin', 'Outer Rim Territories', 'K-18'),
('Javis', 'Tapani', 'Colonies', 'L-13'),
('Jaxus', NULL, 'Core Worlds', 'M-10'),
('Jaymir', NULL, 'Mid Rim', 'I-16'),
('Jazbina', 'Lostar', 'Expansion Region', 'M-8'),
('Jebble', 'Ojoster', 'Outer Rim Territories', 'N-7'),
('Jedd', NULL, 'Wild Space', 'I-14'),
('Jedha', 'Terrabe', 'Mid Rim', 'H-10'),
('Jekara', 'Bryx', 'Mid Rim', 'R-7'),
('Jelucan', 'Kwymar', 'Outer Rim Territories', 'Q-4'),
('Jendar', 'Nembus', 'Outer Rim Territories', 'P-4'),
('Jendiria', 'Maldrood', 'Mid Rim', 'R-7'),
('Jendorn', 'Farstey', 'Expansion Region', 'O-8'),
('Jenenma', NULL, 'Inner Rim', 'M-13'),
('Jenoport', NULL, 'Colonies', 'M-9'),
('Jentares', 'Mieru''kar', 'Outer Rim Territories', 'N-3'),
('Jeosyn', 'Weneen', 'Outer Rim Territories', 'N-6'),
('Jereth', 'Bozhnee', 'Outer Rim Territories', 'L-18'),
('Jerijador', 'Calaron', 'Outer Rim Territories', 'T-9'),
('Jermac', 'Portmoak', 'Outer Rim Territories', 'P-18'),
('Jerne', 'Kanz', 'Outer Rim Territories', 'N-4'),
('Jerrilek', NULL, 'Deep Core', 'L-10'),
('Jerrist', 'Corporate Sector', 'Outer Rim Territories', 'S-4'),
('Jestan', 'Corpheli', 'Expansion Region', 'M-7'),
('Jevelet', NULL, 'Core Worlds', 'K-10'),
('Jexeria', 'Tharin', 'Outer Rim Territories', 'T-8'),
('Jeyell', 'Roche', 'Mid Rim', 'Q-8'),
('Jhantoria', 'Allied Tion', 'Outer Rim Territories', 'S-6'),
('Jhensrus', 'Trax', 'Mid Rim', 'Q-10'),
('Jhosh', 'Albarrio', 'Outer Rim Territories', 'K-5'),
('Jiaan', 'Almak', 'Mid Rim', 'J-17'),
('Jidlor', 'Jidlor Marches', 'Mid Rim', 'J-16'),
('Jillsaaria', 'Minos Cluster', 'Outer Rim Territories', 'M-20'),
('Jilrua', 'Hutt Space', 'Outer Rim Territories', 'R-12'),
('Jinda', 'Tapani', 'Colonies', 'L-13'),
('Jindau Station', NULL, 'Inner Rim', 'L-15'),
('Jinet', 'Brak', 'Expansion Region', 'O-14'),
('Jiran', 'Dantus', 'Outer Rim Territories', 'J-6'),
('Jiroch', 'Yushan', 'Mid Rim', 'K-17'),
('Jiruus', 'Rolion', 'Outer Rim Territories', 'P-7'),
('Jjannex', 'Jjannex', 'Outer Rim Territories', 'L-19'),
('Jmin', 'Masla', 'Mid Rim', 'J-16'),
('Jocal', 'Ghost Nebula', 'Expansion Region', 'P-10'),
('Jodaka', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Jofoger', 'Tharin (Periphery)', 'Outer Rim Territories', 'S-8'),
('Joh''Cire', 'Alui', 'Mid Rim', 'N-17'),
('Johria', NULL, 'Core Worlds', 'M-11'),
('Joiol', 'Orus', 'Inner Rim', 'M-8'),
('Jolia', 'Eucer', 'Mid Rim', 'Q-7'),
('Jomark', 'Jospro', 'Outer Rim Territories', 'R-7'),
('Jondora', 'Ojoster (Taris)', 'Outer Rim Territories', 'N-7'),
('Jonsior', NULL, 'Core Worlds', 'L-10'),
('Joodrudda', NULL, 'Wild Space', 'S-4'),
('Joralla', 'Mektrun', 'Mid Rim', 'L-17'),
('Joran Station', 'Rolion', 'Outer Rim Territories', 'P-7'),
('Jorgan', 'D''Astan', 'Outer Rim Territories', 'O-5'),
('Joruna', 'Farlax', 'Core Worlds', 'K-10'),
('Jostaar', 'Kibilini', 'Outer Rim Territories', 'Q-17'),
('Jovan', 'Gordian Reach', 'Outer Rim Territories', 'P-6'),
('Jovaria', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Jubalene', 'Grumani', 'Outer Rim Territories', 'N-17'),
('Jubilar', 'Jubilar', 'Outer Rim Territories', 'T-7'),
('Judakann', 'Torch Nebula', 'Outer Rim Territories', 'P-18'),
('Julio', 'Marcol', 'Inner Rim', 'L-8'),
('Julsujod', 'Tolonda', 'Outer Rim Territories', 'Q-17'),
('Juma', 'Dalchon', 'Outer Rim Territories', 'R-17'),
('Jumeria', NULL, 'Core Worlds', 'M-10'),
('Jumus', 'Corellian', 'Core Worlds', 'M-11'),
('Junction', 'Vorc', 'Mid Rim', 'J-7'),
('Junction', 'Thesme', 'Outer Rim Territories', 'O-5'),
('Junkfort Station', 'Tharin', 'Outer Rim Territories', 'T-8'),
('Junobia', 'Keldrath', 'Outer Rim Territories', 'T-6'),
('Juntar', 'Emmo', 'Core Worlds', 'M-12'),
('Jurio', 'Corva', 'Outer Rim Territories', 'P-4'),
('Jurzan', 'Jurzan', 'Expansion Region', 'M-15'),
('Jurzuu', 'Suolriep', 'Outer Rim Territories', 'S-8'),
('Jussafet', 'Weneen', 'Outer Rim Territories', 'N-6'),
('Jutrand', 'Grumani', 'Outer Rim Territories', 'M-17'),
('Juvex', 'Juvex', 'Mid Rim', 'L-18'),
('Juzzia', NULL, 'Inner Rim', 'N-8'),
('Jweab', 'Locris', 'Expansion Region', 'O-8'),
('K''ath', 'Juvex', 'Mid Rim', 'L-18'),
('k''Farri', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('K''taktaxka', NULL, 'Inner Rim', 'J-14'),
('Ka''Dedus', 'Tharin (Periphery)', 'Outer Rim Territories', 'S-8'),
('Kaa', NULL, 'Colonies', 'N-10'),
('Kaal', 'Yushan', 'Mid Rim', 'K-17'),
('Kabaira', 'Bajic', 'Outer Rim Territories', 'P-17'),
('Kabal', 'Mayagil', 'Outer Rim Territories', 'N-18'),
('Kabieroun', 'Nijune', 'Outer Rim Territories', 'O-4'),
('Kaboryth Cluster', 'Thaere', 'Expansion Region', 'O-14'),
('Kabray', 'Corweillian', 'Mid Rim', 'P-15'),
('Kadavo', NULL, 'Wild Space', 'S-4'),
('Kaddak', 'Tammuz', 'Outer Rim Territories', 'T-14'),
('Kaderin', 'Wazta', 'Outer Rim Territories', 'J-18'),
('Kadril', 'Thanium', 'Outer Rim Territories', 'R-6'),
('Kaelen', NULL, 'Inner Rim', 'M-9'),
('Kaelinn', 'Corbett', 'Mid Rim', 'I-17'),
('Kafane', 'Hutt Space', 'Outer Rim Territories', 'S-9'),
('Kaikielius', NULL, 'Core Worlds', 'L-10'),
('Kail', 'Corporate Sector', 'Outer Rim Territories', 'R-3'),
('Kailion', 'Kailion', 'Expansion Region', 'O-13'),
('Kailor', NULL, 'Core Worlds', 'L-10'),
('Kaisa', 'Corva', 'Outer Rim Territories', 'P-3'),
('Kajim', 'Locris', 'Expansion Region', 'O-8'),
('Kakra', NULL, 'Wild Space', 'I-14'),
('Kal''Shebbol', 'Kathol', 'Outer Rim Territories', 'M-21'),
('Kalaan', 'Churnis', 'Mid Rim', 'J-7'),
('Kalab', 'Sluis', 'Outer Rim Territories', 'M-19'),
('Kalandis', 'Pallis', 'Inner Rim', 'N-14'),
('Kalarassi', NULL, 'Inner Rim', 'K-8'),
('Kalarba', 'Hevvrol', 'Mid Rim', 'P-15'),
('Kalastar', NULL, 'Outer Rim Territories', 'I-20'),
('Kaldar Trinary', 'Chopani', 'Outer Rim Territories', 'M-4'),
('Kalee', NULL, 'Wild Space', 'J-4'),
('Kalgo', 'Senex', 'Mid Rim', 'L-18'),
('Kalidorn', NULL, 'Wild Space', 'O-20'),
('Kaliida Nebula', 'Juris', 'Outer Rim Territories', 'O-17'),
('Kalinda', 'Vilonis', 'Mid Rim', 'O-16'),
('Kalishik', 'Gordian Reach', 'Outer Rim Territories', 'Q-6'),
('Kaliska', 'Sombure', 'Mid Rim', 'K-17'),
('Kalist', NULL, 'Deep Core', 'K-12'),
('Kalki Nebula', 'Cassander (Tendrannan)', 'Outer Rim Territories', 'L-5'),
('Kalkovak', 'Bortele', 'Mid Rim', 'S-8'),
('Kalla', 'Corporate Sector', 'Outer Rim Territories', 'S-4'),
('Kallakea', 'Authala', 'Expansion Region', 'P-12'),
('Kaller', 'Cassander', 'Outer Rim Territories', 'K-5'),
('Kallidah', 'Subterrel', 'Outer Rim Territories', 'L-20'),
('Kallistas', 'Parmel', 'Outer Rim Territories', 'O-18'),
('Kaloom', 'Noonian', 'Outer Rim Territories', 'M-6'),
('Kalsunor', 'Esstran (Sith Worlds)', 'Outer Rim Territories', 'R-4'),
('Kalzeron', 'Bri''ahl', 'Outer Rim Territories', 'I-17'),
('Kamar', NULL, 'Wild Space', 'S-3'),
('Kamasto', 'Grumani', 'Outer Rim Territories', 'M-17'),
('Kamdon', 'Calamari', 'Outer Rim Territories', 'U-7'),
('Kamgeddon', 'Harron', 'Expansion Region', 'O-12'),
('Kamil', NULL, 'Wild Space', 'J-6'),
('Kammia', NULL, 'Wild Space', 'G-16'),
('Kamori', NULL, 'Core Worlds', 'M-11'),
('Kamparas', 'Dolomar', 'Core Worlds', 'K-9'),
('Kampe', NULL, 'Deep Core', 'L-11'),
('Kamper', 'Tapani', 'Colonies', 'L-13'),
('Kamur', 'Senex', 'Mid Rim', 'L-18'),
('Kanaver', 'Tion Hegemony', 'Outer Rim Territories', 'S-5');