-- Insert galactic systems from Targappia to Tinuvia
INSERT INTO public.galactic_systems (name, sector, region, grid_coordinates) VALUES
('Targappia', NULL, 'Colonies', 'N-12'),
('Targarth', 'Corosi', 'Outer Rim Territories', 'M-6'),
('Targonn', NULL, 'Outer Rim Territories', 'U-7'),
('Tarhassan', 'Harron', 'Expansion Region', 'O-11'),
('Taria', 'Lifh', 'Mid Rim', 'R-8'),
('Taris', 'Ojoster (Taris)', 'Outer Rim Territories', 'N-7'),
('Tarivo', 'Lantillian', 'Mid Rim', 'P-9'),
('Tarkenia', 'Karthakk', 'Outer Rim Territories', 'Q-17'),
('Tarlandia', NULL, 'Core Worlds', 'L-9'),
('Tarmidia', 'Kailion', 'Expansion Region', 'O-13'),
('Tarn', 'Doldur', 'Mid Rim', 'P-15'),
('Tarnith', 'Ojoster', 'Outer Rim Territories', 'N-7'),
('Tarnoonga', 'Arkanis', 'Outer Rim Territories', 'R-17'),
('Tarolax', 'Jidlor Marches', 'Mid Rim', 'I-15'),
('Taronda', 'Corbett', 'Mid Rim', 'I-17'),
('Taroon', 'Rseik', 'Outer Rim Territories', 'N-20'),
('Tarsa', 'D''Aelgoth', 'Mid Rim', 'L-17'),
('Tarshan', 'Maerdocian', 'Mid Rim', 'Q-12'),
('Tarsunt', 'Bothan', 'Mid Rim', 'R-14'),
('Tartaglia', 'Hollan', 'Mid Rim', 'M-7'),
('Tartaria', 'Alderaan', 'Core Worlds', 'M-10'),
('Tas-La', NULL, 'Hutt Space', 'S-9'),
('Tasariq', NULL, 'Inner Rim', 'J-14'),
('Tascollan Nebula', 'Abrion', 'Outer Rim Territories', 'S-15'),
('Tashtor Seneca', 'Tashtor', 'Mid Rim', 'J-16'),
('Taskeed', 'Tharin', 'Outer Rim Territories', 'S-7'),
('Taspir', 'Dynali', 'Outer Rim Territories', 'J-3'),
('Tasrin', NULL, 'Colonies', 'N-10'),
('Tassahondee Station', 'Parmel', 'Outer Rim Territories', 'O-18'),
('Tassar', 'D''Astan', 'Outer Rim Territories', 'P-5'),
('Tassio Moon', 'Kuat', 'Core Worlds', 'M-10'),
('Tastiged', 'Oricho', 'Outer Rim Territories', 'M-6'),
('Tatooine', 'Arkanis', 'Outer Rim Territories', 'R-16'),
('Tauber', 'Jaso', 'Inner Rim', 'L-14'),
('Tavitz', 'Tapani', 'Colonies', 'L-13'),
('Tavya', 'Tapani', 'Colonies', 'L-13'),
('Taw Provode', 'Nuiri', 'Outer Rim Territories', 'Q-6'),
('Tawl', 'Tungra', 'Outer Rim Territories', 'K-18'),
('Tay''ah''loo', 'Elbaran', 'Mid Rim', 'J-17'),
('Tazan', 'Merthian', 'Expansion Region', 'N-13'),
('Tcoleet', NULL, 'Colonies', 'N-10'),
('TD-10036-EM-1271', 'Montitian Grant', 'Expansion Region', 'J-15'),
('Te Hasa', 'Veragi (Gree Enclave)', 'Outer Rim Territories', 'K-2'),
('Teagan', 'Kwymar', 'Outer Rim Territories', 'Q-4'),
('Teardrop', 'Shelsha', 'Colonies', 'M-9'),
('Tebru', 'Juris', 'Outer Rim Territories', 'P-17'),
('Tedel', 'Ehosiq', 'Expansion Region', 'L-8'),
('Tedonia', 'Khuiumin', 'Outer Rim Territories', 'O-18'),
('Teedio', 'Auril', 'Outer Rim Territories', 'R-7'),
('Teevan', 'Kalamith', 'Outer Rim Territories', 'P-5'),
('Tefau', 'Suolriep', 'Outer Rim Territories', 'S-9'),
('Tegrat', 'Koradin', 'Outer Rim Territories', 'J-18'),
('Teh''Jar', 'Minos Cluster', 'Outer Rim Territories', 'M-20'),
('Tehar', NULL, 'Mid Rim', 'I-7'),
('Tei-Untis', NULL, 'Core Worlds', 'K-10'),
('Teirasa', 'Iskin', 'Mid Rim', 'O-16'),
('Teklos', NULL, 'Inner Rim', 'L-14'),
('Tekurr''k', 'Senex', 'Mid Rim', 'L-18'),
('Tel Halthor', NULL, 'Outer Rim Territories', 'L-6'),
('Tel Minor', 'Brak', 'Expansion Region', 'O-14'),
('Telanka', 'Svivreni', 'Outer Rim Territories', 'O-19'),
('Telaris', 'Pakuuni', 'Outer Rim Territories', 'T-6'),
('Telepan', NULL, 'Core Worlds', 'M-11'),
('Telerath', NULL, 'Inner Rim', 'N-7'),
('Teljkon', 'Kossa', 'Expansion Region', 'O-11'),
('Telkadis', 'Greater Plooriod', 'Expansion Region', 'M-7'),
('Telkur Station', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Tellanada', 'Bruanii', 'Mid Rim', 'K-18'),
('Tellanroaeg', 'Gaulus', 'Outer Rim Territories', 'S-17'),
('Tellik', NULL, 'Inner Rim', 'N-7'),
('Tellivar', NULL, 'Colonies', 'M-9'),
('Teloc Ol-sen', 'Eclorar', 'Mid Rim', 'Q-12'),
('Telos', 'Kwymar', 'Outer Rim Territories', 'Q-4'),
('Telti', NULL, 'Inner Rim', 'N-10'),
('Temako', 'Antemeridian', 'Outer Rim Territories', 'R-7'),
('Temesher', 'Lantillian', 'Mid Rim', 'P-9'),
('Tempes', 'Atravis', 'Outer Rim Territories', 'L-20'),
('Tenara', 'Gordian Reach', 'Outer Rim Territories', 'Q-6'),
('Tendo', 'Quess', 'Mid Rim', 'N-17'),
('Tenoo', 'Bri''ahl', 'Outer Rim Territories', 'I-17'),
('Tensor', NULL, 'Core Worlds', 'M-10'),
('Tentator', NULL, 'Colonies', 'L-9'),
('Tentraxis', NULL, 'Inner Rim', 'N-9'),
('Tentrix', 'Baroli', 'Expansion Region', 'N-15'),
('Tenupe', NULL, 'Wild Space', 'I-8'),
('Tepasi', 'Tagge Space', 'Core Worlds', 'L-9'),
('Teptixii', NULL, 'Unknown Regions', 'I-4'),
('Ter Abbes', 'Locris', 'Expansion Region', 'O-8'),
('Teralov', 'Ash Worlds', 'Outer Rim Territories', 'T-6'),
('Terephon', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Teres Lutha Minor', 'Farrfin', 'Core Worlds', 'K-9'),
('Tergamenion', 'Grumani', 'Outer Rim Territories', 'M-17'),
('Teriq Noi', 'Trailing Grant', 'Expansion Region', 'J-15'),
('Terman', 'Tharin (Periphery)', 'Outer Rim Territories', 'S-8'),
('Terminus', 'Kallea', 'Outer Rim Territories', 'K-20'),
('Ternin', 'Alchenaut', 'Expansion Region', 'L-16'),
('Terr''skiar', 'Terr''skiar', 'Mid Rim', 'P-10'),
('Terra Sool', 'Immeria', 'Expansion Region', 'O-14'),
('TerraAsta', NULL, 'Colonies', 'L-9'),
('Terrelia', NULL, 'Inner Rim', 'L-14'),
('Terrijo', 'Venzeiia', 'Expansion Region', 'O-12'),
('Tertiary Feswe', 'Gordian Reach', 'Outer Rim Territories', 'P-6'),
('Tertiary Fujar', 'Tamarin', 'Outer Rim Territories', 'N-19'),
('Tertiary Kesmere', 'Raioballo', 'Outer Rim Territories', 'L-4'),
('Tertiary Usaita', NULL, 'Inner Rim', 'M-13'),
('Tervissis', 'Sertar', 'Outer Rim Territories', 'R-5'),
('Tessen', 'Phelleem', 'Outer Rim Territories', 'S-7'),
('Teth', 'Baxel', 'Outer Rim Territories', 'U-12'),
('Tetso', NULL, 'Core Worlds', 'M-10'),
('Tevel', 'Prefsbelt', 'Outer Rim Territories', 'J-5'),
('Tevraki', NULL, 'Colonies', 'N-9'),
('Teya', 'Lostar', 'Expansion Region', 'M-7'),
('Teyr', NULL, 'Colonies', 'L-13'),
('Th''irus', NULL, 'Wild Space', 'S-4'),
('Thabeska', 'Morshdine', 'Outer Rim Territories', 'O-5'),
('Thabit', NULL, 'Inner Rim', 'M-14'),
('Thaere', 'Thaere', 'Expansion Region', 'O-14'),
('Thairwsthis', 'M''shinni', 'Mid Rim', 'M-7'),
('Thakwaa', 'Tunka', 'Outer Rim Territories', 'I-19'),
('Thalassia', 'Meram', 'Outer Rim Territories', 'P-4'),
('Thaldo', 'Graador', 'Mid Rim', 'J-17'),
('Thandon Nebula', 'Corporate Sector', 'Outer Rim Territories', 'S-3'),
('Thandruss', 'Thand', 'Expansion Region', 'J-15'),
('Thanium', 'Thanium', 'Outer Rim Territories', 'R-6'),
('Thannt', 'Ryndellian', 'Mid Rim', 'O-17'),
('Thanta Zilbra', 'Xappyh', 'Outer Rim Territories', 'Q-3'),
('Thape', 'Lambda', 'Mid Rim', 'Q-15'),
('Tharados', 'Onatos', 'Mid Rim', 'R-15'),
('Tharkos', 'Thanium', 'Outer Rim Territories', 'R-6'),
('Tharl', 'Zuma (Sugai)', 'Outer Rim Territories', 'H-16'),
('Tharnaka', 'Seitia', 'Outer Rim Territories', 'K-19'),
('Thassalia', 'Albanin', 'Outer Rim Territories', 'U-12'),
('Thaylia', 'Sprizen', 'Outer Rim Territories', 'N-5'),
('Theal', NULL, 'Mid Rim', 'J-15'),
('Thearterra', 'Chiss Space*', 'Unknown Regions', 'E-8'),
('Thebeon', NULL, 'Core Worlds', 'K-12'),
('Thedavio', NULL, 'Expansion Region', 'I-8'),
('Thela', 'Aparo', 'Outer Rim Territories', 'R-4'),
('Themis', NULL, 'Inner Rim', 'L-15'),
('Thennqor', 'Sarka', 'Mid Rim', 'Q-8'),
('Therenor', 'Doldur', 'Mid Rim', 'P-15'),
('Thermon', 'Juvex', 'Mid Rim', 'L-17'),
('Theron', 'Vilonis', 'Mid Rim', 'O-16'),
('Theros Major', 'Hollan', 'Mid Rim', 'M-7'),
('Theselon', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Thesme', 'Thesme', 'Outer Rim Territories', 'O-5'),
('Thession', 'Bortele', 'Mid Rim', 'S-8'),
('Thiafeña', 'Mulgard', 'Mid Rim', 'N-16'),
('Thila', 'Illisurevimurasi', 'Outer Rim Territories', 'Q-4'),
('Thisspias', 'Farstey', 'Expansion Region', 'O-8'),
('Thixia', 'Alderaan', 'Core Worlds', 'M-10'),
('Thoadeye', NULL, 'Deep Core', 'M-11'),
('Thobek', 'Farlax', 'Core Worlds', 'K-10'),
('Thodia', 'Perkell', 'Mid Rim', 'Q-7'),
('Thokos', NULL, 'Core Worlds', 'L-9'),
('Thokosia', 'Maerdocian', 'Mid Rim', 'Q-13'),
('Tholatin', 'Mytaranor', 'Mid Rim', 'P-10'),
('Tholaz', 'Farlax', 'Core Worlds', 'K-10'),
('Tholian', 'Meram', 'Outer Rim Territories', 'P-4'),
('Tholon', NULL, 'Wild Space', 'H-17'),
('Tholoth', NULL, 'Colonies', 'N-12'),
('Thomork', NULL, 'Core Worlds', 'L-12'),
('Thomquizzar', 'Meerian', 'Outer Rim Territories', 'O-6'),
('ThonBoka Nebula', 'Centrality', 'Outer Rim Territories', 'U-8'),
('Thonner', 'Zuma (Moddell)', 'Outer Rim Territories', 'H-16'),
('Thoran', 'Bothan', 'Mid Rim', 'R-14'),
('Thorat', 'Galov', 'Outer Rim Territories', 'T-14'),
('Thorgeld', NULL, 'Core Worlds', 'L-9'),
('Thornhedge Nebula', 'Terr''skiar', 'Mid Rim', 'P-10'),
('Thorsgild', 'Meerian', 'Outer Rim Territories', 'N-7'),
('Thorum', 'Vendusii', 'Mid Rim', 'P-16'),
('Thory Prime', 'Thory', 'Mid Rim', 'K-7'),
('Thosa', 'Wyl', 'Outer Rim Territories', 'R-4'),
('Thousand Moons', 'Circarpous', 'Expansion Region', 'O-12'),
('Thovinack', 'Kanz', 'Outer Rim Territories', 'N-4'),
('Thracior', NULL, 'Core Worlds', 'K-12'),
('Thrad', 'Phelleem', 'Outer Rim Territories', 'S-7'),
('Thrago', 'Chiss Space*', 'Unknown Regions', 'H-8'),
('Thraisai', NULL, 'Wild Space', 'U-9'),
('Thrakia', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Thrantin', 'Ollonir Boundaries', 'Colonies', 'J-9'),
('Threfal', 'Iska', 'Mid Rim', 'J-16'),
('Threndria', 'Yminis', 'Outer Rim Territories', 'S-15'),
('Thrinittik', NULL, 'Colonies', 'L-8'),
('Throffdon', NULL, 'Inner Rim', 'J-9'),
('Throova', NULL, 'Colonies', 'M-12'),
('Thrugii', 'Kibilini', 'Outer Rim Territories', 'Q-17'),
('Thrynka', 'Dohlbani', 'Mid Rim', 'R-14'),
('Thule', 'Esstran', 'Outer Rim Territories', 'Q-5'),
('Thulia', 'Kurost', 'Mid Rim', 'Q-12'),
('Thull''s Shroud', 'Senex', 'Mid Rim', 'L-17'),
('Thull''s Vault', 'Juvex', 'Mid Rim', 'K-18'),
('Thumbsnapper''s Bridge', 'Phelleem', 'Outer Rim Territories', 'S-7'),
('Thuna', NULL, 'Wild Space', 'I-6'),
('Thune', 'Wazta', 'Outer Rim Territories', 'I-18'),
('Thurhanna Minor', 'Tynquay', 'Outer Rim Territories', 'R-4'),
('Thustra', 'Sumitra', 'Expansion Region', 'O-7'),
('Thyferra', 'Jaso', 'Inner Rim', 'L-14'),
('Thyron', NULL, 'Colonies', 'M-9'),
('Thyrsus', NULL, 'Inner Rim', 'M-8'),
('Tibrin', 'Hadar', 'Mid Rim', 'L-18'),
('Tibro', 'Baronos', 'Colonies', 'N-9'),
('Tiems', 'Belderone', 'Outer Rim Territories', 'R-6'),
('Tieos', 'Abrion', 'Outer Rim Territories', 'S-15'),
('Tierell', 'Thesme', 'Outer Rim Territories', 'O-6'),
('Tierfon', 'Sumitra', 'Expansion Region', 'O-7'),
('Tiferep Major', 'D''Aelgoth', 'Mid Rim', 'L-17'),
('Tifnyl', 'Elrood', 'Outer Rim Territories', 'M-19'),
('Tiikae', 'Koradin', 'Outer Rim Territories', 'J-18'),
('Tiisheraan', NULL, 'Core Worlds', 'L-13'),
('Tikath', 'Noonian', 'Outer Rim Territories', 'M-6'),
('Till Chorios', 'Meridian', 'Outer Rim Territories', 'R-6'),
('Tillo', 'Tapani', 'Colonies', 'L-13'),
('Tilth', NULL, 'Colonies', 'M-12'),
('Tilurus', 'Kessel', 'Outer Rim Territories', 'T-10'),
('Timbra Ott', 'Kathol (Outback)', 'Outer Rim Territories', 'M-21'),
('Timja', 'Suolriep', 'Outer Rim Territories', 'S-8'),
('Timora', 'Bakura', 'Outer Rim Territories', 'G-16'),
('Tinallis', 'Juvex', 'Mid Rim', 'L-18'),
('Tinnel', 'Quanta', 'Core Worlds', 'M-12'),
('Tinoon', 'Javin (Anoat)', 'Outer Rim Territories', 'K-18'),
('Tinta', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Tintel', 'Belasco', 'Expansion Region', 'P-11'),
('Tinuvia', 'Tragan Cluster', 'Outer Rim Territories', 'N-5');