-- Insert additional galactic systems data  
INSERT INTO public.galactic_systems (name, sector, region, grid_coordinates) VALUES
('Anorelga', 'Braxant', 'Outer Rim Territories', 'K-3'),
('Anoth', NULL, 'Wild Space', 'J-20'),
('Ansarra', 'Iskin', 'Mid Rim', 'O-16'),
('Ansata', NULL, 'Core Worlds', 'M-11'),
('Ansek', 'Eidoloni', 'Mid Rim', 'M-17'),
('Ansett', 'Ciutric', 'Outer Rim Territories', 'N-5'),
('Ansillivog', 'Majoor', 'Expansion Region', 'N-15'),
('Ansion', 'Churnis', 'Mid Rim', 'I-6'),
('Anstares', 'Juvex', 'Mid Rim', 'L-17'),
('Antakaria', 'Bothan', 'Mid Rim', 'R-14'),
('Antamont', 'Meridian', 'Outer Rim Territories', 'R-6'),
('Antar', NULL, 'Inner Rim', 'N-12'),
('Antared', 'Esstran', 'Outer Rim Territories', 'Q-4'),
('Antares', NULL, 'Inner Rim', 'N-12'),
('Anteevy', 'Esuain', 'Mid Rim', 'P-7'),
('Antemeridias', 'Antemeridian', 'Outer Rim Territories', 'R-7'),
('Anthan', 'Braxant', 'Outer Rim Territories', 'K-3'),
('Anthus', 'Brema', 'Outer Rim Territories', 'M-17'),
('Antillion', 'D''Astan', 'Outer Rim Territories', 'O-6'),
('Antine', NULL, 'Outer Rim Territories', 'I-19'),
('Antipose', 'Centrality', 'Outer Rim Territories', 'U-8'),
('Antiquity', 'Senex', 'Mid Rim', 'L-18'),
('Antmuel', 'Chopani', 'Outer Rim Territories', 'M-3'),
('Anto''s Star', 'Saijo', 'Outer Rim Territories', 'K-20'),
('Antolus', 'Sarka', 'Mid Rim', 'Q-8'),
('Anturus', 'Senex', 'Mid Rim', 'L-18'),
('Anukara', 'Prackla', 'Expansion Region', 'O-8'),
('Anx Minor', 'Raioballo', 'Outer Rim Territories', 'L-4'),
('Anzat', 'Bryx', 'Mid Rim', 'R-7'),
('Anzell', 'Bryx', 'Mid Rim', 'R-7'),
('Aostai', NULL, 'Wild Space', 'I-13'),
('Apatros', 'Savareen', 'Outer Rim Territories', 'Q-16'),
('Apgar', 'Hilo', 'Expansion Region', 'O-13'),
('Aphran', NULL, 'Inner Rim', 'K-8'),
('Apiliria', NULL, 'Wild Space', 'T-5'),
('Aplooine', 'Grumani', 'Outer Rim Territories', 'N-17'),
('Apoka', 'Dohlbani', 'Mid Rim', 'R-14'),
('Aq Vetina', 'Relgim', 'Outer Rim Territories', 'M-4'),
('Aquaris', 'Sumitra', 'Expansion Region', 'N-7'),
('Aquella', 'Senex', 'Mid Rim', 'L-17'),
('Aquilae', NULL, 'Colonies', 'N-12'),
('Aquilaris', 'Sanbra', 'Outer Rim Territories', 'O-17'),
('Aquilaris Minor', 'Grumani', 'Outer Rim Territories', 'M-17'),
('Arabanth', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Aradia', NULL, 'Core Worlds', 'K-10'),
('Arah', 'Dantus', 'Outer Rim Territories', 'J-6'),
('Arakein', NULL, 'Inner Rim', 'N-8'),
('Aralia', 'Antemeridian', 'Outer Rim Territories', 'R-7'),
('Aramal', 'Ryborean', 'Expansion Region', 'J-8'),
('Aramand', 'Brak', 'Expansion Region', 'O-14'),
('Aramanoo', 'Bheriz', 'Outer Rim Territories', 'U-10'),
('Arami', 'Galov', 'Outer Rim Territories', 'T-13'),
('Arantara', 'Dalmar', 'Mid Rim', 'Q-16'),
('Arapia', 'Dalchon', 'Outer Rim Territories', 'R-18'),
('Arashar', NULL, 'Inner Rim', 'J-8'),
('Arat Fraca', NULL, 'Colonies', 'M-12'),
('Arath', 'Tunka', 'Outer Rim Territories', 'J-19'),
('Arbiflux', 'Dalonbian', 'Outer Rim Territories', 'L-3'),
('Arbooine', NULL, 'Outer Rim Territories', 'T-17'),
('Arbra', 'Bon''nyuw-Luq', 'Outer Rim Territories', 'N-17'),
('Arbular', 'Lambda', 'Mid Rim', 'Q-15'),
('Arc of Eden', 'Immalia', 'Expansion Region', 'K-8'),
('Arcadi', NULL, 'Inner Rim', 'N-10'),
('Arcan', 'Cronese Mandate', 'Outer Rim Territories', 'S-6'),
('Arcana', 'Lahara', 'Outer Rim Territories', 'M-5'),
('Archae Teuthis', 'Brevost', 'Expansion Region', 'O-14'),
('Archais', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Archenar', 'Metatessu', 'Mid Rim', 'R-10'),
('Archeon Nebula', 'Lothal', 'Outer Rim Territories', 'T-7'),
('Arcopola', 'Spadja', 'Outer Rim Territories', 'Q-5'),
('Arcura', NULL, 'Inner Rim', 'L-8'),
('Arda', 'Gordian Reach', 'Outer Rim Territories', 'Q-6'),
('Ardennia', 'Fath', 'Outer Rim Territories', 'K-6'),
('Ardis', NULL, 'Unknown Regions', 'G-3'),
('Ardroxia', 'Elochar', 'Mid Rim', 'R-9'),
('Ardru', 'Iseno', 'Inner Rim', 'N-13'),
('Argai', 'Cronese Mandate', 'Outer Rim Territories', 'S-6'),
('Argai Minor', 'Haldeen', 'Colonies', 'M-9'),
('Argavat', NULL, 'Colonies', 'J-13'),
('Argazda', 'Kanz', 'Outer Rim Territories', 'N-4'),
('Argo', 'Tragan Cluster', 'Outer Rim Territories', 'N-5'),
('Argoba', 'Trilon', 'Outer Rim Territories', 'H-15'),
('Argoon', 'Tion Hegemony', 'Outer Rim Territories', 'S-6'),
('Argovia', 'Endocray', 'Mid Rim', 'S-14'),
('Argul', 'D''Aelgoth', 'Mid Rim', 'L-17'),
('Argus', 'Lambda', 'Mid Rim', 'P-16'),
('Aria Prime', NULL, 'Inner Rim', 'O-9'),
('Ariarch-17', 'Ariarch', 'Mid Rim', 'J-6'),
('Aridinia', NULL, 'Inner Rim', 'M-13'),
('Aridka', 'Hertae', 'Mid Rim', 'Q-14'),
('Aridus', 'Narvath', 'Expansion Region', 'O-14'),
('Arieli', 'Authala', 'Expansion Region', 'P-12'),
('Aris', 'Albarrio', 'Outer Rim Territories', 'K-5'),
('Aris Minor', 'Parmel', 'Outer Rim Territories', 'O-18'),
('Arkam', NULL, 'Inner Rim', 'M-14'),
('Arkania', NULL, 'Colonies', 'M-8'),
('Arkanis', 'Arkanis', 'Outer Rim Territories', 'R-17'),
('Arkax Station', NULL, 'Inner Rim', 'M-14'),
('Arkinnea', 'Axion', 'Expansion Region', 'P-10'),
('Arkonne', 'Tarabba', 'Outer Rim Territories', 'M-19'),
('Arkuda', 'Gordian Reach', 'Outer Rim Territories', 'Q-6'),
('Arleen', 'Centrality', 'Outer Rim Territories', 'T-8'),
('Armath', 'Mikaster', 'Expansion Region', 'N-15'),
('Arnot Station', 'Far Xandil', 'Mid Rim', 'P-16'),
('Arorua', 'Sertar', 'Outer Rim Territories', 'R-5'),
('Arporatal-Lanin', 'Juvex', 'Mid Rim', 'K-18'),
('Arquata Station', 'Bes Ber Bikade', 'Expansion Region', 'L-15'),
('Arrakan', 'Kalamith', 'Outer Rim Territories', 'P-5'),
('Arramanx', 'Cronese Mandate', 'Outer Rim Territories', 'S-6'),
('Arreyel', NULL, 'Inner Rim', 'M-14'),
('Arrgaw', 'Kira', 'Expansion Region', 'N-16'),
('Arrochar', NULL, 'Hutt Space', 'S-8');