-- Insertar nuevos sistemas galácticos desde Dachat hasta Distilon
INSERT INTO public.galactic_systems (name, sector, region, grid_coordinates) VALUES
('Dachat', NULL, 'Core Worlds', 'K-9'),
('Dactruria', 'Clacis', 'Outer Rim Territories', 'J-4'),
('Daedalon', 'Ktilac Regions', 'Inner Rim', 'N-9'),
('Daemen', 'Woostri', 'Expansion Region', 'M-16'),
('Daermor', 'Corporate Sector', 'Outer Rim Territories', 'S-3'),
('Dagary Minor', NULL, 'Inner Rim', 'M-8'),
('Dagelin Minor', 'Cadma', 'Outer Rim Territories', 'T-8'),
('Daghee', 'Thusa', 'Mid Rim', 'O-7'),
('Dagobah', 'Sluis', 'Outer Rim Territories', 'M-19'),
('Dagro', 'Esuain', 'Mid Rim', 'P-7'),
('Dagu', 'Instrop', 'Outer Rim Territories', 'S-16'),
('Dahrtag', NULL, 'Core Worlds', 'J-13'),
('Dahvil', 'Rayter', 'Outer Rim Territories', 'J-19'),
('Daimar', 'Daimar', 'Mid Rim', 'Q-16'),
('Daimla', 'Kallea', 'Outer Rim Territories', 'K-21'),
('Dairka', 'Churba', 'Mid Rim', 'P-15'),
('Daivak', 'Karthakk', 'Outer Rim Territories', 'Q-17'),
('Daiyu', 'Hocatar', 'Expansion Region', 'P-12'),
('Dakaret', 'Oktos', 'Mid Rim', 'Q-12'),
('Dakot', 'Mortex', 'Outer Rim Territories', 'R-5'),
('Dakshee', 'Barma', 'Colonies', 'M-9'),
('Dalandae', NULL, 'Colonies', 'M-9'),
('Dalastine', NULL, 'Inner Rim', 'L-14'),
('Dalchon', 'Dalchon', 'Outer Rim Territories', 'R-17'),
('Dalcretti', NULL, 'Inner Rim', 'O-8'),
('Dalicron', 'Dalicron', 'Outer Rim Territories', 'K-19'),
('Dalisor', 'Yushan', 'Mid Rim', 'K-17'),
('Dallenor', 'Aldino', 'Mid Rim', 'J-17'),
('Dalna', 'Tunka (Dalnan)', 'Outer Rim Territories', 'I-19'),
('Dalonia', 'Maerdocian', 'Mid Rim', 'Q-13'),
('Dalos', 'Nilgaard', 'Outer Rim Territories', 'S-5'),
('Dalron', 'Ariarch', 'Mid Rim', 'J-6'),
('Daltarra', 'Pakuuni', 'Outer Rim Territories', 'T-5'),
('Daltarri', 'Truum', 'Mid Rim', 'P-8'),
('Daluba', 'Esstran', 'Outer Rim Territories', 'P-5'),
('Daluuj', 'Albanin', 'Outer Rim Territories', 'U-13'),
('Damanos', 'Belderone', 'Outer Rim Territories', 'Q-6'),
('Damendine', 'Calamari', 'Outer Rim Territories', 'U-6'),
('Daminia', 'Perkell', 'Mid Rim', 'Q-7'),
('Damonite Yors B', 'Meridian', 'Outer Rim Territories', 'R-7'),
('Damoria', NULL, 'Colonies', 'N-11'),
('Dampher', 'Tapani', 'Colonies', 'L-13'),
('Damualer', 'Triac', 'Inner Rim', 'O-10'),
('Danadine', 'Dail', 'Outer Rim Territories', 'Q-18'),
('Danalbeth', 'Teraab', 'Mid Rim', 'P-11'),
('Danchian Prime', 'Dail', 'Outer Rim Territories', 'Q-18'),
('Dancreti', NULL, 'Inner Rim', 'N-14'),
('Dandalas', 'Farlax', 'Core Worlds', 'K-10'),
('Dandelo', 'Tammuz', 'Outer Rim Territories', 'T-14'),
('Dandrian', 'Belderone', 'Outer Rim Territories', 'R-7'),
('Dankayo', NULL, 'Colonies', 'L-9'),
('Dannamore', 'Saijo', 'Outer Rim Territories', 'J-20'),
('Danoor', 'Kathol (Outback)', 'Outer Rim Territories', 'M-21'),
('Danoria', 'Nouane', 'Inner Rim', 'N-7'),
('Danos', 'Shadola', 'Outer Rim Territories', 'U-8'),
('Danteel', 'Emmo', 'Core Worlds', 'M-12'),
('Dantooine', 'Raioballo', 'Outer Rim Territories', 'L-4'),
('Danuta', 'Halla', 'Mid Rim', 'S-9'),
('Danzik', 'Dalonbian', 'Outer Rim Territories', 'M-3'),
('Dar''Or', 'Jospro', 'Outer Rim Territories', 'R-7'),
('Darada', NULL, 'Core Worlds', 'K-9'),
('Darakin', NULL, 'Core Worlds', 'M-11'),
('Daranc', 'Meram', 'Outer Rim Territories', 'O-4'),
('Dardanellia', NULL, 'Inner Rim', 'N-14'),
('Darek', 'Rachuk', 'Colonies', 'N-11'),
('Darellia', NULL, 'Core Worlds', 'L-10'),
('Darepp', NULL, 'Colonies', 'M-13'),
('Dargulli', NULL, 'Inner Rim', 'N-14'),
('Darie', 'Likasha', 'Mid Rim', 'Q-14'),
('Dark Nebula', 'Lothal', 'Outer Rim Territories', 'U-7'),
('Darkknell', 'Grumani', 'Outer Rim Territories', 'M-17'),
('Darkon', 'Chaama', 'Mid Rim', 'J-7'),
('Darlon', 'Eucer', 'Mid Rim', 'R-7'),
('Darlyn Boda', 'Javin (Anoat)', 'Outer Rim Territories', 'K-18'),
('Daro', 'Ojoster', 'Outer Rim Territories', 'N-6'),
('Daronak', 'Phelleem', 'Outer Rim Territories', 'S-7'),
('Daroon', 'Harron', 'Expansion Region', 'O-11'),
('Darsie', NULL, 'Colonies', 'L-9'),
('Dartessex', NULL, 'Inner Rim', 'N-10'),
('Daruvvia', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Darvannis', 'Calaron', 'Outer Rim Territories', 'T-9'),
('Darwikia', NULL, 'Core Worlds', 'M-10'),
('Daslkehnt', 'Pelgrin', 'Outer Rim Territories', 'R-17'),
('Dasoor', 'Agarix', 'Mid Rim', 'K-18'),
('Dassal', NULL, 'Unknown Regions', 'H-7'),
('Datar', NULL, 'Inner Rim', 'L-8'),
('Dathomir', 'Quelii', 'Outer Rim Territories', 'O-6'),
('Daupherm', 'Daupherm States', 'Core Worlds', 'K-12'),
('Davezra', 'Dustig', 'Mid Rim', 'N-16'),
('Davirien', 'Corporate Sector', 'Outer Rim Territories', 'R-3'),
('Davnar', 'Kanchen', 'Core Worlds', 'K-9'),
('Dawinia', 'Hynestian', 'Colonies', 'J-13'),
('Daxam', 'Mayagil', 'Outer Rim Territories', 'N-18'),
('Daxan Beta', 'Thesme', 'Outer Rim Territories', 'O-6'),
('Dayark', 'Kathol (Outback)', 'Outer Rim Territories', 'M-21'),
('Dbari', 'Churnis', 'Mid Rim', 'I-6'),
('De''etta', 'Sanbra', 'Outer Rim Territories', 'O-17'),
('De''nel', 'Brak', 'Expansion Region', 'O-14'),
('Deadon', 'Dantus', 'Outer Rim Territories', 'K-6'),
('Debray', NULL, 'Core Worlds', 'M-10'),
('Declavia', NULL, 'Core Worlds', 'M-11'),
('Deersheba', 'Iskin', 'Mid Rim', 'O-16'),
('Dega', 'Elrood', 'Outer Rim Territories', 'M-20'),
('Degarian', NULL, 'Colonies', 'L-13'),
('DeGerrillion', 'Tamarin', 'Outer Rim Territories', 'N-19'),
('Deko Neimoidia', 'Quellor', 'Colonies', 'N-11'),
('Del Zennis', 'Eucer', 'Mid Rim', 'R-7'),
('Dela', 'Centrality', 'Outer Rim Territories', 'T-8'),
('Delacrix', 'Calaron', 'Outer Rim Territories', 'T-9'),
('Delantine', 'Varada', 'Outer Rim Territories', 'I-19'),
('Delari', 'Corva', 'Outer Rim Territories', 'P-4'),
('Delassin', 'Calaron', 'Outer Rim Territories', 'T-9'),
('Delderaan', 'Noonian', 'Outer Rim Territories', 'N-6'),
('Delemede', 'Rseik', 'Outer Rim Territories', 'N-20'),
('Delephr', 'Carrion', 'Outer Rim Territories', 'J-4'),
('Delfii', 'Minos Cluster', 'Outer Rim Territories', 'M-20'),
('Dellalt', 'Tion Hegemony', 'Outer Rim Territories', 'T-6'),
('Delle', NULL, 'Colonies', 'L-9'),
('Delmaas', 'Seswenna', 'Outer Rim Territories', 'M-18'),
('Delphania', 'Esuain', 'Mid Rim', 'Q-7'),
('Delphidian Cluster', NULL, 'Mid Rim', 'I-15'),
('Delphon', 'Javin (Anoat)', 'Outer Rim Territories', 'K-18'),
('Delrakkin', 'Kallea', 'Outer Rim Territories', 'K-21'),
('Delrian', NULL, 'Inner Rim', 'O-9'),
('Delriss', 'Dentari', 'Expansion Region', 'O-8'),
('Deltooine', 'Corporate Sector', 'Outer Rim Territories', 'S-3'),
('Deltron', NULL, 'Inner Rim', 'O-10'),
('Deluvia', 'Klina', 'Outer Rim Territories', 'S-13'),
('Demar', 'Brak', 'Expansion Region', 'O-14'),
('Demesel', 'Meram', 'Outer Rim Territories', 'P-4'),
('Demigue', 'Demetras', 'Outer Rim Territories', 'P-7'),
('Demiloch', 'Lannik Space', 'Mid Rim', 'R-13'),
('Deminol', 'Juvex', 'Mid Rim', 'L-17'),
('Demir', NULL, 'Unknown Regions', 'G-6'),
('Demnadi', 'Far Xandil', 'Mid Rim', 'P-16'),
('Demonsgate', 'Kathol (Rift)', 'Outer Rim Territories', 'M-21'),
('Demophon', 'Demophon', 'Core Worlds', 'M-10'),
('Demos', 'Dustig', 'Mid Rim', 'N-16'),
('Denarii Nebula', 'Gordian Reach', 'Outer Rim Territories', 'P-6'),
('Denash', 'Ash Worlds (Batonn)', 'Outer Rim Territories', 'T-7'),
('Denbar', NULL, 'Inner Rim', 'L-14'),
('Denbo', 'Tamarin', 'Outer Rim Territories', 'N-18'),
('Dendada', 'Seswenna', 'Outer Rim Territories', 'M-18'),
('Dene Gois Cluster', 'Yminis', 'Outer Rim Territories', 'S-14'),
('Deneba', 'Maerdocian', 'Mid Rim', 'Q-13'),
('Denebia', 'Senex', 'Mid Rim', 'L-18'),
('Denebrilla', 'Fei Hu', 'Mid Rim', 'P-13'),
('Deneeli', NULL, 'Core Worlds', 'M-9'),
('Denevar', NULL, 'Core Worlds', 'K-9'),
('Dennaskar', 'Manda', 'Mid Rim', 'R-15'),
('Dennogra', 'Tharin', 'Outer Rim Territories', 'S-8'),
('Denon', 'Iseno', 'Inner Rim', 'N-13'),
('Denova', 'Ojoster', 'Outer Rim Territories', 'N-7'),
('Dentaal', NULL, 'Core Worlds', 'K-13'),
('Dentamma Nebula', 'Varada', 'Outer Rim Territories', 'I-19'),
('Dentaria', 'Dentari', 'Expansion Region', 'O-8'),
('Denubba', 'Likasha', 'Mid Rim', 'Q-14'),
('Denudia', 'Grohl', 'Outer Rim Territories', 'R-15'),
('Denuhi', 'Greater Plooriod', 'Expansion Region', 'M-7'),
('Denusia', NULL, 'Inner Rim', 'M-13'),
('Depatar', 'Cademimu', 'Outer Rim Territories', 'L-6'),
('Deralia', 'Tammuz', 'Outer Rim Territories', 'T-15'),
('Derella', NULL, 'Core Worlds', 'M-10'),
('Derellium', 'Cronese Mandate', 'Outer Rim Territories', 'S-6'),
('Derenzil', NULL, 'Wild Space', 'S-18'),
('Deretta', 'Tarabba', 'Outer Rim Territories', 'N-19'),
('Derf', 'Sluis', 'Outer Rim Territories', 'M-19'),
('Derilyn', 'Elrood', 'Outer Rim Territories', 'M-19'),
('Deris-plata', 'Eucer', 'Mid Rim', 'R-7'),
('Dermos', 'Belsmuth', 'Outer Rim Territories', 'O-6'),
('Derosha', NULL, 'Wild Space', 'J-5'),
('Derra', 'Mikaster', 'Expansion Region', 'N-15'),
('Derricon', 'Spirva', 'Mid Rim', 'L-17'),
('Derso', 'Yminis', 'Outer Rim Territories', 'S-14'),
('Dersonn', 'Tammuz', 'Outer Rim Territories', 'T-14'),
('Dervdis', NULL, 'Core Worlds', 'L-9'),
('Deryvia', NULL, 'Inner Rim', 'L-14'),
('Desargorr', 'Allied Tion', 'Outer Rim Territories', 'S-6'),
('Descopose', 'Farmark', 'Mid Rim', 'H-15'),
('Desevro', 'Tion Hegemony', 'Outer Rim Territories', 'S-6'),
('Desinta', 'Morshdine', 'Outer Rim Territories', 'O-5'),
('Desix', 'Suolriep', 'Outer Rim Territories', 'S-9'),
('Desstious', 'Lambda', 'Mid Rim', 'P-16'),
('Destreg', 'Bon''nyuw-Luq', 'Outer Rim Territories', 'N-18'),
('Devalok', 'Altier', 'Expansion Region', 'O-13'),
('Devaron', 'Duluur', 'Colonies', 'M-13'),
('Devil''s Asteroid', NULL, 'Outer Rim Territories', 'O-2'),
('Devon', 'Atrivis', 'Outer Rim Territories', 'L-5'),
('Devros', 'Manda', 'Mid Rim', 'R-15'),
('Dexus', NULL, 'Colonies', 'L-9'),
('Deylerax', 'Talcene', 'Mid Rim', 'R-8'),
('Deymasoll', NULL, 'Colonies', 'J-13'),
('Deysum', 'Trax', 'Mid Rim', 'Q-10'),
('Dhandu', NULL, 'Expansion Region', 'I-8'),
('Dhen-Moh', NULL, 'Inner Rim', 'K-14'),
('Di''tai''ni', 'Bothan', 'Mid Rim', 'R-14'),
('Di''wor', 'Morshdine', 'Outer Rim Territories', 'O-4'),
('Diab', NULL, 'Wild Space', 'J-6'),
('Diado', 'Lifh', 'Mid Rim', 'R-8'),
('Diamal', NULL, 'Core Worlds', 'L-13'),
('Dianth', NULL, 'Wild Space', 'T-5'),
('Diatia Major', NULL, 'Core Worlds', 'L-12'),
('Dibrook', 'Albarrio', 'Outer Rim Territories', 'K-5'),
('Dica', 'Tolemses', 'Expansion Region', 'P-11'),
('Didyma', NULL, 'Wild Space', 'J-5'),
('Dihneral', NULL, 'Colonies', 'K-13'),
('Dilbana', 'Baxel', 'Outer Rim Territories', 'U-12'),
('Dilestri', 'Hevvrol', 'Mid Rim', 'O-15'),
('Dilonexa', 'Centrality', 'Outer Rim Territories', 'U-8'),
('Dimea', 'Dimean', 'Expansion Region', 'P-13'),
('Din Nebula', 'Zuma (Moddell)', 'Outer Rim Territories', 'H-16'),
('Din Pulsar', 'Zuma (Moddell)', 'Outer Rim Territories', 'H-16'),
('Dinlo', 'Thaere', 'Expansion Region', 'O-14'),
('Dinutu', 'Colundra', 'Outer Rim Territories', 'S-5'),
('Dinwa Prime', NULL, 'Inner Rim', 'L-8'),
('Dinzo', 'Msst', 'Mid Rim', 'P-7'),
('Dioll', 'Juvex', 'Mid Rim', 'L-17'),
('Diophos', 'Quiberon', 'Outer Rim Territories', 'S-15'),
('Diorda', 'Perkell', 'Mid Rim', 'Q-7'),
('Dioya', NULL, 'Unknown Regions', 'F-8'),
('Direllia', 'Nembus', 'Outer Rim Territories', 'P-4'),
('Dirha', 'Hutt Space', 'Hutt Space', 'S-9'),
('Distilon', 'Ash Worlds', 'Outer Rim Territories', 'S-7');