-- Insert next batch of galactic systems (Ghishi to Haurgab)
INSERT INTO galactic_systems (name, sector, region, grid_coordinates) VALUES
('Ghishi', 'Daimar', 'Mid Rim', 'Q-16'),
('Ghita', 'Atravis', 'Outer Rim Territories', 'L-19'),
('Ghoba', 'Chitarghar', 'Expansion Region', 'K-15'),
('Gholondreine', 'Chitarghar', 'Expansion Region', 'K-15'),
('Ghonoath', 'Croynar', 'Inner Rim', 'M-14'),
('Ghorman', 'Sern', 'Colonies', 'L-13'),
('Ghorn', 'Tharin (Karstaxon)', 'Outer Rim Territories', 'S-8'),
('Ghost Moon', 'Wornal', 'Mid Rim', 'K-16'),
('Ghost Nebula', 'Ghost Nebula', 'Expansion Region', 'P-10'),
('Ghothia', 'Stensen', 'Outer Rim Territories', 'I-16'),
('Gibad', 'Abrion', 'Outer Rim Territories', 'S-15'),
('Gibbela', 'Atrivis', 'Outer Rim Territories', 'L-5'),
('Gibraal', 'Itopol', 'Expansion Region', 'K-15'),
('Giddea', 'Merthian', 'Expansion Region', 'N-13'),
('Giermos', NULL, 'Colonies', 'L-8'),
('Gigor', 'Tynquay', 'Outer Rim Territories', 'R-4'),
('Giju', 'Herglic Space', 'Colonies', 'L-13'),
('Gilatter', 'Churnis', 'Mid Rim', 'I-7'),
('Gilliana', 'Tapani', 'Colonies', 'L-13'),
('Gilvaanen', NULL, 'Inner Rim', 'L-8'),
('Ginn Jump', NULL, 'Core Worlds', 'L-10'),
('Giryulan', NULL, 'Wild Space', 'U-6'),
('Gizer', 'Lantillian', 'Mid Rim', 'P-8'),
('Glade', 'Gordian Reach', 'Outer Rim Territories', 'P-5'),
('Glakka', 'Wyl', 'Outer Rim Territories', 'R-4'),
('Glassferra', NULL, 'Inner Rim', 'N-9'),
('Glastis', 'Chiss Space', 'Unknown Regions', 'F-8'),
('Glavis', NULL, 'Core Worlds', 'M-11'),
('Glee Anselm', 'Jalor', 'Mid Rim', 'J-7'),
('Gligger', 'Ash Worlds', 'Outer Rim Territories', 'S-7'),
('Glite-Ven', 'Aparo', 'Outer Rim Territories', 'R-3'),
('Glithnos', NULL, 'Core Worlds', 'M-10'),
('Glom Tho', 'Hevvrol', 'Mid Rim', 'O-15'),
('Gloon', 'Kessel', 'Outer Rim Territories', 'T-10'),
('Glottal', 'Baxel', 'Outer Rim Territories', 'U-11'),
('Glova', 'Tarabba', 'Outer Rim Territories', 'M-19'),
('Gmar Askilon', 'Krenhner', 'Inner Rim', 'L-14'),
('Gnithia', 'Jospro', 'Outer Rim Territories', 'R-7'),
('Goa', 'Bes Ber Bikade', 'Expansion Region', 'L-15'),
('Gobindi', 'Noonian', 'Outer Rim Territories', 'M-6'),
('Gobreton', 'Barma', 'Colonies', 'M-9'),
('Godo', 'Quence', 'Outer Rim Territories', 'O-18'),
('Godsheart, The', 'Hutt Space', 'Outer Rim Territories', 'T-11'),
('Goelitz', 'M''shinni', 'Mid Rim', 'M-7'),
('Goff', 'Airam', 'Outer Rim Territories', 'L-20'),
('Goibniu', 'Videnda', 'Outer Rim Territories', 'L-18'),
('Golden Nyss', 'Fellwe', 'Expansion Region', 'L-8'),
('Golh', 'Videnda', 'Outer Rim Territories', 'L-18'),
('Goliath', 'Mal', 'Colonies', 'N-10'),
('Golkus', NULL, 'Colonies', 'K-9'),
('Golrath', 'Sanbra', 'Outer Rim Territories', 'O-17'),
('Golus', 'Pheyar Tion Hegemony', 'Outer Rim Territories', 'T-6'),
('Golus Station', 'Vilonis', 'Mid Rim', 'O-16'),
('Goluud Minor', NULL, 'Core Worlds', 'L-10'),
('Goluud Prime', NULL, 'Deep Core', 'L-10'),
('Gom', 'Tregillis', 'Expansion Region', 'L-15'),
('Gon Tiek', 'Atravis', 'Outer Rim Territories', 'L-19'),
('Gonda', 'Bon''nyuw-Luq', 'Outer Rim Territories', 'N-18'),
('Gondagali', 'Lahara', 'Outer Rim Territories', 'M-5'),
('Gonmore', 'Fath', 'Outer Rim Territories', 'K-6'),
('Gontzol', NULL, 'Colonies', 'L-13'),
('Goorla', 'Corellian', 'Core Worlds', 'M-11'),
('Goratak', 'Vensensor', 'Expansion Region', 'K-16'),
('Gorbah', 'Atravis', 'Outer Rim Territories', 'L-19'),
('Gorgaria', 'Karthakk', 'Outer Rim Territories', 'Q-17'),
('Gorm', 'Meerian', 'Outer Rim Territories', 'O-6'),
('Gorma', 'Majoor', 'Expansion Region', 'N-15'),
('Gormen', 'Nuiri', 'Outer Rim Territories', 'Q-7'),
('Gorno', 'Arkanis', 'Outer Rim Territories', 'R-17'),
('Gorobei', NULL, 'Inner Rim', 'M-8'),
('Goroth', 'Trans-Nebular', 'Mid Rim', 'R-16'),
('Gorse', NULL, 'Inner Rim', 'O-10'),
('Gorsh', NULL, 'Wild Space', 'O-3'),
('Gortus', 'Kanz', 'Outer Rim Territories', 'N-4'),
('Gorvinia', 'Thusa', 'Mid Rim', 'O-7'),
('Gos Hutta', 'Hutt Space', 'Outer Rim Territories', 'S-11'),
('Gosfambling', 'Lifh', 'Mid Rim', 'R-8'),
('Gosho', 'Parmel', 'Outer Rim Territories', 'O-18'),
('Goshyn', 'Tolonda', 'Outer Rim Territories', 'Q-18'),
('Gotar', NULL, 'Wild Space', 'U-9'),
('Gotida', NULL, 'Inner Rim', 'O-10'),
('Gotoma', 'Farlax', 'Core Worlds', 'K-10'),
('Gottlegoob', NULL, 'Wild Space', 'O-20'),
('Govia', 'Corellian', 'Core Worlds', 'M-11'),
('Gowdawl', NULL, 'Inner Rim', 'M-14'),
('Gozgo', 'Hutt Space', 'Outer Rim Territories', 'S-9'),
('Gra Ploven', NULL, 'Colonies', 'N-12'),
('Graador', 'Graador', 'Mid Rim', 'I-17'),
('Graal''diin', 'Spadja', 'Outer Rim Territories', 'R-6'),
('Graddus Rex', NULL, 'Inner Rim', 'L-14'),
('Gradilis Rift', NULL, 'Wild Space', 'I-5'),
('Grakouine', 'Onatos', 'Mid Rim', 'R-15'),
('Gralack', 'Kwymar', 'Outer Rim Territories', 'P-4'),
('Graland', 'Corellian', 'Core Worlds', 'M-11'),
('Grand Tharkand', NULL, 'Inner Rim', 'O-9'),
('Grandeel', 'Tynna', 'Expansion Region', 'N-14'),
('Grandine', NULL, 'Colonies', 'M-9'),
('Grange', 'Kurost', 'Mid Rim', 'Q-11'),
('Granna', NULL, 'Core Worlds', 'K-10'),
('Granus', NULL, 'Inner Rim', 'M-14'),
('Grathus', 'Jospro', 'Outer Rim Territories', 'R-7'),
('Grava', 'Kallea', 'Outer Rim Territories', 'K-20'),
('Gravan', NULL, 'Inner Rim', 'O-8'),
('Gravane', 'Klina', 'Outer Rim Territories', 'S-13'),
('Gravdinia', NULL, 'Colonies', 'N-10'),
('Gravlex Med', 'Raioballo', 'Outer Rim Territories', 'L-4'),
('Great Aglamerti', 'Charra', 'Expansion Region', 'P-14'),
('Great Forveen Nebula', 'Churnis', 'Mid Rim', 'J-6'),
('Great Zilk', 'Irishi', 'Mid Rim', 'K-6'),
('Greater Marianas', 'Sevetta', 'Outer Rim Territories', 'S-15'),
('Gree', 'Veragi (Gree Enclave)', 'Outer Rim Territories', 'L-2'),
('Gree Baaker', 'Atrivis', 'Outer Rim Territories', 'L-5'),
('Greeb-Streebling Cluster', 'Bozhnee', 'Outer Rim Territories', 'L-18'),
('Greeve', 'Grumani', 'Outer Rim Territories', 'N-17'),
('Gregonia', 'Dimean', 'Expansion Region', 'P-13'),
('Grehollo', 'Manoe', 'Mid Rim', 'K-7'),
('Grella', 'Tapani', 'Colonies', 'L-13'),
('Greyman''s Planet', 'Wazta', 'Outer Rim Territories', 'J-18'),
('Grimdock', 'Axion', 'Expansion Region', 'P-10'),
('Grimwald', 'Truum', 'Mid Rim', 'P-8'),
('Griq', NULL, 'Unknown Regions', 'H-7'),
('Grizal', 'Hadar', 'Mid Rim', 'L-17'),
('Grizmallt', NULL, 'Core Worlds', 'L-9'),
('Gromas', 'Perkell', 'Mid Rim', 'Q-7'),
('Groth', 'Hutt Space', 'Outer Rim Territories', 'S-11'),
('Grumwall', 'Illisurevimurasi', 'Outer Rim Territories', 'Q-4'),
('Gruvia', 'Hilo', 'Expansion Region', 'P-13'),
('Gryphon', NULL, 'Inner Rim', 'N-9'),
('Guagenia', 'Guagenian', 'Inner Rim', 'J-14'),
('Guat''a', 'Torch Nebula', 'Outer Rim Territories', 'P-19'),
('Guavian Drift', 'Meram', 'Outer Rim Territories', 'P-4'),
('GUHL-J03870', 'Trilon', 'Outer Rim Territories', 'H-15'),
('Guiteica', 'Kadok Regions', 'Wild Space', 'J-4'),
('Gulf of Tatooine', 'Arkanis', 'Outer Rim Territories', 'R-16'),
('Gulhadar', NULL, 'Inner Rim', 'L-8'),
('Gulma', NULL, 'Wild Space', 'P-3'),
('Gultanna', 'Va di Gult', 'Mid Rim', 'K-8'),
('Gulvitch', 'Gordian Reach', 'Outer Rim Territories', 'Q-6'),
('Gundravia', 'Hadar', 'Mid Rim', 'L-17'),
('Gunthar', 'Kriz', 'Outer Rim Territories', 'J-18'),
('Gurrisalia', 'Relgim', 'Outer Rim Territories', 'L-5'),
('Gutretee', 'Javin (Anoat)', 'Outer Rim Territories', 'K-18'),
('Guudria', NULL, 'Wild Space', 'R-19'),
('Guuko', 'Weneen', 'Outer Rim Territories', 'N-6'),
('Gwar', NULL, 'Mid Rim', 'H-15'),
('Gwongdeen', NULL, 'Colonies', 'J-9'),
('Gwori', 'Clacis', 'Outer Rim Territories', 'K-4'),
('Gymelo', 'Bakura', 'Outer Rim Territories', 'G-16'),
('Gyndine', 'Circarpous', 'Expansion Region', 'O-12'),
('Gyndorath', NULL, 'Unknown Regions', 'G-11'),
('Gyosha', NULL, 'Core Worlds', 'K-12'),
('H''Grathi Nebulae', 'Thrasybule', 'Outer Rim Territories', 'P-6'),
('H''ken', 'Corva', 'Outer Rim Territories', 'P-4'),
('H''nemthe', 'Mayagil', 'Outer Rim Territories', 'M-18'),
('H''ratth', NULL, 'Inner Rim', 'N-10'),
('H''relac', 'Aparo', 'Outer Rim Territories', 'R-3'),
('Haariden', NULL, 'Inner Rim', 'O-9'),
('Haaridin', 'Kwymar', 'Outer Rim Territories', 'P-4'),
('Haashimut', 'Ash Worlds', 'Outer Rim Territories', 'S-7'),
('Habassa', 'Herdessa', 'Mid Rim', 'Q-16'),
('Had Abbadon', NULL, 'Deep Core', 'L-10'),
('Hadi', 'Kalamith', 'Outer Rim Territories', 'P-5'),
('Hadlress', NULL, 'Inner Rim', 'M-14'),
('Hadros', 'Prefsbelt', 'Outer Rim Territories', 'J-6'),
('Haffrin', 'Esstran', 'Outer Rim Territories', 'Q-4'),
('Hagar Secundus', 'Brak', 'Expansion Region', 'O-14'),
('Haidoral Prime', 'Kastolar', 'Mid Rim', 'R-10'),
('Haileap', 'Tunka (Dalnan)', 'Outer Rim Territories', 'I-19'),
('Hakara', 'Corva', 'Outer Rim Territories', 'P-3'),
('Hakartha', 'Hakartha', 'Expansion Region', 'K-16'),
('Hakassi', NULL, 'Deep Core', 'M-11'),
('Hakotei', 'D''Astan', 'Outer Rim Territories', 'O-6'),
('Halais', NULL, 'Colonies', 'N-10'),
('Halanit', NULL, 'Colonies', 'N-11'),
('Halbara', 'Elrood', 'Outer Rim Territories', 'M-20'),
('Halcyon', NULL, 'Colonies', 'K-13'),
('Haldeen', 'Haldeen', 'Colonies', 'M-9'),
('Hali', 'Hali', 'Expansion Region', 'O-9'),
('Hallion', 'Esstran (Sith Worlds)', 'Outer Rim Territories', 'R-5'),
('Hallitron', 'Jalor', 'Mid Rim', 'J-7'),
('Hallrin', 'Surron', 'Expansion Region', 'O-13'),
('Halm', 'Halm', 'Mid Rim', 'J-16'),
('Halmad', 'Quelii', 'Outer Rim Territories', 'N-6'),
('Halowan', 'Fakir', 'Colonies', 'K-9'),
('Halpat', NULL, 'Core Worlds', 'K-9'),
('Halthor', 'Halthor', 'Outer Rim Territories', 'L-6'),
('Haluria', 'Vendusii', 'Mid Rim', 'P-16'),
('Halyard', 'Bes Ber Bikade', 'Expansion Region', 'L-15'),
('Handooine', 'Phelleem', 'Outer Rim Territories', 'S-7'),
('Haneli', 'Arc d''Stot', 'Expansion Region', 'K-15'),
('Hanna', NULL, 'Inner Rim', 'M-8'),
('Hanod', 'Corva', 'Outer Rim Territories', 'P-3'),
('Hanofar', NULL, 'Colonies', 'L-13'),
('Hapes', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Hapor', NULL, 'Inner Rim', 'O-8'),
('Hapuntep', 'Ado', 'Mid Rim', 'M-17'),
('Har Binande', 'Har Worlds', 'Expansion Region', 'J-16'),
('Harbin-re', NULL, 'Inner Rim', 'N-13'),
('Harda', 'Phelleem', 'Outer Rim Territories', 'S-7'),
('Hardex', 'Jubilar', 'Outer Rim Territories', 'T-7'),
('Hargeeva', 'Jurzan', 'Expansion Region', 'M-15'),
('Harix', NULL, 'Colonies', 'K-9'),
('Harko Station', 'D''Astan', 'Outer Rim Territories', 'N-5'),
('Harkrova', NULL, 'Inner Rim', 'N-9'),
('Harlequin Station', 'Garis', 'Outer Rim Territories', 'N-17'),
('Harloen', 'Belsmuth', 'Outer Rim Territories', 'O-6'),
('Harloff Minor', NULL, 'Core Worlds', 'L-9'),
('Harpori', 'Druess', 'Mid Rim', 'O-15'),
('Harrandarr', 'Bosph', 'Outer Rim Territories', 'Q-3'),
('Harridan', 'Dantus', 'Outer Rim Territories', 'J-6'),
('Harrin', 'Harrin', 'Inner Rim', 'L-15'),
('Harrod''s Planet', 'Oplovis', 'Outer Rim Territories', 'M-5'),
('Harswee', 'Mandalore', 'Outer Rim Territories', 'O-7'),
('Hartaga', 'Drannik', 'Expansion Region', 'K-8'),
('Harterra', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Haruun Kal', 'Dustig', 'Mid Rim', 'M-17'),
('Hasaq', 'Askarian', 'Expansion Region', 'P-12'),
('Haseria', 'Haserian', 'Mid Rim', 'P-15'),
('Hasiki', NULL, 'Inner Rim', 'O-8'),
('Hassaria', 'Wazta', 'Outer Rim Territories', 'I-17'),
('Hasskyn', 'Minos Cluster', 'Outer Rim Territories', 'M-20'),
('Hast', NULL, 'Wild Space', 'U-6'),
('Hathrox', 'Halla', 'Mid Rim', 'R-10'),
('Haurgab', 'Spirva', 'Mid Rim', 'L-16');