-- Insert next batch of galactic systems (Fleyars to Gherillia)
INSERT INTO galactic_systems (name, sector, region, grid_coordinates) VALUES
('Fleyars', 'Baroli', 'Expansion Region', 'N-14'),
('Fligger', 'Kibilini', 'Outer Rim Territories', 'Q-17'),
('Florn', 'Pakuuni', 'Outer Rim Territories', 'T-5'),
('Florrum', 'Sertar', 'Outer Rim Territories', 'R-5'),
('Floubette', NULL, 'Colonies', 'L-13'),
('Fluwhaka', 'Mortex', 'Outer Rim Territories', 'R-5'),
('Flyntaria', 'D''Astan', 'Outer Rim Territories', 'O-6'),
('Fnessal', NULL, 'Inner Rim', 'K-14'),
('Fobaris', 'Parmel', 'Outer Rim Territories', 'O-18'),
('Fodro', 'Clacis', 'Outer Rim Territories', 'K-4'),
('Fodurant', 'Trans-Gascon', 'Mid Rim', 'P-8'),
('Foerost', NULL, 'Core Worlds', 'L-10'),
('Fokask', 'Klina', 'Outer Rim Territories', 'S-13'),
('Folende', 'Tion Hegemony', 'Outer Rim Territories', 'S-5'),
('Foless', NULL, 'Colonies', 'M-13'),
('Fondor', 'Tapani', 'Colonies', 'L-13'),
('Foran Tutha', 'Cronese Mandate', 'Outer Rim Territories', 'S-6'),
('Forbelea', NULL, 'Unknown Regions', 'H-8'),
('Fordon', 'Savareen', 'Outer Rim Territories', 'Q-16'),
('Forlonis Minor', 'Tharin', 'Outer Rim Territories', 'S-8'),
('Formos', 'Kessel', 'Outer Rim Territories', 'T-10'),
('Fornax', 'Glythe', 'Mid Rim', 'J-7'),
('Fornow', 'Pacanth Reach', 'Outer Rim Territories', 'H-16'),
('Forntay', NULL, 'Core Worlds', 'L-12'),
('Forome', 'Kessel', 'Outer Rim Territories', 'T-10'),
('Forrn', 'Xan', 'Mid Rim', 'Q-15'),
('Forscan', 'Auril', 'Outer Rim Territories', 'R-7'),
('Forsen', 'Cassander', 'Outer Rim Territories', 'K-5'),
('Forvand', 'Corellian', 'Core Worlds', 'M-11'),
('Fostin', 'Grumani', 'Outer Rim Territories', 'N-17'),
('Foundry', NULL, 'Colonies', 'N-10'),
('Foxar', NULL, 'Wild Space', 'N-3'),
('Fradian', 'Roche', 'Mid Rim', 'Q-8'),
('Freda', 'Esaga', 'Mid Rim', 'Q-11'),
('Freerock', NULL, 'Wild Space', 'H-13'),
('Frego', NULL, 'Core Worlds', 'L-13'),
('Freliq', 'Calaron', 'Outer Rim Territories', 'U-9'),
('Fremond', NULL, 'Inner Rim', 'N-14'),
('Fresia', 'Torranix', 'Core Worlds', 'K-10'),
('Frewwil', NULL, 'Expansion Region', 'I-14'),
('Freya', NULL, 'Wild Space', 'S-18'),
('Frezno', 'Cademimu', 'Outer Rim Territories', 'M-6'),
('Friijillis', 'Dail', 'Outer Rim Territories', 'P-18'),
('Frisal', 'Atrisian CW', 'Core Worlds', 'J-12'),
('Frithia', 'Glythe', 'Mid Rim', 'K-7'),
('Froffl', 'Churba', 'Mid Rim', 'P-15'),
('Fromiria', 'Mortex', 'Outer Rim Territories', 'R-5'),
('Fromish', NULL, 'Core Worlds', 'M-11'),
('Frommon', NULL, 'Colonies', 'M-9'),
('Frong', 'Ojoster', 'Outer Rim Territories', 'N-7'),
('Froswythe', NULL, 'Colonies', 'M-13'),
('Froz', 'Corellian', 'Core Worlds', 'M-11'),
('Frunchettan', NULL, 'Wild Space', 'I-6'),
('Fryiaa', 'Dail', 'Outer Rim Territories', 'Q-18'),
('Fuacha', 'Galov', 'Outer Rim Territories', 'T-14'),
('Fusai', 'Zuma (Fusai)', 'Outer Rim Territories', 'H-16'),
('Fwatna', 'Subterrel', 'Outer Rim Territories', 'K-20'),
('Fwiis', NULL, 'Inner Rim', 'M-13'),
('Fwillsving', 'Calaron', 'Outer Rim Territories', 'T-10'),
('Fyodos', 'Tammuz', 'Outer Rim Territories', 'U-14'),
('Fyrth', NULL, 'Inner Rim', 'J-8'),
('Fytoun', 'Brak', 'Expansion Region', 'O-14'),
('G''haris', 'Perinn', 'Outer Rim Territories', 'J-4'),
('G''rho', NULL, 'Wild Space', 'G-16'),
('G''Tep''Noi', 'Croynar', 'Inner Rim', 'N-14'),
('G''wenee', 'Weneen', 'Outer Rim Territories', 'N-6'),
('Gaalt', 'Meram', 'Outer Rim Territories', 'O-4'),
('Gaaten', 'Garis', 'Outer Rim Territories', 'N-17'),
('Gabdor', NULL, 'Expansion Region', 'H-14'),
('Gabredor', 'Myto', 'Outer Rim Territories', 'K-4'),
('Gacerian', 'Baroli', 'Expansion Region', 'N-15'),
('Gad', 'Brema', 'Outer Rim Territories', 'M-17'),
('Gaddria', 'Oricho', 'Outer Rim Territories', 'M-5'),
('Gadon', 'Cronese Mandate', 'Outer Rim Territories', 'S-6'),
('Gaftikar', 'Kalamith', 'Outer Rim Territories', 'P-5'),
('Gagrew Station', 'Hutt Space', 'Outer Rim Territories', 'S-9'),
('Gailea', NULL, 'Core Worlds', 'M-12'),
('Gaios', NULL, 'Core Worlds', 'K-9'),
('Gairm', 'Venaarian', 'Mid Rim', 'O-7'),
('Gal Milnor', 'Seitia', 'Outer Rim Territories', 'K-19'),
('Gala', 'Nuiri', 'Outer Rim Territories', 'Q-7'),
('Galaan', 'Corva', 'Outer Rim Territories', 'P-4'),
('Galagolos', NULL, 'Colonies', 'J-9'),
('Galand', 'Torranix', 'Core Worlds', 'K-10'),
('Galantos', 'Farlax', 'Core Worlds', 'K-10'),
('Galara', 'Roche', 'Mid Rim', 'Q-8'),
('Galator', 'Belsmuth', 'Outer Rim Territories', 'O-6'),
('Galboron', 'Hertae', 'Mid Rim', 'Q-14'),
('Galdi', 'Brema (Reithcas)', 'Outer Rim Territories', 'M-18'),
('Galdria', 'Cronese Mandate', 'Outer Rim Territories', 'S-6'),
('Galdronia', NULL, 'Core Worlds', 'L-10'),
('Galidraan', 'Thanium', 'Outer Rim Territories', 'R-6'),
('Galitan', 'Bormea', 'Core Worlds', 'L-9'),
('Galjaero', 'Tungra', 'Outer Rim Territories', 'K-18'),
('Gall', 'Cadavine', 'Outer Rim Territories', 'P-17'),
('Gallapraxis', 'Hythrope', 'Expansion Region', 'M-16'),
('Galleefryn', 'Corporate Sector', 'Outer Rim Territories', 'S-3'),
('Gallinore', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Gallion', 'Grumani', 'Outer Rim Territories', 'N-17'),
('Galloa', 'D''Astan', 'Outer Rim Territories', 'O-5'),
('Galltine', 'Thesme', 'Outer Rim Territories', 'O-6'),
('Gallus', 'Allied Tion', 'Outer Rim Territories', 'S-6'),
('Galmerah', 'Jalor', 'Mid Rim', 'J-7'),
('Galov', 'Galov', 'Outer Rim Territories', 'T-14'),
('Galpos', 'Abrion', 'Outer Rim Territories', 'S-15'),
('Galshebbis Prime', 'Nilgaard', 'Outer Rim Territories', 'S-5'),
('Galsol', 'Belderone', 'Outer Rim Territories', 'R-6'),
('Galtea', 'Kathol', 'Outer Rim Territories', 'M-21'),
('Galtea Binary', 'Kathol (Outback)', 'Outer Rim Territories', 'M-21'),
('Galvoni', NULL, 'Core Worlds', 'K-9'),
('Galzez', 'Dustig', 'Mid Rim', 'M-17'),
('Gam Tim''nisi', 'Tungra', 'Outer Rim Territories', 'K-18'),
('Gama', NULL, 'Core Worlds', 'L-12'),
('Gamerong', 'Nijune', 'Outer Rim Territories', 'N-4'),
('Gammalin', 'Vish', 'Mid Rim', 'N-16'),
('Gamor', 'Chaykin', 'Expansion Region', 'O-14'),
('Gamorr', 'Galov', 'Outer Rim Territories', 'T-14'),
('Gan Moradir', 'Xan', 'Mid Rim', 'Q-15'),
('Ganath', 'Hutt Space', 'Outer Rim Territories', 'R-12'),
('Gand', 'Shadola', 'Outer Rim Territories', 'T-8'),
('Gandalla', 'Boeus', 'Expansion Region', 'M-15'),
('Gandan', 'Oricho', 'Outer Rim Territories', 'M-6'),
('Gandeal', NULL, 'Core Worlds', 'M-12'),
('Gandeid', 'Trailing Grant', 'Expansion Region', 'J-15'),
('Gandle Ott', 'Kathol', 'Outer Rim Territories', 'M-21'),
('Gandolo', 'Lahara', 'Outer Rim Territories', 'M-5'),
('Gandrossi', 'Perinn', 'Outer Rim Territories', 'J-4'),
('Gandrun', NULL, 'Colonies', 'J-13'),
('Gangxi Station', NULL, 'Wild Space', 'I-15'),
('Gania', 'Tapani', 'Colonies', 'L-13'),
('Ganlihk', 'Dantus', 'Outer Rim Territories', 'J-6'),
('Gannaria', 'Trilon', 'Outer Rim Territories', 'H-15'),
('Gannymeda', NULL, 'Inner Rim', 'M-8'),
('Ganoidi', 'Brema', 'Outer Rim Territories', 'M-17'),
('Gansett', 'Manda', 'Mid Rim', 'R-15'),
('Ganthel', 'Bormea', 'Core Worlds', 'L-9'),
('Gantho', NULL, 'Inner Rim', 'N-12'),
('Gantonnerre', NULL, 'Inner Rim', 'N-8'),
('Ganzik', 'Maldrood', 'Mid Rim', 'R-7'),
('Garban', 'Abrion', 'Outer Rim Territories', 'S-15'),
('Garcornia', 'Ado', 'Mid Rim', 'M-17'),
('Gardaji', 'Rift (Gardaji)', 'Outer Rim Territories', 'M-1'),
('Garel', 'Lothal', 'Outer Rim Territories', 'U-7'),
('Garen', 'Thuldin''s Grant', 'Expansion Region', 'J-15'),
('Garfin', 'Immeria', 'Expansion Region', 'O-14'),
('Gargolyn', NULL, 'Wild Space', 'I-8'),
('Gargon', 'Mandalore', 'Outer Rim Territories', 'O-7'),
('Garia', 'Brak', 'Expansion Region', 'O-14'),
('Garis', 'Tamarin', 'Outer Rim Territories', 'N-18'),
('Garn', 'Cadma', 'Outer Rim Territories', 'T-8'),
('Garnib', 'Bozhnee', 'Outer Rim Territories', 'L-18'),
('Garobi', 'Tapani', 'Colonies', 'L-13'),
('Garollia', 'Baroli', 'Expansion Region', 'N-15'),
('Garos', 'Msst', 'Mid Rim', 'P-7'),
('Garqi', 'Cassander (Tadrin)', 'Outer Rim Territories', 'K-5'),
('Garr''lst', NULL, 'Inner Rim', 'O-8'),
('Garrthinius', 'Steniplis', 'Outer Rim Territories', 'M-18'),
('Garwillia', NULL, 'Core Worlds', 'M-10'),
('Gascon', 'Trans-Gascon', 'Mid Rim', 'P-8'),
('Gastrula', 'Rayter', 'Outer Rim Territories', 'J-19'),
('Gatalenta', NULL, 'Core Worlds', 'M-10'),
('Gathus', 'Tynquay', 'Outer Rim Territories', 'Q-4'),
('Gattering', 'Noolian', 'Mid Rim', 'Q-13'),
('Gaulus', 'Gaulus', 'Outer Rim Territories', 'S-17'),
('Gaurick', 'Corporate Sector', 'Outer Rim Territories', 'S-4'),
('Gavana', 'Belasco', 'Expansion Region', 'O-11'),
('Gavens', 'Tregillis', 'Expansion Region', 'M-15'),
('Gavos', 'Kastolar', 'Mid Rim', 'Q-10'),
('Gavriza', 'Prackla', 'Expansion Region', 'O-8'),
('Gavryn', 'Romintine', 'Mid Rim', 'Q-8'),
('Gaxxa', NULL, 'Inner Rim', 'N-10'),
('Gazian', 'Truum', 'Mid Rim', 'P-8'),
('Gazzari', 'Grumani', 'Outer Rim Territories', 'M-17'),
('Gazzari Minor', 'Garis', 'Outer Rim Territories', 'N-17'),
('Gbu', 'Keldrath', 'Outer Rim Territories', 'T-6'),
('Geal', 'Gendius', 'Mid Rim', 'K-17'),
('Gedi', 'Arkanis', 'Outer Rim Territories', 'R-16'),
('Geedon', 'Sumitra', 'Expansion Region', 'N-7'),
('Gefthaine', 'Mandalore', 'Outer Rim Territories', 'O-7'),
('Geillia', 'Keldrath', 'Outer Rim Territories', 'T-6'),
('Geister', 'Iskin', 'Mid Rim', 'O-16'),
('Gelda', 'Carrion', 'Outer Rim Territories', 'J-4'),
('Geldoll', 'Kossa', 'Expansion Region', 'O-11'),
('Gelemeade', 'Kordu', 'Mid Rim', 'L-7'),
('Gelgelar', 'Elrood', 'Outer Rim Territories', 'M-20'),
('Gellefon', 'Savareen', 'Outer Rim Territories', 'Q-16'),
('Gelviddis Cluster', NULL, 'Inner Rim', 'N-9'),
('Gem, The', NULL, 'Unknown Regions', 'G-14'),
('Genassa', 'M''shinni', 'Mid Rim', 'M-7'),
('Gendius', 'Gendius', 'Mid Rim', 'J-17'),
('Gendoraan', NULL, 'Core Worlds', 'M-10'),
('Gendrah-Narvin', NULL, 'Inner Rim', 'N-13'),
('Generis', 'Atrivis', 'Outer Rim Territories', 'L-5'),
('Genesia', 'Brak', 'Expansion Region', 'O-14'),
('Genetia', NULL, 'Expansion Region', 'I-14'),
('Genhu', 'Tharin (Periphery)', 'Outer Rim Territories', 'S-8'),
('Genian', 'Trax', 'Mid Rim', 'P-10'),
('Geniseria', 'Jurzan', 'Expansion Region', 'M-15'),
('Genon', NULL, 'Inner Rim', 'N-13'),
('Genosha', NULL, 'Outer Rim Territories', 'I-20'),
('Geonosis', 'Arkanis', 'Outer Rim Territories', 'R-16'),
('Gepparin', 'Shelsha', 'Colonies', 'M-9'),
('Geran', 'Calaron', 'Outer Rim Territories', 'T-9'),
('Gerhalt', 'Altier', 'Expansion Region', 'O-13'),
('Geridard', 'Doldur', 'Mid Rim', 'P-15'),
('Gerinia', 'Trans-Vulta', 'Mid Rim', 'N-7'),
('Geris', 'Trans-Vulta', 'Mid Rim', 'O-7'),
('Geroon', NULL, 'Unknown Regions', 'I-8'),
('Gerrard', NULL, 'Core Worlds', 'K-12'),
('Gerrenthum', 'Javin (Anoat)', 'Outer Rim Territories', 'K-18'),
('Gerres Gule', 'Primtara', 'Mid Rim', 'P-15'),
('Gertafuu', NULL, 'Wild Space', 'S-18'),
('Gerzob', 'Hunnoverrs', 'Outer Rim Territories', 'R-18'),
('Gesaral Beta', 'Gordian Reach', 'Outer Rim Territories', 'P-6'),
('Gesaril', 'Minos Cluster', 'Outer Rim Territories', 'M-20'),
('Geska Prime', 'Lifh', 'Mid Rim', 'Q-8'),
('Gestrex', 'Calaron', 'Outer Rim Territories', 'T-9'),
('Gestron', 'Tennuutta', 'Mid Rim', 'Q-7'),
('Gevarno Cluster', 'Brema', 'Outer Rim Territories', 'M-17'),
('Ggy-ynt', 'Esuain', 'Mid Rim', 'Q-7'),
('GH-531', NULL, 'Unknown Regions', 'I-5'),
('Ghaina', NULL, 'Core Worlds', 'K-9'),
('Gheia', 'Albarrio', 'Outer Rim Territories', 'K-5'),
('Gherillia', 'Bes Ber Bikade', 'Expansion Region', 'L-15');