-- Insert galactic systems from Marais to Morellia (196 systems)
INSERT INTO galactic_systems (name, sector, region, grid_coordinates) VALUES
('Marais, The', 'Hatawa', 'Core Worlds', 'J-10'),
('Maraken', 'Oktos', 'Mid Rim', 'R-12'),
('Maramere', 'Karthakk', 'Outer Rim Territories', 'Q-17'),
('Marasai', 'Marasa Nebula', 'Inner Rim', 'O-10'),
('Marasaln', 'Outer Jalor', 'Mid Rim', 'I-7'),
('Marca', 'Meerian', 'Outer Rim Territories', 'N-6'),
('Marcadia', NULL, 'Inner Rim', 'N-14'),
('Marcelan Prime', NULL, 'Wild Space', 'J-5'),
('Marcol Void', 'Kathol (Outback)', 'Outer Rim Territories', 'M-21'),
('Mardona', NULL, 'Inner Rim', 'N-13'),
('Mareg', NULL, 'Wild Space', 'I-20'),
('Marfa', NULL, 'Core Worlds', 'M-10'),
('Maridun', 'Rolion', 'Outer Rim Territories', 'Q-6'),
('Markbee''s Star', 'Atrivis', 'Outer Rim Territories', 'L-5'),
('Markon', NULL, 'Core Worlds', 'L-9'),
('Marleyvane', 'Tharin', 'Outer Rim Territories', 'T-8'),
('Marmoth', 'Albarrio', 'Outer Rim Territories', 'K-4'),
('Marngar', NULL, 'Core Worlds', 'M-10'),
('Maro', 'Della Mektrun', 'Mid Rim', 'L-17'),
('Marotan', NULL, 'Inner Rim', 'O-9'),
('Marquarra', 'Prefsbelt', 'Outer Rim Territories', 'J-5'),
('Marquinn', NULL, 'Inner Rim', 'K-8'),
('Marranis', 'Esstran', 'Outer Rim Territories', 'P-5'),
('Marrovia', 'Gordian Reach', 'Outer Rim Territories', 'P-5'),
('Martaus', NULL, 'Inner Rim', 'N-8'),
('Martle Station', 'Indrexu', 'Outer Rim Territories', 'S-5'),
('Maryo', 'Corporate Sector', 'Outer Rim Territories', 'S-4'),
('Maryx Minor', 'Sujimis', 'Outer Rim Territories', 'O-19'),
('Marzoon', 'Marzoon', 'Mid Rim', 'I-16'),
('Masgen', 'Churnis', 'Mid Rim', 'I-7'),
('Masposhani', 'Taldot', 'Mid Rim', 'Q-9'),
('Massiff Nebula', NULL, 'Core Worlds', 'K-9'),
('Massoss', NULL, 'Unknown Regions', 'G-8'),
('Masterra', 'Hertae', 'Mid Rim', 'Q-14'),
('Matabre', 'Eucer', 'Mid Rim', 'Q-7'),
('Matacorn', 'Lambda', 'Mid Rim', 'P-15'),
('Mataou', 'Javin (Anoat)', 'Outer Rim Territories', 'K-18'),
('Matarri', NULL, 'Inner Rim', 'N-8'),
('Mathas', NULL, 'Inner Rim', 'J-14'),
('Matra', 'Corporate Sector', 'Outer Rim Territories', 'S-4'),
('Matterhelm', NULL, 'Inner Rim', 'N-9'),
('Mattri', NULL, 'Inner Rim', 'O-10'),
('Mauk', 'Metatessu', 'Mid Rim', 'R-9'),
('Maun', 'Digitalis', 'Colonies', 'L-8'),
('Mauphin', NULL, 'Core Worlds', 'K-12'),
('Mavinia', NULL, 'Inner Rim', 'N-13'),
('Mavva', 'Aparo', 'Outer Rim Territories', 'R-3'),
('Maw Cluster', 'Kessel', 'Outer Rim Territories', 'T-10'),
('Mawan', NULL, 'Core Worlds', 'M-11'),
('Maxca', 'Brak', 'Expansion Region', 'O-14'),
('Maxet', 'Tragan Cluster', 'Outer Rim Territories', 'N-5'),
('Maxilia', 'Vulcusion', 'Expansion Region', 'L-16'),
('Maya Kovel', 'Zuma (Moddell)', 'Outer Rim Territories', 'H-16'),
('Mayagil', 'Mayagil', 'Outer Rim Territories', 'M-18'),
('Mayvitch', 'Immalia', 'Expansion Region', 'L-8'),
('Mazhar', 'Spadja', 'Outer Rim Territories', 'R-6'),
('Mazuma', 'Nuiri', 'Outer Rim Territories', 'Q-6'),
('Mearalis', 'Bri''ahl', 'Outer Rim Territories', 'I-17'),
('Meastrinnar', NULL, 'Inner Rim', 'K-8'),
('Mechis', NULL, 'Inner Rim', 'L-14'),
('Medepiest', 'Lambda', 'Mid Rim', 'P-15'),
('Media', 'Corporate Sector', 'Outer Rim Territories', 'S-4'),
('Medoslea', NULL, 'Inner Rim', 'O-8'),
('Medth', 'Ado', 'Mid Rim', 'M-17'),
('Meedis Minor', 'Tandon', 'Mid Rim', 'Q-13'),
('Mefti', NULL, 'Colonies', 'L-8'),
('Megalox Beta', 'Bes Ber Bikade', 'Expansion Region', 'L-15'),
('Megaria', NULL, 'Inner Rim', 'M-8'),
('Meglumine', NULL, 'Inner Rim', 'J-8'),
('Mek va Uil', 'Surron', 'Expansion Region', 'O-13'),
('Mek-Sha', 'Belderone', 'Outer Rim Territories', 'R-6'),
('Mek''tradi', 'Baroli', 'Expansion Region', 'N-14'),
('Mektrun Cluster', 'Mektrun', 'Mid Rim', 'L-17'),
('Melagawni', 'Likasha', 'Mid Rim', 'Q-15'),
('Melahna', NULL, 'Core Worlds', 'K-9'),
('Melasaton', 'Jjannex', 'Outer Rim Territories', 'L-18'),
('Melchior', 'Zeemacht Cluster', 'Inner Rim', 'N-8'),
('Meldazar', 'Immalia', 'Expansion Region', 'K-8'),
('Melida/Daan', 'Cadavine', 'Outer Rim Territories', 'P-17'),
('Meligin', 'Ehosiq', 'Expansion Region', 'L-8'),
('Melinz', NULL, 'Core Worlds', 'L-9'),
('Melldia', 'Esstran', 'Outer Rim Territories', 'Q-4'),
('Melm', 'Wyl', 'Outer Rim Territories', 'S-4'),
('Melnea''s World', 'Arkanis', 'Outer Rim Territories', 'R-16'),
('Melus', 'Nicandra', 'Mid Rim', 'L-7'),
('Mendacia', 'Fei Hu', 'Mid Rim', 'P-13'),
('Mendavi', 'Ferra', 'Outer Rim Territories', 'S-16'),
('Mendenbatt', 'Mortex', 'Outer Rim Territories', 'R-5'),
('Mendicat', NULL, 'Wild Space', 'I-8'),
('Mengjini', 'Bright Jewel', 'Mid Rim', 'L-7'),
('Mennar-Daye', 'Thesme', 'Outer Rim Territories', 'O-6'),
('Mentanar', 'Vosk Nijune', 'Outer Rim Territories', 'O-4'),
('Menthusa', NULL, 'Colonies', 'M-9'),
('Meor Ain', 'Jubilar', 'Outer Rim Territories', 'T-7'),
('Mepha''as Prime', 'Belsmuth', 'Outer Rim Territories', 'O-6'),
('Mephitis', NULL, 'Colonies', 'J-13'),
('Mephout', 'Mephout Dominion', 'Wild Space', 'H-20'),
('Merakai', NULL, 'Core Worlds', 'K-9'),
('Meria', NULL, 'Mid Rim', 'H-15'),
('Meridian', 'Meridian', 'Outer Rim Territories', 'R-7'),
('Merikon', 'Fath', 'Outer Rim Territories', 'K-6'),
('Merisee', 'Elrood', 'Outer Rim Territories', 'M-19'),
('Merj', 'Thesme', 'Outer Rim Territories', 'O-6'),
('Merokia', 'Koradin', 'Outer Rim Territories', 'J-18'),
('Merren', 'Chaykin', 'Expansion Region', 'O-14'),
('Merson', NULL, 'Inner Rim', 'O-10'),
('Merthia', 'Merthian', 'Expansion Region', 'N-13'),
('Meruud', 'Narrant', 'Mid Rim', 'I-16'),
('Mes Cavoli', 'Venaarian', 'Mid Rim', 'O-7'),
('Meserian', 'Nijune', 'Outer Rim Territories', 'O-4'),
('Meshakia', 'Likasha', 'Mid Rim', 'Q-14'),
('Messert', 'Mytaranor', 'Mid Rim', 'Q-10'),
('Messia', NULL, 'Core Worlds', 'M-11'),
('Mestare', NULL, 'Deep Core', 'L-12'),
('Mestra', 'Minos Cluster', 'Outer Rim Territories', 'M-20'),
('Mestun', 'Thrasybule', 'Outer Rim Territories', 'P-6'),
('Mesula', 'Eidoloni', 'Mid Rim', 'M-16'),
('Metalorn', 'Talcene', 'Mid Rim', 'R-8'),
('Metellos', 'Corusca', 'Core Worlds', 'K-10'),
('Metharg', 'Hook Nebula', 'Outer Rim Territories', 'O-17'),
('Metharian Nebula', 'Tantra', 'Outer Rim Territories', 'M-19'),
('Metlok', 'Nouane', 'Inner Rim', 'N-8'),
('Mev', 'Javin (Anoat)', 'Outer Rim Territories', 'K-18'),
('Mexeluine', 'Javin (Anoat)', 'Outer Rim Territories', 'K-18'),
('Mezeg', 'Mezeg', 'Mid Rim', 'N-7'),
('Mhalanduin', 'Oktos', 'Mid Rim', 'R-12'),
('Mhatma', NULL, 'Mid Rim', 'I-16'),
('Mhettghar', 'Atravis', 'Outer Rim Territories', 'L-19'),
('Midani', 'Thuris', 'Outer Rim Territories', 'P-18'),
('Midarr', 'Mulgard', 'Mid Rim', 'N-16'),
('Midgor', 'Croynar', 'Inner Rim', 'M-14'),
('Miele Nova', NULL, 'Core Worlds', 'L-9'),
('Miglar', 'Morshdine', 'Outer Rim Territories', 'O-4'),
('Mijos', 'Javin (Anoat)', 'Outer Rim Territories', 'K-18'),
('Mika', 'Arkanis', 'Outer Rim Territories', 'R-17'),
('Mikaster', 'Mikaster', 'Expansion Region', 'N-15'),
('Mikkia', 'Greater Plooriod', 'Expansion Region', 'M-7'),
('Miko', 'Esaga', 'Mid Rim', 'Q-11'),
('Mil Velay', NULL, 'Inner Rim', 'M-8'),
('Mila', 'Brak', 'Expansion Region', 'O-14'),
('Milagro', 'Chaykin', 'Expansion Region', 'O-14'),
('Milarian', 'Trans-Nebular', 'Mid Rim', 'R-16'),
('Mileva', 'Maldrood', 'Mid Rim', 'R-7'),
('Millinar', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Milvayne', NULL, 'Inner Rim', 'L-8'),
('Mima', 'D''Aelgoth', 'Mid Rim', 'L-17'),
('Minashee', 'Cassander (Tadrin)', 'Outer Rim Territories', 'K-5'),
('Minavar', 'Bheriz', 'Outer Rim Territories', 'U-10'),
('Mindabaal', 'Faultheen', 'Inner Rim', 'J-13'),
('Mindemir', NULL, 'Colonies', 'N-10'),
('Mindor', NULL, 'Inner Rim', 'M-8'),
('Minfar', NULL, 'Inner Rim', 'I-13'),
('Minkring', 'Shelsha', 'Colonies', 'M-9'),
('Minntaa', 'Nilgaard', 'Outer Rim Territories', 'S-5'),
('Minntooine', 'Calamari', 'Outer Rim Territories', 'T-6'),
('Minoth', 'Masla', 'Mid Rim', 'J-17'),
('Mirak Major', NULL, 'Inner Rim', 'M-14'),
('Mircapala', NULL, 'Wild Space', 'S-3'),
('Mirial', 'Illisurevimurasi', 'Outer Rim Territories', 'Q-4'),
('Miriatin', 'Var Hagen', 'Mid Rim', 'M-16'),
('Mirit', NULL, 'Colonies', 'K-9'),
('Mirnic', 'Seswenna', 'Outer Rim Territories', 'M-18'),
('Miro', 'Fath', 'Outer Rim Territories', 'K-6'),
('Mirran', 'Morobe', 'Colonies', 'N-11'),
('Mirrin Prime', 'Kalamith (Mirrin)', 'Outer Rim Territories', 'P-5'),
('Mirshaf', NULL, 'Core Worlds', 'L-9'),
('Mirshilan', 'Dalchon', 'Outer Rim Territories', 'R-17'),
('Mis-Tenek', 'Manda', 'Mid Rim', 'S-15'),
('Misnor', 'Meram', 'Outer Rim Territories', 'O-4'),
('Mistar', 'Tragan Cluster', 'Outer Rim Territories', 'N-5'),
('Mitek-Por', NULL, 'Inner Rim', 'M-8'),
('Mittoblade', NULL, 'Inner Rim', 'K-8'),
('Miv''rah', 'Gaulus', 'Outer Rim Territories', 'R-17'),
('Mizra', NULL, 'Inner Rim', 'O-8'),
('Miztoc', 'Irnaj', 'Mid Rim', 'K-17'),
('Mobetta', 'Airam', 'Outer Rim Territories', 'M-20'),
('Modus', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Moer', 'Hewett', 'Mid Rim', 'M-7'),
('Mogoshyn', 'Gordian Reach', 'Outer Rim Territories', 'P-5'),
('Mohsenia', 'Meridian', 'Outer Rim Territories', 'R-6'),
('Mokivj', 'Pacanth Reach', 'Outer Rim Territories', 'G-16'),
('Mokk', NULL, 'Inner Rim', 'N-10'),
('Mol''leaj', 'Thaere', 'Expansion Region', 'O-14'),
('Molavar', 'Abrion', 'Outer Rim Territories', 'S-15'),
('Moldour', 'Lothal', 'Outer Rim Territories', 'U-7'),
('Mollo Tanka', 'Corellian', 'Core Worlds', 'M-11'),
('Molos', 'Stensen', 'Outer Rim Territories', 'I-17'),
('Moloskia', 'Mbandamonte', 'Expansion Region', 'N-15'),
('Moltok', 'Atrivis', 'Outer Rim Territories', 'L-5'),
('Momansi', 'Brevost', 'Expansion Region', 'O-15'),
('Mon Cala', 'Calamari', 'Outer Rim Territories', 'U-6'),
('Mon Gazza', 'Lambda', 'Mid Rim', 'Q-16'),
('Mon Torri', 'Msst', 'Mid Rim', 'P-7'),
('Monadin', 'Kuat', 'Core Worlds', 'M-10'),
('Monastery', 'Haserian', 'Mid Rim', 'Q-14'),
('Mondress', 'Mondress', 'Expansion Region', 'J-7'),
('Monhudle', 'Cassander (Tadrin)', 'Outer Rim Territories', 'K-5'),
('Monic', 'Trianii Space', 'Wild Space', 'R-3'),
('Monor', 'Doldur', 'Mid Rim', 'P-15'),
('Monsua Nebula', 'Zuma (Moddell)', 'Outer Rim Territories', 'H-16'),
('Monta', 'Daimar', 'Mid Rim', 'Q-16'),
('Montalsia', 'Corellian', 'Core Worlds', 'M-11'),
('Montitia', 'Montitian Grant', 'Expansion Region', 'J-15'),
('Montross', 'Truum', 'Mid Rim', 'P-8'),
('Moobia', 'Kastolar', 'Mid Rim', 'R-10'),
('Moog Mot', 'Tharin', 'Outer Rim Territories', 'S-8'),
('Mooga', 'Perkell', 'Mid Rim', 'Q-7'),
('Moonflower Nebula', NULL, 'Wild Space', 'U-16'),
('Moonus Mandel', 'Bothan', 'Mid Rim', 'R-14'),
('Moorja', NULL, 'Inner Rim', 'L-15'),
('Moorjhone', 'Jospro', 'Outer Rim Territories', 'R-7'),
('Mooshie Cluster', 'Videnda', 'Outer Rim Territories', 'L-18'),
('Moraband', 'Esstran (Sith Worlds)', 'Outer Rim Territories', 'R-5'),
('Morado', 'Hune', 'Mid Rim', 'Q-11'),
('Moraga', 'Oricho', 'Outer Rim Territories', 'M-5'),
('Morak', NULL, 'Wild Space', 'H-18'),
('Moralan', 'Hutt Space', 'Outer Rim Territories', 'T-10'),
('Morath Nebula', 'Hatawa', 'Core Worlds', 'J-10'),
('Moravia', 'Lambda', 'Mid Rim', 'Q-16'),
('Moraysi', 'Skine', 'Outer Rim Territories', 'P-18'),
('Mordagon', 'Authala', 'Expansion Region', 'P-12'),
('Mordal', 'Illisurevimurasi', 'Outer Rim Territories', 'Q-4'),
('Mordis', 'Lambda', 'Mid Rim', 'P-16'),
('Morellia', 'Morellian CW', 'Wild Space', 'S-3');