-- Insertar nuevos sistemas galácticos desde Cheravh hasta Daalang
INSERT INTO public.galactic_systems (name, sector, region, grid_coordinates) VALUES
('Cheravh', 'Mandalore', 'Outer Rim Territories', 'O-7'),
('Cherridan', 'Belnar', 'Colonies', 'M-9'),
('Cheruba', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Chespea', 'Rayter (Berenge)', 'Outer Rim Territories', 'J-19'),
('Chestrashus', NULL, 'Wild Space', 'Q-3'),
('Chibbier', 'Stensen', 'Outer Rim Territories', 'I-17'),
('Chibias', 'Sombure', 'Mid Rim', 'K-17'),
('Chiloon Rift', NULL, 'Wild Space', 'O-3'),
('Chiron', 'Ash Worlds', 'Outer Rim Territories', 'T-7'),
('Chirrion', 'Rolion', 'Outer Rim Territories', 'Q-6'),
('Choah', 'Mortex', 'Outer Rim Territories', 'S-5'),
('Choi', NULL, 'Inner Rim', 'M-13'),
('Chokan', 'Maerdocian', 'Mid Rim', 'Q-13'),
('Chol', 'Nebula', 'Outer Rim Territories', 'T-5'),
('Cholganna', NULL, 'Outer Rim Territories', 'T-5'),
('Chommell Minor', 'Chommell', 'Mid Rim', 'O-17'),
('Chonsetta', 'Metatessu', 'Mid Rim', 'R-9'),
('Chorax', 'Rachuk', 'Colonies', 'N-11'),
('Chorgad', 'Fei Hu', 'Mid Rim', 'Q-13'),
('Chorin', NULL, 'Inner Rim', 'N-14'),
('Chorra', 'Bamula', 'Inner Rim', 'J-13'),
('Chortose', 'Rseik', 'Outer Rim Territories', 'N-20'),
('Chosper', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Choss', NULL, 'Colonies', 'J-13'),
('Chrellis', 'Lahara', 'Outer Rim Territories', 'M-5'),
('Chrelythiumn', NULL, 'Wild Space', 'K-2'),
('Chrenthoan Abyss', 'Chrenthoa', 'Inner Rim', 'J-14'),
('Christophsis', 'Savareen', 'Outer Rim Territories', 'Q-16'),
('Chroma Zed', 'Maerdocian', 'Mid Rim', 'Q-12'),
('Chroman', 'D''Aelgoth', 'Mid Rim', 'K-17'),
('Chrome Citadel', 'Harron', 'Expansion Region', 'O-11'),
('Chromovon', 'Nembus', 'Outer Rim Territories', 'P-4'),
('Chrona', NULL, 'Inner Rim', 'O-8'),
('Chryya', 'Dustig', 'Mid Rim', 'M-17'),
('Chundu', 'Cegul', 'Outer Rim Territories', 'L-20'),
('Churr', 'Quellor', 'Colonies', 'N-12'),
('Churruma', 'Velcar', 'Outer Rim Territories', 'J-5'),
('Chuzalla', 'Tammuz', 'Outer Rim Territories', 'T-14'),
('Chyron', 'Har Worlds', 'Expansion Region', 'J-16'),
('Cianap', 'Piryn Shar', 'Expansion Region', 'K-16'),
('Ciaox Venith', 'Croynar', 'Inner Rim', 'M-14'),
('Cificap', 'Herdessa', 'Mid Rim', 'Q-16'),
('Cilare', 'Veragi', 'Outer Rim Territories', 'K-3'),
('Cilpar', NULL, 'Colonies', 'L-13'),
('Cimarosa', 'Irnaj', 'Mid Rim', 'K-17'),
('Cinnabar', 'Corellian', 'Core Worlds', 'M-11'),
('Cioral', 'Chiss Space', 'Unknown Regions', 'F-8'),
('Cioran', NULL, 'Core Worlds', 'L-12'),
('Ciratu', 'Immerian Outback', 'Expansion Region', 'N-14'),
('Circarpous', 'Circarpous', 'Expansion Region', 'O-12'),
('Circumtore', 'Hutt Space', 'Hutt Space', 'S-12'),
('Cirilia', 'Lannik Space', 'Mid Rim', 'R-13'),
('Cirra', 'Brak', 'Expansion Region', 'O-14'),
('Cirrus', 'Dantus', 'Outer Rim Territories', 'J-6'),
('Cirtappa', 'Alui', 'Mid Rim', 'O-17'),
('Cirus', 'Arkanis', 'Outer Rim Territories', 'R-17'),
('Citlik', 'Citlik', 'Expansion Region', 'O-14'),
('Ciutric', 'Ciutric', 'Outer Rim Territories', 'N-5'),
('Clabron', NULL, 'Core Worlds', 'K-13'),
('Claer', 'Sern', 'Colonies', 'L-13'),
('Clak''dor', 'Mayagil', 'Outer Rim Territories', 'M-18'),
('Clantaano', 'Albanin', 'Outer Rim Territories', 'U-12'),
('Clar, The', NULL, 'Wild Space', 'I-20'),
('Clariv', 'Tion Hegemony', 'Outer Rim Territories', 'S-6'),
('Clear View', NULL, 'Wild Space', 'U-13'),
('Clendor', NULL, 'Inner Rim', 'O-8'),
('Clerion', 'Palamut', 'Expansion Region', 'N-13'),
('Cloak of the Sith, The', 'Abrion', 'Outer Rim Territories', 'S-15'),
('Clyne', 'Corellian', 'Core Worlds', 'M-11'),
('Clysm', 'D''Astan', 'Outer Rim Territories', 'O-5'),
('Cmaoli Di', 'Brema', 'Outer Rim Territories', 'M-17'),
('Coachelle', 'Terr''skiar', 'Mid Rim', 'P-10'),
('Cobal', NULL, 'Core Worlds', 'K-13'),
('Codia', NULL, 'Mid Rim', 'H-15'),
('Cog Hive Seven', 'Tharin', 'Outer Rim Territories', 'S-8'),
('Cole-Haddon', 'Dalonbian', 'Outer Rim Territories', 'M-3'),
('Colla', NULL, 'Inner Rim', 'N-9'),
('Colonial Station Camco', 'Chiss Space', 'Unknown Regions', 'F-8'),
('Colonial Station Chaf', 'Chiss Space', 'Unknown Regions', 'F-9'),
('Cols', 'Kastolar', 'Mid Rim', 'Q-10'),
('Colsassa', 'Jospro', 'Outer Rim Territories', 'R-7'),
('Columex', 'Vorzyd', 'Outer Rim Territories', 'R-6'),
('Columus', NULL, 'Core Worlds', 'M-11'),
('Colunda Prime', 'Phelleem (Colunda)', 'Outer Rim Territories', 'S-7'),
('Cometwash, The', 'Gordian Reach', 'Outer Rim Territories', 'Q-6'),
('Comkin', NULL, 'Inner Rim', 'N-7'),
('Commenor', NULL, 'Colonies', 'N-10'),
('Comra', 'Prefsbelt', 'Outer Rim Territories', 'J-5'),
('Cona', 'Inner Cluster', 'Inner Rim', 'O-11'),
('Concord Dawn', 'Mandalore', 'Outer Rim Territories', 'O-7'),
('Condular', NULL, 'Core Worlds', 'M-12'),
('Conjenus', 'Vish', 'Mid Rim', 'N-16'),
('Constancia', NULL, 'Deep Core', 'K-12'),
('Contruum', 'Truum', 'Mid Rim', 'O-8'),
('Coonee', 'Brevost', 'Expansion Region', 'O-15'),
('Coorimbus', 'Tapani', 'Colonies', 'L-13'),
('Copero', 'Chiss Space', 'Unknown Regions', 'F-9'),
('Cophrigin', 'Ash Worlds', 'Outer Rim Territories', 'T-7'),
('Copperline', 'Vatha', 'Expansion Region', 'K-16'),
('Cor I', 'Tapani', 'Colonies', 'L-13'),
('Cor II', 'Tapani', 'Colonies', 'L-13'),
('Cor III', 'Tapani', 'Colonies', 'L-13'),
('Corann', NULL, 'Core Worlds', 'M-9'),
('Corbantis', 'Chaykin', 'Expansion Region', 'O-14'),
('Corbett Cluster', 'Corbett', 'Mid Rim', 'I-17'),
('Corbos', 'Esstran', 'Outer Rim Territories', 'Q-5'),
('Cordaxia', 'Kibilini', 'Outer Rim Territories', 'Q-17'),
('Cordes', NULL, 'Inner Rim', 'N-9'),
('Cordota', 'Lantillian', 'Mid Rim', 'P-8'),
('Corellia', 'Corellian', 'Core Worlds', 'M-11'),
('Corfai', 'Corellian', 'Core Worlds', 'M-11'),
('Corg', NULL, 'Wild Space', 'O-20'),
('Coriallis', NULL, 'Core Worlds', 'K-9'),
('Corips', NULL, 'Inner Rim', 'N-14'),
('Corjain', 'Kathol', 'Outer Rim Territories', 'M-21'),
('Corlaasi', 'Minos Cluster', 'Outer Rim Territories', 'M-20'),
('Corlass', 'Cronese Mandate', 'Outer Rim Territories', 'S-6'),
('Corlax', 'Allied Tion', 'Outer Rim Territories', 'S-6'),
('Corlus', 'Woostri', 'Expansion Region', 'M-16'),
('Cormit', 'Chiss Space', 'Unknown Regions', 'F-8'),
('Cornesia', 'Manda', 'Mid Rim', 'R-14'),
('Coronar', NULL, 'Colonies', 'L-9'),
('Corosi', 'Corosi', 'Outer Rim Territories', 'N-6'),
('Corphelion', 'Corpheli', 'Expansion Region', 'M-7'),
('Corrdair', 'Hevvrol', 'Mid Rim', 'O-15'),
('Corroth', NULL, 'Colonies', 'N-9'),
('Corsin', 'Greater Plooriod', 'Expansion Region', 'M-7'),
('Corson Prime', 'Tharin (Periphery)', 'Outer Rim Territories', 'S-8'),
('Corstris', 'Quelii', 'Outer Rim Territories', 'O-6'),
('Cortella', NULL, 'Core Worlds', 'K-9'),
('Corthenia', 'Corthenia', 'Mid Rim', 'K-7'),
('Cortilium Major', 'Eucer', 'Mid Rim', 'Q-7'),
('Cortina', NULL, 'Core Worlds', 'K-12'),
('Corulag', 'Bormea', 'Core Worlds', 'L-9'),
('Corus', 'Wyl', 'Outer Rim Territories', 'S-4'),
('Coruscant', 'Corusca (Coruscant)', 'Core Worlds', 'L-9'),
('Coruschal', NULL, 'Core Worlds', 'K-10'),
('Coruscul', NULL, 'Core Worlds', 'L-10'),
('Corutarn', NULL, 'Core Worlds', 'M-10'),
('Corva', 'Corva', 'Outer Rim Territories', 'P-4'),
('Corva Yag', 'Rseik', 'Outer Rim Territories', 'N-20'),
('Corvanni', 'Neshig', 'Inner Rim', 'N-9'),
('Corvis Minor', 'Ciutric', 'Outer Rim Territories', 'N-5'),
('Corvus', 'Cronese Mandate', 'Outer Rim Territories', 'S-6'),
('Corweillia', 'Corweillian', 'Mid Rim', 'P-15'),
('Cosia', NULL, 'Deep Core', 'M-11'),
('Cosmatanic Steppes', 'Grohl', 'Outer Rim Territories', 'R-16'),
('Cotellier', 'Rseik', 'Outer Rim Territories', 'N-20'),
('Coth Fuuras', 'Deadalis', 'Expansion Region', 'J-8'),
('Council', 'Javin (Anoat)', 'Outer Rim Territories', 'K-18'),
('Couronne', 'Couronne', 'Expansion Region', 'P-10'),
('Cousault', 'Semagi', 'Mid Rim', 'I-16'),
('Coveway', 'Koradin', 'Outer Rim Territories', 'I-18'),
('Cowl Crucible', 'Oricho', 'Outer Rim Territories', 'M-5'),
('Coxixia', NULL, 'Core Worlds', 'M-12'),
('Coyerti', 'Bortele', 'Mid Rim', 'S-8'),
('Coyn', 'Elrood', 'Outer Rim Territories', 'M-20'),
('Craci', 'Corporate Sector', 'Outer Rim Territories', 'R-4'),
('Crait', 'Bon''nyuw-Luq', 'Outer Rim Territories', 'N-17'),
('Crakull', NULL, 'Unknown Regions', 'G-10'),
('Cranan', 'Arkanis', 'Outer Rim Territories', 'R-16'),
('Crandel', NULL, 'Wild Space', 'U-11'),
('Crash''s Drift', 'Corellian', 'Core Worlds', 'M-11'),
('Credaan', NULL, 'Inner Rim', 'M-14'),
('Crella', 'Tapani', 'Colonies', 'L-13'),
('Cridark', 'Baroli', 'Expansion Region', 'N-15'),
('Criigo', 'Ash Worlds', 'Outer Rim Territories', 'T-7'),
('Crintlia', 'Outer Jalor', 'Mid Rim', 'I-7'),
('Crispin', NULL, 'Wild Space', 'S-3'),
('Critoki', 'Esstran', 'Outer Rim Territories', 'Q-4'),
('Criton''s Point', 'Myto', 'Outer Rim Territories', 'K-3'),
('Critonia', NULL, 'Mid Rim', 'I-15'),
('Cro-Akon', 'Thuldin''s Grant', 'Expansion Region', 'J-15'),
('Croce', 'Yminis', 'Outer Rim Territories', 'S-14'),
('Croluthe Zenj', 'Lannik Space', 'Mid Rim', 'R-13'),
('Crombach Nebula', 'Belsmuth', 'Outer Rim Territories', 'O-6'),
('Cron Drift', 'Auril', 'Outer Rim Territories', 'R-6'),
('Crondre', 'Dufilvian', 'Mid Rim', 'R-15'),
('Crossing Lanes Station', 'D''Astan', 'Outer Rim Territories', 'O-5'),
('Crothy', 'Seitia', 'Outer Rim Territories', 'K-19'),
('Crovna', 'Senex', 'Mid Rim', 'L-17'),
('Croyden', NULL, 'Inner Rim', 'M-13'),
('Crseih', 'Pakuuni', 'Outer Rim Territories', 'T-6'),
('Crucival', 'Tion Hegemony', 'Outer Rim Territories', 'S-6'),
('Crul', 'Lannik Wilds', 'Mid Rim', 'R-13'),
('Crushank Nebulae', 'Tantra', 'Outer Rim Territories', 'M-19'),
('Crustai', NULL, 'Unknown Regions', 'H-8'),
('Cryon', 'Meram', 'Outer Rim Territories', 'O-4'),
('Crystal Web Station', 'Palamut', 'Expansion Region', 'N-13'),
('Crystan', NULL, 'Deep Core', 'L-12'),
('Crytal Nest', NULL, 'Wild Space', 'H-20'),
('Csaus', 'Chiss Space', 'Unknown Regions', 'F-9'),
('Csilla', 'Chiss Space', 'Unknown Regions', 'F-8'),
('Cuirilla', 'Mbandamonte', 'Expansion Region', 'N-15'),
('Cujicor', 'Pakuuni', 'Outer Rim Territories', 'T-5'),
('Cularin', 'Thaere', 'Expansion Region', 'P-14'),
('Culroon', NULL, 'Wild Space', 'P-20'),
('Curreck', 'Sertar', 'Outer Rim Territories', 'R-5'),
('Cuthbern', 'Wazta', 'Outer Rim Territories', 'J-18'),
('Cuvacia', NULL, 'Core Worlds', 'K-13'),
('Cuyacan', 'Sepan', 'Expansion Region', 'P-13'),
('Cvetaen', 'Sumitra', 'Expansion Region', 'N-7'),
('Cyax', 'Hutt Space', 'Hutt Space', 'S-11'),
('Cybloc', 'Meridian', 'Outer Rim Territories', 'R-7'),
('Cyborrea', 'Hutt Space', 'Hutt Space', 'S-9'),
('Cyclor', 'Alui', 'Mid Rim', 'N-17'),
('Cyclorria', NULL, 'Inner Rim', 'N-9'),
('Cydorria', NULL, 'Colonies', 'K-13'),
('Cygnus', 'Kontahr', 'Mid Rim', 'R-11'),
('Cyimarra', 'Senex', 'Mid Rim', 'L-17'),
('Cymoon', 'Bes Ber Bikade', 'Expansion Region', 'L-15'),
('Cyphar', 'Spirva', 'Mid Rim', 'L-17'),
('Cyrillia', 'Cyrillian Protectorate', 'Expansion Region', 'O-12'),
('Cyrkon', 'Al''Nasrl', 'Outer Rim Territories', 'T-13'),
('CZ-198', NULL, 'Unknown Regions', 'G-6'),
('Czerialus', 'Kailion', 'Expansion Region', 'O-13'),
('D''Anjon Nebula', 'Arkanis', 'Outer Rim Territories', 'R-16'),
('D''faria', 'Hune', 'Mid Rim', 'Q-12'),
('D''ian', 'Corporate Sector', 'Outer Rim Territories', 'S-3'),
('D''janis', 'Halm', 'Mid Rim', 'J-16'),
('D''Nile', 'Hertae', 'Mid Rim', 'Q-14'),
('D''Qar', 'Sanbra', 'Outer Rim Territories', 'O-17'),
('D''rinba', 'Sombure', 'Mid Rim', 'K-17'),
('Daalang', 'Daalang', 'Mid Rim', 'Q-12');