-- Insert galactic systems from Ord Ortag to Perin (196 systems)
INSERT INTO galactic_systems (name, sector, region, grid_coordinates) VALUES
('Ord Ortag', 'Hutt Space', 'Outer Rim Territories', 'S-13'),
('Ord Pardron', 'Dufilvian', 'Mid Rim', 'R-15'),
('Ord Pentala', NULL, 'Inner Rim', 'K-14'),
('Ord Radama', 'Esstran', 'Outer Rim Territories', 'Q-5'),
('Ord Sabaok', NULL, 'Core Worlds', 'J-13'),
('Ord Sedra', 'Clacis', 'Outer Rim Territories', 'K-4'),
('Ord Segra', 'Dufilvian', 'Mid Rim', 'Q-15'),
('Ord Sigatt', 'Noonian', 'Outer Rim Territories', 'N-6'),
('Ord Simres', 'Brema', 'Outer Rim Territories', 'M-17'),
('Ord Tellarom', 'Suolriep', 'Outer Rim Territories', 'S-8'),
('Ord Tessebok', 'Irishi', 'Mid Rim', 'K-6'),
('Ord Thabl', 'Elochar', 'Mid Rim', 'R-9'),
('Ord Thoden', 'Dynali', 'Outer Rim Territories', 'J-4'),
('Ord Tiddell', 'Tennuutta', 'Mid Rim', 'Q-7'),
('Ord Torrenze', 'Sertar', 'Outer Rim Territories', 'S-5'),
('Ord Traga', 'Tragan Cluster', 'Outer Rim Territories', 'N-5'),
('Ord Trasi', 'Relgim', 'Outer Rim Territories', 'L-4'),
('Ord Varee', 'Belshar', 'Mid Rim', 'J-7'),
('Ord Vaug', 'Rocantor', 'Expansion Region', 'L-15'),
('Ord Vaxal', 'Callia', 'Inner Rim', 'N-13'),
('Ord Wylan', 'Oktos', 'Mid Rim', 'R-12'),
('Ord Yndar', 'Esaga', 'Mid Rim', 'Q-11'),
('Ord Zat', 'Jospro', 'Outer Rim Territories', 'S-7'),
('Ord Zeuol', 'Vilonis', 'Mid Rim', 'O-16'),
('Ord Zynthar', 'Lambda', 'Mid Rim', 'P-16'),
('Ordnandell', 'Kastolar', 'Mid Rim', 'R-10'),
('Ordo', 'Mandalore', 'Outer Rim Territories', 'O-7'),
('Ordo Eris', 'Chorlian', 'Outer Rim Territories', 'S-4'),
('Ordo Moon', 'Bortele', 'Mid Rim', 'R-8'),
('Ordo Tera', 'Belasco', 'Expansion Region', 'P-11'),
('Oreenda', 'Fayett', 'Colonies', 'L-13'),
('Orelon', 'Hapes Cluster', 'Inner Rim', 'O-9'),
('Orgri, The', 'Jubilar', 'Outer Rim Territories', 'T-7'),
('Oricho', 'Oricho', 'Outer Rim Territories', 'M-6'),
('Oricon', 'Corva', 'Outer Rim Territories', 'P-3'),
('Oridol Cluster', 'Rolion', 'Outer Rim Territories', 'P-7'),
('Orimanther', 'Quelii', 'Outer Rim Territories', 'O-6'),
('Orinackra', NULL, 'Wild Space', 'J-3'),
('Orinca', 'Tunka', 'Outer Rim Territories', 'I-19'),
('Orinda', 'Irishi', 'Mid Rim', 'K-6'),
('Oriolanis', 'Oriolan', 'Mid Rim', 'J-16'),
('Orion', 'Tion Hegemony', 'Outer Rim Territories', 'T-6'),
('Orish', 'Brema', 'Outer Rim Territories', 'M-17'),
('Oristrom', NULL, 'Unknown Regions', 'I-5'),
('Orixon Nebula', 'Phelleem', 'Outer Rim Territories', 'S-7'),
('Orkellia', 'Haserian', 'Mid Rim', 'Q-15'),
('Orko', 'Videnda', 'Outer Rim Territories', 'L-18'),
('Orleon', 'Talcene', 'Mid Rim', 'Q-8'),
('Orma', 'Brak', 'Expansion Region', 'O-14'),
('Orn Kios', 'Javin (Yarith)', 'Outer Rim Territories', 'K-18'),
('Ornfra', 'Chiss Space', 'Unknown Regions', 'F-8'),
('Oro Sankeria', 'Tharin', 'Outer Rim Territories', 'S-7'),
('Orocco', 'Ottega', 'Mid Rim', 'M-7'),
('Orondia', 'Hutt Space', 'Outer Rim Territories', 'S-11'),
('Orooturoo', 'Farlax', 'Core Worlds', 'K-10'),
('Orowat', 'Myto', 'Outer Rim Territories', 'K-4'),
('Orra', 'D''Astan', 'Outer Rim Territories', 'O-5'),
('Orranana', 'Cadma', 'Outer Rim Territories', 'T-8'),
('Orrik', 'Dalicron', 'Outer Rim Territories', 'K-19'),
('Orroman', NULL, 'Wild Space', 'I-14'),
('Orron', 'Corporate Sector', 'Outer Rim Territories', 'S-4'),
('Orryxia', 'Seswenna', 'Outer Rim Territories', 'M-18'),
('Orsis', 'Haserian', 'Mid Rim', 'Q-15'),
('Orthellin', 'Binarran Cloud', 'Colonies', 'M-9'),
('Orto', 'Sluis', 'Outer Rim Territories', 'M-19'),
('Orto Norwe', 'Trans-Vulta', 'Mid Rim', 'N-7'),
('Oru', 'Veragi', 'Outer Rim Territories', 'L-3'),
('Orvax', 'Dalchon', 'Outer Rim Territories', 'R-17'),
('Osadia', NULL, 'Core Worlds', 'K-10'),
('Osara', NULL, 'Inner Rim', 'K-8'),
('Oseon', 'Centrality', 'Outer Rim Territories', 'T-8'),
('Oshetti', 'Aparo', 'Outer Rim Territories', 'R-3'),
('Oshira', 'Vilonis', 'Mid Rim', 'O-16'),
('Oshora', 'Tolonda', 'Outer Rim Territories', 'Q-17'),
('Osirrag', 'Elrood', 'Outer Rim Territories', 'M-20'),
('Osisis Station', 'Regani', 'Inner Rim', 'M-8'),
('Oslumpex', 'Corporate Sector', 'Outer Rim Territories', 'S-4'),
('Osmani', 'Senex', 'Mid Rim', 'L-18'),
('Ossel', 'Bozhnee', 'Outer Rim Territories', 'L-18'),
('Osseriton', NULL, 'Unknown Regions', 'G-9'),
('Ossi', 'Mezeg', 'Mid Rim', 'N-7'),
('Ossiathora', 'Juvex', 'Mid Rim', 'L-17'),
('Osskorn', 'Tyan', 'Mid Rim', 'L-6'),
('Osssorck Nebulae', NULL, 'Core Worlds', 'J-12'),
('Ossus', 'Auril', 'Outer Rim Territories', 'R-6'),
('Ostega', 'Grohl', 'Outer Rim Territories', 'R-15'),
('Ostor', 'Koradin', 'Outer Rim Territories', 'I-18'),
('Ota', 'Mytaranor', 'Mid Rim', 'Q-10'),
('Otavon', 'Hollan', 'Mid Rim', 'M-7'),
('Oteroa', 'Corthenia', 'Mid Rim', 'K-7'),
('Otomok', 'Prefsbelt', 'Outer Rim Territories', 'K-6'),
('Otor''s Hub', 'Ojoster', 'Outer Rim Territories', 'N-7'),
('Otranto', 'Nembus', 'Outer Rim Territories', 'P-4'),
('Ottabesk', NULL, 'Deep Core', 'M-11'),
('Ottethan', 'Halthor', 'Outer Rim Territories', 'M-6'),
('Ottinger', 'Perinn', 'Outer Rim Territories', 'J-4'),
('Otunia', 'Bosph', 'Outer Rim Territories', 'Q-3'),
('Oulanne', NULL, 'Inner Rim', 'L-14'),
('Outer Mebarius', NULL, 'Inner Rim', 'N-10'),
('Outland Station', 'Baxel', 'Outer Rim Territories', 'T-12'),
('Ova', 'Quelii', 'Outer Rim Territories', 'O-6'),
('Ovanis', 'Pacanth Reach', 'Outer Rim Territories', 'G-16'),
('Ovise', 'Zuma (Moddell)', 'Outer Rim Territories', 'H-16'),
('Ovissi', 'Manda', 'Mid Rim', 'R-14'),
('Oyokal', 'Chiss Space', 'Unknown Regions', 'E-8'),
('Oznek', 'Cademimu', 'Outer Rim Territories', 'M-6'),
('Ozri Far', 'Xandil', 'Mid Rim', 'P-16'),
('Ozu', 'Javin (Anoat)', 'Outer Rim Territories', 'K-18'),
('P''frorin', 'Bheriz', 'Outer Rim Territories', 'U-10'),
('Pa Tho', NULL, 'Inner Rim', 'K-14'),
('Pa''hir''al', 'Urce Space', 'Mid Rim', 'L-7'),
('Paarin Minor', 'Cademimu', 'Outer Rim Territories', 'M-6'),
('Pabu', 'Chopani', 'Outer Rim Territories', 'L-3'),
('Pacara', NULL, 'Mid Rim', 'J-15'),
('Padua', NULL, 'Core Worlds', 'M-12'),
('Paecia', 'Quelii', 'Outer Rim Territories', 'O-6'),
('Pagodon', 'Pelgrin', 'Outer Rim Territories', 'R-18'),
('Paig', 'Drannik', 'Expansion Region', 'K-8'),
('Paigu', 'Vorzyd', 'Outer Rim Territories', 'R-6'),
('Paklan', 'Niuri', 'Outer Rim Territories', 'Q-6'),
('Paklarn', 'Abaar', 'Mid Rim', 'K-7'),
('Pako Ramoon', 'Rayter', 'Outer Rim Territories', 'J-19'),
('Pakrik', 'Kanchen', 'Core Worlds', 'K-9'),
('Pakuuni', 'Pakuuni', 'Outer Rim Territories', 'T-6'),
('Pal Goral', 'Mortex', 'Outer Rim Territories', 'R-4'),
('Palanhi', 'Fakir', 'Colonies', 'K-9'),
('Palawa', NULL, 'Core Worlds', 'L-10'),
('Palek', 'Cyrillian Protectorate', 'Expansion Region', 'O-12'),
('Pallaxides', 'Ojoster', 'Outer Rim Territories', 'N-7'),
('Palliduva', NULL, 'Wild Space', 'U-12'),
('Palmatian', 'Baronos', 'Colonies', 'M-9'),
('Pam''ba', NULL, 'Mid Rim', 'H-15'),
('Pamaradia', NULL, 'Colonies', 'L-8'),
('Pamarthe', 'Mayagil', 'Outer Rim Territories', 'N-18'),
('Pamina Prime', NULL, 'Inner Rim', 'M-8'),
('Pammant', 'Calamari', 'Outer Rim Territories', 'U-6'),
('Pamorjal', 'Immerian Outback', 'Expansion Region', 'N-14'),
('Panatha', 'Pacanth Reach', 'Outer Rim Territories', 'H-16'),
('Pandem Nai', 'Thrasybule', 'Outer Rim Territories', 'P-6'),
('Pandori', 'Sarin', 'Outer Rim Territories', 'O-18'),
('Panela', NULL, 'Core Worlds', 'M-12'),
('Pangarees, The', 'Airam', 'Outer Rim Territories', 'L-20'),
('Panisia', 'Halthor', 'Outer Rim Territories', 'L-6'),
('Panna', 'Cronese Mandate', 'Outer Rim Territories', 'S-6'),
('Pantolomin', 'Dolomar', 'Core Worlds', 'K-9'),
('Pantora', 'Sujimis', 'Outer Rim Territories', 'P-19'),
('Pantrosian Eye', 'Endocray', 'Mid Rim', 'R-14'),
('Paonid', NULL, 'Inner Rim', 'O-8'),
('Paqualis', NULL, 'Inner Rim', 'L-8'),
('Paqwepor Major', 'Paqwepori', 'Mid Rim', 'P-15'),
('Parabaw Station', 'Jospro', 'Outer Rim Territories', 'S-7'),
('Parada', 'Hadar', 'Mid Rim', 'L-17'),
('Paradise', 'Airam', 'Outer Rim Territories', 'M-20'),
('Paradise Station', 'Gendius', 'Mid Rim', 'J-17'),
('Paramatan', 'Senex', 'Mid Rim', 'L-17'),
('Parau', 'Great Agash', 'Expansion Region', 'K-15'),
('Parcelus Major', 'Parcelus', 'Expansion Region', 'O-12'),
('Parcelus Minor', 'Parcelus', 'Expansion Region', 'O-12'),
('Parcovey Minor', 'Hune', 'Mid Rim', 'Q-12'),
('Parein', 'Sarin', 'Outer Rim Territories', 'O-18'),
('Pargaux', NULL, 'Core Worlds', 'K-12'),
('Parkella', 'Elbaran', 'Mid Rim', 'J-17'),
('Parkis', NULL, 'Colonies', 'M-10'),
('Parlatal', 'Javin (Yarith)', 'Outer Rim Territories', 'K-18'),
('Parliock', 'Ariarch', 'Mid Rim', 'J-6'),
('Parmel', 'Parmel', 'Outer Rim Territories', 'O-18'),
('Parmic', 'Parmic', 'Outer Rim Territories', 'P-19'),
('Parnassos', NULL, 'Unknown Regions', 'H-6'),
('Parozha', 'Dustig', 'Mid Rim', 'M-16'),
('Parshoone', 'Perinn', 'Outer Rim Territories', 'J-4'),
('Parthovian Cluster', NULL, 'Wild Space', 'T-4'),
('Partold', 'Instrop', 'Outer Rim Territories', 'T-17'),
('Parwa', 'Seswenna', 'Outer Rim Territories', 'M-18'),
('Pas''sic', 'Oricho', 'Outer Rim Territories', 'M-5'),
('Pasa Novo', 'Onatos', 'Mid Rim', 'R-15'),
('Pasaana', 'Altier (Ombakand)', 'Expansion Region', 'O-13'),
('Pasher', NULL, 'Inner Rim', 'M-14'),
('Pashvi', NULL, 'Wild Space', 'I-5'),
('Pasmin', 'Cronese Mandate', 'Outer Rim Territories', 'S-6'),
('Pastil', 'Abrion', 'Outer Rim Territories', 'S-15'),
('Pastoria', 'Juris', 'Outer Rim Territories', 'P-17'),
('Patch', 'Cademimu', 'Outer Rim Territories', 'M-6'),
('Pathandr', NULL, 'Inner Rim', 'O-8'),
('Patitite Pattuna', 'Bright Jewel', 'Mid Rim', 'L-7'),
('Patriim', 'Seswenna', 'Outer Rim Territories', 'M-18'),
('Patrolia', NULL, 'Inner Rim', 'L-14'),
('Paucris Major', 'Tamarin', 'Outer Rim Territories', 'N-18'),
('Paulking', 'Centrality', 'Outer Rim Territories', 'U-8'),
('Pavia', 'Tapani', 'Colonies', 'L-13'),
('Pavo Prime', NULL, 'Inner Rim', 'N-10'),
('Pax', 'Kira', 'Expansion Region', 'N-16'),
('PDC3141-02', 'Trax', 'Mid Rim', 'P-10'),
('Pedd', 'D''Astan', 'Outer Rim Territories', 'O-6'),
('Pedducis Chorios', 'Meridian', 'Outer Rim Territories', 'R-7'),
('Pedoria', 'Bryx', 'Mid Rim', 'R-8'),
('Peg Shar', 'Halla', 'Mid Rim', 'R-8'),
('Pegg', 'Tynquay', 'Outer Rim Territories', 'R-4'),
('Peirs', 'Kathol', 'Outer Rim Territories', 'M-21'),
('Pelagon', 'Tapani', 'Colonies', 'L-13'),
('Peldon Minor', 'Cassander', 'Outer Rim Territories', 'L-5'),
('Pelemax', NULL, 'Colonies', 'M-9'),
('Pelgrin', 'Pelgrin', 'Outer Rim Territories', 'R-17'),
('Pella', 'Tapani', 'Colonies', 'L-13'),
('Pellastrallas', 'Agarix', 'Mid Rim', 'K-18'),
('Peluchia', 'Kurost', 'Mid Rim', 'Q-11'),
('Pembric', 'Kathol', 'Outer Rim Territories', 'M-21'),
('Pencael', NULL, 'Colonies', 'M-12'),
('Pendal', 'Homon', 'Mid Rim', 'M-7'),
('Pendari', 'Vensensor', 'Expansion Region', 'K-16'),
('Pendarr', 'Alchenaut', 'Expansion Region', 'L-15'),
('Pendaxa', 'Jjannex', 'Outer Rim Territories', 'K-19'),
('Penegelen', NULL, 'Inner Rim', 'L-14'),
('Penga', NULL, 'Inner Rim', 'N-10'),
('Pengalan', NULL, 'Inner Rim', 'O-8'),
('Penhalla', 'Klina', 'Outer Rim Territories', 'S-13'),
('Peppel', 'Corva', 'Outer Rim Territories', 'P-3'),
('Per Lupelo', NULL, 'Inner Rim', 'L-8'),
('Peragus', 'Xappyh', 'Outer Rim Territories', 'Q-4'),
('Pergitor', 'Minos Cluster', 'Outer Rim Territories', 'M-20'),
('Peridon''s Folly', 'Esaga', 'Mid Rim', 'Q-11'),
('Perilious', 'Pelgrin', 'Outer Rim Territories', 'R-17'),
('Perilix', NULL, 'Colonies', 'L-9'),
('Perimako Major', 'Ash Worlds', 'Outer Rim Territories', 'S-7'),
('Perin', 'Trianii Space', 'Wild Space', 'R-3');